
    import { Article } from "@/atoms/Article";
    
    export const Article20220925LechodeslabosMetadata = {"tags":["dengue","recherche","covid","déontologie"],"title":"25 septembre 2022","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste. Bienvenue à tous sur l'Echo des Labos.","date":"2022-09-25"}
    
    export const Article20220925Lechodeslabos : Article = ({
      className, title, UTip, img
    }) => {
      return (<div className={className}>
          <h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche, et c'est un jour de victoire, où le droit et la vérité ont triomphé de l'injustice aveugle de la machine (oui, oui, rien que ça, je suis de bonne humeur, vous voyez). Vous êtes donc bien à nouveau sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { UTip( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Parlons encore de LE VACCIN (oui, se moquer c&rsquo;est mal, je suis une vilaine grenouille). Cela fait plusieurs jours que circule l&rsquo;info (enfin l&rsquo;intox du coup) que le Danemark aurait interdit LE VACCIN aux enfants et l&rsquo;aurait déconseillé (ou interdit, selon qui diffuse le message) aux moins de 50 ans. Est-ce qu&rsquo;on va encore avoir beaucoup de bruit pour rien à pas cher ? Allez, on regarde.</p>
<p>Le Danemark cherche à protéger sa population vulnérable à l&rsquo;approche de l&rsquo;hiver et d&rsquo;une nouvelle vague. Il a donc émis une liste de personnes qui seront appelées à faire leur rappel (donc la 4e dose) à partir du 1er octobre, liste incluant donc les plus de 50 ans, mais aussi les soignants, les personnes souffrant de comorbidités ou encore les femmes enceintes (oui, on va revenir sur ce point-là). Mais ça, c&rsquo;est la liste des personnes appelées, c&rsquo;est tout, les autres font ce qu&rsquo;ils veulent pour la 4e, et pour celle-là uniquement, puisque les autorités continuent à appeler les moins de 50 ans à faire leur schéma vaccinal initial. On est donc très loin d&rsquo;une interdiction.</p>
<p>Le cas des femmes enceintes est à part, puisque les antivax prétendent qu&rsquo;elles sont également interdites de vaccination, alors qu&rsquo;elles font au contraire partie des publics ciblés pour la dose de rappel de l&rsquo;automne.</p>
<p>Le cas des enfants est un poil plus complexe. Le Danemark a effectivement fait en sorte que, depuis le 1er juillet, les mineurs ne soient plus éligibles à la première dose, et depuis le 1e septembre, plus non plus à la seconde pour ceux ayant déjà reçu la première…<br />
Sauf si l&rsquo;enfant a, pour une raison quelconque, un risque de développer une forme grave. En effet, cette décision n&rsquo;est pas motivée par un quelconque risque que le vaccin ferait courir aux enfants, mais par le fait qu&rsquo;ils ne sont plus considérés comme une population à risque de forme sévère…<br />
Notamment parce qu&rsquo;ils sont déjà beaucoup vaccinés. 80% des 12-15 ans et 40% des 5-11 ans ont un schéma vaccinal complet (en France, cette tranche d&rsquo;âge plafonne à 5%…).</p>
<hr />
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p>Parlons d&rsquo;un autre vaccin maintenant ! La grosse découverte de la semaine, c&rsquo;est l&rsquo;autorisation de mise sur le marché d&rsquo;un vaccin contre la bronchiolite pour tous les nourrissons de moins d&rsquo;un an (il existait déjà quelque chose dans ce genre, mais réservé aux prématurés et aux bébés à risques).</p>
<p>En réalité, on peut considérer cette injection plus comme une sérothérapie que comme un vaccin, puisque l&rsquo;idée est de fournir des anticorps « prêts à l&rsquo;emploi » aux tout petits dont le système immunitaire n&rsquo;est pas encore apte à fabriquer son immunité tout seul.</p>
<p>Chaque année en France, 30% de tous les nourrissons sont atteints, en moyenne 20.000 nourrissons sont hospitalisés pour une bronchiolite, et on estime qu&rsquo;entre 100 et 200 en mourront.</p>
<p>Source : Santé Publique France</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Dengue</strong> - la surveillance des données épidémiologiques a révélé un nombre anormalement élevé de cas de dengue en France métropolitaine. Si pour l&rsquo;instant il n&rsquo;est question « que » de 26 cas, ces derniers interrogent car aucun des patients n&rsquo;avaient voyagé depuis moins de 15 jours dans des zones touchées. La présence dans 67 départements du moustique tigre, un des vecteurs préférés de la maladie, fait suspecter une situation plus grave qu&rsquo;en apparence. Plusieurs plans de démoustification doivent être lancés dans les départements touchés.<br />
Source : Direction Générale de la Santé</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Recherche</strong> - vous vous souvenez du moment où j&rsquo;ai promis que je ferai un jour une sorte de guide de survie du doctorant ? Bon, il va falloir que je m&rsquo;y mette mieux que ça, parce que ça urge. Sans grande surprise, alors que la recherche a rappelé au monde son importance absolue pour lutter contre les épidémies, le réchauffement climatique ou la perte de biodiversité, tout le monde a l&rsquo;air de penser que les chercheurs se nourrissent de H-index et d&rsquo;amour de la vérité. Sauf que non. Le dernier rapport de la FAGE est tombé (et il est là <a href="https://www.fage.org/ressources/documents/4/7962-DP-enquete-doctorat-2022-FAGE.pdf">https://www.fage.org/ressources/documents/4/7962-DP-enquete-doctorat-2022-FAGE.pdf</a>). En 10 ans, la France a perdu 10.000 inscrits en doctorats, 10.000 étudiants spécialisés qui ne deviendront jamais chercheurs. Cela s&rsquo;explique (entre autres, je vous jure j&rsquo;ai une liste tellement longue qu&rsquo;il faut un index pour s&rsquo;y repérer) par le fait qu&rsquo;un quart des doctorants ne parvient pas à subvenir à ses besoins. Un sur trois a été confronté à des lenteur administratives et des retards de paiement qui mettaient leur sécurité alimentaire ou énergétique en danger (un jour je vous parlerai de la fois où j&rsquo;ai dû attendre 1 an et demi le paiement de mes heures de cours…). 23% doivent avoir un emploi à côté alors qu&rsquo;une thèse, ça occupe facilement 50h par semaine. Selon le type de dépenses, entre 31% et 54% doivent payer de leur poche leur participation à un colloque ou leurs frais de parution. Mais cet abandon massif s&rsquo;explique aussi par un climat de violence et de dépendance délétère, puisque 24% ont été victimes de discrimination, de violences sexuelles ou de harcèlement dans le cadre de leur doctorat (ok, y a peut-être tous les effectifs de l&rsquo;IHU de Marseille dedans, mais quand même, ça fait un paquet). L&rsquo;épuisement est également un facteur majeur, puisque la FAGE, le premier syndicat étudiant, milite actuellement pour que les doctorants aient le droit à un jour de repos hebdomadaire, à ne pas passer plus de 13h par jour au travail et à bénéficier de jours de congés annuels. Oui, on en est là.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Covid</strong> - Variant : mets tes deux pieds en canaaaaaaard… c&rsquo;est le Covid qui redémaaaaaaaaarre ! Alors, on y retourne pour un tour, vous reprendrez bien un peu de variant-encore-plus-relou-que-le-variant-précédent ? Non ? Et bien tant pis, on a pas toujours tout ce qu&rsquo;on veut dans la vie, moi petite je voulais un renard et je l&rsquo;ai jamais eu, c&rsquo;est comme ça. Donc, le dernier de la bande porte le doux nom de BA 2.75.2, il a été repéré en Inde, en Australie, aux USA, au UK, et en Espagne, autant vous dire que comme l&rsquo;ennemi il est à nos portes. Et il a la capacité de pouvoir encaisser les attaques d&rsquo;anticorps dans la tronche sans mourir, même si en vrai vu qu&rsquo;on sait déjà pas si un virus est vivant c&rsquo;est compliqué de dire s&rsquo;il peut mourir, mais il faut arrêter c&rsquo;est déjà assez compliqué comme ça. Comme c&rsquo;est un sous-variant d&rsquo;Omicron, on espère que les derniers vaccins qui doivent être disponibles à l&rsquo;automne arriveront à le faire rentrer dans les clous. Sinon, il se pourrait qu&rsquo;on passe un hiver bien sympa encore…</p>
<p>Source : OMS</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Déontologie</strong> - il ne faut pas rire du malheur des autres. Mais je pense qu&rsquo;on peut apprécier à sa juste valeur le fait que ceux qui ont fait de la merde alors qu&rsquo;ils avaient des responsabilités paient pour les conséquences de leurs actes. Ainsi donc, après Didier Raoult, c&rsquo;est au tour de Philippe Douste-Blazy d&rsquo;être poussé vers la sortie de l&rsquo;IHU de Marseille. Pour rappel, présent au conseil d&rsquo;administration de la structure, l&rsquo;ancien ministre de la santé avait non seulement crée et diffusé des pétitions pour la prescription de l&rsquo;hydroxychloroquine en dehors de tout résultat d&rsquo;étude valide (ça, voyez-vous, les enfants, ça c&rsquo;est un conflit d&rsquo;intérêt), mais il s&rsquo;était affiché avec Perrone pour lui apporter son soutien alors que celui-ci merdait déjà dans les grandes largeurs et, comble de l&rsquo;infâmie, avait même participé activement à Hold-Up (oui, j&rsquo;ai un PTSD avec ce film pourrave, mais vous en auriez aussi si vous aviez dû écouter Martine Wonner en boucle pendant 3h pour détricoter toutes ses âneries). Le ménage avance, la déontologie ne s&rsquo;en portera que mieux, et c&rsquo;est tout ce qu&rsquo;on demande.</p>
<p>Source : AP-HM</p>
<hr />
<h3 id="-quest-ce-que-putain-de-quoi--"><a href="#-quest-ce-que-putain-de-quoi--">« QU&rsquo;EST-CE QUE PUTAIN DE QUOI ? »</a></h3>
<p>A force, cette section va devenir la rubrique nécrologique de la semaine… Mais vous me connaissez, j&rsquo;ai une sainte horreur de la récupération des morts (les thanatopracteurs, ne vous sentez pas visés, tout le monde voit très bien ce que je veux dire), donc on va s&rsquo;y coller à nouveau.<br />
Le monde du surf a été endeuillé la semaine dernière par la disparition brutale de Kalani David, prodige du surf et du skateboard, foudroyé sur sa planche à l&rsquo;âge de seulement 24 ans. Combien de temps a-t-il fallu, à votre avis, pour voir fleurir les affirmations selon lesquelles il aurait été victime d&rsquo;une grave myocardite due à LE VACCIN (désolée, je m&rsquo;en lasse pas) ? La réponse est « certainement pas assez aux yeux de la décence ».</p>
<p>Kalani David est bien mort d&rsquo;une crise cardiaque, mais ça n&rsquo;a hélas surpris personne (même si évidemment c&rsquo;est un choc). Depuis 2016 et sa première crise cardiaque, il se savait atteint d&rsquo;une maladie rare, le syndrome de Wolff-Parkinson-White. Il s&rsquo;agit d&rsquo;un trouble du rythme, où le battement du cœur est accéléré anormalement par la présence d&rsquo;un faisceau surnuméraire de cellules musculaires cardiaques, appelé le faisceau de Kent. La maladie touche surtout les hommes et sa cause est majoritairement inconnue à ce jour.</p>
<p>Si la moitié des malades restent asymptomatiques toute leur vie, ce ne fut hélas pas le cas pour Kalani David. Réanimé une seconde fois en 2017, il subit une lourde opération à cœur ouvert pour tenter l&rsquo;ablation de ce faisceau surnuméraire. Cela n&rsquo;aura malheureusement pas suffi. Vivant avec une épée de Damoclès au-dessus de la tête, Kalani David est mort en faisant ce qu&rsquo;il aimait et en essayant, jusqu&rsquo;au bout, d&rsquo;être plus fort que le mal qu&rsquo;il portait en lui.</p>
<p>Son courage mérite mieux que les ragots des conspis.</p>
<hr />
<h3 id="point-methode-de-la-semaine--diffuser-la-vulgarisation"><a href="#point-methode-de-la-semaine--diffuser-la-vulgarisation">POINT METHODE DE LA SEMAINE : diffuser la vulgarisation</a></h3>
<p>Comme vous le voyez, je suis de retour, pour vous jouer un mauvais t… non pardon, ça c&rsquo;est la Team Rocket. Les restrictions qui pesaient sur la page ont été levées, et les publications incriminées sont revenues. De ce fait, nous reprenons la publication sur Facebook. Certains d&rsquo;entre vous nous ont indiqué préférer le format blog, nous allons donc travailler à pouvoir fournir une version blog de la chronique chaque semaine.</p>
<p>Mais, et il va falloir être clairs là-dessus, elle ne pourra pas remplacer la publication sur Facebook pour la raison pure et simple que lorsqu&rsquo;on publie sur un blog et que notre post sur la page se résume à un lien, les audiences s&rsquo;effondrent de manière calamiteuse (et depuis quelques temps, elles ne sont déjà pas très bonnes, pour nous mais aussi pour les vulgarisateurs en général).</p>
<p>A titre d&rsquo;exemple, alors que la visibilité au cœur de la crise nous assurait jusqu&rsquo;à 90.000 vues par publication, la page vivote désormais péniblement autour de 5.000 vues, ce qui signifie tout de même que la moitié de nos abonnés n&rsquo;est pas notifiée des publications. Mais le passage au format blog, donnant simplement donc un lien extérieur, a encore divisé ce chiffre par 5. C&rsquo;est pas comme si on faisait de la pub dessus et qu&rsquo;on en avait besoin pour vivre, c&rsquo;est sûr, mais il faut reconnaître que la seule chose qui fait que je continue ce travail est la conviction qu&rsquo;il est utile, et pour être utile, il a besoin d&rsquo;être lu.</p>
<p>Nous continuerons donc ici, faute de solution plus efficace. Merci à nos abonnés qui se sont manifestés pour faire jouer leurs contacts et obtenir la régularisation de la situation, car oui, il est probable que par la voie normale, on serait toujours en train de ramer. Ce n&rsquo;est pas normal. Nous travaillons activement à pouvoir vous proposer, en plus, une version blog plus agréable. En attendant, n&rsquo;hésitez pas à liker, commenter et partager pour soutenir l&rsquo;audience de la page, c&rsquo;est aussi ça qui nous motive à continuer</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec le retour de nos publications. En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
{ img("/img/aceattorneyobjection.jpg",  "Une image du jeu Ace Attorney où il cri OBJECTION!",  "width:100%" ) }
        </div>)
  }