
import { Article } from "@/atoms/Article";

export const Article20220828LechodeslabosMetadata = {"tags":["suspension","censure abusive","Facebook","cogito ergo seum","complotist deleter","les Vaxxeuses","Hervérifie","ban"],"title":"L'écho des Labos…","description":"Comme vous êtes probablement en train de le constater avec dépit, il n’y a pas d’Echo des Labos cette semaine…","date":"2022-08-28","layout":"layouts/post.njk"}

export const Article20220828Lechodeslabos : Article = ({
  className, title
}) => {
  return (<div className={className}>
      <h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Chère audience,</p>
<p>Comme vous êtes probablement en train de le constater avec dépit, il n&rsquo;y a pas d&rsquo;Echo des Labos cette semaine, et il n&rsquo;y en aura pas d&rsquo;autres tant qu&rsquo;au moins un des appels que nous avons fait concernant la censure abusive de Facebook n&rsquo;aura pas été examiné. Pour rappel, cela fait depuis le 1er juin que nous réclamons qu&rsquo;un modérateur humain prenne 3 minutes pour lire la chronique incriminée, ce qui est le temps nécessaire pour différencier la désinformation du débunkage. Le nouveau strike dont nous avons été victimes cette semaine met clairement la page en sursis. Il a bien sûr été immédiatement contesté par l&rsquo;équipe, mais l&rsquo;appel n&rsquo;a, lui non plus, toujours pas été examiné. Comme les sanctions s&rsquo;appliquent toujours avant les appels, un troisième strike sonnerait la disparition pure et simple de la page (et ce probablement même si la modération finissait par reconnaître son tort sur les appels précédents…).</p>
<p>Nous ne sommes pas les seuls dans ce cas, bien loin de là. J&rsquo;ai une pensée particulière pour <a href="https://www.facebook.com/Stand4science/?__cft__%5B0%5D=AZVmBNkPITIEARPesYBR-moI5iFqKOaDRybnzo53lOM4vKQqe6d_Mcnrl6zJNRHvSLTEat74RFl6xXoNDwRDsDSO1xkumqZ1aI8sA9J3eqGkrq25hcTxPs8FeN1weodRJP3mcgwrI_7zxsMOAdOihedZ1BqB4uj0cDKbE7g66mtnmw&#x26;__tn__=kK-R">Cogito Ergo Seum 2</a>, qui en est à sa deuxième page pour les mêmes raisons, <a href="https://www.facebook.com/ComplotistDeleterFR/?__cft__%5B0%5D=AZVmBNkPITIEARPesYBR-moI5iFqKOaDRybnzo53lOM4vKQqe6d_Mcnrl6zJNRHvSLTEat74RFl6xXoNDwRDsDSO1xkumqZ1aI8sA9J3eqGkrq25hcTxPs8FeN1weodRJP3mcgwrI_7zxsMOAdOihedZ1BqB4uj0cDKbE7g66mtnmw&#x26;__tn__=kK-R">Complotist Deleter</a> qui a vécu avec l&rsquo;épée de Damoclès lui piquant le crâne pendant des mois, <a href="https://www.facebook.com/vaxxeuses/?__cft__%5B0%5D=AZVmBNkPITIEARPesYBR-moI5iFqKOaDRybnzo53lOM4vKQqe6d_Mcnrl6zJNRHvSLTEat74RFl6xXoNDwRDsDSO1xkumqZ1aI8sA9J3eqGkrq25hcTxPs8FeN1weodRJP3mcgwrI_7zxsMOAdOihedZ1BqB4uj0cDKbE7g66mtnmw&#x26;__tn__=kK-R">Les Vaxxeuses</a>, chez qui ce genre de bataille est devenu le quotidien, ou encore <a href="https://www.facebook.com/HERVERIFIE?__cft__%5B0%5D=AZVmBNkPITIEARPesYBR-moI5iFqKOaDRybnzo53lOM4vKQqe6d_Mcnrl6zJNRHvSLTEat74RFl6xXoNDwRDsDSO1xkumqZ1aI8sA9J3eqGkrq25hcTxPs8FeN1weodRJP3mcgwrI_7zxsMOAdOihedZ1BqB4uj0cDKbE7g66mtnmw&#x26;__tn__=-%5DK-R">Hervérifie</a>, dont le merveilleux travail est plus ou moins shadow ban de la plateforme. Si je me refuse à publier une nouvelle chronique cette semaine, c&rsquo;est parce que je sais que le travail des vulgarisateurs est important, et que chaque perte est lourde pour notre communauté. Je n&rsquo;ai pas la prétention d&rsquo;être un poids lourd, mais j&rsquo;en connais quelques-uns, je sais qu&rsquo;ils sont fatigués, qu&rsquo;on ne peut pas attendre tout d&rsquo;eux, et que chaque travail que les petits comptes comme le nôtre font est une charge en moins pour eux. La machine tourne parce que nous sommes nombreux.</p>
<p>Mais elle tourne mal. Elle tourne mal, déjà, parce que le boulot que nous faisons, nous sommes obligés de le faire parce que ceux dont cela devrait être la charge ne le font pas. Comment cela se fait-il que cela ait été à nous d&rsquo;alerter sur les magouilles de l&rsquo;IHU, sur l&rsquo;arnaque Jean-Dominique Michel, sur la dérive Mucchielli ? Où étaient les ARS, les journalistes, le CNRS qui auraient dû procéder à des contrôles, vérifier le background de leurs interviewés, sanctionner les dérives ? Où était le Conseil de l&rsquo;Ordre quand des médecins prescrivaient du shampooing pour moutons à leurs patients pour les guérir du Covid ? Où était le ministère de la recherche quand des chercheurs étaient insultés, harcelés, menacés pour simplement expliquer leur métier ? Le travail que nous faisons est important parce que les institutions qui auraient dû être là pour vérifier, dénoncer, expliquer, ont failli.</p>
<p>Dès lors, la machine ne peut que mal tourner, parce qu&rsquo;elle est tenue par des bénévoles. Sans protection contre les mécontents qui croient qu&rsquo;ils ont tous les droits parce qu&rsquo;ils sont en colère, y compris celui de harceler, d&rsquo;insulter, de menacer, de diffamer. Sans protection contre les charlatans dénoncés, dont la force de frappe financière et populaire est sans commune mesure avec celle de leurs détracteurs. Sans protection, enfin, contre la gestion stupide, cynique et aveugle, des plateformes sur lesquelles le travail est produit. Car ne nous voilons pas la face : sans appeler au complot pour autant (ce qui serait un comble), force est de constater que s&rsquo;il faut aux grandes plateformes de réseaux sociaux 2 ans de pandémie avant de fermer un seul des douze plus gros comptes de désinformation, comptes dont la liste est publique depuis des années, tandis que l&rsquo;algorithme fait plus souvent qu&rsquo;à son tour sauter des pages comme la nôtre, on peut dire sans grand risque de se tromper que la véracité de l&rsquo;information n&rsquo;est pas le premier critère suivi par les plateformes pour savoir qui a le droit de publier chez elles.</p>
<p>On nous a souvent demandé « mais pourquoi vous n&rsquo;ouvrez pas plutôt un Wordpress ou autre truc du genre, et vous quittez Facebook, ça serait quand beaucoup plus simple ». Cela est vrai, cela serait plus simple. Mais je ne fais pas ça pour que ce soit simple, sinon, croyez-moi que je ferais autre chose. Faire un fraisier, c&rsquo;est simple, changer un joint de bac à douche, c&rsquo;est simple, faire pousser du persil, c&rsquo;est simple (sauf quand vous avez un chaton glouton à la maison…), mais rendre accessible au plus grand nombre la science dans un contexte de perte de confiance et de crise avec des hordes d&rsquo;illuminés prêts à vous mordre jusqu&rsquo;au sang pour défendre les gourous qui les exploitent, ça, ce n&rsquo;est pas vraiment simple. Je n&rsquo;ai jamais fait ça parce que c&rsquo;était simple, je l&rsquo;ai fait parce que c&rsquo;était nécessaire. Et je pense que, parmi tous ceux que j&rsquo;ai croisés dans cette activité, que ce soit lors d&rsquo;évènements massifs comme le REC ou en privé lors de session de travail, c&rsquo;est ce qui nous a fait tenir : ce que nous faisons est nécessaire. Et de fait, la page se doit de rester là où elle est nécessaire, c&rsquo;est-à-dire sur le terrain où la désinformation s&rsquo;étend. Le Débarquement, c&rsquo;était sans doute plus facile à vivre en Franche-Comté, mais c&rsquo;était pas là que c&rsquo;était le plus utile d&rsquo;être. Nous ne partirons pas de Facebook, parce que c&rsquo;est là qu&rsquo;est la bataille (après, je ne suis pas suicidaire non plus, je choisis mes batailles, et c&rsquo;est pour ça que je ne serai sans doute jamais sur Twitter : Verdun, c&rsquo;est un trop gros morceau pour moi).</p>
<p>Chez les vulgarisateurs, je ne connais personne qui ne soit pas usé, mais je sais que la plupart aussi sont prêts à tenir leur position aussi longtemps qu&rsquo;ils le pourront. Parce que, au bout du jour, ça paye (j&rsquo;avoue que le jour même du strike, le fait de savoir qu&rsquo;Irène Grosjean était dans la sauce a sauvé ma journée). Parce que, au milieu des insultes, on reçoit aussi plein de messages de gens qui nous disent combien notre travail a compté pour eux (je dis pas que j&rsquo;ai imprimé certains de vos messages et les ai affichés sur mon bureau pour m&rsquo;empêcher de jeter l&rsquo;éponge, je dis que c&rsquo;est une possibilité). Parce qu&rsquo;on a cette conviction que la science est un bien commun formidable, et qu&rsquo;il doit être partagé pour que chacun comprenne le monde qui l&rsquo;entoure et fasse des choix éclairés. Parce que je pense, enfin, que les chercheurs et les vulgarisateurs ont en commun un attrait profond pour la vérité, et que cela nous amène à préférer ce qui est juste à la facilité.</p>
<p>Il n&rsquo;y a pas d&rsquo;Echo des Labos cette semaine. Il n&rsquo;y en aura pas jusqu&rsquo;à ce que les appels aient été examinés, car le but est qu&rsquo;il puisse y en avoir encore, à l&rsquo;avenir, ou tout simplement que la page continue d&rsquo;exister pour accueillir de nouveaux formats, des questions, des collaborations, et continue à faire le travail qui est nécessaire, autrement, avec toutes les maigres armes à notre disposition. L&rsquo;homme à la pelle et moi, on a encore du travail, et j&rsquo;en connais certains qui seraient bien trop contents de notre disparition pour leur faire ce plaisir et leur laisser le champ libre.</p>
<blockquote>
<p>C&rsquo;est pour ça que je n&rsquo;abandonne jamais face à un adversaire. Pour le faire chier jusqu&rsquo;au bout.</p>
</blockquote>
    </div>)
}