
import {FC} from "react";

export const Article20221204LechodeslabosMetadata = {"tags":["covid","France Soir","Presse","Didier Raoult","Xavier Azalbert","météorite","Université d’Alberta","Canada","Tombée du Ciel","elaliite","elkinstantonite","variole du singe","Santé Publique France","Fact & Furious","harcèlement","permafrost","montée des eaux","Martine Wonner","Bill Gates","Bon Sens","plainte","Christian Peronne","Silvano Trotta","Bonsens.org"],"title":"l'Écho des Labos - 4 déc 2022","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2022-12-04"}

export type Article20221204LechodeslabosProps = {className?: string, title: string, img: (...args: unknown[]) => string, UTip: (...args: unknown[]) => string}

export const Article20221204Lechodeslabos : FC<Article20221204LechodeslabosProps> = ({
  className, title, img, UTip
}) => {
  return (<div className={className}>
      <dl>
<dt>{ img("/img/research.published.png",  "↓" ) }</dt>
<dd>Le meme où Léonardo di caprio et un gars discutent: J'ai fais mes recherches - J'adorerai les lire. Elles sont publiées où ? et caprio de regarde l'autre avec un air entre colère et incompréhension
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.<br />
Si vous aimez la chronique, vous pouvez nous soutenir sur { UTip( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Aujourd&rsquo;hui, plutôt qu&rsquo;un Fake isolé, parlons d&rsquo;une usine à Fake. France Soir vient de perdre son statut de service de presse (tous ceux qui ont crié «&nbsp;enfin&nbsp;» dénoncez-vous).</p>
<p>Oui, parce que, le sachiez-tu cher public, jusque-là, France Soir bénéficiait d&rsquo;aides publiques et d&rsquo;avantages fiscaux payés avec tes impôts pour raconter des salades à tout le monde et menacer les collègues de la guillotine. Oui, oui, les mêmes impôts qui payent l&rsquo;aide juridique de Didier Raoult quand il intente des procès perdus d&rsquo;avance à tout le monde au lieu d&rsquo;avoir des vrais arguments scientifiques oui, que veux-tu, je suppose qu&rsquo;il y en a déjà trop pour les écoles et les hôpitaux.</p>
<p>Concrètement, ça veut dire quoi (à part qu&rsquo;il faut être prêt à ce qu&rsquo;ils nous rebattent les oreilles pendant des semaines avec leur obsession comme quoi on les censure et que donc c&rsquo;est la preuve qu&rsquo;ils ont raison, bref, la routine habituelle quoi)&nbsp;? Ça veut dire qu&rsquo;il n&rsquo;est désormais plus possible d&rsquo;appeler France Soir un journal, comme il n&rsquo;est plus possible d&rsquo;appeler Wakefield un médecin ou un pain au chocolat une chocolatine. Ça veut dire aussi que France Soir va perdre une partie importante de ses revenus, et cela d&rsquo;autant plus que le blog était déjà coupé de la régie publicitaire de Google. Ça veut dire également que, en cas de procès (au hasard pour diffamation, ou menaces de mort, ou appels à la violence, vous avez le choix servez-vous), les responsables ne pourront plus se planquer derrière le secret des sources, puisque c&rsquo;est une prérogative de journalistes (et que pour ça il faut, soit bosser pour un journal, soit avoir une carte de presse) et seront donc tenus de révéler qui a écrit quoi. Ça veut peut-être, s&rsquo;il te plait petit Jésus, dire que Xavier Azalbert va arrêter de faire du fric en racontant des conneries et va donc se lasser et aller ennuyer quelqu&rsquo;un d&rsquo;autre ailleurs. Mais ça j&rsquo;avoue j&rsquo;y crois pas trop…</p>
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p>Aujourd&rsquo;hui, on va parler météorite.<br />
Alors, je sais, c&rsquo;est pas spécialement mon domaine et il y en a d&rsquo;autres qui font ça bien mieux que moi, sur Facebook ou sur Youtube (surtout sur Youtube d&rsquo;ailleurs). Mais, là il faut que je vous parle de ce cas.<br />
C&rsquo;est l&rsquo;université d&rsquo;Alberta, au Canada, qui a publié cette semaine un communiqué sur le sujet (<a href="https://www.ualberta.ca/folio/2022/11/new-minerals-discovered-in-massive-meteorite-may-reveal-clues-to-asteroid-formation.html">là</a>). Sans doute parce que la nouvelle était tellement énorme que ça allait de toute façon fuiter avant la sortie d&rsquo;un papier scientifique en bonne et due forme.</p>
<p>En examinant le contenu d&rsquo;une météorite (on parle là d&rsquo;un caillou de 15 tonnes tout de même, donc les prélèvements faits pour les analyses n&rsquo;ont détruit ni la roche, ni les légendes somaliennes à son sujet qui courent sur au moins 5 générations), les chercheurs y ont découvert deux nouveaux minéraux, inconnus sur Terre. Plus précisément, inconnus sur Terre à l&rsquo;état naturel, ils avaient pu être synthétisés par des chercheurs en laboratoire, mais ils n&rsquo;avaient à notre connaissance aucune existence ailleurs. Néanmoins, on connaissait donc leur composition et c&rsquo;est pour ça que la comparaison a pu être faite aussi vite et avec autant de certitude concernant les échantillons retrouvés dans la météorite.</p>
<p>«&nbsp;Tombée du Ciel&nbsp;», puisque c&rsquo;est ainsi que les locaux l&rsquo;appellent, est la première et seule à ce jour source naturelle au monde d&rsquo;elaliite (du nom de la ville El Ali, près d&rsquo;où elle a été découverte) et d&rsquo;elkinstantonite (du nom de Lindy Elkins-Tanton, Professeure spécialiste dans la formation des noyaux des planètes). Un troisième minéral pourrait également être identifié dans les prochaines semaines, certains échantillons n&rsquo;étant pas encore identifiés.</p>
<p>Toutefois, impossible de retourner sur place pour faire d&rsquo;autres prélèvements&nbsp;: les contacts des chercheurs sur place les ont informés que la météorite aurait été déplacée en Chine, à la recherche d&rsquo;un potentiel acquéreur…</p>
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Variole du singe</strong>&nbsp;: vous allez me dire «&nbsp;hé mais c&rsquo;est vrai qu&rsquo;il y avait ça aussi&nbsp;!&nbsp;» et vous aurez raison. Le dernier bilan de Santé Publique France compte 5 nouveaux cas (dont 3 sont des femmes, alors encore une fois remballez vos idées sur le fait que c&rsquo;est une maladie de gays, merci) sur le mois de novembre, pour un total de 4.109 cas en 7 mois. La dynamique inquiétante de l&rsquo;été a été drastiquement cassée et, si la situation est toujours sous stricte surveillance, on peut penser que la vaccination rapide des populations les plus exposées a permis de circonscrire l&rsquo;épidémie et d&rsquo;éviter qu&rsquo;elle ne se propage.</p>
<p><em>Source&nbsp;: Santé Publique France</em></p>
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Fact-checking et débunkage</strong>&nbsp;: nous déplorons cette semaine la mort de Fact &#x26; Furious (le site seulement, Antoine va bien… enfin bien…). Lassé du harcèlement permanent, de la diffamation (des plaintes sont en cours, mais le temps de la justice est long) et des menaces, son créateur a jeté l&rsquo;éponge. Il est le rappel triste et impitoyable que ce que nous faisons nous expose à des menaces et des dangers bien réels, que les gens dont nous démontons les erreurs et les mensonges n&rsquo;ont pas pour but de chercher la vérité et le débat mais bien de nous faire taire, et qu&rsquo;ils n&rsquo;hésiteront pas à user de tout ce qui est en leur pouvoir, même immoral, même illégal, pour parvenir à leur fin.</p>
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Permafrost</strong>&nbsp;: le changement climatique est un problème pour de nombreux aspects, de la montée des eaux à l&rsquo;augmentation des feux de forêts. Si on s&rsquo;en doutait déjà, de nouvelles études indiquent également la présence d&rsquo;un danger supplémentaire sous la glace. La fonte du permafrost pourrait libérer dans l&rsquo;air et réactiver des virus vieux de plusieurs dizaines de milliers d&rsquo;années. L&rsquo;une de ces études (<a href="https://www.biorxiv.org/content/10.1101/2022.11.10.515937v1.full">encore en pré-print</a>) a ainsi isolé dans le permafrost de Sibérie 13 souches virales dont une au moins est toujours infectieuse, même après près de 50 000 ans passés dans la glace… On en a vraiment pas fini avec les épidémies.</p>
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Covid &#45; Ordre des Médecins</strong>&nbsp;: bon, elle est plus très fraîche (la nouvelle, la nouvelle, les enfants&nbsp;!), mais Martine Wonner a été interdite vendredi dernier d&rsquo;exercice de la médecine pendant un an. En vrai, ça change pas grand-chose, puisqu&rsquo;elle faisait de toute façon partie des soignants suspendus pour refus vaccinal. Et c&rsquo;est pas plus mal, je rappelle quand même qu&rsquo;elle est psychiatre. Psychiatre. Est-ce que vous lui confieriez un membre de votre famille schizophrène ou paranoïaque, sérieusement&nbsp;? Un membre auquel vous tenez, je précise… Evidemment, Martine va faire appel et a fait savoir via son avocat (vous savez, le mec dans Hold Up qui expliquait que chaque fois qu&rsquo;on sacrifie une liberté au nom de la santé on la retrouve plus et qui a dû être très surpris quand les couvre-feux ont effectivement été levés…) qu&rsquo;elle ne comprenait pas ce qui lui était reproché. Ou comment dire que tu pannes rien à la biologie sans dire que tu pannes rien à la biologie…</p>
<p><em>Source&nbsp;: Conseil National de l&rsquo;Ordre des Médecins</em></p>
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Parfois, je me demande comment les gens en arrivent à faire ce qu&rsquo;ils font. Je sais, venant de la part de la nana qui a tout plaqué pour aller vivre à l&rsquo;autre bout de l&rsquo;Europe avec une bourse de recherche et un chat, c&rsquo;est un peu étrange, mais tout de même, il y a des choses qui me restent incompréhensibles. Comme le fait d&rsquo;intenter un procès à Bill Gates quand vous l&rsquo;avez jamais rencontré de votre vie.</p>
<p>Les génies qui ont tenté ça, c&rsquo;est Bon Sens (je vous laisse 5 secondes… c&rsquo;est bon, vous avez fini de rigoler, on peut reprendre&nbsp;?) qui avait intenté à Bill Gates en personne (pas sa fondation ou quoi que ce soit, le bonhomme himself) un procès pour… et bien on sait pas trop en fait. Et déjà, n&rsquo;importe quel juriste pourra vous dire que ça part mal.</p>
<p>Le collectif, ainsi que trois membres qui ont porté la plainte (Xavier Azalbert, le patron de plus-le-journal-France-Soir, Christian Peronne le plus-chef-de-service-de-Garches, et Silvano Trotta, le … mec qui croit que la Lune est creuse&nbsp;(?) s&rsquo;estimait en effet attaqué parce que en «&nbsp;soutenant que les soi-disant “complotistes” mettent en danger la vie des Français par leur remise en cause de l&rsquo;efficacité des vaccins contre la Covid-19 », Bill Gates « laisserait penser aux téléspectateurs que les actions sociales ou judiciaires entreprises par l&rsquo;association Bonsens.org seraient néfastes pour la population ». Ici, le collectif fait référence à une interview dans laquelle Bill Gates, à la question de comment il réagissait au fait que des gens croient qu&rsquo;il avait crée le virus, répondait « C&rsquo;est très étrange, je ne m&rsquo;y attendais pas. J&rsquo;ai dépensé des milliards sur les vaccins pour sauver des millions de vies. Et maintenant, ils ont complètement retourné la situation en disant que je gagne des milliards en tuant des gens. D&rsquo;une certaine manière, c&rsquo;est assez humoristique, mais c&rsquo;est aussi problématique. Cela décourage des gens qui pourraient prendre le vaccin et c&rsquo;est notre meilleur outil pour empêcher des morts. De ce point de vue-là, c&rsquo;est quelque chose de tragique. J&rsquo;aimerais que les faits soient mis en avant : c&rsquo;est un excellent vaccin et nous essayons de faire de notre mieux pour sauver des vies. »</p>
<p>Alors, j&rsquo;ai cherché. Mais les mecs ont donc porté plainte au motif que les traiter de complotistes était une attaque, contre un mec qui ne les cite nulle part et ne prononce même pas le terme de complotiste… Je sais même pas comment a pu leur venir à l&rsquo;idée que peut-être, dans une certaine version de l&rsquo;univers, ça pouvait marcher… C&rsquo;est triste car ça encombre les tribunaux qui n&rsquo;ont pas besoin de ça, mais on peut quand même se réjouir car l&rsquo;association, en plus d&rsquo;avoir été évidemment déboutée, a été condamnée à payer les frais de justice de Bill Gates, et je subodore que son avocat doit avoir un tarif horaire au prix de mon loyer.</p>
<h3 id="point-methode-de-la-semaine-devenir-chercheur--on-étudie-quoi-le-parcours"><a href="#point-methode-de-la-semaine-devenir-chercheur--on-étudie-quoi-le-parcours">POINT METHODE DE LA SEMAINE&nbsp;: Devenir chercheur &#45; On étudie quoi&nbsp;? Le parcours</a></h3>
<p>Merci à ceux qui ont fait des suggestions dans les commentaires concernant ce vaste point méthode sur comment on devient un brave petit soldat surcaféiné qui sert la science parce que c&rsquo;est sa joie. J&rsquo;ai séparé certaines parties par rapport à ce que j&rsquo;avais annoncé, donc ce sera un peu plus long que prévu, mais j&rsquo;espère plus complet et mieux organisé. On va commencer aujourd&rsquo;hui avec la question de comment on devient chercheur, et plus précisément quel parcours on emprunte quand on se destine à ça.</p>
<p>Et tout de suite, je vais devoir faire deux catégories d&rsquo;aspirants chercheurs&nbsp;: les Appelés et les Reconvertis.</p>
<h4 id="les-appelés"><a href="#les-appelés">Les Appelés</a></h4>
<p>La révélation leur est tombée dessus un jour comme les livres sur la tête dans une bibliothèque mal rangée (rigolez pas, j&rsquo;ai fini aux urgences pour ça). Ils ont toujours su qu&rsquo;ils voulaient faire de la recherche, ou du moins assez tôt, et ils ont donc un parcours relativement en ligne droite. Relativement.<br />
Ils entrent d&rsquo;abord à l&rsquo;université pour une licence (3 ans) à l&rsquo;issue de laquelle ils vont être admis en master. Les choses se corsent déjà à ce moment-là, car toutes les universités n&rsquo;ont pas les mêmes équivalences entre licence et master, surtout si l&rsquo;étudiant change de pays. Il n&rsquo;est pas inhabituel qu&rsquo;on impose à l&rsquo;étudiant, qu&rsquo;il arrive en première ou en seconde année de master, de faire un mois, un semestre voire une année (ça c&rsquo;est plus rare) de mise à niveau. Soit parce que les universités n&rsquo;arrivent pas à trouver d&rsquo;équivalence, soit parce qu&rsquo;il y a une différence de niveau, soit parce que l&rsquo;étudiant change de pays et apprend la langue, soit parce qu&rsquo;il change un peu de spécialité, pas assez pour devoir refaire une licence mais assez tout de même pour qu&rsquo;il y ait un peu de travail. Par exemple, j&rsquo;ai moi-même eu à faire un mois de remise à niveau avant mon entrée en Master 2 à Descartes lorsque je suis venue à Paris depuis Lille.</p>
<p>Au cours de leur Master, les étudiants vont commencer à s&rsquo;intéresser à un ou des sujets sur lesquels ils ont envie de travailler et vont devoir 1-trouver un encadrant 2-le convaincre que le sujet est bon 3-apporter quelque chose sur le sujet en question. Durant cette période, l&rsquo;étudiant va progressivement muter en apprenti chercheur&nbsp;: il va devoir fabriquer du contenu scientifique. C&rsquo;est généralement assez simple, on peut pour son master faire un état de l&rsquo;art d&rsquo;une question dans une discipline (ça casse pas trois pattes à un canard mais c&rsquo;est un travail honnête et utile). On peut aussi être plus ambitieux et produire un type de mémoire qu&rsquo;on va appeler «&nbsp;prolégomène de thèse&nbsp;» (en gros, l&rsquo;étudiant a identifié un problème, une question, un vide, il a fait un état de l&rsquo;art dessus, il propose une hypothèse de travail et expose un plan d&rsquo;attaque de comment qu&rsquo;il faudrait faire pour savoir si l&rsquo;hypothèse est correcte ou non). L&rsquo;étudiant qui fait ça termine son Master (2 ans) en ayant déjà quasiment un projet de thèse sous le bras, et il lui est alors plus facile de démarcher université et directeurs potentiels. A noter que les places en thèse sont rares (du fait de la pénurie de financement et de professeurs, car chaque enseignement ne peut encadrer que 10 thésards, ce qui est déjà énorme), et un étudiant n&rsquo;a quasiment aucune chance d&rsquo;en décrocher une, encore moins financée, s&rsquo;il ne termine pas son Master avec au moins 15 de moyenne et une mention bien ou très bien à son mémoire.</p>
<p>Par la suite, l&rsquo;apprenti chercheur va devoir décrocher une place en thèse, et il en existe de trois types. Pour la thèse «&nbsp;simple&nbsp;», il faut trouver un directeur et le convaincre de vous prendre sous sa supervision, puis il faudra convaincre l&rsquo;école doctorale à laquelle il est relié de vous accepter en thèse et, de plus en plus, il faudra trouver un financement tout seul. Les labos ont chaque année quelques places en doctorat financé, mais ce n&rsquo;est pas toujours le cas, le nombre est variable, parfois il faut accepter un sujet imposé et c&rsquo;est souvent pour ceux qui ont déjà fait leur master au sein du même laboratoire. Pour la thèse en co-tutelle, c&rsquo;est pareil sauf qu&rsquo;il faut recommencer le même cinéma avec un autre superviseur dans une autre université en plus des étapes précédentes. Ce type de thèse est utilisée principalement sur des projets européens, pour répondre à des problématiques qui affectent plusieurs pays qui collaborent pour les résoudre ou en cas de besoin d&rsquo;un travail de terrain à l&rsquo;autre bout du monde. Pour la thèse Cifre, en plus de l&rsquo;inscription à l&rsquo;université, le doctorant va aussi être en entreprise, avec un superviseur supplémentaire. Le but est de se partager entre l&rsquo;université et le service R&#x26;D de l&rsquo;entreprise, afin de l&rsquo;aider à résoudre un problème de science appliquée. Ce type de thèse est particulièrement intéressant financièrement et pour les doctorants qui se destinent à l&rsquo;industrie. Ces démarches sont longues et complexes, et il n&rsquo;est pas rare que les aspirants chercheurs passent une année «&nbsp;vide&nbsp;» à chercher leur financement, leur encadrant ou à effectuer des stages dans des laboratoires susceptibles de les recevoir l&rsquo;année suivante.</p>
<p>Quoi qu&rsquo;il en soit, aujourd&rsquo;hui, une thèse dure de plus en plus 3 ans pile, en particulier parce que beaucoup de financements refusent d&rsquo;aller au-delà, et beaucoup d&rsquo;universités refusent la réinscription en thèse passée la 4e année, hors situation exceptionnelle (congé maternité, maladie grave, service militaire pour les pays concernés etc.). Quelques exceptions de domaines existent (par exemple on sait que les thèses en archéologie sont longues car il y a souvent des délais pour accéder aux terrains de fouilles), mais ce sont des exceptions. Le docteur sort donc docteur de l&rsquo;université au bout de 8 à 10 ans, selon la facilité de transition entre les étapes. Et il est pas au bout de ses peines, mais ça, on en reparlera plus tard.</p>
<h4 id="les-reconvertis"><a href="#les-reconvertis">les Reconvertis</a></h4>
<p>Le parcours est différent. Ce sont souvent des gens déjà bien diplômés (ingénieurs, détenteurs d&rsquo;un master ou équivalent) qui ont travaillé en R&#x26;D pendant des années, et qui se sont de plus en plus sentis limités dans ce qu&rsquo;ils faisaient. Ils avaient besoin de travailler sur quelque chose plus en profondeur, ils avaient besoin de résoudre de manière scientifique et non plus juste technique, bref, ils ont tourné un jour leurs yeux vers la Science et elle leur a répondu. Les reconversions complètes (des gens qui repartent à zéro depuis la licence parce qu&rsquo;ils ont eu une révélation) sont rarissimes. Mais elles existent. On en a un dans le département comme ça. Les Reconvertis vont devoir passer par le même parcours du combattant pour trouver leur place en thèse, avec en plus la difficulté de l&rsquo;âge&nbsp;: catapultés dans des groupes de jeunes chercheurs bien plus jeunes qu&rsquo;eux et à qui on a plus envie d&rsquo;accorder une place, c&rsquo;est principalement leur réseau professionnel qui va leur servir.</p>
<p>Quoi qu&rsquo;il en soit, pour arriver au bout du parcours, il faut déjà être quelqu&rsquo;un qui en veut&nbsp;: selon les disciplines, entre 30% et 50% des doctorants abandonnent en cours de thèse.</p>
<p>Voilà pour ce qui est du parcours, la semaine prochaine on regardera plus en détail qu&rsquo;est-ce qu&rsquo;on apprend comme compétences tout au long de ce parcours et pourquoi on écrit une thèse pour devenir docteur.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec l&rsquo;ouverture du calendrier de l&rsquo;avent. En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur <a href="https://www.facebook.com/TheDendrobateDoctor/?ref=page_internal">la page Facebook du Docteur</a>.</p>
    </div>)
}