
import { Article } from "@/atoms/Article";

export const Article20221002LechodeslabosMetadata = {"tags":["fake-up","covid","justice"],"title":"2 octobre 2022","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste. Bienvenue à tous sur l'Echo des Labos.","date":"2022-10-02"}

export const Article20221002Lechodeslabos : Article = ({
  className, title, UTip, img
}) => {
  return (<div className={className}>
      <h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { UTip( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Le « fake » de la semaine… c&rsquo;est Fake-Up. Celui qu&rsquo;on a attendu sans qu&rsquo;il arrive et qui est finalement arrivé quand on ne l&rsquo;attendait plus. Il rassemble le travail de débunkage que nous avons fait avec le collectif Covid19Fédération sur le faux documentaire Hold-Up, un travail collectif long et méticuleux, qui m&rsquo;a donné de sacrés maux de tête (comme souvent quand je travaille trop longtemps sur écran), une animosité épidermique contre Martine Wonner (mais je vous jure que si vous aussi vous aviez passé 3h sur un extrait de 15 minutes pour vous rendre compte que la personne ment effrontément trois fois par phrase, ça vous ferait ça aussi), et un sentiment étrange de vacuité de l&rsquo;existence face à ce bousin auquel il a fallu consacrer le temps qui passe et ne se rattrape guère, oui, que de temps perdu qui ne se rattrape plus, mais je m&rsquo;égare.<br />
Fake-Up, c&rsquo;est la loi de Brandolini poussée jusqu&rsquo;à l&rsquo;art. Il aura fallu quelques semaines de tournage pour produire 2h53 de n&rsquo;importe quoi, et contredire ça aura nécessiter près de 2 ans de travail et 4h40 de film. Oui, on a pas fait les choses à moitié.<br />
Est-ce que le documentaire est toujours d&rsquo;actualité ? Oui, car les mécanismes conspirationnistes sont toujours les mêmes, et ils fonctionnent à pleine balle aujourd&rsquo;hui, en particulier avec la guerre en Ukraine. Et aussi parce que maintenant, on est sûrs qu&rsquo;être vacciné ne vous fait pas tomber raide mort au beau milieu de la rue (sinon vu le nombre de doses injectées, ça ferait sacrément désordre), donc on peut bien montrer que non seulement le film mentait, mais aussi comment et pourquoi.<br />
Donc allez regarder Fake-Up (en tout cas la première partie, de 1h40, qui est là <a href="https://www.youtube.com/watch?v=QTIs1exv-R0">https://www.youtube.com/watch?v=QTIs1exv-R0</a> et n&rsquo;hésitez pas à le diffuser autour de vous, si Barnérias a fait des centaines de milliers d&rsquo;euros avec son torchon, le travail de Clément mérite au moins le soutien d&rsquo;estime.</p>
<hr />
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p>La découverte de la semaine, ou plutôt l&rsquo;exploit de la semaine, c&rsquo;est DART. DART c&rsquo;est (enfin c&rsquo;était, paix à son âme artificielle) un intercepteur. C&rsquo;est-à-dire qu&rsquo;on a fabriqué un truc très cher sur lequel plein plein de gens très compétents ont travaillé pendant des années pour le mettre dans un satellite encore plus cher et l&rsquo;envoyer s&rsquo;écraser sur un caillou dans l&rsquo;espace. Non, mais, dit comme ça, forcément…<br />
DART est allé s&rsquo;écraser pleine balle sur un astéroïde appelé Dimorphos (ça veut dire Le Moche… les astronomes sont pas forcément les champions de la bienveillance on va dire). Dimorphos fait un peu plus de 160m de diamètre et vivait sa vie de caillou de l&rsquo;espace tranquille autour de Didymos, un encore plus gros caillou, jusqu&rsquo;à ce qu&rsquo;on vienne l&rsquo;emmerder. En le percutant, DART avait deux objectifs. Tout d&rsquo;abord, soulever…quelque chose. De la poussière, de la caillasse, de la glace, selon de quoi Dimorphos est constitué, afin de permettre aux astronomes de faire des photos de la poussière et d&rsquo;apprendre des trucs sur la composition des astéroïdes. Mais surtout, en lui rentrant dans le chou comme ça, DART a perturbé la trajectoire de Dimorphos, et cette déviation va être étudiée, de manière à pouvoir servir à l&rsquo;avenir de moyen de défense. En effet, si Dimorphos, et plus encore Didymos, ne présentent aucun danger pour la Terre, le risque qu&rsquo;un astéroïde nous fonce droit sur la tête est lui bien réel, et si cela devait arriver, il serait un peu tard pour se demander seulement à ce moment-là « hé les gars, quoi qu&rsquo;on fait ? ». Avec les vitesses de déplacement des corps célestes, il est tout à fait possible qu&rsquo;une simple pichenette suffise à dévier un bolide qui viendrait dans notre direction, mais on ne sait pas quelle force il faut pour le bouger de combien, et c&rsquo;est ça que les chercheurs vont étudier dans le cas de Dimorphos et Didymos. Mais la réussite de l&rsquo;interception par DART est déjà un exploit. Il faut penser qu&rsquo;on est sur un gros caillou qui file dans le vide en tournant sur lui-même, qu&rsquo;on a lancé un machin de 600 kilos à 22.000 km/h pour aller percuter un machin de même pas 200m qui file à 24.000km/h à plus de 11 millions de kilomètres de là. Et on l&rsquo;a touché. C&rsquo;est pas beau ça quand même ?</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Covid</strong> &#45; Blocage de la dissémination : alors que Omicron et sa petite famille se répandent partout, et que l&rsquo;efficacité de l&rsquo;immunité, vaccinale comme post-infectieuse, semble reculer, les chercheurs de l&rsquo;Inrae proposent un nouvel angle d&rsquo;attaque. Ils ont en effet réussi à synthétiser des protéines capables de reconnaître la protéine Spike du virus, de s&rsquo;y lier et de l&rsquo;empêcher ainsi d&rsquo;utiliser sa « clé » génétique pour entrer dans les cellules humaines et s&rsquo;y reproduire, bloquant ainsi sa dissémination. Les traitements issus de ces protéines, appelés AlphaReps, sont de plus très stables et peu coûteux à produire (ça va les paranos de BigPharma, vous pouvez lâcher votre clavier). Des études plus poussées vont démarrer prochainement afin de mettre au point un traitement nasal qui empêchera la dissémination dans les poumons et possiblement la contagion.</p>
<p>Source : Inrae</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Covid</strong> &#45; Cherry Picking : alors, on va devoir refaire un coup sur le cherry picking dans le point méthode de la semaine… parce qu&rsquo;il est assez frustrant de constater que certains n&rsquo;ont toujours rien compris. Lorsqu&rsquo;il existe un nombre important d&rsquo;études sur un sujet (au hasard, mais alors vraiment au hasard, hein, le Covid) vous ne pouvez prendre les résultats de quelques études qui vous arrangent parce qu&rsquo;elles vont à contresens du reste… et cela encore moins en ne lisant pas les conclusions que les chercheurs portent sur leurs propres travaux. Par exemple, vous ne pouvez pas brandir un seul article (c&rsquo;est marrant, d&rsquo;un seul coup, les antivax ont plus de problème à citer le Lancet quand ils en ont besoin) disant que la vaccination augmente le risque d&rsquo;infection, quand au sein de l&rsquo;étude même les chercheurs disent que cette conclusion est probablement erronée à cause des données manquantes et insistent sur la nécessité d&rsquo;avoir des échantillons complets (vous pouvez aller vérifier cet aspect dans la partie <a href="https://www.thelancet.com/journals/landia/article/PIIS2213-8587(22)00158-9/fulltext#seccestitle160">Discussion de l&rsquo;étude</a>). Ou alors, vous ne pouvez pas affirmer que LE VACCIN (désolée, je peux pas résister) est « 18 à 98 fois pire que le virus » comme je l&rsquo;ai vu passer, quand la seule chose que vous avez pour soutenir cette affirmation, c&rsquo;est un article unique calculant avec une méthodologie pourrie que chaque décès évité grâce à la dose de booster chez les jeunes (et uniquement en étudiant cette partie-là, donc en omettant les bénéfices de toutes les autres doses et populations) est « échangé » en quelque sorte contre 18 à 98 hospitalisations auto-déclarées, article qui n&rsquo;a jamais passé la revue par les pairs (et non, je ne vous mettrai pas le lien pour celui-là, c&rsquo;est pas hygiénique sur ma page). Est-ce qu&rsquo;on peut admettre que les antivax ont faux sur toute la ligne depuis des mois et commencer à parler de vraie science correctement, s&rsquo;il vous plait ?</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Covid</strong> &#45; Reprise : avec la rentrée des classes, on teste à nouveau à tours de bras en France. La barre du million de tests par semaine a été franchie à nouveau en France, et le taux d&rsquo;incidence remonte, que c&rsquo;est surprenant dis-moi donc Gertrude ! Même qu&rsquo;il paraitrait qu&rsquo;on approche le chiffre des 400 cas pour 100.000 habitants et qu&rsquo;on a pris 30% en une semaine, qui l&rsquo;eut cru ? Pis c&rsquo;est qu&rsquo;avec un R à 1.3, c&rsquo;est pas près de s&rsquo;arranger tout ça, dis voir, hein… Une aspirine ?</p>
<p>Source : Santé Publique France</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Justice</strong> &#45; Ordre des avocats : je l&rsquo;ai dit, il ne faut pas rire du malheur des gens. Mais parfois, y en a, on les a tellement dans le nez que ça fait du bien quand même quand ça leur tombe sur le coin de la tronche. Di Vizio a été convoqué devant le conseil de son ordre, parce qu&rsquo;à force de raconter autant d&rsquo;absurdités dégueulasses qu&rsquo;un platiste du Ku Klux Klan sous LSD, fallait bien que ça arrive. La sanction ne pourra hélas pas être bien lourde, car aucun de ses clients n&rsquo;a techniquement porté plainte contre lui, c&rsquo;est simplement l&rsquo;Ordre qui s&rsquo;autosaisit, mais le réquisitoire en fin d&rsquo;audience a réclamé qu&rsquo;il soit suspendu pendant 6 mois, dont 3 fermes. Et en vrai, si ça peut l&rsquo;empêcher de représenter Raoult pendant l&rsquo;appel ou d&rsquo;instruire la trinité de plaintes de l&rsquo;hyperdocteur, ce sera toujours ça de pris.</p>
<p>Source : Conseil de l&rsquo;Ordre des Avocats de Paris</p>
<hr />
<h3 id="-quest-ce-que-putain-de-quoi--"><a href="#-quest-ce-que-putain-de-quoi--">« QU&rsquo;EST-CE QUE PUTAIN DE QUOI ? »</a></h3>
<p>Parfois, je me prends à rêver d&rsquo;un monde où les conspis n&rsquo;auraient jamais eu accès à Internet, et où, au lieu de faire des posts en majuscules sur le premier truc qu&rsquo;ils croisent, ils auraient été de fantastiques écrivains de science-fiction, de polar ou de fantasy, régalant le monde de leur plume féconde, au lieu de me donner des envies d&rsquo;exiger du comité olympique que le lancer de chaise<br />
sur cuistres deviennent une discipline officielle.<br />
Non parce que, en vrai, devinez ce qui est à l&rsquo;origine du dernier grand élan conspirationniste sur le thème de « la famine organisée » ? La rétention des stocks de blé en Ukraine ? Non. Les mauvaises récoltes mondiales pour cause de sécheresse ? Même pas. La pénurie de moutarde ? Ouh là, toujours pas. Non, c&rsquo;est un feu de palettes. Je plaisante pas, il y a des palettes qui ont pris feu dans un marché où on entasse des palettes en bois et tout un tas de trucs (genre des gens qui fument, au hasard). Alors, il s&rsquo;avère que c&rsquo;est Rungis. Mais justement : le feu a détruit 8.000 mètres carrés, tout le monde trouve ça énorme, mais Rungis, ça fait 234 hectares, les mecs. L&rsquo;incendie n&rsquo;a heureusement fait aucune victime, ne va pas empêcher le marché de continuer à tourner, même si ce sera peut-être un peu au ralenti le temps de l&rsquo;enquête, et n&rsquo;a pas détruit les stocks mondiaux de quoi que ce soit. La famine est donc loin d&rsquo;être à nos portes.<br />
Mais c&rsquo;est pas fini, non parce que certains pensent que l&rsquo;incendie (forcément criminel « comme Notre-Dame » alors que pour Notre-Dame, la cause accidentelle a été établie BREF) n&rsquo;avait pas pour but de provoquer la famine, mais de « purifier par le feu », de faire disparaitre les preuves de « quelque chose d&rsquo;inavouable ».<br />
…<br />
C&rsquo;est Rungis ! On parle vraiment du terrible complot inavouable des carottes et des choux de Bruxelles là ?! Tu veux faire disparaitre quoi par le feu, la preuve que Gérard a entubé Marcel sur le prix des patates alors qu&rsquo;il aurait pu les acheter vachement moins chères à Lucienne s&rsquo;il avait accepté un prix de gros avec les potirons ?! Je sais bien que les mecs sont capables de voir des souterrains pédo-satanistes option cannibalisme dans des pizzerias de quartier, mais est-ce qu&rsquo;on est sérieusement en train de débattre de si oui ou non quelqu&rsquo;un a cherché à purifier des navets pour servir un grand complot mondial ? Il reste quoi après, le contrôle mental reptilien par l&rsquo;eau du robinet ?! Comment ça, ça aussi ils l&rsquo;ont fait ?!</p>
<hr />
<h3 id="point-methode-de-la-semaine--retour-sur-le-cherry-picking"><a href="#point-methode-de-la-semaine--retour-sur-le-cherry-picking">POINT METHODE DE LA SEMAINE : retour sur le cherry picking</a></h3>
<p>Le cherry picking, littéralement cueillette des cerises, consiste globalement à monter dans un cerisier au mois d&rsquo;avril, à retirer les trois pauvres cerises qui sont vaguement mûres et en conclure que ça y est, c&rsquo;est la saison des cerises (non, c&rsquo;est juin, mai si vous êtes très au sud avec des variétés précoces).<br />
Le cherry picking fait ça avec les faits, et, lorsqu&rsquo;on parle de recherche, avec les études. Globalement, il faut bien se dire que tout, dans le monde, peut arriver par hasard. Vous pouvez tirer 100 fois de suite un 6 sur un dé non-pipé. C&rsquo;est possible, mais c&rsquo;est très rare. De fait, pour chaque étude, on établit une possibilité que les résultats qu&rsquo;on a obtenus soient dus au hasard chanceux, mais techniquement faux. C&rsquo;est aussi pour ça qu&rsquo;il est important d&rsquo;avoir plusieurs études sur le même sujet, afin de pouvoir avoir une image globale de la situation, où les études faussées par le hasard ne pèseront pas trop lourd. Elles ne sont pas truquées, elles ne sont pas forcément mauvaises ni même fragiles. Parfois, c&rsquo;est juste le hasard.<br />
Mais le cherry picking, c&rsquo;est constater que vous avez 10.000 boussoles qui indiquent que le Nord est en face de vous, et partir à gauche parce qu&rsquo;il y en a 3 qui disent qu&rsquo;en fait le Nord c&rsquo;est par là. Ce n&rsquo;est pas malin. Et si vous tentez de justifier votre choix auprès des gens en ne leur montrant que les 3 boussoles en question et en flanquant les autres dans le ravin, c&rsquo;est malhonnête.<br />
De fait, chaque fois que quelqu&rsquo;un vous met une étude sous le nez (oui, même quand c&rsquo;est moi) demandez-vous ce qu&rsquo;il y a d&rsquo;autre sur le sujet. Parfois, il n&rsquo;y a rien d&rsquo;autre, et c&rsquo;est pas grave, on va attendre. Parfois l&rsquo;étude renverse la table parce qu&rsquo;elle a une nouvelle méthodologie ou de nouvelles données, et c&rsquo;est peut-être très intéressant. Parfois l&rsquo;étude va dans le sens du consensus, et c&rsquo;est une pierre de plus à l&rsquo;édifice. Et parfois, c&rsquo;est juste une cerise vaguement rouge dans un arbre encore vert.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec la découverte de notre capacité à dévier les météores, un problème à la fois. En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
{ img("/img/fakeup.png",  "Affiche de Fake-Up première partie",  "width:100%" ) }
    </div>)
}