
    import { Article } from "@/atoms/Article";
    
    export const Article20231112LechodeslabosMetadata = {"tags":["covid","Pierre Chaillot","ONS","Office for National Statistic","décès","Angleterre","Royaume-Uni","rats","intelligence","imagination","réalité virtuelle","hippocampe","planétologie","Theia","Cannabis","THC","apoptose","microglies","adolescence","Sum’eau","Biodiversité","échidné à long bec d’Attenborough","montagnes des Cyclopes","Papouasie","Didier Raoult","IHU Marseille","Mathieu Molimard","AP-HM","hôpitaux de Marseille","ANSM","France Soir","Odysee"],"title":"l'Écho des Labos - 12 novembre 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Monbazillac, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-11-12","layout":"layouts/post.njk"}
    
    export const Article20231112Lechodeslabos : Article = ({
      className, title, img, quote, KissKissBankBank, Facebook
    }) => {
      return (<div className={className}>
          { img("https://www.towfigh.net/wp-content/uploads/bizarro-com-rats.png",  "voir figcaption en-dessous",  "width:100%" ) }
<dl>
<dt>Description &#x26; Traduction</dt>
<dd>l'éditrice
</dd>
<dt>Description</dt>
<dd>Deux scientifiques en blouses blanches, un homme à lunettes et une femme à chignon, l'homme dit: "Pendant que nous étudions les rats, ils nous étudiaient. Et, à la différence de la notre, leur étude a été publiée."
</dd>
<dt>Crédits</dt>
<dd>Bizarro.com — Bizarro Comics — Dan Piraro — 5/11/16
</dd>
</dl>
<p>{ img("/img/IMG-20231111-WA0007.jpg",  "voir figcaption en-dessous",  "width:100%" ) }</p>
<dl>
<dt>Description</dt>
<dd>Un graphique, de type courbes à marges, montrant l'évolution entre juillet 2021 et janvier 2023 en pourcentage de la population en Angleterre du "taux de décès chez les 18-39 ans en fonction du statut vaccinal" réparti en deux groupes:
<ul>
<li>Non vacciné</li>
<li>Vaccinés au moins une dose</li>
</ul>
</dd>
<dd>
<p>{ quote('Je ne veux pas fausser la compréhension du graphique par mon interprétation,  pour une meilleur compréhension s`en référer aux données et leurs analyse par le Biostatisticien et le Dendrobate Doctor dans la section "FAKE DE LA SEMAINE" du billet.',  "L'Éditrice" ) }</p>
</dd>
<dt>Crédits</dt>
<dd>Le Biostatisticien &#x26; le Dendrobate Doctor
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Monbazillac, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Le fake de cette semaine est une demande d&rsquo;un abonné. Pour être très honnête, moi et les stats ça fait deux, donc je me suis fait assister sur cette rubrique par mon cher ami Le Biostatisticien, que je remercie chaleureusement. La question de l&rsquo;abonné était en gros&nbsp;: «&nbsp;Que penser de l&rsquo;analyse que Pierre Chaillot fait de cette étude anglaise de septembre 2023 qui montre qu&rsquo;il y a plus de morts vaccinés que non vaccinés chez les jeunes&nbsp;?&nbsp;» La réponse rapide c&rsquo;est «&nbsp;pas du bien&nbsp;» mais c&rsquo;est un peu court jeune homme comme dirait l&rsquo;autre, alors décortiquons.</p>
<p>Déjà, mettons les pieds dans le plat tout de suite&nbsp;: il n&rsquo;y a pas d&rsquo;étude anglaise de septembre 2023. Voilà. Déjà ça, ça devrait suffire à ranger Chaillot au rayon guignols avec Gnafron et Kermit la Grenouille (aucun lien de parenté avec moi). Ce qu&rsquo;il présente comme une étude est un banal billet de blog, écrit par on ne sait qui, publié dans aucun journal et jamais revu par les pairs (sinon, ils auraient trouvé les grosses bêtises dont on va parler maintenant et auraient empêcher la publication de ce torchon). Donc point de vue crédibilité, c&rsquo;est niveau «&nbsp;Jawad explique qu&rsquo;il a juste rendu service quoi&nbsp;».</p>
<p>Mais admettons. Admettons qu&rsquo;il y ait derrière ce papier révélation un super vrai chercheur sérieux qui aura décidé de poster l&rsquo;article de sa vie vite fait en lousdé sur un pauvre blog avant de partir visiter sa vieille tata à Mont-de-Marsan plutôt que de publier dans un journal sérieux et donner du poids à son travail. Admettons. Ben même là, c&rsquo;est compliqué. C&rsquo;est compliqué parce que le post se focalise sur les 18-39 ans et déjà je comprends pas pourquoi&nbsp;: lorsque j&rsquo;ai dû aller vérifier les chiffres (parce que oui, vous pensez, j&rsquo;ai vérifié), il a fallu que j&rsquo;additionne deux catégories distinctes, les 18-29 ans et les 30-39 ans. Et ce n&rsquo;est pas très clair pour quelle raison l&rsquo;auteur a considéré que «&nbsp;les plus jeunes&nbsp;» c&rsquo;étaient ceux-là&nbsp;: ça n&rsquo;est pas un ajout logique (18-29, ok, mais les 30-39 ans, ce ne sont pas «&nbsp;les jeunes&nbsp;», je le sais, mes genoux le savent, mes lombaires le savent et les vôtres aussi probablement) et dans les différents tableaux de données, certains utilisent cette catégorie mais certains la subdivisent, et à aucun moment l&rsquo;auteur n&rsquo;explique pourquoi ce choix-là et en quoi il fait sens.</p>
<p>Mais bon admettons. Admettons que pour une raison qui m&rsquo;échappe, tellement géniale que l&rsquo;auteur n&rsquo;a pas senti le besoin de l&rsquo;expliquer dans le papier, cette catégorie fasse sens, et que ça soit pas juste du bricolage pour trouver ce qu&rsquo;on veut. Admettons. Et bien ça reste compliqué. C&rsquo;est compliqué parce que «&nbsp;l&rsquo;étude&nbsp;», qui se focalise sur les 18-39 ans (même s&rsquo;il y a plusieurs fois dans le texte 18-19 ans, mais bon, on va dire que à défaut de relecture par les pairs, il s&rsquo;est pas relu lui-même non plus), affirme que 30% de cette tranche d&rsquo;âge est non-vaccinée contre 70% ayant reçu au moins une dose (ce qui est discutable, mais une chose à la fois) et s&rsquo;étonne que le groupe vacciné ait plus de morts… alors qu&rsquo;il est plus de deux fois plus grand que le groupe non-vacciné. J&rsquo;ai arrêté les maths en seconde, mais même moi je vois que ça va pas là, Pierrot.</p>
<p>Cette conclusion est d&rsquo;autant plus stupide qu&rsquo;elle est par deux fois problématique. De un, concernant le fait que 70% des 18-39 sont vaccinés à au moins une dose, je n&rsquo;arrive pas à recouper cette statistique. Comme il y a autant de source sur ce post que sur la Lune, je me suis donc farcie d&rsquo;aller recompter MANUELLEMENT CANTON PAR CANTON les vaccinations dans cette tranche d&rsquo;âge (<a href="https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthinequalities/datasets/coronavirusandvaccinationratesinpeopleaged18yearsandoverbysociodemographiccharacteristicandregionengland">et comme moi je donne mes sources, si vous êtes maso, vous pouvez refaire les calculs à partir du fichier à télécharger là</a> en sélectionnant la version la plus récente du jeu de données, attention on est sur du tableur Excel qui fait plus de 55 MégaOctets…). Et je tombe sur le fait que plus de 80% de la tranche d&rsquo;âge mentionnée a en réalité reçue au moins une dose de vaccination. Comment ont-ils fait une erreur aussi grosse&nbsp;? Eh bien moi je pensais qu&rsquo;ils étaient nuls en maths, jusqu&rsquo;à ce que Le Biostatisticien refasse les calculs et me dise qu&rsquo;il trouvait le même chiffre qu&rsquo;eux. Peut-être que c&rsquo;était moi qui étais nulle en maths. On a donc regardé les jeux de plus près, et on s&rsquo;est aperçus qu&rsquo;ils étaient peut-être pas nuls en maths… mais en géographie. Parce que les mecs ont pris la mortalité toute cause en Angleterre et l&rsquo;ont comparée au taux de vaccination du Royaume-Uni, comme si c&rsquo;était le même pays. Ce que ça n&rsquo;est pas, en fait. On aurait pu s&rsquo;arrêter là, parce qu&rsquo;il n&rsquo;y a rien à tirer d&rsquo;une étude où on cherche une corrélation au sein de populations différentes. Mais on a continué, en prenant ce nouveau chiffre de 81% (Le Biostatisticien m&rsquo;a même fait un graph&nbsp;!). Donc, avec les vrais chiffres des vaccinations, quand l&rsquo;auteur s&rsquo;étonne que «&nbsp;oh la la, les vaccinés ils sont 70% et ils comptent pour 83% des morts&nbsp;», déjà on pourrait se dire que en fait, on a une catégorie qui fait 81% de la population concernée et qui compte pour 83% des morts. Ça pourrait être normal en fait (surtout si on tient compte du fait que, parmi les gens jeunes qui ont été vaccinés, il y a les individus les plus fragiles de cette tranche d&rsquo;âge). Mais ça, ce serait si ce pourcentage de mortalité était vrai. Et vous vous en doutez, s&rsquo;ils sont pas foutus de compter les vaccinés, c&rsquo;est pas mieux pour compter les macchabés.</p>
<p>Pour une fois, l&rsquo;article donne une source, un fichier de données issus de l&rsquo;ONS, l&rsquo;équivalent anglais (anglais, pas Royaume-Uni, d&rsquo;accord&nbsp;?) de l&rsquo;Insee. <a href="https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/deathsbyvaccinationstatusengland/deathsoccurringbetween1january2021and31may2022/referencetable06072022accessible.xlsx">Ce fichier, vous pouvez le télécharger</a>(si la première séance vous a pas suffit) pour vérifier ce que je vous dit, et je vous encourage à regarder par exemple la table 2 (oui, c&rsquo;est chiant, mais y a pas de raison que ce soit que moi qui m&rsquo;emmerde, ok&nbsp;?). Si on observe les données les plus récentes (aux alentours des lignes 690 par exemple), on constate que, en divisant le nombre de morts de chaque catégorie (non-vaccinés, 3e dose etc.) par le nombre de personnes de cette catégorie on tombe sur des chiffres sensiblement similaires (par exemple en mars 2022, il y a eu 0,00027 % de morts dans la catégorie «&nbsp;non-vacciné&nbsp;» comme dans la catégorie «&nbsp;vacciné 3e dose ou booster il y a plus de 21 jours&nbsp;»). Cette surmortalité des vaccinés est inexistante. «&nbsp;Mais alors, la grenouille, est-ce à dire que le vaccin n&rsquo;a pas non plus protégé les gens&nbsp;?&nbsp;» Pour répondre à ça, il faut compiler les données dans leur globalité, ce que je ne sais pas faire, mais ce que notre ami et ses poneys (mais surtout lui quand même) savent faire. Et le résultat, c&rsquo;est le graphique en illustration annexe aujourd&rsquo;hui. Même en proportion, même en regardant uniquement les groupes jeunes, les non-vaccinés meurent beaucoup plus que les vaccinés. Il y a deux moments d&rsquo;exception à ça&nbsp;: la période avant juillet 2021, où les vaccinés étaient majoritairement encore, surtout chez les jeunes, des gens très à risque, donc beaucoup plus susceptibles de mourir&nbsp;; et la période actuelle (même si l&rsquo;intervalle de confiance fait qu&rsquo;on est pas réellement sûr que les courbes se soient inversées), où les plus fragiles, donc plus susceptibles de mourir, sont toujours dans le groupe vacciné, et où les non-vaccinés bénéficient à la fois de l&rsquo;immunité de groupe (les gens sont vaccinés autour d&rsquo;eux et transmettent moins) et de l&rsquo;immunité post-infection (puisque la majorité d&rsquo;entre eux a eu le Covid au moins une fois). Le post de blog, la vidéo, l&rsquo;analyse de Chaillot, tout ça, c&rsquo;est du flan.</p>
<p>Moi, j&rsquo;ai arrêté les stats au lycée, mais je sais voir quand on fait dire aux chiffres des trucs qui vont pas. Chaillot est censé être économiste. Il n&rsquo;a aucune excuse à part une profonde malhonnêteté.</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>Ceux qui suivent mes travaux depuis quelques temps savent que les rats, pour mal-aimés qu&rsquo;ils soient, font partis de mes chouchous. Ce sont des animaux sociables, affectueux (mais oui), propres (je vous jure), pas agressifs pour deux sous (je vous assure) et surtout très, très intelligents. Mais si dans l&rsquo;intelligence, on englobe une large variété de caractéristiques, on pense rarement à celle de l&rsquo;imagination. Et pourtant, c&rsquo;est bien cette dernière qui vient d&rsquo;être mise en évidence chez nos petits amis rongeurs.</p>
<p><a href="https://www.science.org/doi/10.1126/science.adh6206">L&rsquo;expérience est incroyable</a>, alors accrochez-vous. Les petits sujets ont été tout d&rsquo;abord entrainés à se déplacer dans une arène de réalité virtuelle (et déjà rien que ça c&rsquo;est classe). Par la suite, ils ont été reliés à une interface cerveau-machine, en l&rsquo;occurrence reliée à leur hippocampe, une zone du cerveau impliquée dans la mémoire, et qui chez l&rsquo;humain est au cœur de notre capacité à «&nbsp;revivre&nbsp;» une expérience passée, comme quand on refait mentalement le chemin entre la porte d&rsquo;entrée et la chambre pour se souvenir de où on a posé ses clés de bagnole alors même qu&rsquo;on est dans l&rsquo;ascenseur.<br />
Une fois dans l&rsquo;arène, deux conditions d&rsquo;expérience étaient posées. Dans la première (dite Jumper), les rats devaient résoudre un problème en se déplaçant vers une zone déjà connue de l&rsquo;arène virtuelle, mais sans pouvoir faire le chemin en lui-même. Ils devaient «&nbsp;convoquer&nbsp;» la carte mentale de l&rsquo;endroit où ils voulaient se rendre et étaient «&nbsp;téléportés&nbsp;» à l&rsquo;endroit correspondant. Le taux de précision dont les rats ont fait preuve montre qu&rsquo;ils avaient une idée très claire de l&rsquo;agencement de l&rsquo;endroit où ils voulaient se rendre et qu&rsquo;ils manipulent cette carte mentale avec aisance. Dans la seconde condition (dite Jedi, je vous jure que c&rsquo;est vrai, je suis fan de cette équipe), les rats devaient déplacer un objet dans l&rsquo;espace virtuel, comme nous le faisons en déplaçant un objet dans un jeu vidéo grâce à une manette, mais en «&nbsp;convoquant&nbsp;» encore une fois la carte mentale de l&rsquo;endroit et en visualisant le trajet que l&rsquo;objet devait effectuer. Là encore, le taux de réussite montre la grande habilité des rats à imaginer un lieu dans lequel ils ne sont plus et des actions qu&rsquo;ils ne sont pas en train de faire. Chez les chercheurs, on parle de rien de moins que du «&nbsp;premier modèle animal de l&rsquo;imagination&nbsp;». Des bestioles incroyables, je vous dis&nbsp;!</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Planétologie</strong>&nbsp;: il y a un paquet d&rsquo;anomalies sur Terre, comme la foudre en boule, le cycle de reproduction du sabot de Vénus ou l&rsquo;existence des platistes, mais il y en a une qui était particulièrement intrigante du fait qu&rsquo;elle est située au cœur-même de la Terre. Le manteau de notre planète comporte ainsi deux énormes masses rocheuses (de la taille d&rsquo;un continent chacune, excusez du peu), découvertes dans les années 80, et qui n&rsquo;ont absolument rien à faire là. Leur présence pourrait avoir une explication qui résoudrait un second mystère&nbsp;: pourquoi ne reste-t-il aucun fragment visible de Theia, la protoplanète qui aurait percuté la Terre il y a 4.468 milliards d&rsquo;années, selon la théorie la plus solide à l&rsquo;heure actuelle d&rsquo;explication de formation de la Lune&nbsp;? <a href="https://www.nature.com/articles/s41586-023-06589-1">Les modélisations publiées par les chercheurs</a> apportent une piste d&rsquo;explication&nbsp;: il existe bien des fragments de Theia, mais ils ont été absorbés par le manteau de la Terre après l&rsquo;impact et constituent les poches anormales repérées il y a 40 ans. Clairement, le débat est loin d&rsquo;être clos, mais l&rsquo;hypothèse est élégante et convaincante d&rsquo;après la plupart des planétologues. Affaire à suivre.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Cannabis</strong>&nbsp;: dans notre beau pays, qui arrive à être à la fois consommateur numéro 1 de la plante favorite de Bob Marley et plus répressif législateur sur le sujet (signe que peut-être ça sert pas à grand-chose et qu&rsquo;on s&rsquo;y prend mal, mais bon, si on faisait de la démagogie en politique chez nous, ça se saurait), c&rsquo;est une nouvelle qui pose problème. <a href="https://www.nature.com/articles/s41467-023-42276-5">La dernière étude en date consacrée au THC, la principale substance active du cannabis, sur des souris en croissance,</a> montre que sa consommation à l&rsquo;adolescence induit l&rsquo;apoptose (c&rsquo;est-à-dire le suicide cellulaire) des microglies (des cellules immunitaires spécifiques au système nerveux central) dans le cortex préfrontal. Les souris consommatrices affichaient des scores de mémoire inférieurs de 40% à ceux des souris témoins. Si les résultats sur l&rsquo;animal doivent toujours être transposés à l&rsquo;humain avec prudence, ceux-ci sont particulièrement inquiétants car le phénomène d&rsquo;apoptose dans le système nerveux central entraîne en général un déficit permanent, en particulier s&rsquo;il a lieu dans une période de construction du cerveau comme l&rsquo;est l&rsquo;adolescence.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Covid</strong>&nbsp;: la reprise est bien là (levez la main ceux qui sont surpris), et c&rsquo;est les données du projet Sum&rsquo;eau (le projet de surveillance des eaux usées qui a pris le relais du projet précédent qui était arrêté on sait pas trop pourquoi mais que voulez-vous) qui le disent. <a href="https://www.data.gouv.fr/fr/datasets/surveillance-du-sars-cov-2-dans-les-eaux-usees-sumeau/">Disponibles en ligne</a>, elles montrent une augmentation fulgurante des cas depuis août et qui ne faiblit toujours pas&nbsp;: les cas augmentent encore et toujours et la courbe des contaminations ne s&rsquo;inverse toujours pas.</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Biodiversité</strong>&nbsp;: c&rsquo;est souvent, hélas, qu&rsquo;on apprend qu&rsquo;une espèce vivante s&rsquo;est éteinte. C&rsquo;est assez rare d&rsquo;apprendre l&rsquo;inverse. Et pourtant, les chercheurs se sont aperçus qu&rsquo;une espèce déclarée éteinte depuis plus de 60 ans était bien vivante. L&rsquo;échidné à long bec d&rsquo;Attenborough, un animal au moins aussi improbable que son cousin l&rsquo;ornithorynque puisqu&rsquo;il possède des pics de hérisson, un long museau d&rsquo;un fourmilier, des pattes d&rsquo;une taupe, et, manifestement, un cul bordé de nouilles, a pu être observé sur la toute dernière carte mémoire d&rsquo;un piège photographique au cours d&rsquo;une expédition de l&rsquo;enfer (intempérie, canicule, tremblement de terre, paludisme, sangsues, les mecs ont tout eu) de deux mois dans les montagnes des Cyclopes en Papouasie. La vocation, mesdames et messieurs&nbsp;! Et le machin se promenait là, tranquille, devant la caméra, à planter son museau dans le sol pour faire des petits trous, des petits trous, encore des petits trous. Nan mais vas-y, cousin, fait ta vie, t&rsquo;occupe pas des humains qui crient en se prenant dans les bras à côté, c&rsquo;est des biologistes, ils sont tous un peu frappés.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Didier. Sérieux, Didier, il va falloir arrêter. Il va falloir que tu arrêtes, parce que j&rsquo;ai même pas besoin de dire ton nom en entier, tout le monde sait de qui on parle, et tu emmerdes tous les autres Didiers qui sont des gens bien (en tout cas j&rsquo;en connais un, et c&rsquo;est quelqu&rsquo;un de très bien, donc tu arrêtes).</p>
<p>Si vous vous souvenez, l&rsquo;IHU s&rsquo;était retrouvé dans la tourmente lorsque son directeur avait publié une étude rétrospective en pré-print sur 30.000 patients qui était:</p>
<ol>
<li>écrite avec le postérieur (et encore, un postérieur pas très doué)</li>
<li>faite sur des patients sans consentement et sans aval d&rsquo;un comité d&rsquo;éthique ce qui est, genre, LA BASE.</li>
</ol>
<p>La défense de Didier donc ça a avait été:</p>
<ol>
<li>de dire «&nbsp;c&rsquo;est nous les gentils&nbsp;» (texto, sans rire)</li>
<li>retirer le pré-print pour «&nbsp;protéger&nbsp;» certains des auteurs.</li>
</ol>
<p>Ce qui marche pas, hein, de la même manière que brûler un cadavre n&rsquo;empêche personne d&rsquo;être condamné pour un meurtre (sauf si du coup on arrive pas à prouver que c&rsquo;est lui, mais c&rsquo;est encore autre chose).</p>
<p>Mais là, plot twist&nbsp;! Saroumane décide que, puisqu&rsquo;on l&rsquo;embête avec son papier de toute façon, il va le faire publier pour de vrai. Et il y arrive. Son papier, avec 30.000 patients et autant d&rsquo;infractions à la déontologie médicale et scientifique, a été publié. Dans un journal qu&rsquo;il a fondé spécifiquement pour recevoir tous ses papiers qui étaient rejetés des vrais journaux, on est d&rsquo;accord, mais publiés quand même. Avec en co-auteurs des gars qui bossent encore à l&rsquo;IHU (qui pour rappel est toujours sous surveillance étroite pour les malversations précédentes, franchement, comme dit Mathieu Molimard, ils voudraient couler l&rsquo;IHU, ils s&rsquo;y prendraient pas autrement).</p>
<p>Comme ça ne devait pas être assez ridicule comme ça, ils ont ajouté Peter McCullough dans les co-auteurs (qu&rsquo;on a déjà débunké plusieurs fois dans la chronique → (<a href="https://www.facebook.com/profile/100063579131125/search/?q=McCullough">lien vers les résultats de recherche sur la page Facebook</a>)(nde: <a href="/tags/mccullough/">une seule fois dans les archives du site, car elles ne couvrent pas tout l'historique</a>).</p>
<p>L&rsquo;AP-HM (les hôpitaux de Marseille, la co-tutelle de l&rsquo;IHU) condamne fermement la publication et rappelle qu&rsquo;ils n&rsquo;ont cessé de demander à ce que l&rsquo;étude soit retirée pour infraction grave aux droits des patients. L&rsquo;ANSM a annoncé qu&rsquo;elle portait plainte, juste après avoir accepté en octobre de commencer progressivement à lever les sanctions et restrictions contre l&rsquo;IHU.</p>
<p>Y en a vraiment un qui se fout de la gueule du monde.</p>
<hr />
<h3 id="point-méthode-de-la-semaine-oui-mais-et-sil-avait-raison-quand-même"><a href="#point-méthode-de-la-semaine-oui-mais-et-sil-avait-raison-quand-même">POINT MÉTHODE DE LA SEMAINE&nbsp;: Oui, mais, et s&rsquo;il avait raison quand même&nbsp;?</a></h3>
<p>Aujourd&rsquo;hui, je vais revenir un peu sur le Fake de la semaine. Lorsque l&rsquo;abonné qui me l&rsquo;a proposé m&rsquo;a écrit, il a commencé par reconnaître qu&rsquo;il savait que Pierre Chaillot n&rsquo;était pas fiable&nbsp;: il collaborait pour France Soir, a raconté n&rsquo;importe quoi pendant la crise Covid, bref. Mais pour autant, mon abonné trouvait que ce n&rsquo;était pas suffisant&nbsp;: et si malgré tout, il avait raison quand même&nbsp;? Car après tout, même une montre arrêtée donne l&rsquo;heure exacte deux fois par jour.</p>
<p>Une des raisons qui fait que les chercheurs attachent de l&rsquo;importance à la forme et non juste au fond, c&rsquo;est que, en réalité, l&rsquo;argument «&nbsp;oui mais, et s&rsquo;il avait raison quand même&nbsp;» ne tient pas, justement grâce à la forme.</p>
<p>Admettons que je trouve les résultats de Chaillot et que je sois sûre que j&rsquo;ai raison, et admettons que dans ce cas-ci, j&rsquo;ai effectivement raison.</p>
<p>Mon premier réflexe, ce serait d&rsquo;essayer de publier mon étude dans une revue à fort impact, fiable et connue, pour que mes résultats soient connus de tous, surtout pour un truc aussi grave. Pas de faire l&rsquo;analyse d&rsquo;un post de blog en vidéo sur Odysee.</p>
<ul>
<li>Mais admettons que, pour les raisons que vous voulez (corruption, censure, BigPharma, le Nouvel Ordre Mondial, Ta Sœur en Salopette), on m&rsquo;empêche de publier dans des grands journaux. A ce moment-là, ma meilleure option serait de mettre mon texte sur des serveurs de pré-print avec commentaires, afin que mes pairs puissent me lire librement et gratuitement, qu&rsquo;ils puissent commenter et critiquer, et que de l&rsquo;échange naisse le consensus. Pas de faire l&rsquo;analyse d&rsquo;un post de blog en vidéo sur Odysee.</li>
<li>Mais admettons que, pour ça, je reçoive des menaces, qu&rsquo;on essaye de cacher mon étude, de m&rsquo;intimider, et même que les gérants des sites de pré-prints subissent des pressions pour retirer mon papier. Dans ce cas, la bonne carte à jouer, ce serait de contacter les journalistes d&rsquo;un média d&rsquo;importance, avec une large audience et une bonne réputation (les journalistes, ça résiste difficilement à un scoop, encore plus si ça peut faire un scandale qui secoue des politiques dans un gouvernement impopulaire, ce serait le meilleur tirage de leur année). Pas de faire l&rsquo;analyse d&rsquo;un post de blog en vidéo sur Odysee.</li>
</ul>
<p>S&rsquo;il avait raison quand même, surtout s&rsquo;il avait raison en fait, Pierre Chaillot ou un autre, surtout sur un sujet aussi grave, son attitude serait de choisir une forme de publication qui lui assure que ses résultats soient connus de tous, et en particulier des gens qu&rsquo;il doit convaincre, à savoir les autres scientifiques. Pas de faire l&rsquo;analyse d&rsquo;un post de blog en vidéo sur Odyssée.</p>
<p>Une montre arrêtée donne l&rsquo;heure exacte deux fois par jour, mais on lui fait pas confiance pour aller prendre son TGV.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec la floraison des bleuets de France, même si symboliquement ça aurait été beau. En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
        </div>)
  }