
import {FC} from "react";

export const Article20230205LechodeslabosMetadata = {"tags":["covid","Project Veritas","Jordon Trishton Walker","Pfizer","Drugs for Neglected Diseases initiative","DNDi","trypanosoma brucei gambiense","mouche tsé-tsé","Afrique subsaharienne","anémie","troubles cardiaques","troubles rénaux","symptômes neurologiques","coma","acoziborole","Sanofi","République démocratique du Congo","rhume","Harvard","Benjamin Bleier","masque","FDA","U.S. FDA","double vaccination","vaccin bivalent","AVC","Académie des Sciences","Alain Fischer","Recherche en France","La Tronche en Biais","Thomas Durand","Arnaud Thiry","Astronogeek","Annie Lobé","Mouvement du Sang Pur","WhatsApp","Telegram","antivax"],"title":"l'Écho des Labos - 5 février 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-02-05"}

export type Article20230205LechodeslabosProps = {className?: string, title: string, img: (...args: unknown[]) => string, UTip: (...args: unknown[]) => string, abbr: (...args: unknown[]) => string}

export const Article20230205Lechodeslabos : FC<Article20230205LechodeslabosProps> = ({
  className, title, img, UTip, abbr
}) => {
  return (<div className={className}>
      <dl>
<dt>{ img("https://neofronteras.com/humor/wp-content/photos/voodoo_on_papers.png",  "↓" ) }</dt>
<dd>Un scientifique tente de pratiquer le voodoo ssur des papiers en y insérant des aiguilles.
</dd>
<dd>
<p>&#45; The Scientific Cartoonist, Voodoo on papers.</p>
</dd>
<dd>Sous license Creative Commons BY-NC-ND 2.5
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { UTip( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>J&rsquo;aurais voulu parler de la dernière sortie du Project Veritas la semaine dernière, mais je manquais encore de sources. Et je manque toujours de sources vérifiables à l&rsquo;heure actuelle, et c&rsquo;est bien ça le problème. La vidéo montre un homme présenté comme Jordon Trishton Walker, un haut responsable de Pfizer, en train d&rsquo;expliquer que le laboratoire modifie le virus du Covid pour le faire muter et produire des nouveaux vaccins.</p>
<p>Sauf que déjà, il est impossible de trouver la moindre source fiable concernant la réalité de l&rsquo;existence de ce monsieur, et encore moins de sa position chez Pfizer. Mais admettons qu&rsquo;il soit possible que quelqu&rsquo;un soit à un poste majeur d&rsquo;une des plus grosses compagnies du monde sans qu&rsquo;on puisse en trouver une trace claire en ligne nulle part…</p>
<p>Il y a ensuite un second problème&nbsp;: la vidéo, soi-disant réalisée en caméra cachée, n&rsquo;est pas d&rsquo;une traite, elle semble plus une collection de clips découpés, et, comme l&rsquo;interlocuteur qui filme n&rsquo;est pas visible, il est impossible de dire si les réponses correspondent aux questions posées. Du coup, il faut se demander s&rsquo;il y a quelque chose qui est, en tant que tel, problématique dans ce que dit l&rsquo;homme à l&rsquo;image. Et là aussi on est embêtés. Déjà, parce que les sous-titres disponibles sont très orientés, il faut aller chercher l&rsquo;audio original. Ensuite parce que, surtout en sachant que le discours est découpé, je n&rsquo;ai personnellement rien trouvé de plus que ce qui pourrait être la description d&rsquo;un programme destiné à comprendre comment le virus pourrait muter et à adapter les vaccins en conséquence.</p>
<p>Peut-être que l&rsquo;homme dans la vidéo est réel et réellement en poste chez Pfizer, et peut-être qu&rsquo;il a réellement tenu les propos qu&rsquo;on entend dans la vidéo. Et même avec ça, ça ne prouverait rien de ce que Project Veritas avance. Quand on veut la vérité, mon cher, on la sert nue sur un plateau, on la découpe pas façon jambon reconstitué en la planquant en plus derrière la salade.</p>
<hr />
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p>La Drugs for Neglected Diseases initiative (DNDi) est une initiative qui met en relation des laboratoires pharmaceutiques et des gouvernements locaux confrontés à des maladies sur lesquelles il y a peu de recherche mais dont l&rsquo;impact sur la population est important.</p>
<p>Parmi ses cibles, il y a la maladie du sommeil. Il s&rsquo;agit d&rsquo;une infection à parasite (il s&rsquo;appelle Trypanosoma brucei gambiense et avec ça vous êtes bien avancés) transmis par la piqûre de la mouche tsé-tsé, qui est endémique de l&rsquo;Afrique subsaharienne et qui pourrait toucher 70.000 personnes chaque année. Les malades souffrent d&rsquo;anémie, de troubles cardiaques et rénaux, et finissent par être atteints de symptômes neurologiques. Ce sont eux qui donnent son nom à la maladie&nbsp;: le parasite perturbe les cycles du sommeil, entrainant des somnolences le jour, des insomnies la nuit, créant de la fatigue, de la confusion et des hallucinations. En l&rsquo;absence de traitement, le cerveau, privé de sommeil, se détériore pendant quelques semaines à quelques mois avant que la personne tombe dans le coma, dans lequel elle finit par mourir sans avoir repris connaissance. Quelques traitements existent, mais ils sont lourds, demandent une hospitalisation pendant 2 à 3 semaines et ne sont pas accessibles aux populations rurales, les plus durement touchées.</p>
<p>La DNDi a donc soutenu la mise en place d&rsquo;un essai clinique révolutionnaire qui permettrait de soigner la maladie du sommeil par voie orale. Les résultats sont tombés (<a href="https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(22)00660-0/fulltext">et sont disponibles ici</a>)&nbsp;: l&rsquo;acoziborole, une molécule mise au point par Sanofi a montré une efficacité de 95% en seulement une prise. Se présentant sous forme de comprimés, elle est de surcroit facile à transporter et à conserver. Les responsables du programme en République démocratique du Congo évoquent la possibilité de protéger les 60 millions de personnes que la maladie menace dans 36 pays différents et, peut-être, de parvenir à l&rsquo;éradication de sa forme sévère en permettant le traitement dès les premiers symptômes.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Rhume</strong>&nbsp;: il a beau être très commun, on continue de découvrir des choses sur le banal rhume d&rsquo;hiver. Jusqu&rsquo;ici, sa plus grande fréquence l&rsquo;hiver était principalement expliquée par des facteurs environnementaux&nbsp;: les gens sont plus souvent en intérieur, aèrent moins et se contaminent donc plus facile. Mais des chercheurs d&rsquo;Harvard ont découvert une autre cause&nbsp;: un abaissement de la température intérieure du nez de 5C° (correspondant à une température extérieure de 4C°) fait chuter de 42% la production de certaines vésicules de la paroi nasale. Or ces vésicules sont spécialisées dans la capture des virus respiratoires&nbsp;: en respirant de l&rsquo;air froid, on perd temporairement la moitié de notre immunité locale. Alors que faire&nbsp;? Et bien les chercheurs recommandent tout simplement… de porter le masque dehors dès qu&rsquo;il fait moins de 10C°. «&nbsp;C&rsquo;est comme porter un pull sur le nez&nbsp;» dit ainsi Benjamin Bleier, l&rsquo;un des principaux chercheurs de l&rsquo;étude. J&rsquo;en connais qui vont encore râler…</p>
<p><em>Source&nbsp;: Ecole de médecine de Harvard</em></p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Double vaccination</strong>&nbsp;: si vous vous souvenez, je vous avais parlé, il y a quelques semaines, d&rsquo;un signal statistique qui était en cours d&rsquo;étude par la FDA (ce qui a fait dire à toute la complosphère que «&nbsp;le vaccin bivalent donne des AVC&nbsp;!&nbsp;»). Et comme la pharmacovigilance travaille, des résultats préliminaires sont déjà disponibles. Et comme d&rsquo;habitude, c&rsquo;est plus complexe que ça. Sur plus de 4 millions de dossiers étudiés, il n&rsquo;existe aucun lien, même de loin, entre le vaccin bivalent et un surrisque d&rsquo;AVC. En revanche, il pourrait (souvenez-vous, résultats préliminaires, tout ça tout ça) exister un risque plus élevé d&rsquo;AVC chez les plus de 65 ans (et eux uniquement) ayant reçu le même jour le vaccin bivalent et un vaccin fortement dosé contre la grippe. Le signal statistique est toutefois très faible, et une étude de plus grande ampleur vient d&rsquo;être lancée pour l&rsquo;étudier. En attendant, il est possible, si vous êtes dans la tranche d&rsquo;âge concernée, de séparer vos vaccins pour éviter cet éventuel risque (à noter que le fait de contracter la grippe à cet âge augmente le risque d&rsquo;AVC de toute façon, et ça de manière certaine, donc faites-vous vacciner).</p>
<p><em>Source&nbsp;: { abbr("U.S. FDA", "The United States Food and Drug Administration" ) }</em></p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Recherche en France</strong>&nbsp;: après la période Covid pendant laquelle on a subitement donné des vrais moyens à la recherche en lui demandant de sauver notre peau, la baisse de virulence de l&rsquo;épidémie a également conduit à une baisse des moyens. Alain Fischer, pour l&rsquo;Académie des Sciences, a dressé un constat très amer&nbsp;: moyens insuffisants, stratégie incompréhensible (ça veut dire qu&rsquo;on demande à des administratifs d&rsquo;expliquer à des chercheurs comment ils doivent faire un boulot qu&rsquo;ils ne comprennent pas), carrières peu attractives (ça veut dire que les chercheurs sont payés une misère par rapport à leur niveau de compétence et qu&rsquo;ils sont de  plus en plus nombreux à aller voir ailleurs si l&rsquo;herbe est plus verte) et investissements à la traîne. Le risque de déclassement de la France en matière de recherche est réel. Pour Fisher, la première urgence est de simplifier l&rsquo;organisation des agences et des opérateurs de la recherche et de réduire la charge administrative qui pèsent sur les chercheurs (comme quoi vous voyez, quand je râle sur le fait de devoir faire mon dossier de qualif toute pourrite, je suis pas un avis isolé).</p>
<p><em>Source&nbsp;: Académie des Sciences</em></p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Justice</strong>&nbsp;: dans l&rsquo;affaire qui opposait la chaîne de vulgarisation scientifique La Tronche en Biais, et plus particulièrement son principal représentant Thomas Durand (mais aussi, on l&rsquo;a appris au débotté, Arnaud Thiry d&rsquo;Astronogeek, qui s&rsquo;est retrouvé par surprise dans la sauce) contre la désinformatrice Annie Lobé, cette dernière a été déboutée. En réalité, l&rsquo;action s&rsquo;est éteinte, faute de réaction à temps de la part de son avocat, qui avait sans doute compris qu&rsquo;il n&rsquo;y avait rien à plaider dans cette histoire sans passer pour un dément. Et de fait, même si l&rsquo;expertise psychiatrique demandée n&rsquo;a pas été réalisée, je vous demanderais donc de ne pas aller harceler cette dame qui a de toute évidence plus besoin d&rsquo;aide qu&rsquo;autre chose.</p>
<p>Réjouissons-nous dans la mesure et le respect.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>L&rsquo;affaire du Sang Pur continue. La désinformation prend une telle ampleur qu&rsquo;elle a contraint les épidémiologistes américains à communiquer publiquement sur le fait que, non, recevoir du sang de vacciné ne vaccinait pas contre le Covid (en plus du fait que, à mon humble avis, si tu en es au stade de devoir recevoir une transfusion, le Covid c&rsquo;est pas ton plus gros souci frère…).</p>
<p>Plus grave, sur les groupes privés WhatsApp et Telegram, les appels à la violence contre les soignants qui vaccinent et/ou transfusent se font de plus en plus nombreux et précis. Les complotistes sont ainsi de plus en plus nombreux à affirmer qu&rsquo;il ne faut pas hésiter à résister par la violence, car on ne risque rien&nbsp;: vu que «&nbsp;les vaccinés meurent en masse&nbsp;», refuser du «&nbsp;sang contaminé&nbsp;» est légalement de la «&nbsp;légitime défense&nbsp;» (c&rsquo;est dingue comment ils me forcent à abuser des guillemets ces nouilles). Non mais en vrai, si on se cale sur leur mode de preuve, à savoir le témoignage&nbsp;: comment ça se fait que moi qui suis vaccinée, entourée de collègues, d&rsquo;amis, de proches qui le sont, je connaisse personne qui soit mort&nbsp;? Alors, si on leur pose la question, ils vous diront que oui, mais eux, ils en connaissent (d&rsquo;ailleurs, y a que les antivax qui connaissent des «&nbsp;morts en masse&nbsp;» du vaccin). J&rsquo;en conclus donc tout naturellement qu&rsquo;avoir des proches antivax vous fait mourir. Voilà. Suivant&nbsp;!</p>
<hr />
<h3 id="point-methode-de-la-semaine-la-publication-scientifique--annonce"><a href="#point-methode-de-la-semaine-la-publication-scientifique--annonce">POINT METHODE DE LA SEMAINE&nbsp;: la publication scientifique &#45; Annonce</a></h3>
<p>C&rsquo;est encore le point méthode de la flemme cette semaine, mais j&rsquo;ai eu une très grosse semaine assez compliquée. Notamment à cause de deadlines pour des papiers. Et je me suis dit que c&rsquo;était peut-être l&rsquo;occasion de vous faire un grand sujet sur la publication scientifique. Comme pour la dernière fois, je vous présente donc le sommaire auquel je pense, et vous pouvez me laisser vos questions <a href="https://www.facebook.com/TheDendrobateDoctor/?ref=page_internal">dans les commentaires</a>, ou me dire si vous aimeriez que je traite plus d&rsquo;un aspect en particulier.</p>
<ol>
<li>Semaine 1- Les différentes catégories d&rsquo;articles&nbsp;: quoi écrire pour montrer quoi&nbsp;?</li>
<li>Semaine 2- Le contenu d&rsquo;un article&nbsp;: fournir ses données, détailler ses conflits d&rsquo;intérêt, nommer les auteurs, sourcer son travail</li>
<li>Semaine 3- Les journaux&nbsp;: open source, prédateurs, impact factor</li>
<li>Semaine 4- La peer-review&nbsp;: pourquoi, qui, comment&nbsp;?</li>
<li>Semaine 5- Itinéraire d&rsquo;un article&nbsp;: de la rédaction à la publication et plus</li>
</ol>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec le mois de janvier (qui est un mois suffisamment nul pour qu&rsquo;on ait donné le nom de janviose au fait d&rsquo;être malade du mois de janvier, c&rsquo;est dire). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur <a href="https://www.facebook.com/TheDendrobateDoctor/?ref=page_internal">la page Facebook du Docteur</a>.</p>
    </div>)
}