
import { Article } from "@/atoms/Article";

export const Article20231105LechodeslabosMetadata = {"tags":["Échelle de Léonard","étudiant de Master","thésard","ATER","Assistant Temporaire d’Enseignement et de Recherche","post-doc/chargé de TD","PI","assistant professeur","Principal Investigator","maître de conférences","chargé de recherche","MCF","HDR","directeur d’équipe","Habilitation à Diriger les Recherches","professeur","directeur de recherche","directeur d’études","émérite"],"title":"l'Écho des Labos - 5 novembre 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio SNCF (cette chronique est débutée en la merveilleuse et gigantesque gare de Saint-Eémilion, 1800 habitants, deux minutes d’arrêt), je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-11-05","layout":"layouts/post.njk"}

export const Article20231105Lechodeslabos : Article = ({
  className, title, img, KissKissBankBank, Facebook
}) => {
  return (<div className={className}>
      <dl>
<dt>{ img("http://japethno.hypotheses.org/files/2016/12/raoul4.gif",  "↓",  "width:100%" ) }</dt>
<dd>Basile, le disciple de Léonard, de la bande dessinée éponyme, se plaint:"Je voulais servir la science parce que c'était ma joie, et au lieu de ça, qu'est-ce que je fais ?…". Et le chat de répondre: "Oui, au fait, qu'est-ce qu'il fait ?", et le crâne sur le bureau de répondre: "À mon avis il se plaint !"
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio SNCF (cette chronique est débutée en la merveilleuse et gigantesque gare de Saint-Eémilion, 1800 habitants, deux minutes d&rsquo;arrêt), je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos, édition spéciale Échelle de Léonard.</p>
<hr />
<p>Aujourd&rsquo;hui, nous allons donc parler de l&rsquo;Échelle de Léonard, une échelle que j&rsquo;ai nommée ainsi:</p>
<ol>
<li>en hommage à la BD du même nom dans laquelle servir la science n&rsquo;est pas toujours notre joie</li>
<li>parce que j&rsquo;ai une aversion profonde pour les chercheurs qui se prennent au sérieux quand ils nomment des trucs.</li>
</ol>
<p>Comme l&rsquo;échelle de Richter, l&rsquo;échelle de Léonard est logarithmique, ce qui veut dire qu&rsquo;il faut dix fois plus d&rsquo;efforts pour passer au niveau du dessus à chaque fois qu&rsquo;on grimpe dans l&rsquo;échelle (en gros, en très gros, j&rsquo;ai pas fait math spé voyez-vous). Si celle de Richter mesure la quantité d&rsquo;énergie sismique dégagée par un tremblement de terre, celle de Léonard mesure plutôt le potentiel du chercheur à secouer les choses autour de lui sans perdre sa place. Et comme j&rsquo;aime bien les comparaisons nulles poussées jusqu&rsquo;au bout, on va reprendre les catégories de l&rsquo;échelle de Richter pour notre échelle de Léonard.</p>
<h3 id="niveaux-1-à-3-à-peine-un-impact"><a href="#niveaux-1-à-3-à-peine-un-impact">Niveaux 1 à 3&nbsp;: à peine un impact:</a></h3>
<p>Dans cette catégorie, on trouve les chercheurs en tout début de carrière, dont globalement tout le monde se fout et qui se font piétiner allègrement par le reste du staff qui les considère comme corvéable à merci. Les syndicats des doctorants ont dû ainsi à plusieurs reprises rappeler qu&rsquo;il n&rsquo;était pas possible de payer les gens une fois tous les 6 mois seulement, qu&rsquo;on ne pouvait pas exiger des gens d&rsquo;être là dimanche et jours fériés en toutes circonstances et que si les superviseurs acceptaient des tâches annexes (comme faire la review d&rsquo;articles scientifiques), systématiquement tout refourguer à leurs subordonnés n&rsquo;était pas une pratique convenable. Le fait qu&rsquo;un syndicat ait à rappeler ça régulièrement est déjà un problème en soi…</p>
<h4 id="niveau-1-létudiant-de-master"><a href="#niveau-1-létudiant-de-master">Niveau 1&nbsp;: l&rsquo;étudiant de Master</a></h4>
<p>Il est techniquement en train de commencer la recherche et d&rsquo;être formé par des chercheurs plus chevronnés que lui. En pratique, on lui confie les manipulations les plus pénibles et répétitives en disant que c&rsquo;est un bon moyen d&rsquo;apprendre, parce que ça évite de devoir payer un technicien de recherche ou un laborantin, vu que ces étudiants ne sont pas payés, à part lors de certains stages où ils sont alors gracieusement payés une misère. Ils doivent continuer leurs études de front, rendre un mémoire à la fin de l&rsquo;année et seuls ceux qui ont eu une très bonne note (voire excellente selon les domaines) pourront prétendre à entrer en thèse.</p>
<h4 id="niveau-2-le-thésard"><a href="#niveau-2-le-thésard">Niveau 2&nbsp;: le thésard</a></h4>
<p>Dit aussi «&nbsp;doctorant&nbsp;», dit aussi «&nbsp;force vive du laboratoire&nbsp;», dit aussi «&nbsp;Toto&nbsp;» (mais uniquement par ses amis). C&rsquo;est un tout jeune chercheur en cours de formation, qui se spécialise sur un domaine précis, son thème de recherche, encadré par un ou plusieurs directeurs de thèse. Dans la pratique, il est souvent sur-sollicité pour les projets de recherche du laboratoire où il y a besoin de petites mains, y compris lorsque ça ne fait pas avancer son projet. Selon les disciplines, il arrive qu&rsquo;il soit recruté directement pour faire sa thèse sur un sujet décidé par le laboratoire, afin de faire de expériences, travaux de terrains ou manipulations précises, qui s&rsquo;inscrivent dans un contexte plus large. Généralement, il peut être vu du lundi matin au dimanche soir dans le département, il connait mieux que personne les vigiles de nuit, les codes d&rsquo;alarme pour les jours fériés et les recettes de café-redbull. Il est en principe embauché pour 3 ans afin de produire une thèse qui lui donnera le titre de docteur, mais certains, en particulier au sein des sciences humaines et sociales, sont sans financement et doivent en plus travailler à côté pour manger et payer leur loyer. Ceux qui dépassent ce délai sans une excellente raison voient leurs chances d&rsquo;obtenir des postes par la suite fondre comme la neige carbonique hors du frigo du labo.</p>
<h4 id="niveau-3-later"><a href="#niveau-3-later">Niveau 3&nbsp;: l&rsquo;ATER</a></h4>
<p>L&rsquo;Assistant Temporaire d&rsquo;Enseignement et de Recherche (dit aussi «&nbsp;le bouche-trou&nbsp;») a une double particularité. La première, c&rsquo;est que c&rsquo;est un statut cumulable, sous conditions, avec d&rsquo;autres niveaux de l&rsquo;échelle. Un doctorant en dernière année peut être ATER, un jeune docteur affilié peut l&rsquo;être également, ce qui importe c&rsquo;est qu&rsquo;il soit capable de venir combler les trous du département qui le recrute (c&rsquo;est-à-dire la plupart du temps assurer les TD dont personne ne veut). La seconde, c&rsquo;est que son espérance de vie au sein de l&rsquo;université est très courte, puisqu&rsquo;il est recruté pour un an, renouvelable maximum une fois (et, dans le cas où c&rsquo;est un doctorant de dernière année, si et seulement si, il soutient sa thèse avant le début de son renouvellement de contrat). Il est généralement en charge des enseignements de Licence, car c&rsquo;est ce qui intéresse le moins ses supérieurs, et, si le nombre d&rsquo;heures d&rsquo;enseignement est plafonné, celui des heures de recherche ne l&rsquo;est pas, et il peut donc être allègrement exploité par le reste du laboratoire, surtout qu&rsquo;il est un maillon particulièrement vulnérable de la chaîne, a donc besoin de publications pour tenter de se faire recruter et dira à peu près amen à tout.</p>
<h3 id="niveaux-4-et-5-impact-mineur"><a href="#niveaux-4-et-5-impact-mineur">Niveaux 4 et 5&nbsp;: impact mineur</a></h3>
<p>Dans cette catégorie, on trouve des chercheurs qui commencent à faire leur trou dans le milieu académique, et qui de ce fait commence à avoir leurs propres publications et leur petit impact, mais y a pas encore de quoi casser trois pattes à un confit de canard. Ils sont pourtant le gros des troupes de la recherche et la science leur doit beaucoup.</p>
<h4 id="niveau-4-le-post-docchargé-de-td"><a href="#niveau-4-le-post-docchargé-de-td">Niveau 4&nbsp;: le post-doc/chargé de TD</a></h4>
<p>On va commencer ici à entrer dans des statuts un peu flous, qui se superposent ou se complètent sur des branches distinctes. Tout d&rsquo;abord, le chercheur post-doctorant, et son pendant d&rsquo;enseignement le chargé de TD, sont recrutés dans le cadre d&rsquo;un projet ou d&rsquo;un cursus précis, pour faire un boulot sous la supervision de chercheurs plus chevronnés. Le post-doctorant est recruté sur projet, et sa durée de vie dans le département est donc celle du projet, allant de 6 mois à 5 ans. Il n&rsquo;est toujours pas sûr de quand il aura un boulot stable, il doit souvent déménager entre deux contrats (il est fréquent pour un chercheur d&rsquo;avoir entre 2 et 6 post-docs à son actif avant d&rsquo;arriver à trouver un emploi fixe) et il est souvent à la merci du PI, le Principal Investigator, qui chapeaute le projet, mais il peut être relativement bien classé sur la liste des auteurs qui signent les articles scientifiques et représenter le laboratoire en conférence. La plupart du temps, son poste exclut l&rsquo;enseignement et il est concentré sur la recherche. A l&rsquo;inverse, le chargé de TD ne fait pas (officiellement) de recherche, mais enseigne dans le cadre d&rsquo;un cursus à l&rsquo;université. Il ne choisit pas les cours qu&rsquo;il donné puisqu&rsquo;il assure les travaux dirigés liés aux cours magistraux délivrés par un professeur plus gradé. S&rsquo;il est récemment sorti de thèse, et s&rsquo;il veut continuer la recherche, il est possible qu&rsquo;il publie ou fréquente les conférences sous le statut de «&nbsp;chercheur associé&nbsp;», un statut conféré par son ancienne université qui le reconnaît comme membre de son personnel (sans rien lui payer bien entendu, mais ça permet de se présenter avec une affiliation aux conférences et de pas juste avoir l&rsquo;air de Jo le Clodo). A eux deux, le post-doc et le chargé de TD sont le gros des forces de la recherche et de l&rsquo;université et leur rôle dans l&rsquo;écosystème est inestimable.</p>
<h4 id="niveau-5-le-piassistant-professeur-moi-je-suis-là-coucou"><a href="#niveau-5-le-piassistant-professeur-moi-je-suis-là-coucou">Niveau 5&nbsp;: le PI/assistant professeur (moi je suis là, coucou&nbsp;!)</a></h4>
<p>Attention, ça va à nouveau être un peu subtil. Le PI (donc Principal Investigator) est le gérant d&rsquo;un projet de recherche. Il peut en être le coordinateur, il peut en être le superviseur (si des thésards sont impliqués et qu&rsquo;il est leur directeur) mais il peut aussi être un post-doctorant autonome, qui a monté et fait financer son propre projet de recherche, qui signe ses papiers en premier auteur et qui va donc en conférence présenter son travail. Ca a l&rsquo;air d&rsquo;être un peu de la triche comme ça, mais en réalité on considère que l&rsquo;important c&rsquo;est la capacité à mener de la recherche de manière autonome, en gérant un projet depuis l&rsquo;aspect budgétaire jusqu&rsquo;au calendrier des rendus. Il est régulièrement encore précaire, sa durée de vie étant encore souvent celle du projet (sauf s&rsquo;il a un autre statut indépendant de celui de PI) et comme il doit courir partout et gérer de la recherche (à savoir des projets avec la moitié du temps nécessaire et le tiers des moyens), il souffre régulièrement de surmenage, d&rsquo;épuisement et de crises d&rsquo;autorité quand il a des subordonnés. Si en revanche tout se passe bien et qu&rsquo;il fait preuve d&rsquo;inventivité et de diligence, il se trouve bien placé pour prétendre à des postes un peu plus stables. Son pendant en enseignement, l&rsquo;assistant professeur, peut être un post-doc, un ATER ou un PI (aussi, j&rsquo;avais dit que c&rsquo;était un peu le boxon ici). Il travaille main dans la main dans la conception des cours avec un professeur plus chevronné, prépare les sujets d&rsquo;examens, corrige des copies et il est un mix entre le conseiller-psy des étudiants et le secrétaire du professeur, faisant le lien entre les deux. Il est (encore et toujours) souvent un employé précaire, à la merci des crises d&rsquo;autorité ou de la toxicité du professeur qu&rsquo;il assiste et peut lui-même être une sale petite teigne avec les étudiants. La plupart du temps, il est toutefois LA personne sur qui ils peuvent compter et qui va leur servir de référence, surtout dans le cas d&rsquo;étudiants loin de chez eux, étrangers ou peu familiers avec la langue.</p>
<h3 id="niveaux-6-et-7-impact-réel"><a href="#niveaux-6-et-7-impact-réel">Niveaux 6 et 7&nbsp;: impact réel</a></h3>
<p>Dans cette catégorie, on entre enfin dans ce qui intéresse tous les aspirants à la recherche et au monde académique. Ces chercheurs là ont des postes qui leur permettent enfin de travailler sur les sujets qu&rsquo;ils veulent, et c&rsquo;est là qu&rsquo;ils vont commencer à pouvoir déployer leurs idées.</p>
<h4 id="niveau-6-le-maître-de-conférenceschargé-de-recherche"><a href="#niveau-6-le-maître-de-conférenceschargé-de-recherche">Niveau 6&nbsp;: le maître de conférences/chargé de recherche</a></h4>
<p>En France, les deux sont recrutés sur concours au même niveau, la seule différence est que le chargé de recherche ne fait que de la recherche alors que le maître de conférences (dit MCF) est enseignant et chercheur. Il s&rsquo;agit (enfin, hurlent tous les échelons du dessous) d&rsquo;un poste pérenne, il y en a donc ridiculement peu (à titre d&rsquo;exemple, dans mon domaine, le taux d&rsquo;entrée au CNRS est inférieur à 5%) et ils sont relativement mal payés (en France toujours, le reste du monde est mort de rire quand il regarde nos feuilles de salaire), mais ils ont enfin une certaine liberté académique et ce sont souvent eux qui vont venir dynamiser les département en proposant de nouveaux axes, de nouveaux projets ou de nouveaux cursus.</p>
<h4 id="niveau-7-lhdrdirecteur-déquipe"><a href="#niveau-7-lhdrdirecteur-déquipe">Niveau 7&nbsp;: l&rsquo;HDR/directeur d&rsquo;équipe</a></h4>
<p>Ici, il s&rsquo;agit réellement d&rsquo;un simple «&nbsp;level&nbsp;up&nbsp;». Le premier est un MCF qui a passé quasiment une seconde thèse (appelée l&rsquo;Habilitation à Diriger les Recherches) qui lui confère la possibilité d&rsquo;encadrer des doctorants (toujours en France, ça n&rsquo;existe pas dans la plupart des autres pays, où il est possible de commencer, souvent sous forme de co-encadrement, dès sa propre thèse validée). Comme ils sont les premiers niveaux de l&rsquo;échelle à pouvoir le faire, ils sont généralement archi-débordés et beaucoup croulent sous le surencadrement (le fait d&rsquo;avoir plus de 10 thésards sous sa responsabilité). Le second est un chargé de recherche qui se retrouve en position de diriger un ou plusieurs axes de recherche de son laboratoire. Il ne bénéficie généralement d&rsquo;aucune paie supplémentaire pour ça, mais se retrouve à avoir son nom sur plein d&rsquo;articles scientifiques, en tant qu&rsquo;encadrant. Ca peut être parce qu&rsquo;il fout rien et qu&rsquo;il exige qu&rsquo;on mette son nom partout. La plupart du temps, c&rsquo;est quand même parce qu&rsquo;il assure le management des troupes, la gestion des projets et se porte garant de l&rsquo;intégrité des résultats. Lui aussi souffre généralement de surmenage, compliqué par un gros turnover de ses équipes, directement lié à la précarité des échelons inférieurs. C&rsquo;est donc tout naturellement à ce moment-là que les deux, HDR et directeur d&rsquo;équipe, se disent qu&rsquo;il est temps de passer un concours supplémentaire, après tout, dormir c&rsquo;est pour les faibles.</p>
<h3 id="niveau-8-impact-majeur"><a href="#niveau-8-impact-majeur">Niveau 8&nbsp;: impact majeur</a></h3>
<h4 id="niveau-8-le-professeurdirecteur-de-recherchedirecteur-détudes"><a href="#niveau-8-le-professeurdirecteur-de-recherchedirecteur-détudes">Niveau 8&nbsp;: le professeur/directeur de recherche/directeur d&rsquo;études</a></h4>
<p>Le professeur, ou professeur des universités, est l&rsquo;échelon maximale dans l&rsquo;enseignement. Le directeur de recherche est son pendant dans la recherche pure. Le directeur d&rsquo;études est un mix des deux. Tous les trois entrent dans leurs fonctions sur concours, un encore plus difficile, sélectif et retors que celui des MCF ou chargés de recherche. Ils sont globalement la tête pensante de leurs unités, ceux qui indiquent la direction générale, fixent les axes de recherche, cadrent les problématiques et, contrairement à leurs collègues HDR qui peuvent encore encadrer des étudiants de Master, ils ne supervisent en général que les doctorants. Ils doivent globalement avoir des yeux, des oreilles et des mains de fers dans des gants de velours partout car tout ce qui est fait et qu&rsquo;ils laissent faire peut être retenus contre eux. En théorie. En pratique, c&rsquo;est généralement à cette position que ceux qui étaient déjà des gros cons avant vont réellement se mettre à abuser de leur pouvoir. C&rsquo;est aussi là, heureusement, que la grande majorité d&rsquo;entre eux à la pouvoir de protéger les collaborateurs les plus précaires des gros nuisibles. Le gros de leur travail va d&rsquo;être de courir partout pour trouver les financements qui font tourner les laboratoires, subventionnent les étudiants et payent les loyer des petites mains. Dans les équipes calmes, ils vivent comme des patriarches au milieu de leur famille aimante. Dans les équipes compliquées, ils sont les capitaines de navires en perdition. Dans les équipes hostiles, ils sont les rois très provisoires de Game of Thrones.</p>
<h3 id="niveau-9-impossible-à-quantifier-précisément"><a href="#niveau-9-impossible-à-quantifier-précisément">Niveau 9&nbsp;: impossible à quantifier précisément</a></h3>
<h4 id="niveau-9-lémérite"><a href="#niveau-9-lémérite">Niveau 9&nbsp;: l&rsquo;émérite</a></h4>
<p>Le chercheur qui a atteint l&rsquo;âge de la retraite peut demander un éméritat, à savoir de pas partir à la retraite et de continuer à bosser. Oui, on a vraiment un grain. Si celui-ci lui est accordé, l&rsquo;émérite est indéboulonnable jusqu&rsquo;à la fin du délai octroyé, il se fout de tout, il recherche ce qu&rsquo;il veut, il écrit sur ce qui l&rsquo;intéresse, il donne les cours qui lui plaisent et, s&rsquo;il ne peut plus encadrer directement de doctorants (sauf s&rsquo;ils ont déjà commencé leur travail avec lui avant son éméritat, en principe), il peut continuer à faire partie de comités, à conseiller les étudiants et à relire des travaux de recherche. S&rsquo;il a envie. S&rsquo;il aime ça. Bref, c&rsquo;est un chercheur détendu et heureux. Moyenne d&rsquo;âge&nbsp;: 73 ans.</p>
<hr />
<p>En espérant avoir pu vous éclairer un peu sur le petit monde des scientifiques et de leur échelle de cramponnage à la recherche, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas, même si on sert la science et que c&rsquo;est notre joie. En attendant, prenez soin de vous et des chercheurs qui bossent (vraiment, mais alors vraiment) dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}