
import { Article } from "@/atoms/Article";

export const Article20230416LechodeslabosEdSpeDebunkageDVedHMetadata = {"tags":["covid","débunk","Des vaccins et des hommes","vaccination","rougeole","HPV","papillomavirus humain","Le Biostatisticien","Pr. Jacques Robert","Inserm","Société Française du Cancer","les Vaxxeuses","SPAV","Steve Claude","Martine Wonner","Arte","Andrew Wakefield","Rougeole-Oreillon-Rubéole","autisme","rougeole","CNC","Michèle Rivasi","Yannick Jadot","Michel Georget","ARCOM"],"title":"l'Écho des Labos - Ed.Spé. débunkage du film « Des Vaccins et des Hommes »","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-04-16","layout":"layouts/post.njk"}

export const Article20230416LechodeslabosEdSpeDebunkageDVedH : Article = ({
  className, title, img
}) => {
  return (<div className={className}>
      <dl>
<dt>{ img("https://bigpragma.files.wordpress.com/2023/04/vh-00.jpg",  "↓" ) }</dt>
<dd>Analyse complète de "Des vaccins et des hommes"
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour une édition spéciale, sur un projet de longue haleine.<br />
Si elle disparait, retrouvez la chronique sur le blog (https://www.the-dendrobate-doctor.fr/)</p>
<p>Bienvenue à tous sur l'Echo des Labos, spécial débunkage du film «&nbsp;Des Vaccins et des Hommes&nbsp;»</p>
<h3 id="un-debunk-ou-comment-par-qui-pourquoi"><a href="#un-debunk-ou-comment-par-qui-pourquoi">UN DEBUNK&nbsp;: OU, COMMENT, PAR QUI, POURQUOI&nbsp;?</a></h3>
<p>Le débunk complet, je vous le dis tout de suite, il n&rsquo;est pas chez moi, parce qu&rsquo;il fait plus d&rsquo;une centaine de pages et 333 références bibliographiques (je le sais, c&rsquo;était moi le responsable bibliographie du groupe… oui, quand on a dit qu&rsquo;on a bétonné notre travail, il est en béton armé). Vous le trouverez sur le site des Vaxxeuses (<a href="https://bigpragma.wordpress.com/2023/04/14/analyse-complete-du-documentaire-des-vaccins-et-des-hommes">ici</a>), organisé par chapitre selon que vous voulez en savoir plus sur qui est derrière le Machin, comment c&rsquo;est bien avec la vaccination qu&rsquo;on a éradiqué la variole, comment la rougeole peut encore être mortelle 10 ans après que vous l&rsquo;ayez chopée ou pourquoi le vaccin contre le HPV est la seule chose qui peut nous permettre, un jour, de faire du cancer du col de l&rsquo;utérus une maladie du passé.</p>
<p>Pour monter ça, nous avons appliqué la méthode scientifique, la vraie. Tout d&rsquo;abord nous avons retranscrit l&rsquo;intégralité du Machin, y compris les graphs qui apparaissaient à l&rsquo;écran. Nous sommes allés vérifier chaque affirmation, point par point. Lorsque le Machin disait une connerie (ce qui arrive en moyenne une fois toutes les 30 secondes dans le film), nous avons expliqué pourquoi c&rsquo;était une connerie, et chacune de nos explications a été étayée avec des sources fiables, depuis les coupures de presse historiques (quand le Machin mentait sur ce qui s&rsquo;était passé à l&rsquo;époque) aux méta-analyses (quand il cherchait à manipuler les données). Chaque affirmation démontée a été classée selon sa thématique, et les thématiques ont été organisées en chapitres cohérents. Chaque chapitre a été confié à un ou plusieurs membres de l&rsquo;équipe, selon ses compétences mais aussi ses propres conflits (et je vais vous expliquer pourquoi j&rsquo;ai refusé certains chapitres plus bas), rédigé et relu plusieurs fois, par des spécialistes internes ou proches de l&rsquo;équipe (ce qui m&rsquo;a donné une bonne occasion d&rsquo;aller encore embêter Le Biostatisticien, coucou aux poneys Matthieu&nbsp;!), avant de bénéficier d&rsquo;une relecture générale par le Pr. Jacques Robert de l&rsquo;Inserm, secrétaire général de la Société Française du Cancer après en avoir été le président pendant des années (tu vois, Anne, ça c&rsquo;est de la relecture par des spécialistes, ça c&rsquo;est du travail de recherche, pas comme tes conseils en écriture à la mords-moi-l&rsquo;œil, là, prends exemple et rends l&rsquo;argent&nbsp;!). En toute modestie, on a blindé le truc.</p>
<p>Parlons de l&rsquo;équipe, justement, qui sont les tarés qui ont pondu ça, et en quoi ils sont plus légitimes pour parler du sujet que, au hasard, une documentariste qui interview des médecins radiés de l&rsquo;Ordre pour faire croire aux gens que les médicaments (en général, pas juste les vaccins) ne servent à rien&nbsp;? On se le demande, hein… L&rsquo;équipe contient une vingtaine de membres, dont une dizaine ont été les principaux rédacteurs du débunk (les autres comptant des relecteurs grammaire/orthographe, des admins, des reviewers etc.). Certains ont choisi de rester anonymes (parce que les menaces c&rsquo;est chiant), mais d&rsquo;autres sont représentants d&rsquo;un groupe (vous vous doutez bien que les Vaxxeuses ou SPAV sont dans le coup) et d&rsquo;autres agissent en leur nom propre (genre moi, ou Steve Claude, le gars qui a réussi à ce que Martine Wonner se fasse recadrer dans l&rsquo;hémicycle pour avoir dit que les pharmaciens étaient des épiciers qui avaient raté médecine). Le groupe compte donc des chercheurs, des toubibs, des vulgarisateurs, des pharmaciens et, globalement, des gens qui savent lire une étude et pas lui faire dire n&rsquo;importe quoi juste parce que ça nous arrange.</p>
<p>Quant à pourquoi l&rsquo;équipe a fait ça, je vais commencer par la négative. Ce n&rsquo;est pas parce qu&rsquo;on a été payés (contrairement à ceux qui reçoivent de l&rsquo;argent public pour construire et diffuser de la désinformation, n&rsquo;est-ce pas Anne, n&rsquo;est-ce pas ARTE&nbsp;?), ça a été fait sur notre temps libre et c&rsquo;est pour ça que ça a pris tant de temps&nbsp;: on en a pas beaucoup. Ce n&rsquo;est pas non plus parce qu&rsquo;on va en tirer de la gloire et de la reconnaissance, le modérateur est déjà sur les dents… Ce n&rsquo;est pas parce qu&rsquo;on a quelque chose contre Anne ou ARTE (enfin, à la base, on n&rsquo;avait rien contre, après des mois à patauger dans la bouse, tu finis par plus pouvoir voir les vaches en peinture…). Ce n&rsquo;est même pas parce que c&rsquo;était amusant (vous avez une idée de ce que ça représente à trier, 333 références bibliographiques&nbsp;?). Non, si on l&rsquo;a fait, c&rsquo;est parce que le Machin est un vrai problème, et que ce qui se passe est très grave.</p>
<h3 id="en-vrai-cest-quoi-le-probleme"><a href="#en-vrai-cest-quoi-le-probleme">EN VRAI, C&rsquo;EST QUOI LE PROBLEME&nbsp;?</a></h3>
<p>L&rsquo;Histoire ne se répète pas toujours, mais elle bégaye souvent. En 1998, Andrew Wakefield publie une étude dans laquelle il affirme que le vaccin combiné Rougeole-Oreillon-Rubéole peut être à l&rsquo;origine de l&rsquo;autisme chez certains enfants. L&rsquo;étude est bidon dès le départ (il y a 12 cas, aucun prélèvement probant, les relations sont faites selon ce que les parents croient se souvenir) et la communauté scientifique la considère comme ce qu&rsquo;elle est&nbsp;: un papier sans valeur. Mais Wakefield ne s&rsquo;intéresse pas à l&rsquo;avis des chercheurs, il se fiche de comment son article est reçu par ses pairs, lui, il veut que le public qui n&rsquo;y connait rien le croit. Alors il convoque une conférence de presse pour présenter ses résultats, et l&rsquo;intégralité des journalistes du UK gobe l&rsquo;histoire. Pendant des mois et des mois, malgré les mises en garde des vrais spécialistes, les médias diffuseront sans vergogne cette hypothèse que le ROR est peut-être la cause de l&rsquo;autisme, causant un effondrement de la vaccination chez nos voisins britanniques (je vais passer sur le fait que manifestement certains parents préféraient leurs enfants morts que autistes, je suis déjà assez remontée comme ça). Ce n&rsquo;est qu&rsquo;après qu&rsquo;une longue enquête de l&rsquo;équivalent britannique de l&rsquo;Ordre des Médecins, appuyée par les révélations du journaliste d&rsquo;investigation Brian Deer (si l&rsquo;affaire vous intéresse, <a href="https://youtu.be/8BIcAZxFfrc">vous avez cette excellente vidéo, ici</a>, avec des sous-titres français si besoin), ait montré que Wakefield avait littéralement torturé ses petits patients par des procédures dangereuses et invasives dans l&rsquo;espoir de trouver un lien entre ROR et autisme, qu&rsquo;il avait falsifié ses résultats faute de pouvoir trouver ce lien, et qu&rsquo;il devait absolument trouver ce lien sur commande (grassement) payée d&rsquo;un avocat qui pensait faire des millions en attaquant les laboratoires une fois que Wakefield aurait «&nbsp;prouvé&nbsp;» que leur produit avait rendu des enfants autistes, que l&rsquo;étude a été rétractée, Wakefield radié et la panique s&rsquo;est estompée. Cela aura pris 12 ans. Entre temps, la rougeole a refait surface dans le pays, et a fait des morts. Des gens sont morts d&rsquo;une maladie parfaitement évitable parce que les médias ont préféré relayer l&rsquo;hypothèse séduisante d&rsquo;un médecin véreux plutôt que d&rsquo;écouter le consensus scientifique.</p>
<p>Et le Machin, c&rsquo;est l&rsquo;Histoire qui bégaye. Nous l&rsquo;avons vu, dans les groupes de vulgarisateurs, chez les fact-checkers, des gens parfaitement convaincus de l&rsquo;utilité de la vaccination se sont mis à douter. Plein de gens sont venus nous parler avec angoisse du mal qu&rsquo;ils étaient sûrs de faire à leurs enfants à cause de l&rsquo;obligation vaccinale (nul doute que cette obligation ne serait pas en place, on aurait observé la même chute de la vaccination que lors de l&rsquo;affaire Wakefield). Tout comme cela s&rsquo;est produit il y a quelques années, le Machin va causer des morts. Sans doute moins immédiatement, car les vaccins les plus critiques sont obligatoires, mais il va entretenir notre retard dans la vaccination HPV, causant des milliers de cancers du col chaque année. Il va encourager les gens qui le peuvent à inscrire leurs enfants dans des «&nbsp;écoles alternatives&nbsp;» qui seront, comme il y a quelques années, les épicentres d&rsquo;épidémies de rougeole qui feront des morts (10 pour la dernière épidémie avec «&nbsp;seulement&nbsp;» 20.000 cas, imaginez les dégâts sur l&rsquo;ensemble de la population si cela prenait de l&rsquo;ampleur). Et si vous ne voyez pas en quoi c&rsquo;est un problème quand quelqu&rsquo;un manipule les gens d&rsquo;une manière qui va générer des morts, je peux pas grand-chose pour vous.</p>
<h3 id="a-qui-profite-le-crime"><a href="#a-qui-profite-le-crime">A QUI PROFITE LE CRIME&nbsp;?</a></h3>
<p>C&rsquo;est vrai, quel intérêt de tuer des gens quand c&rsquo;est pas votre insupportable voisin qui joue de la perceuse à 6h du mat le dimanche&nbsp;? Comme toujours, il n&rsquo;y a jamais une réponse claire et définitive aux questions complexes, il y a plusieurs facteurs.</p>
<p>Le premier, c&rsquo;est que nous pensons que, même s&rsquo;ils mentent, même s&rsquo;ils tronquent les données, même s&rsquo;ils falsifient les témoignages, Anne et ses co-auteurs sont convaincus d&rsquo;avoir raison. Ils le font pour la bonne cause. Alors, on est d&rsquo;accord, à ce niveau de déni là, c&rsquo;est plus proche de Nathan Bates qui parle au cadavre de sa mère que de la démarche scientifique. Mais cela explique aussi pourquoi il est plus difficile de trouver des explications évidentes que pour Wakefield (chez qui il suffisait de suivre l&rsquo;argent). Anne fait ce film parce qu&rsquo;elle veut que sa croyance gagne. Elle veut que les gens croient ce qu&rsquo;elle croit parce que c&rsquo;est la vérité, même si les faits ont l&rsquo;air d&rsquo;aller à l&rsquo;encontre, elle le SAIT.</p>
<p>Mais… n&rsquo;écartons pas la piste de l&rsquo;argent trop vite. En effet, entre Anne et ses co-auteurs (en particulier un certain De Lestrade), on peut trouver une bonne dizaine de «&nbsp;documentaires&nbsp;» tous plus moisis les uns que les uns (vous saviez vous que le jeûne ça empêche de vieillir&nbsp;? eh bien la biologie non plus, mais De Lestrade lui, il sait&nbsp;!). On peut aussi trouver que l&rsquo;un d&rsquo;entre eux a le statut de lecteur pour les commissions du CNC (donc il fait partie de ceux qui décident qui est financé pour faire des films et qui l&rsquo;est pas). On peut aussi voir que tout ce petit monde a plein de trucs à vendre, des bouquins, des stages, des formations, des machines à voyager dans le temps (ok, ça non, du moins pas encore). Et plus les gens croient leur vérité à eux, plus leur camelote se vend (vachement plus cher qu&rsquo;un vaccin au passage…).</p>
<p>Enfin, n&rsquo;écartons pas trop vite non plus la piste du pouvoir. Parmi les impliqués, on a l&rsquo;assistant parlementaire de Michèle Rivasi, bras droit de Yannick Jadot, connue pour avoir fait venir au parlement européen… Wakefield… et avoir rédigé la préface de livres de … Michel Georget… Allez, tous en chœur&nbsp;: AAAAAAAH COMME LE MOOOOOOONDE EEEESSST PETIIIIIT&nbsp;!</p>
<h3 id="mon-dieu-serait-ce-un--complot"><a href="#mon-dieu-serait-ce-un--complot">MON DIEU, SERAIT-CE UN … COMPLOT&nbsp;?!</a></h3>
<p>Je l&rsquo;ai déjà dit sur la page&nbsp;: les complots existent. C&rsquo;est juste jamais les conspis qui les mettent au jour. L&rsquo;affaire Wakefield était un complot, le complot d&rsquo;un médecin sans scrupule, d&rsquo;un avocat véreux et de parents prêts à tout pour extorquer des millions à des fabricants de vaccins, quitte à mettre en danger des millions de leurs concitoyens. Est-ce que le Machin est le symptôme d&rsquo;un complot&nbsp;? Eh bien, c&rsquo;est encore un peu difficile à dire, car pour que complot il y ait, il faut que tout le monde soit dans le coup. Or, lorsque nous avons contacté la RTS pour leur dire «&nbsp;hé les gars, z&rsquo;avez grave merdé&nbsp;», ils ont aussitôt organisé un contre-feu en montant une émission avec un spécialiste, en lui demandant de commenter des extraits du film, commentaires qui avaient un peu remis l&rsquo;église au milieu du village. Bon, lorsque deux des membres de l&rsquo;équipe sont allés les rencontrer, ils nous ont aussi sorti la bonne vieille soupe de «&nbsp;il faut avoir le droit de poser des questions, d&rsquo;alimenter le débat&nbsp;» (et le débat sur la Terre Plate, le Moyen-Âge qui a pas existé et les Reptiliens, vous le diffusez aussi au nom de la sacro-sainte neutralité helvète, ou c&rsquo;est juste un traitement réservé aux sujets sur lesquels on peut vous berner parce que vous pannez rien&nbsp;?).</p>
<p>En revanche, pour ARTE, ça commence à puer. Parce qu&rsquo;entre les œuvres de Anne, de ses co-auteurs, de ses conseillers en écriture, toutes co-financées par la chaîne et diffusées avec autant de recul qu&rsquo;un myope faisant du maquettisme, il commence à y avoir un nid. Un nid qui nous a envoyé une fin de non-recevoir quand nous avons tenté de les alerter. Un nid dont il est difficile de dire s&rsquo;il est victime de Georget fille et sa clique, ou s&rsquo;il en est le complice. Mais un nid dont le pouvoir de nuisance devient suffisamment grave pour qu&rsquo;on puisse se dire qu&rsquo;il va falloir que ça cesse, et vite.</p>
<h3 id="est-ce-quon-va-tous-mourir"><a href="#est-ce-quon-va-tous-mourir">EST-CE QU&rsquo;ON VA TOUS MOURIR&nbsp;?</a></h3>
<p>Oui. Mais ça, c&rsquo;est pas particulièrement la faute de Anne pour le coup. En revanche, on va sans doute être plus nombreux à mourir de maladies évitables qu&rsquo;on aurait pu l&rsquo;être. Et ça sera en partie sa faute. A elle, à ses producteurs, à ses complices, à ses diffuseurs, mais aussi à ceux qui la laissent faire…</p>
<h3 id="que-fait-la-police"><a href="#que-fait-la-police">QUE FAIT LA POLICE&nbsp;?</a></h3>
<p>La police des médias, c&rsquo;est l&rsquo;ARCOM. Qui a changé de nom, avant c&rsquo;était le CSA, si ça vous parle plus. L&rsquo;ARCOM est garant (le R dans son nom c&rsquo;est pour «&nbsp;régulation&nbsp;», donc le fait d&rsquo;imposer les règles et faire qu&rsquo;elles soient appliquées) que les médias, et en particulier ceux du service public, respectent la déontologie de l&rsquo;information. Une des composantes de cette déontologie (c&rsquo;est d&rsquo;ailleurs un motif de signalement, lorsque vous en faites un sur le site de l&rsquo;ARCOM), c&rsquo;est le fait de fournir une information honnête. Donc bien sûr, avant de faire tout ce boulot de dingue, nous avons alerté l&rsquo;ARCOM. Nous sommes 5 mois plus tard, toujours aucune réponse (ah ça, pour s&rsquo;insurger quand des gens se foutent des nouilles dans le slip chez Hanouna, y a du monde, mais pour mise en danger de la vie d&rsquo;autrui, y a plus personne).</p>
<p>Comme nous sommes tenaces (certains diraient teigneux, on les embrasse), nous sommes allés, par le biais d&rsquo;un de nos membres qui a ses accès, directement confronter des représentants de l&rsquo;ARCOM sur le sujet. Et la réponse a été «&nbsp;nous ne voulons pas faire d&rsquo;ingérence&nbsp;», traduisez «&nbsp;nous refusons de jouer notre rôle de régulateur&nbsp;», traduisez «&nbsp;si des chaines du service public diffusent des contenus dangereux, tant que c&rsquo;est pas signalé en masse, c&rsquo;est pas notre problème&nbsp;», traduisez «&nbsp;circulez, y a rien à voir&nbsp;». Bon. Du coup, j&rsquo;espère qu&rsquo;ils prendront pas trop mal qu&rsquo;on les accuse de complicité, mais le «&nbsp;refus d&rsquo;ingérence&nbsp;» lors de la mise en danger d&rsquo;autrui, ça s&rsquo;appelle «&nbsp;non-assistance à personne en danger&nbsp;» donc bon, quitte à pas se faire des copains, autant y aller jusqu&rsquo;au bout. J&rsquo;avais pas pour projet de faire carrière chez eux de toute façon. Donc pour la cavalerie, on repassera.</p>
<h3 id="serieusement-pourquoi-vous-vous-êtes-inflige-un-truc-pareil"><a href="#serieusement-pourquoi-vous-vous-êtes-inflige-un-truc-pareil">SERIEUSEMENT, POURQUOI VOUS VOUS ÊTES INFLIGE UN TRUC PAREIL&nbsp;?</a></h3>
<p>A ce stade, je pense qu&rsquo;il est évident que ce travail était nécessaire. Mais il est légitime, au vu de l&rsquo;ampleur de la tâche, de la gratification nulle ou négative (j&rsquo;ai dit que le modo était dans les starting blocks déjà, non&nbsp;?) que nous allons en tirer et de la difficulté du sujet, de se demander pourquoi nous avons quand même décider de nous y atteler. Déjà, parce qu&rsquo;il fallait bien que quelqu&rsquo;un le fasse. Il y a des dizaines, des centaines de sujets importants à traiter, et je fais partie de ceux qui pensent que le monde avance mieux lorsque chacun travaille là où il le peut plutôt que lorsqu&rsquo;on passe un temps fou à débattre de quel sujet doit passer en premier, lequel est plus important, et pourquoi tu parles pas du lobbying de Pfizer à la place, et qui s&rsquo;en fout des vaccins quand y a la famine au Yémen, et, et, et… Si vous estimez que c&rsquo;est du temps perdu, qu&rsquo;il y a plus important à traiter, faites-vous plaisir, je ne vous disputerais pas la place. Il y a bien assez de travail pour tout le monde, chacun peut trouver quelque chose qui lui parle.</p>
<p>Et c&rsquo;est justement parce que, derrière le chercheur, le médecin, le pharmacien, ce problème nous parle en tant qu&rsquo;humain qu&rsquo;on a décidé de s&rsquo;y attaquer, à ça plutôt qu&rsquo;à un autre. Je disais plus tôt qu&rsquo;il y a des parties que j&rsquo;ai refusé de traiter, les confiant à d&rsquo;autres collègues, parfois par compétence, parfois par défiance envers moi-même. Mon petit frère a failli mourir de la rougeole enfant, je ne suis pas capable de traiter calmement les propos des gens disant que «&nbsp;chez nous, c&rsquo;est des maladies bénignes&nbsp;». Lorsque j&rsquo;étais à l&rsquo;université, nous avons fait face à une épidémie de méningite et avons dû tous être vaccinés en urgence, mais cela est arrivé trop tard pour les premiers cas, ceux par qui l&rsquo;alerte était arrivée, et un camarade en est mort. Je ne suis pas capable de traiter objectivement les arguments fallacieux de gens qui ne voient pas en quoi l&rsquo;obligation vaccinale apporte quoi que ce soit par rapport à la vaccination «&nbsp;en anneaux&nbsp;» (c&rsquo;est-à-dire vacciner l&rsquo;entourage du ou des cas quand la maladie arrive). Je dois vivre, aujourd&rsquo;hui, avec les conséquences de la complication d&rsquo;un virus contre lequel un vaccin existe, avec des séquelles qui étaient parfaitement évitables, et si je ne suis plus en danger et n&rsquo;en souffre pas non plus de façon quotidienne, j&rsquo;ai forcément de la colère contre les gens qui, finalement, militent pour que plus de gens soient atteints des mêmes souffrances que moi. Je ne peux pas traiter avec recul des passages où des gens comme Anne essayent de tuer des gens comme moi. C&rsquo;est la raison pour laquelle nous savions qu&rsquo;il fallait s&rsquo;attaquer au Machin, mais s&rsquo;y attaquer en groupe, pour ne pas tomber dans les biais que nous voulions dénoncer, pour ne pas devenir comme ceux que nous voulions exposer (quand tu regardes l&rsquo;abîme, tout ça tout ça).</p>
<hr />
<p>Alors lisez <a href="https://bigpragma.wordpress.com/2023/04/14/analyse-complete-du-documentaire-des-vaccins-et-des-hommes">le débunk</a> (par morceaux, selon ce qui vous intéresse). Partagez-le. Mettez-le en avant quand des gens doutent, se posent des questions ou diffusent n&rsquo;importe quoi. Souvenez-vous qu&rsquo;il a été fait avec soin, rigueur et méthode, mais aussi avec colère et sentiment d&rsquo;urgence. Souvenez-vous que si nous, nous faisons de la science, de la vulgarisation, du débunkage, cela n&rsquo;est rien sans impact populaire, sans force de frappe, et cette force c&rsquo;est vous. Nous vous donnerons toujours les ressources, pour peu que vous nous donniez la force.</p>
<hr />
<p>Vous l&rsquo;avez fait encore une fois. Merci à vous.</p>
    </div>)
}