
import { Article } from "@/atoms/Article";

export const Article20230528LechodeslabosMetadata = {"tags":["covid","SIDA","VIH","trithérapie","Johnson&Johnson","Malawi","Mozambique","Zambie","Afrique du Sud","Zimbabwe","Institut de recherche vaccinale","tuberculose","anticorps","lymphocytes T","cellules dendritiques","trauma générationnel","décodage biologique","biogénérationnel","épigénétique","Rachel Yehuda","Centre de psychothérapie psychédélique et de recherche sur les traumas","École de médecine de New York, NY","New York University School of Medicine","cortisol","troubles de l’humeur","anxiété","stress post-traumatique","adrénaline","gamète","ovocyte","embryogénèse","attentats du 11 septembre 2001","gène","FKBP5","psychothérapie cognitivo-comportementale","autisme","psychanalyse","pseudo-médecine","Tina Turner","hypertension","homéopathie","AVC","greffe d'organes","Show Your Kidneys Love","Maladie émergente","OMS","ebola","marburg","fièvre de Lassa","fièvre hémorragique de Crimée-Congo","maladie X","Centre international de gastronomie moléculaire","AgroParisTech-Inrae","Didier Raoult","François Asselineau"],"title":"l'Écho des Labos - 28 mai 2023","description":"Aujourd&#39;hui, c&#39;est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l&#39;état de la recherche sur l&#39;épidémie de Covid-19 et le reste. Si vous aimez la chronique, vous pourrez bientôt nous soutenir à nouveau sur KissKissBankBank (on y travaille).","date":"2023-05-28","layout":"layouts/post.njk"}

export const Article20230528Lechodeslabos : Article = ({
  className, title, img, KissKissBankBank, abbr, Facebook
}) => {
  return (<div className={className}>
      <dl>
<dt>{ img("https://laboutique.edpsciences.fr/system/product_pictures/data/009/981/962/original/Vulgarisation_scientifique_Mode_d_emploi.jpg",  "↓",  "width:100%" ) }</dt>
<dd>Couverture du livre "Vulgarisation scientifique — Mode d'emploi" de Cécile Michaut. Il y a un dessin d'une femme, tenue rose, et un homme, tenu rouge, face à face à deux homme, le premier en blouse blanche et le second chemise orange et pipe. L'homme à la chemise rouge demande: "Pouvez-vous nous expliquer simplement pourquoi c'est compliqué ?"
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }, c&rsquo;est tout nouveau, ça vient de sortir.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>C&rsquo;est pas vraiment un fake, plus un tissu de bêtises généralisé, mais comme on est venu gentiment me chatouiller les gonades avec ça après la vidéo d&rsquo;interview du débunk, soit, il faut qu&rsquo;on parle des avancées sur le vaccin contre le { abbr("SIDA", "syndrome d'immunodéficience acquise" ) }.</p>
<p>«&nbsp;Ouais, mais comment ça se fait le Covid on a eu un vaccin en quelques mois le SIDA 40 ans et toujours rien&nbsp;!&nbsp;» Du calme Jean-Gérard, regarde, tu fais même peur à la ponctuation, elle s&rsquo;est enfuie&nbsp;! Déjà, on rappelle qu&rsquo;un vaccin, c&rsquo;est l&rsquo;immunité naturelle qu&rsquo;on forme en avance. Tout ce qu&rsquo;on sait faire aujourd&rsquo;hui, c&rsquo;est utiliser l&rsquo;immunité naturelle en lui désignant une cible, c&rsquo;est tout. Sauf que le { abbr("VIH", "Virus de l'immunodéficience humaine" ) }, lui, il colonise en premier les cellules de l&rsquo;immunité. Donc c&rsquo;est un peu comme distribuer des flingues à une armée où t&rsquo;as plus un seul soldat au poste, c&rsquo;est pas gagné pour avoir un résultat. Et donc on rame.</p>
<p>«&nbsp;Oui, les labos ils cherchent même pas, parce qu&rsquo;ils veulent vendre leur trithérapie à la place&nbsp;» Ils cherchent, on a eu plusieurs tentatives, mais elles sont juste pas assez bonnes pour qu&rsquo;on en parle. Par exemple Johnson&#x26;Johnson a lancé un essai de 4 ans sur des jeunes femmes du Malawi, du Mozambique, de Zambie, d'Afrique du Sud et du Zimbabwe, mais il a été arrêté lorsque les résultats ont montré une efficacité inférieure à 25%. Côté recherche publique, l'institut de recherche vaccinale avait aussi dû mettre un terme à son essai clinique, après des résultats décevants autour de 30% de protection seulement. Tu voudrais quand même pas que les mecs ils te vendent un vaccin qui marche pas, Jean-Gérard&nbsp;?</p>
<p>«&nbsp;Oui, tout ça pour nous fourguer encore de l&rsquo;{ abbr("ARN", "acide ribonucléique" ) }&nbsp;!&nbsp;» L&rsquo;ARN est un composant essentiel du vivant, tu en manges tous les jours, gars, il faut te détendre, tu vas nous faire un AVC. Il est effectivement très possible que, à l&rsquo;avenir, de plus en plus de vaccins soient à ARN (c&rsquo;est d&rsquo;ailleurs sur cette piste qu&rsquo;on s&rsquo;oriente pour fournir un nouveau vaccin, plus efficace, contre la tuberculose), parce que quand on trouve une nouvelle technologie en s&rsquo;en sert. En revanche, pour le VIH, ce n&rsquo;est pas vraiment ce vers quoi on s&rsquo;oriente. Le candidat vaccin le plus prometteur à l&rsquo;heure actuelle (et il est français, cocorico) repose sur l&rsquo;injection d&rsquo;anticorps, mais prend pour cible, contrairement à la plupart des vaccins qui ciblent les fameux lymphocytes T, les cellules dendritiques, des composants auxiliaires du système immunitaire qui n&rsquo;attaquent pas eux-mêmes les pathogènes mais «&nbsp;forment&nbsp;» les cellules tueuses. Un changement de stratégie qui vient du fait qu&rsquo;on comprend petit à petit pourquoi ce qu&rsquo;on a fait avant ne marchait pas. Ca s&rsquo;appelle l&rsquo;auto-critique, Jean-Gérard, tu devrais essayer.</p>
<hr />
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p>À l&rsquo;heure où tout un tas de charlatans viennent vous parler des «&nbsp;traumas générationnels&nbsp;» pour expliquer les problèmes de santé des gens, et leur vendre derrière (cher) des formations en «&nbsp;décodage biologique&nbsp;», des soins «&nbsp;biogénérationnels&nbsp;» et autres thérapies «&nbsp;transneuroquantiques de réharmonisation généticokarmique&nbsp;» parce que moi aussi je peux inventer des concepts bidons qui sonnent classe t&rsquo;as vu, il y a, en fait, de vraies recherches menées sur la transmission du trauma par l&rsquo;épigénétique. Rachel Yehuda, qui dirige le Centre de psychothérapie psychédélique et de recherche sur les traumas à l&rsquo;école de médecine de New York (nde: dans l'état de New York), a ainsi montré avec son équipe que les traumatismes vécus par les parents avaient des impacts sur le taux de cortisol des enfants, les rendant plus susceptibles de souffrir de troubles de l&rsquo;humeur, d&rsquo;anxiété et de stress post-traumatique… d&rsquo;évènements qu&rsquo;ils n&rsquo;ont pas vécus. En cause, l&rsquo;épigénétique via l&rsquo;impact des hormones du stress (adrénaline et cortisol) sur le développement des gamètes. Le stress intense modifie la façon dont les gamètes maturent, en particulier les ovocytes, dont le stock est présent et fixe dès la naissance. L&rsquo;équipe a aussi étudié des enfants marqués par le stress lors de l&rsquo;embryogénèse, dans le cas de femmes enceintes rescapées ou proches de victimes du { abbr("11 septembre", "Attentats du 11 septembre 2001" ) }. Les travaux, loin d&rsquo;être fatalistes, ouvrent des pistes de traitement, puisqu&rsquo;un des gènes impliqués repéré, FKBP5 de son petit nom, peut voir son expression modifiée par la psychothérapie cognitivo-comportementale. L&rsquo;épigénétique, c&rsquo;est une vraie science les enfants.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Autisme</strong>&nbsp;: après que la psychanalyse ait enfin arrêté d&rsquo;emmerder les mères des enfants autistes en les comparant à des frigidaires (c&rsquo;est pas vrai, elle a pas arrêté, c&rsquo;est juste qu&rsquo;on l&rsquo;écoute plus), la science commence sérieusement à se tourner du côté des pères pour comprendre comment cette condition apparaît. Une étude récente de génomique (<a href="https://www.sciencedirect.com/science/article/pii/S2666979X23000873?via%3Dihub">à lire ici</a>) montre ainsi que, dans les fratries où au moins deux enfants sont autistes, ceux-ci partagent plus que prévu leur génome paternel. L&rsquo;étude, qui a inclu 6.000 familles volontaires, laisse entrevoir 2 hypothèses majeures. La première est épigénétique&nbsp;: pour une raison inconnue, les gènes paternels ne seraient pas «&nbsp;silenciés&nbsp;» correctement lors de la fabrication des spermatozoïdes, conduisant, soit à la transmission de gènes inducteurs de l&rsquo;autisme, soit à la non-transmission de gènes protecteurs. La seconde est immunitaire&nbsp;: en transmettant un génome en surnombre, le père conduirait l&rsquo;organisme de la mère à déclencher une réaction immunitaire plus forte que normal face à l&rsquo;embryon (cette réaction existe toujours, car l&rsquo;embryon est un corps étranger pour le système immunitaire de la mère, mais elle est normalement rapidement sous contrôle), qui souffrirait lors de son développement d&rsquo;avoir été attaqué plus durement par les défenses maternelles. Aucune hypothèse n&rsquo;est privilégiée à ce jour, et on ignore si ce modèle est pertinent pour les familles où un seul enfant est porteur.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Pseudo-médecine</strong>&nbsp;: cette semaine, la merveilleuse et puissante Tina Turner nous a quittés à l&rsquo;âge de 83 ans. Si la cause de la mort n&rsquo;est pas précisément connue (et n&rsquo;a pas à l&rsquo;être par le grand public, car il s&rsquo;agit avant tout du drame intime d&rsquo;une famille), la musicienne avait exprimé quelques jours plus tôt, le 5 mai, sur les réseaux, son immense regret d&rsquo;avoir cru en les pseudo-médecines, croyance qui a été la source de grandes souffrances et a probablement abrégé sa vie. Pendant des années, elle a ainsi soigné son hypertension avec de l&rsquo;homéopathie, au lieu des traitements conventionnels, entrainant (parmi d&rsquo;autres facteurs) son accident vasculaire cérébral, mais surtout la destruction complète de ses reins. Comprenant trop tard son erreur, Tina Turner n&rsquo;avait dû sa survie qu&rsquo;à la chance que son mari soit un donneur volontaire et compatible (ce qui est assez rare entre conjoints). Greffée en 2017 pour ne plus avoir à vivre sous dialyse, la légende du rock soutenait depuis l&rsquo;initiative Show Your Kidneys Love (<a href="https://www.showyourkidneyslove.com">ici pour plus d&rsquo;infos</a>) pour éviter à d&rsquo;autres personnes la même erreur qu&rsquo;elle. Souhaitons que son dernier message soit entendu.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Maladie émergente</strong>&nbsp;: alors que le monde commence à peine à sortir la tête du Covid, l&rsquo;{ abbr("OMS", "Organisation Mondiale pour la Santé" ) } s&rsquo;inquiète déjà de la suite. Quelle suite, me direz-vous, est-ce que franchement on n&rsquo;a pas assez morflé comme ça&nbsp;? Et bien que nenni, mais la suite n&rsquo;est pas encore connue. Parmi les épidémies sur le tableau de chasse de l&rsquo;OMS, on trouve Ébola (qui tue à peu près la moitié des malades), son lointain cousin Marburg (qui frise les 80% de létalité de son côté), la fièvre de Lassa (bénigne la plupart du temps, mais pouvant être mortelle selon les souches en circulation), la fièvre hémorragique de Crimée-Congo (transmise par les tiques et tuant jusqu&rsquo;à 30% des patients atteints) et enfin la fameuse «&nbsp;maladie X&nbsp;», le truc qu&rsquo;on aura pas vu venir et qui sortira par surprise au détour d&rsquo;une chauve-souris, d&rsquo;un vison ou d&rsquo;un ornithorynque parce qu&rsquo;il faut au moins ça pour concurrencer le pangolin. Non, on n&rsquo;est pas sortis du sable.</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Cuisine</strong>&nbsp;: la science se mêle de tout, et donc aussi des choses importantes comme la cuisine, la meilleure façon de faire une mayonnaise et c&rsquo;est quoi comme vin qui va le mieux avec la ratatouille. Et la science a tranché&nbsp;: si vous voulez que vos pâtes, pâtisseries, vol-au-vent et autres tourtes soient le plus doré, c&rsquo;est le jaune d&rsquo;œuf battu seul (sans eau, sans sel, sans rien on a dit) et appliqué en deux couches qui marche le mieux. Oui, c&rsquo;est très sérieux, c&rsquo;est le Centre international de gastronomie moléculaire d&rsquo;AgroParisTech-Inrae qui le dit. Oui, c&rsquo;est français, comment vous avez deviné&nbsp;?</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Ca faisait longtemps qu&rsquo;on avait pas parlé de { abbr("Didier", "Didier Raoult" ) } (ceux qui ont dit «&nbsp;et ça nous manquait pas dans le fond&nbsp;» ont le droit de se faire un café avant de continuer à lire). En même temps, quelqu&rsquo;un qui n&rsquo;a fait que des conneries depuis 20 ans (oui, quand on lit un peu les rapports d&rsquo;inspection, on se rend compte que ça fait un sacré moment que ce souk dure…), on ne peut pas taper dessus tout le temps, ça fait acharnement.</p>
<p>Mais ce coup-ci, il a presque dit un truc bien&nbsp;! Presque, on va en reparler… Et ça, il faut le dire aussi. Dans une longue (très longue, trop longue, beaucoup trop longue) interview accordée à François Asselineau (qui a aussi sorti pas mal de dingueries de son côté, vous pouvez les retrouver traitées dans la chronique via l&rsquo;outil recherche de la page), Didier nous dit, comme ça, sans qu&rsquo;on soit prêt, que les vaccinés contre le Covid, ben en fait, ils sont moins morts du Covid.</p>
<p>J&rsquo;avoue, on était pas prêts. Bon, et juste après, il a fait un tweet pour dire que en fait il parlait que des vieux et que chez les jeunes, le vaccin n&rsquo;avait en fait que des effets secondaires et rien de positif et vas-y Didi que c&rsquo;est reparti… Mais pendant quelques heures, on a pensé que le flop monumental de sa biographie et sa complète mise au ban de la communauté scientifique internationale (enfin encore plus complète qu&rsquo;avant, on rappelle que même avant la crise, il était interdit de publication dans plusieurs grands journaux américains pour fraude) avaient produit l&rsquo;électrochoc salvateur et que Saroumane était revenu à la raison.</p>
<p>Bon ben raté, mais ça valait le coup de vérifier.</p>
<hr />
<h3 id="point-methode-de-la-semaine-nouveau-grand-sujet-la-vulgarisation"><a href="#point-methode-de-la-semaine-nouveau-grand-sujet-la-vulgarisation">POINT METHODE DE LA SEMAINE&nbsp;: Nouveau grand sujet&nbsp;: la vulgarisation</a></h3>
<p>Ensemble, on a déjà parlé de pas mal de choses (oui, je sais que certains veulent que j&rsquo;en fasse un livre, vous en faites pas, je serai sans doute au chômage à un moment ou un autre, j&rsquo;aurais le temps de me pencher dessus), mais, une fois qu&rsquo;on parle de la méthode de la recherche, il faut aussi parler de la méthode qui fait que la recherche arrive correctement jusqu&rsquo;à… ben jusqu&rsquo;à vous, en fait.</p>
<p>Donc, comme précédemment avec les grands sujets, voici le plan de ce gros tour d&rsquo;horizon que je prévois de faire. N&rsquo;hésitez pas à dire en commentaire (nde: sur { Facebook( ) }) si vous pensez que ça ne répond pas à toutes vos questions, s&rsquo;il y a des aspects que vous voulez voir traiter (plus, mieux autrement), s&rsquo;il y a des sujets que je n&rsquo;ai pas abordés.</p>
<ul>
<li>Semaine 1&nbsp;: choisir le bon interlocuteur, doit-on «&nbsp;croire&nbsp;» ou «&nbsp;accorder sa confiance&nbsp;», comment et pourquoi</li>
<li>Semaine 2&nbsp;: pour qui vulgarise-t-on, à quoi ça sert de vulgariser</li>
<li>Semaine 3&nbsp;: comment bien vulgariser un propos compliqué, jusqu&rsquo;où simplifier, quoi préciser</li>
<li>Semaine 4&nbsp;: la vulgarisation est faite par des humains, quand et pourquoi faut-il arrêter</li>
</ul>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec le mois de mai, contrairement à ce que beaucoup ont voulu croire. En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}