
import { Article } from "@/atoms/Article";

export const Article20230910LechodeslabosMetadata = {"tags":["covid","scorbut","cancer","vitamine C","embriyons","cellules souches","épiblaste de blastocyte","Bioéthique","Cosmologie","superamas du Bouvier","antivaxx","Antivaccinalisme","USA","rage","Wakefield","Brigitte Bardot","Santé Publique France","Éris","fêtes de Bayonne","HPV","papillomavirus humain","Henri Joyeux","hépatite B","effet Ratatouille","Idéfix","Centre national d’études spatiales de Toulouse","Phobos","Mars","MMX"],"title":"l'Écho des Labos - 10 septembre 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-09-10","layout":"layouts/post.njk"}

export const Article20230910Lechodeslabos : Article = ({
  className, title, img, KissKissBankBank, Facebook
}) => {
  return (<div className={className}>
      { img("https://i.ytimg.com/vi/ZRJ_0PeIGhY/maxresdefault.jpg",  "Le space core de portal 2 qui est surrexité car il est dans l'espace !!!",  "width:100%" ) }
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Aujourd&rsquo;hui, je vais revenir sur un fake apparemment inoffensif, mais qui pourrait être, selon les dernières données, beaucoup, beaucoup plus dangereux que soupçonné à l&rsquo;origine.<br />
Normalement, tout le monde voit c&rsquo;est quoi la vitamine C. Vous en prenez peut-être en hiver quand vous êtes fatigués. Pendant le Covid c&rsquo;était présenté comme un remède (comme à peu près tout depuis la pisse de vache jusqu&rsquo;au shampooing pour mouton), et c&rsquo;est largement présenté dans le «&nbsp;bon sens&nbsp;» populaire comme pouvant prévenir le rhume ou la grippe, ce genre de chose.</p>
<p>Deux choses à ce sujet. La première, c&rsquo;est que tout ça est bidon. Prendre de la vitamine C ne sert à rien si vous n&rsquo;avez pas de carence, ça soigne effectivement le scorbut mais vous êtes pas tous Rackam-le-Rouge que je sache donc dans la plupart des cas bernique. Ce mythe vient d&rsquo;un mec (deux fois Prix Nobel tout de même, comme quoi), dont j&rsquo;ai prévu de vous parler dans un prochain format, donc patience. Mais de nombreuses études ont pu montrer que, au contraire, la prise de vitamine C pouvait augmenter le risque d&rsquo;infarctus ou de cancer. Et la dernière découverte en date à ce sujet concerne le cancer du poumon.</p>
<p>Ce sont les Suédois qui ont mis le doigt sur l&rsquo;affaire (et c&rsquo;est <a href="https://www.jci.org/articles/view/169671">publié ici</a>), le tout étant dû au fameux «&nbsp;effet antioxydant&nbsp;» de la vitamine C. Les antioxydants, c&rsquo;est bon pour plein de trucs, notamment empêcher la mort cellulaire (même des cellules mutantes qui devraient vraiment mourir…) ou aider à former de nouveaux vaisseaux sanguins (même quand lesdits vaisseaux alimentent des tumeurs et permettent aux métastases de se répandre…). L&rsquo;équipe appelle à une très grande vigilance dans l&rsquo;usage des compléments alimentaires chez les patients atteints de cancers, en particulier à une heure où les «&nbsp;médecines alternatives&nbsp;», les «&nbsp;soins complémentaires&nbsp;» et autres «&nbsp;ça peut pas faire de mal&nbsp;» fleurissent partout.</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>Aujourd&rsquo;hui, on va parler d&rsquo;une grosse, très grosse prouesse scientifique. Et on va prendre notre temps parce que c&rsquo;est compliqué, pour plein de raisons. <a href="https://www.nature.com/articles/s41586-023-06604-5">Un article paru dans la très prestigieuse revue Nature</a> est en train de retourner à lui seul plusieurs domaines de la recherche. L&rsquo;équipe a réussi à créer pour la première fois des embryons humains complets, qui se sont développés normalement pendant 14 jours, sans ovule, ni spermatozoïde. Maintenant, on panique pas, et on détaille.</p>
<p>Comment ils ont fait, sérieux, c&rsquo;est quoi ce bordel&nbsp;? Les embryons ont été obtenus à partir de cellules souches, des cellules qui ont la capacité de se différencier par la suite pour donner tout ce dont le corps peut avoir besoin (la peau, les yeux, le foie, mais aussi dans le cas d&rsquo;un embryon le placenta). Il existe différents types de cellules souches et différentes manières de les obtenir, que je ne vais pas détailler parce que c&rsquo;est assez long et complexe. Dans le cas qui nous intéresse aujourd&rsquo;hui, les cellules souches de l&rsquo;étude sont issues de l&rsquo;épiblaste d&rsquo;un blastocyte (et avec ça, on est bien avancé, pas vrai&nbsp;?), donc si ça vous aide vous pouvez vous dire que, niveau performance, c&rsquo;est à peu près aussi dingue que si, à la naissance d&rsquo;un petit humain, vous récupériez le placenta, vous lui filiez un coup de jus façon Frankenstein et le machin se développait en un jumeau (ce n&rsquo;est PAS ça qui se passe, c&rsquo;est une caricature pour vous transmettre le niveau de difficulté de la prouesse technique, c&rsquo;est tout ; si on sait «&nbsp;demander&nbsp;» à des cellules souches de se spécialiser en un tissu particulier, leur faire produire un embryon complet est juste absolument dingue).<br />
Pourquoi 14 jours, qu&rsquo;est-ce qu&rsquo;il leur est arrivé après ça, est-ce qu&rsquo;ils ont juste atrocement muté et qu&rsquo;on nous le cache&nbsp;? Non, au jour 14 ils sont morts dans la Javel. Je déconne presque pas (je sais pas pour la Javel), les lois de bioéthique interdisent la recherche sur les embryons humains passés le jour 14, donc ils ont tout simplement été détruits. Mais jusque-là, leur développement se passait relativement bien.</p>
<p>Ou du moins, on le pense, parce qu&rsquo;en fait, on en sait trop rien. Et oui, et c&rsquo;est là l&rsquo;intérêt de la recherche&nbsp;: le développement de l&rsquo;embryon humain est encore très, très mal connu, pour la bonne et simple raison que c&rsquo;est un merdier sans nom à observer et du coup, ben on pense qu&rsquo;ils se sont développés normalement, peut-être à l&rsquo;exception de quelques tissus qui semblaient pas placés où on pensait, mais comme on connait pas vraiment bien le «&nbsp;normalement&nbsp;» chez l&rsquo;humain, on est sûrs de rien. En produisant ces embryons, les chercheurs ont voulu proposer un modèle qui permettrait d&rsquo;étudier le développement humain passé le jour 14, parce qu&rsquo;on a plein de trucs à comprendre avec ça&nbsp;: comment étudier la toxicité d&rsquo;un traitement destiné à la mère sur son embryon sans faire courir de risque à un vrai bébé en route&nbsp;; à quel moment certaines pathologies de développement apparaissent-elles, est-ce qu&rsquo;on peut les prévenir, peut-être même les traiter en rectifiant le tir très tôt&nbsp;; si on arrive à «&nbsp;demander&nbsp;» à une cellule souche un embryon complet, est-ce qu&rsquo;on pourrait leur «&nbsp;commander&nbsp;» un cœur de rechange, un poumon&nbsp;; qu&rsquo;est-ce qui se passe vraiment lors d&rsquo;une fausse couche, est-ce que ça peut être prévenu etc. Autant de questions auxquelles il est impossible pour l&rsquo;instant d&rsquo;apporter des réponses parce qu&rsquo;on a rien sur quoi les étudier. D&rsquo;où la création de ce modèle… et l&rsquo;avalanche de questions éthiques et philosophiques qu&rsquo;il soulève.</p>
<p>Peut-on parler d&rsquo;un embryon humain s&rsquo;il n&rsquo;est pas issu d&rsquo;une reproduction humaine&nbsp;? Si une cellule souche issue d&rsquo;un humain se développe, est-ce qu&rsquo;elle appartient à cet humain donneur, est-ce qu&rsquo;elle est la propriété de ceux qui la font se développer, est-ce que c&rsquo;est un individu&nbsp;? Le modèle présenté dans l&rsquo;étude ne pourra jamais se développer en bébé dans un utérus, car «&nbsp;il contourne l&rsquo;étape nécessaire pour s&rsquo;accrocher à la paroi&nbsp;», mais quid du suivant&nbsp;? Et bien on ne sait pas. D&rsquo;un côté, il n&rsquo;y a pas d&rsquo;urgence, le temps de la recherche est long, et il va encore y avoir du café qui va couler sous les paillasses avant qu&rsquo;on arrive à ce stade. De l&rsquo;autre, c&rsquo;est justement parce qu&rsquo;on en est encore loin qu&rsquo;il faut se poser les questions maintenant. C&rsquo;est l&rsquo;intérêt de la bioéthique (et on va en reparler dans le Point méthode de la semaine), et c&rsquo;est pas plus mal qu&rsquo;on prenne son temps&nbsp;: lorsque la question centrale «&nbsp;c&rsquo;est quoi un être humain&nbsp;», les philosophes et les éthiciens peuvent en avoir pour un moment.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Cosmologie</strong>&nbsp;: a-t-on enfin observé directement l&rsquo;une des structures témoins des tous premiers temps de l&rsquo;Univers&nbsp;? Peut-être (mais non partez pas, vous allez voir c&rsquo;est chouette). C&rsquo;est en tout cas ce que pense l&rsquo;équipe qui vient de <a href="https://iopscience.iop.org/article/10.3847/1538-4357/aceaf3">publier la découverte</a> de ce qu&rsquo;on pense être une colossale bulle d&rsquo;un milliard d&rsquo;années-lumière de diamètre entourant le superamas du Bouvier, à 820 millions d&rsquo;années-lumière de notre galaxie, qui fait quant à elle partie du superamas Local (parce qu&rsquo;on avait vraiment des idées nazes pour nous alors qu&rsquo;à coté y a ptet des ET qui vivent dans superamas Poissons-Baleine et c&rsquo;est trop classe). Appelée Ho'oleilana (un terme TRES difficile à traduire, qui vient du Kumulipo, le chant de la création dans la culture Hawaïenne, mais qui donnerait à peu près quelque chose comme «&nbsp;les murmures de l&rsquo;éveil&nbsp;»), la découverte n&rsquo;est toutefois pas une surprise pour la communauté scientifique, puisque de telles structures sont prédites depuis un bon demi-siècle. Mais c&rsquo;est comme trouver le fossile d&rsquo;une créature prédite par la théorie sur laquelle personne n&rsquo;avait jamais posé les yeux.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Antivaccinalisme</strong>&nbsp;: est-ce que j&rsquo;ai besoin de faire un rappel sur pourquoi dire que les vaccins «&nbsp;donnent&nbsp;l&rsquo;autisme&nbsp;» (quoi que cela veuille dire) est parfaitement absolument absurde&nbsp;? Non, vous pensez que c&rsquo;est bon sur cette partie-là&nbsp;? Eh bien accrochez-vous à vos slips alors, parce que vous êtes pas prêts. Bon la nouvelle nous arrive des USA donc je sais que c&rsquo;est un peu prévisible, mais les Américains sont des Homo sapiens comme nous (je le sais, j&rsquo;ai pu le constater sur pièce avec ma belle-sœur) et il n&rsquo;y a pas de raison qu&rsquo;ils soient spécialement plus perchés que nous autres bouffeurs de grenouilles ou nos voisins qui ont inventé la marmite (même si c&rsquo;est vrai que c&rsquo;est pas bon). Une petite étude (menée sur un échantillon représentatif de la population et <a href="https://www.sciencedirect.com/science/article/abs/pii/S0264410X23010150?via%3Dihub">publiée ici</a>) concernant les propriétaires de chiens, a montré que 53% d&rsquo;entre eux remettent en question la vaccination pour leur animal domestique, y compris, pour la moitié d&rsquo;entre eux, pour la rage (on rappelle que, si la couverture vaccinale chez les chiens tombent sous les 70%, les humains sont les victimes suivantes, donc ça rigole moyen là). Mais surtout (tenez fort le slip, là) 37% de l&rsquo;échantillon pense que vacciner leur chien peut… le rendre autiste. Sérieusement. Et du coup, la prochaine étape c&rsquo;est quoi&nbsp;? Est-ce que le labrador autiste a le droit d&rsquo;avoir son propre labrador d&rsquo;assistance, ou ça se passe comment&nbsp;? Est-ce que Wakefield sortira un spin-of de son film pourri featuring Brigitte Bardot&nbsp;? Le monde veut savoir&nbsp;!</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Covid &#45; Eris</strong>&nbsp;: l&rsquo;épidémie avance à bas bruit en France. Après les fêtes de Bayonne, un laboratoire d&rsquo;analyse témoignait auprès de FranceBleu d&rsquo;un taux de positivité des tests à plus de 70%. En Nouvelle-Aquitaine, la barre de 15 cas dépistés pour 100.000 habitants a été franchie. En Ile-de-France, les actions de SOS Médecins pour des suspicions Covid ont pris 43% en une semaine. Ca ne flambe pas encore, mais le feu couve…</p>
<p><em>Source&nbsp;: Santé Publique France</em></p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>HPV et désinformation</strong>&nbsp;: d&rsquo;abord radié, puis dé-radié, Henri Joyeux vient d&rsquo;être à nouveau interdit d&rsquo;exercer la médecine pour une durée de 2 ans pour ses propos (et ses pétitions) sur le vaccin HPV et celui sur l&rsquo;hépatite B. Il s&rsquo;opposait notamment à la vaccination des enfants pour ce dernier, arguant que ça n&rsquo;avait pas de sens de vacciner des bébés contre une maladie sexuellement transmissible (je rappelle que la source des contaminations c&rsquo;est 18% dans un contexte familial non-sexuel, 14% suite à une exposition dans l&rsquo;enfance comme la transmission mère-enfant et 25% des cas où on ne retrouve jamais la porte d&rsquo;entrée, donc ça fait quand même plus de la moitié des cas qui ont rien à voir avec la choucroute ou avec la pétition), et à celle des adolescents pour le HPV, arguant que ça n&rsquo;avait pas de sens de vacciner alors qu&rsquo;il suffisait de «&nbsp;se respecter&nbsp;» pour ne pas être contaminé (je rappelle qu&rsquo;il peut aller se faire cuire le cul). Plus sérieusement, on rappelle que le HPV, à l&rsquo;heure actuelle, infecte 80% des adultes de plus de 40 ans, donc il circule pleine balle chez tout le monde et dès que les ados vont avoir le début d&rsquo;une vie sexuelle (oui, les vôtres aussi, et vous serez les derniers au courant) ils vont être exposés, donc on arrête de raconter n&rsquo;imp, merci.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Je sais que chez les chercheurs, on se prend pas au sérieux (chez les vrais, je veux dire, y a ceux qui éructent qu&rsquo;ils sont des vrais experts et ceux qui bossent, que voulez-vous), et je suis personne pour juger les noms que les collègues donnent à leurs projets, leurs concepts ou leurs inventions (je suis moi-même à l&rsquo;origine du concept «&nbsp;d&rsquo;effet Ratatouille&nbsp;», le fait que mes collègues continuent à me prendre au sérieux est pour moi un fascinant mystère). Et puis je sais, aussi, que lorsqu&rsquo;on envoie des rovers sur Mars, avec leur taille et leurs gestes un peu pataud, que ce soit Curiosity ou les autres, on a tendance à leur trouver des airs de chiens de l&rsquo;espace, c&rsquo;est normal.<br />
Mais quand même. Est-ce que, pour une fois que la France envoie un de ces machins sur Mars, on était obligés de se vautrer dans les clichés et l&rsquo;appeler… Idéfix. Oui&nbsp;? Bon, ben dans ce cas, sachez que Idéfix vient d&rsquo;être présenté au Centre national d&rsquo;études spatiales de Toulouse, que c&rsquo;est un beau bébé de 25 kilos et qu&rsquo;il devrait atterrir sur Phobos, une des deux lunes de Mars, en 2027 pour servir d&rsquo;éclaireur à la sonde japonaise MMX et aller renifler des cailloux. Je ne sais pas qui est le mec qui a convaincu un comité de direction de donner un nom pareil à un bijou technologique de plusieurs millions d&rsquo;euros, mais je lui voue une admiration sans borne.</p>
<hr />
<h3 id="point-méthode-de-la-semaine-la-bioéthique-pour-quoi-faire-"><a href="#point-méthode-de-la-semaine-la-bioéthique-pour-quoi-faire-">POINT MÉTHODE DE LA SEMAINE&nbsp;: la bioéthique, pour quoi faire ?</a></h3>
<p>Nous ne comprenons pas le vivant. Ce n&rsquo;est pas un cri de désespoir, c&rsquo;est un constat extrêmement basique. Nous avons des dizaines de définitions de «&nbsp;la vie&nbsp;» (et sans doute pas loin autant lorsqu&rsquo;il s&rsquo;agit de parler «&nbsp;d&rsquo;espèces&nbsp;»). Le vivant, c&rsquo;est un continuum.<br />
Nous sommes des humains, mais jusqu&rsquo;à quand&nbsp;? Qu&rsquo;est-ce que ça veut dire, lorsqu&rsquo;on remonte dans le temps «&nbsp;humain&nbsp;»&nbsp;? On se doute qu&rsquo;il n&rsquo;y a pas eu un jour une proto-humaine qui a donné naissance à un bébé humain, nous avons bien en tête que cela s&rsquo;est fait par étape. Pourtant, nous avons besoin de définitions pour étudier notre histoire.<br />
Nous sommes vivants, mais jusqu&rsquo;à quand&nbsp;? La mort est un processus graduel, quelqu&rsquo;un en arrêt cardiaque, en état de «&nbsp;mort apparente&nbsp;», peut parfois être ramené au bout de longues minutes, parfois des heures (c&rsquo;est rare, mais on a eu des cas). A l&rsquo;inverse, il y a des gens dont le cœur bat et dont on peut dire avec certitude qu&rsquo;ils ne sont plus que des machines biologiques, sans espoir de retour (c&rsquo;est le cas de tous les donneurs de cœur pour les greffes). Quel pourcentage de cellules du cerveau doit s&rsquo;éteindre pour que celui-ci, et avec lui l&rsquo;humain qui pense, soit considéré comme «&nbsp;mort&nbsp;»&nbsp;? A l&rsquo;inverse, et c&rsquo;est un sujet explosif dans le débat sur l&rsquo;avortement, quand commence-t-on à être un humain&nbsp;? Est-ce le simple potentiel de la première cellule, est-ce le moment où le système nerveux se met en place, est-ce le moment où le fœtus serait viable en-dehors de la mère&nbsp;?</p>
<p>La science n&rsquo;a pas d&rsquo;avis tranché sur ces questions parce qu&rsquo;il n&rsquo;existe pas de réponses scientifiques claires sur ces sujets, et il n&rsquo;en existera jamais. Parce que la nature même du vivant, c&rsquo;est d&rsquo;être un continuum et de ne pas avoir de limite franche et fixe. Mais nous, chez les humains, nous avons besoins de ces limites. Nous avons besoin de savoir quand un embryon est légalement un humain, quand un humain est légalement mort, quand quelque chose est officiellement un vivant. La bioéthique, c&rsquo;est le passage de relai de la biologie à la philosophie. Le moment où la science donne tout ce qu&rsquo;elle a accumulé à la philosophie pour lui demander d&rsquo;en sortir une morale. Qui forcément sera arbitraire. Qui forcément aura des cas limites. Et qui, forcément, devra être modifiée dans le futur, lorsque la science aura de meilleures lunettes, pour regarder le vivant d&rsquo;encore plus près, et voir les limites encore plus floues. Et qu&rsquo;elle reviendra tendre de nouveaux résultats à la philosophie en lui disant «&nbsp;tu vas pas me croire, mais j&rsquo;ai encore tout cassé&nbsp;».</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec l&rsquo;ouverture de la saison des marécages (et ouais, ici, c&rsquo;est la période de cueillette des champignons, des cranberries, des airelles et des astelpajud, que j&rsquo;ai jamais trouvé comment ça se disait en français mais c&rsquo;est bon). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}