
import { Article } from "@/atoms/Article";

export const Article20231022LechodeslabosMetadata = {"tags":["covid","Prix Nobel","Prix Nobel de médecine/physiologie","Dr. Katalin Karikó","Dr. Drew Weissman","ARNm","ADN","ARN","Robert Malone","pseudo-uridine","spike","Vical","thérapies géniques","hématopoïèse","hôpital pour enfants de Philadelphie","Reconstruction mammaire","cancer du sein","Lattice Medical","phase d’essai clinique","CHU de Lille","syndrome de Guillain-Barré","désinformation","situation Israélo-Palestinienne","Conspiracy Watch","OSINT","harcèlement","Vi-Vi","V_V","To be or not Toubib","complotist deleter","procédures bâillon","Didier Raoult","Alexander Samuel","IHU Marseille","Reiner Fuellmich","escroquerie aggravée","OSINT","Open Source Intelligence","Bellingcat","53e brigade anti-aérienne de l’armée Russe","crimes de guerre","Ukraine","Cour Pénale Internationale","Sergueï Skripal","Ioulia Skripal"],"title":"l'Écho des Labos - 22 octobre 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Monbazillac, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-10-22","layout":"layouts/post.njk"}

export const Article20231022Lechodeslabos : Article = ({
  className, title, img, KissKissBankBank, Facebook
}) => {
  return (<div className={className}>
      <dl>
<dt>{ img("https://i0.wp.com/mackaycartoons.net/wp-content/uploads/2023/10/2023-10-04.jpg?resize=700, 664&#x26;ssl=1",  "voir figcaption en-dessous",  "width:100%" ) }</dt>
<dt>Description</dt>
<dd>Un dessin des Docteurs Drew Weissman et Katalin Karikó sur un podium, partageant la plus haute marche, avec leur médailles d'or de prix nobel de médecine 2023.
</dd>
<dd>Sous une pluie de virus.
</dd>
<dd>Le Dr. Weissman les protégeant d'un parapluie siglé "mRNA" et le Docteur Karikó tendant un parapluie siglé "Vaccin" à une famille aillant l'air triste, dont le père arbore un polo "COVID Fatigue".
</dd>
<dd>On peut voir des bulles d'exclamations venant de personnes hors-champ et criant:
<blockquote>
<p>J'ai fais mes propres recherches</p>
</blockquote>
<blockquote>
<p>Les vaccins ne sont pas nécessaires</p>
</blockquote>
<blockquote>
<p>L'immunité naturelle est mailleure</p>
</blockquote>
<blockquote>
<p>Les vaccins causent l'autisme</p>
</blockquote>
<blockquote>
<p>C'est un complot de Big Pharma</p>
</blockquote>
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Monbazillac, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>On va démarrer le retour de la chronique par un fake qui pourrait recevoir le prix Nobel du culot, si jamais c&rsquo;était une discipline valide. Comme vous l&rsquo;avez sans doute vu passer un peu partout (et au grand dam de nos antivax favoris), le prix Nobel de médecine/physiologie a été attribué cette année à Katalin Karikó et Drew Weissman, pour leur découverte qui a permis que les vaccins à ARNm voient le jour. Ils n&rsquo;en sont pas les inventeurs directs, mais ils sont ceux qui ont permis de lever l&rsquo;obstacle le plus complexe&nbsp;: produire in vitro l&rsquo;ARN et le protéger de façon à ce qu&rsquo;il puisse atteindre les cellules sans se faire dégommer dès l&rsquo;entrée par le système immunitaire. Sans eux, pas de vaccin à ARN. Voilà, merci (beaucoup, du fond du cœur), bonsoir (et félicitations).</p>
<p>QUAND SOUDAIN (oui, c&rsquo;est la reprise, il faut que je retravaille mes effets) entre en scène Robert Malone. Si le nom vous dit quelque chose, c&rsquo;est sans doute parce qu&rsquo;on a déjà eu, plusieurs fois, à débunker cette égérie des antivax lors du lancement de la campagne de vaccination en 2021. Et si vous pensiez que l&rsquo;attribution du nouveau prix Nobel lui aurait un peu appris l&rsquo;humilité, vous êtes tellement pas prêts… En effet, Malone a plutôt twitté (oui, je sais, on est censé dire X, mais c&rsquo;est débile, je refuse) «&nbsp;Kariko (sic) et Weissman obtiennent le Nobel, non pas pour avoir inventé des vaccins à ARNm (parce que c&rsquo;est moi qui l&rsquo;ai fait) mais pour avoir ajouté la pseudo-uridine qui a permis de fabriquer un nombre illimité de toxines spike dans ce qui aurait pu être une plate-forme vaccinale sûre et efficace, si elle était développée en toute sécurité. Bon à savoir.&nbsp;» Le tout, sans trembler des genoux. C&rsquo;est tellement énorme qu&rsquo;on va décortiquer un peu.</p>
<p>Malone a-t-il inventé le vaccin à ARN&nbsp;? Evidemment que non. En revanche, il a effectivement été un pionnier de l&rsquo;idée des usages concernant l&rsquo;ARN messager, mais ses idées ne vont jamais aboutir, pour différentes raisons. La première, c&rsquo;est qu&rsquo;après avoir rédigé un article fondateur sur l&rsquo;idée du transport d&rsquo;ARNm dans les cellules, il se brouille avec son directeur de recherche et doit interrompre son doctorat. La seconde, c&rsquo;est qu&rsquo;ayant par la suite intégré l&rsquo;entreprise Vical pour mener des expériences sur la synthèse des protéines codées par ARN, il ne publiera jamais ses travaux dans des journaux scientifiques (de fait, il sera compliqué pour les pairs de prendre ce travail au sérieux). La troisième, c&rsquo;est qu&rsquo;après ces quelques années de recherche, il se brouillera à nouveau avec son superviseur et devra à nouveau changer d&rsquo;équipe. La quatrième, c&rsquo;est qu&rsquo;après avoir enfin réussi à finir son doctorat, il verra ses demandes de financement de recherche (notamment pour développer un vaccin à ARNm destiné à lutter contre les infections saisonnières à coronavirus…) rejetées car la piste ne semble pas viable (trop complexe, trop coûteuse, trop instable). Robert Malone fait certes partie des centaines de personnes qui ont rendu la création des vaccins à ARNm possible, mais il n&rsquo;en est clairement pas l&rsquo;inventeur.<br />
C&rsquo;est quoi cette histoire de «&nbsp;toxine spike&nbsp;»&nbsp;? La vieille marotte de Malone, qu&rsquo;on a déjà débunké 20 fois, et qui part du principe que si la spike peut être dangereuse pour certaines cellules du corps humain (ce qui est vrai), alors le vaccin qui la fait produire à une poignée de cellules est dangereux (ce qui est faux, la dose, le poison, tout ça tout ça) surtout pour les enfants qui font peu de formes graves (mais qui auront quand même la protéine spike du virus qui va proliférer partout, donc l&rsquo;argument ne se tient pas sur ce point-là) et qui sont peu contaminants (ce qui est faux puisque les chiffres de l&rsquo;Institut Pasteur estiment que la présence d&rsquo;un adolescent dans le foyer renforce le risque de contamination des adultes de 30%, un chiffre pouvant aller jusqu&rsquo;à 90% en présence d&rsquo;enfants de moins de 3 ans).<br />
Pourquoi il dit des dingueries pareilles alors, cette espèce de grosse endive&nbsp;? Le message peut sembler très contradictoire (le vaccin à ARN est dangereux, mais en même temps c&rsquo;est novateur c&rsquo;est moi qui l&rsquo;ai inventé etc.) et je pense que c&rsquo;est dû à deux motivations contradictoires chez Malone. La première, c&rsquo;est le conflit d&rsquo;intérêt, puisqu&rsquo;il travaille pour l&rsquo;un des plus gros conglomérats indiens de fabricants de vaccins concurrents de la technologie ARNm (donc on est sur du classique «&nbsp;eux c&rsquo;est toxique et dangereux, mon produit à moi est mieux, achetez-le&nbsp;»). La seconde, qui là pour le coup est spéculative, est que je pense que Malone est malade de jalousie&nbsp;: le mec avait des idées réellement novatrices, personne n&rsquo;a voulu les financer parce que ça ne semblait pas rentable (et aussi parce qu&rsquo;il publiait pas dans des vrais journaux et qu&rsquo;il avait manifestement un caractère de merde pour arriver à se brouiller avec la moitié de son réseau…) et finalement c&rsquo;est devenu LA grosse invention en immunologie du XXIe siècle, c&rsquo;est rageant. Mais Karikó aussi en a chié et ça l&rsquo;a pas fait tourner antivax pour autant. On appelle ça l&rsquo;intégrité, Robert, tu devrais essayer…</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>Pour rester dans le thème, je vais vous parler cette semaine d&rsquo;une découverte, liée également à l&rsquo;ARN, et qui a le potentiel pour valoir un prix Nobel à quelqu&rsquo;un un jour… quand la technologie sera au point (et là, le chemin est encore long, mais c&rsquo;est bien normal). Avant de vous la présenter, un point de contexte sur les thérapies géniques. Les thérapies géniques visent à modifier le matériel génétique des cellules impliquées dans des maladies graves, pour qu&rsquo;elles arrêtent de faire nawak. Aujourd&rsquo;hui, on sait ainsi traiter certaines maladies du sang et de l&rsquo;immunité de cette manière, mais le processus est complexe et dangereux. En effet, pour ce faire on prélève de grandes quantités de cellules de la moelle osseuse en charge de l&rsquo;hématopoïèse (un mot compliqué pour dire que ces cellules vont fabriquer à peu près tout ce qui circule dans le sang, des plaquettes aux globules rouges en passant par toutes les cellules de l&rsquo;immunité), on modifie leur code génétique en laboratoire (pour qu&rsquo;elles produisent ce qu&rsquo;il faut ou arrêtent de produire un truc qu&rsquo;il faut pas), et on les réinjecte au patient… après lui avoir fait une chimiothérapie pour tuer la plupart de sa moelle osseuse, afin que les cellules modifiées soient seuls maîtres à bord. Autant dire que les indications sont limitées car la balance bénéfice-risque est rarement favorable. La question qui se pose est donc&nbsp;: comment modifier les gènes de ces cellules directement à l&rsquo;intérieur de la personne&nbsp;?</p>
<p>C&rsquo;est une équipe de <a href="https://pubmed.ncbi.nlm.nih.gov/37499029/">l&rsquo;hôpital pour enfants de Philadelphie qui vient de publier des résultats qui vont peut-être changer la donne</a>. L&rsquo;équipe a réussi à améliorer l&rsquo;ARN messager de synthèse pour le rendre plus stable et donc lui faire faire des opérations plus complexes au cœur des cellules. En faisant des tests sur la moelle osseuse de souris, l&rsquo;équipe a montré que leur méthode permettait de «&nbsp;livrer&nbsp;» aux cellules et d&rsquo;y maintenir au travail l&rsquo;ARNm livré. En l&rsquo;occurrence, il s&rsquo;agit d&rsquo;un fragment codant l&rsquo;enzyme Cre, une enzyme qui est capable de recombinaison de l&rsquo;ADN (c&rsquo;est le copier-coller de la génétique) et qui pourrait donc éditer des portions de gènes directement au cœur des cellules concernées.</p>
<p>Evidemment, il s&rsquo;agit là d&rsquo;une recherche très balbutiante, une étape qu&rsquo;on appelle «&nbsp;preuve de concept&nbsp;», c&rsquo;est-à-dire qu&rsquo;elle démontre la faisabilité d&rsquo;un concept par l&rsquo;expérience, mais elle est encore très préliminaire, courte et incomplète. Il faudra d&rsquo;autres études précliniques avant d&rsquo;envisager des études sur l&rsquo;humain.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Reconstruction mammaire</strong>&nbsp;: c&rsquo;est une piste prometteuse pour la reconstruction mammaire post-ablation due au cancer du sein qu&rsquo;a mise au point la société Lattice Medical. L&rsquo;entreprise a crée une prothèse, imprimée en 3D à partir de matériau biorésorbable, qui permettrait aux tissus adipeux de se reconstruire et de reformer un sein, sans maintien de matériel médical à l&rsquo;intérieur du corps. <a href="https://pubmed.ncbi.nlm.nih.gov/36569243/">Les résultats sur modèle animal ont été encourageants</a> et l&rsquo;entreprise entre désormais en phase d&rsquo;essai clinique avec un partenaire hospitalier. Si vous êtes concernée ou avez une proche qui pourrait l&rsquo;être, vous pouvez contacter le CHU de Lille afin de vérifier votre éligibilité à intégrer l&rsquo;essai en question.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Covid &#45; complications</strong>&nbsp;: avec les progrès de la recherche sur le sujet, on en finit plus de découvrir des nouvelles complications au Covid, souvent heureusement assez rares, sinon, on les aurait vues avant. La dernière en date concerne le syndrome de Guillain-Barré, une maladie auto-immune où le corps se met à attaquer ses propres cellules nerveuses, provoquant des paralysies. Vous en avez peut-être déjà entendu parler parce que c&rsquo;est un des chouchous des antivax, qui s&rsquo;imaginent voir des liens entre ce syndrome et vaccination partout. Bon. <a href="https://n.neurology.org/content/early/2023/10/18/WNL.0000000000207998">La dernière étude publiée sur le sujet tend à montrer que les personnes infectées au Sars-Cov-2 dans les 18 mois précédent l&rsquo;étude avaient 6 fois plus de chances de déclencher un Guillain-Barré que les autres</a>. Un résultat particulièrement inquiétant (au vu du nombre de personnes qui l&rsquo;ont eu…) mais pas très surprenant car différents virus sont déjà soupçonnés d&rsquo;être des «&nbsp;déclencheurs&nbsp;» de la maladie, en paniquant le système immunitaire. La petite blagounette dans tout ça, c&rsquo;est quand même que l&rsquo;étude montre aussi un effet inverse avec la vaccination&nbsp;: les personnes qui avaient reçu une injection d&rsquo;ARNm dans les 18 derniers mois voyaient quant à elle leur risque divisé par deux… mais on est vraiment pas sûrs de pourquoi.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Désinformation</strong>&nbsp;: après le Covid19, après la guerre en Ukraine, c&rsquo;est maintenant le conflit Israélo-palestinien qui est une source majeure de désinformation sur les réseaux sociaux. Le phénomène est majeur mais pas surprenant, Conspiracy Watch par exemple constatant ce type de phénomène lors de chaque évènement de «&nbsp;crise&nbsp;». Je ne suis pas politologue (et je me contrefous de la politique, si ça m&rsquo;intéressait, j&rsquo;aurais fait SciencePo, pas un doctorat), je n&rsquo;ai donc pas d&rsquo;avis sur qui a raison, qui a tort, qui a commencé, quoi qu&rsquo;il faut faire et en fait personne n&rsquo;en a vraiment (même les experts, surtout les experts, ont une opinion très prudente). Je tiens simplement à rappeler que les informations doivent se vérifier avant d&rsquo;être partagées, peu importe l&rsquo;opinion que vous en avez, peu importe si ça conforte votre vision du monde, peu importe ce que vous ressentez face à ça. Si vous ne vous en sentez pas capable (pas le temps, pas l&rsquo;énergie, pas la compétence), alors on s&rsquo;abstient de partager, surtout de manière virulente, ça évite que la désinformation circule et ça vous évite d&rsquo;être dans l&rsquo;embarras si vous hurler vigoureusement contre un truc qui est démenti deux jours plus tard. Si vous voulez avoir de informations objectives dans les temps troublés, je vous encourage à vous penchez sur le travail des équipes d&rsquo;OSINT, des citoyens et organismes qui exploitent tout un tas de données disponibles en accès libre (depuis des images partagées sur les réseaux aux données des satellites météo). C&rsquo;est un travail énorme et ça mérite bien un Point méthode de la semaine.</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Harcèlement antivax</strong>&nbsp;: le groupe d&rsquo;origine italienne Vi-Vi (ou V_V ou «&nbsp;deux fois le V de Vendetta honteusement récupéré&nbsp;» ou «&nbsp;le club de ceux qui mangeaient de la colle au fond de la classe en cours de SVT&nbsp;») avait été particulièrement en pointe en ce qui concerne le harcèlement des vulgarisateurs, des soignants (et l&rsquo;ami To be or not Toubib en avait fait les frais) et des élus, s&rsquo;organisant en raids particulièrement agressifs (on peut ici remercier Complotist Deleter, qui avait organisé une surveillance accrue de leurs réseaux pour prévenir les attaques et sécuriser les pages ciblées), qui ont valu plusieurs jours d&rsquo;ITT à un certain nombre de leurs victimes. Certaines ont porté plainte et c&rsquo;est ainsi que 11 d&rsquo;entre eux (dont 10 «&nbsp;absolument sans histoire&nbsp;» avec des casiers judicaires parfaitement vierges) ce sont retrouvés sur le banc des accusés ce mois-ci. Les peines réclamées vont de 4 mois avec sursis à 4 mois fermes, certaines assorties de stage de citoyenneté et d&rsquo;amendes. On peut regretter que cela semble léger, mais c&rsquo;est un premier pas indéniable. Jugement attendu le 20 décembre.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>L&rsquo;Univers a un drôle de sens de l&rsquo;humour. Et parfois, la justice aussi. Du coup, j&rsquo;avoue ne pas trop savoir qui est mon chouchou de cette semaine. (ndle: la justice étant partie de l'Univers, perso toujours l'Univers)</p>
<p>Ca pourrait être Didier. Parce que Didier, il nous a quand même bien donné la migraine pendant des mois avec ses conneries à l&rsquo;IHU, et le fait d&rsquo;attaquer en justice les gens qui osaient pointer qu&rsquo;il faisait nimp, c&rsquo;était quand même le pompon sur la cerise sur le gâteau. Du coup, le retournement de situation qui a eu lieu dans l&rsquo;affaire qui l&rsquo;oppose à Alexander Samuel (mais si, vous voyez bien, le gars aux cheveux longs, métalleux, avec qui j&rsquo;étais dans le Parisien dans l&rsquo;article sur les scientifiques menacés par les antivax, biologiste, lâche jamais l&rsquo;affaire pire qu&rsquo;un pitbull, un mec adorable&nbsp;? vous le remettez&nbsp;? bien&nbsp;!) fait rudement plaisir. En effet, si l&rsquo;audience a été renvoyée du fait que les avocats de l&rsquo;accusation (de Didier donc) n'étaient pas prêts, elle a réservé une surprise de taille&nbsp;: l&rsquo;IHU s&rsquo;est désolidarisé de la plainte, mettant par là même fin à la prise en charge des frais judiciaires de Didier dans le procès. Hormis le fait que ça va peut-être le refroidir un peu, l&rsquo;IHU et lui sont co-plaignants dans une dizaine d&rsquo;affaires, dans lesquelles donc Didier n&rsquo;avait rien à payer puisque tout (pas loin de 100.000 euros tout de même) était pris en charge par l&rsquo;IHU. Si celui-ci décidait de se retirer des autres procédures, peut-être que Saroumane serait alors obligé de mettre fin à sa frénésie de procédures bâillon…</p>
<p>Mais il y a encore plus drôle. C&rsquo;est l&rsquo;arrestation de Reiner Fuellmich, l&rsquo;avocat Allemand qui devait être en charge de «&nbsp;traîner devant la justice&nbsp;» d&rsquo;un grand «&nbsp;Nuremberg 2.0&nbsp;» tous les «&nbsp;criminels contre l&rsquo;humanité&nbsp;» liés à la pandémie (j&rsquo;étais dans le lot, et je suis limite déçue, je suis jamais allée en Allemagne, ça aurait été l&rsquo;occasion)… mais qui a préféré se barrer au Mexique avec la caisse (plus d&rsquo;un million d&rsquo;euros tout de même, généreusement donnés par tout un tas de gens très éclairés qui appellent les autres des pigeons). Fuellmich avait fui lorsqu&rsquo;un mandat d&rsquo;arrêt avait été émis à son encontre dans son pays, probable raison pour laquelle le Mexique s&rsquo;est dit qu&rsquo;il avait autre chose à faire que renouveler son titre de séjour et l&rsquo;a réexpédié manu militari direction Francfort. En détention provisoire, son procès aura sans doute lieu pour «&nbsp;escroquerie aggravée&nbsp;» ou quoi que ce soit dans le droit allemand qui ressemble à ça. Moi, je suis dans le canap&rsquo; et j&rsquo;attends toujours mon «&nbsp;arrestation imminente&nbsp;» par contre.</p>
<hr />
<h3 id="point-méthode-de-la-semaine-losint-quoi-que-cest"><a href="#point-méthode-de-la-semaine-losint-quoi-que-cest">POINT MÉTHODE DE LA SEMAINE&nbsp;: l&rsquo;OSINT, quoi que c&rsquo;est</a></h3>
<p>L'OSINT ou « Open Source Intelligence » (ou Renseignement de sources ouvertes, dans la langue de Francis Cabrel) est un type de renseignement obtenu à partir de données accessibles au public, par des membres de la société civile, parfois regroupés en communautés informelles et temporaires (typiquement pour collaborer sur une enquête en particulier avant de disparaitre dans la nature à nouveau) et parfois en entité pérennes et identifiables. La plus connue dans ce domaine se nomme Bellingcat (tiré d&rsquo;une fable qu&rsquo;on trouve en plusieurs langues au cours de l&rsquo;histoire, qui dit que le meilleur moyen de rendre un chat inoffensif, c&rsquo;est que les rats lui accrochent une clochette autour du cou).</p>
<p>Les communautés OSINT (et donc Bellingcat) ont deux particularités qui les distinguent du renseignement classique, opéré par les Etats. La première, c&rsquo;est de n&rsquo;utiliser que des données publiques, en accès libre sur Internet, et donc que tout le monde peut consulter. La seconde, c&rsquo;est que leurs rapports contiennent la méthodologie avec laquelle ils ont exploité ces données, permettant à n&rsquo;importe qui (en théorie, il faut parfois avoir les logiciels utilisés et les compétences techniques) de reproduire leurs manipulations et de vérifier leurs résultats.</p>
<p>Si cela peut sembler un simple passe-temps de geek (ça l&rsquo;est, mais pas que), il ne faut pas sous-estimer la puissance d&rsquo;analyse et la force de travail dont ces communautés sont capables, et leur influence lors des enquêtes internationales. Par exemple, lors du procès concernant l&rsquo;avion civil abattu en 2014 au-dessus de la Crimée, le rapport de Bellingcat fait partie des pièces versées au dossier grâce auxquelles les juges ont établi que l&rsquo;attaque émanait bel et bien de la 53e brigade anti-aérienne de l&rsquo;armée Russe. A l&rsquo;heure actuelle, ils font partie des groupes fournissant des enquêtes sur les crimes de guerre commis par cette même armée en Ukraine à la Cour Pénale Internationale et ont été les premiers à identifier clairement les empoisonneurs de Sergueï et Ioulia Skripal (autant dire que son fondateur doit avoir une prime sur la tête qui doit valoir son pesant de roubles). Les communautés OSINT sont donc observées de près par les instances judiciaires et le renseignement classique, qui considèrent de plus en plus que ce travail informel est une source fiable (de par sa nature ouverte et vérifiable) et puissante (de par le nombre de personnes impliquées).</p>
<p>De fait, je vous invite à vous pencher sur le travail de ces communautés, qui ne sont affiliées à personne, sans doute pleine de gens aux idées et convictions très diverses, dont les sources sont accessibles et la méthodologie publique. Si vous voulez avoir une opinion sur un évènement de grande ampleur, où des versions différentes s&rsquo;affrontent et où les enjeux sont sensibles, l&rsquo;OSINT est un excellent point de départ pour se forger une opinion.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec mon retour (sans doute temporaire, parce que je sais pas rester en place) en France. En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}