
import {FC} from "react";

export const Article20230122LechodeslabosMetadata = {"tags":["covid","Céline Dion","SRP","syndrome de la Personne Raide","syndrome de l’Homme Raide","syndrome de Moersch et Woltman","Lisa Marie Presley","Bert Smith","malaise vagal","malaise orthostatique","Alex Stalock","Giuseppe Perrino","Raphaël Dwamena","Boris Sadecky","Frédéric Lartillot","Chinelle Henry","Chedean Nation","Greg Luyssen","fibrose cardiaque","Meghan Roth","Johnson&Johnson","cancer","vaccin ARNm","thérapie génique","thérapie cellulaire","CRISPR-Cas9","glioblastome","XBB.1.5","CH.1.1","Orthos","OMS","BigPharma","The Intercept","BioNTech","Twitter","gouvernement allemand","brevets","Nina Morschhaeuser","Office fédéral de la sécurité des technologies de l'information","Bundesamt für Sicherheit in der Informationstechnik","BSI","OMC","tribunal administratif de Paris","France Soir","vaccin bivalent","AVC","FDA","U.S. FDA","naturopathe","Naturopathie","MIVILUDES","CNRS","Mucchielli","ARS","Didier Raoult","IHU"],"title":"l'Écho des Labos - 22 janvier 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-01-22"}

export type Article20230122LechodeslabosProps = {className?: string, title: string, img: (...args: unknown[]) => string, UTip: (...args: unknown[]) => string, abbr: (...args: unknown[]) => string}

export const Article20230122Lechodeslabos : FC<Article20230122LechodeslabosProps> = ({
  className, title, img, UTip, abbr
}) => {
  return (<div className={className}>
      <dl>
<dt>{ img("https://saltwire.imgix.net/2021/6/11/thumbnail_Bruce_06_12_2021_RGB.jpg?cs=srgb&#x26;h=568&#x26;w=847&#x26;auto=compress%2Cenhance%2Cformat",  "" ) }</dt>
<dd>Une femme en blouse blanche hurle avec un mégaphone estampillé SCIENCE sur un homme en chemise orange et bermuda caki tenant une manette de jeux vidéos dans les mains et portant un casque de réalité virtuelle marqué SOCIAL MEDIA.
</dd>
<dd>
<p>Bruce MacKinnon</p>
</dd>
<dd>12 juin 2021
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { UTip( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>On a parlé de Céline Dion la semaine dernière, certains d&rsquo;entre vous m&rsquo;ont fait remarquer que la même rhétorique de «&nbsp;célafotovaxin&nbsp;» était déjà à l&rsquo;œuvre en ce qui concerne la mort de Lisa Marie Presley, et la vérité est que ça va à un tel rythme qu&rsquo;il devient difficile de suivre. Dans le cas de Lisa Marie, il n&rsquo;a fallu que quelques minutes pour que des tweets liant sa mort au vaccin anti-Covid apparaissent (oubliant que, malheureusement, cette femme avait un très lourd passif d&rsquo;abus de toutes les substances sur lesquelles elle pouvait mettre la main pour tenter de combattre le chagrin lié à la mort de son fils unique, quelques années plutôt, et que ce genre de traitement peut avoir raison du cœur le plus solide).</p>
<p>Pour comprendre l&rsquo;ampleur du phénomène, le mieux est encore de regarder des exemples comme ce montage vidéo qui tourne beaucoup en ce moment, dans lequel 82 personnes s&rsquo;effondrent ou sont déclarées victimes « de morts inexpliquées&nbsp;», par arrêt cardiaque dû au vaccin nous dit-on. Et non, je ne vous mettrai pas de lien, vous allez comprendre pourquoi.<br />
Déjà, il est intéressant de noter, lorsqu&rsquo;on regarde les images en détails (ce que les auteurs de la vidéo ne veulent pas que vous fassiez, c&rsquo;est pour ça qu&rsquo;ils présentent ces 82 cas en 58 secondes…), que 4 des personnes sont des doublons, ça vous pose déjà la rigueur du schmilblick.</p>
<p>Ensuite, on peut éliminer 4 autres cas pour raisons chronologiques. 3 séquences datent de début 2020, 2015 et 2013. Si c&rsquo;est lié au vaccin Covid, ça veut dire que le voyage dans le temps existe, et c&rsquo;est peut-être une nouvelle plus importante que les myocardites. Un autre cas, celui de l&rsquo;arbitre de basket Bert Smith, a eu lieu avant que l&rsquo;homme puisse recevoir sa première injection, et ne peut donc lui être relié. Il en reste donc 74.</p>
<p>Parmi ceux-ci, 3 autres peuvent être éliminés puisqu&rsquo;il s&rsquo;agissait de simples malaises vagaux (ça se dit&nbsp;? c&rsquo;est moche non&nbsp;?) ou orthostatiques (genre ils se sont levés trop vite), et les «&nbsp;victimes&nbsp;» se portent très bien. 3 autres cas, plus tragiques, peuvent être évacués également, puisque la mort est due à un suicide, une overdose ou une crise d&rsquo;épilepsie. Reste 68.</p>
<p>L&rsquo;ironie commence là à être réelle, puisque 10 autres cas peuvent également être exclus, en raison du fait que le malaise cardiaque a pu être attribué… au Covid. C&rsquo;est le cas du gardien de hockey Alex Stalock, par exemple. 17 autres cas peuvent être exclus car liés à des pathologies préexistantes, comme c&rsquo;est le cas des footballeurs Giuseppe Perrino (dont le frère était déjà mort jeune d&rsquo;un arrêt cardiaque) et Raphaël Dwamena (qui se savait malade depuis 2017). Reste 41.</p>
<p>Pour 37 d&rsquo;entre eux, la mort est une «&nbsp;mort subite du sportif&nbsp;», un décès brutal de cause inconnue, non-élucidée car les familles ont refusé les autopsies (et c&rsquo;est leur droit, des familles en deuil ne doivent rien à personne, et surtout pas à des vautours qui cherchent à récupérer la mort de leurs proches). Lors des entretiens avec les proches, la cause vaccinale a été exclue, et pour plusieurs (le joueur de hockey Boris Sadecky ou encore le footballeur Frédéric Lartillot) la famille a expressément demandé à ce qu&rsquo;il n&rsquo;y ait pas de récupération par les antivax. Vous comprenez pourquoi, par respect pour les familles, je ne donnerai pas le lien d&rsquo;une vidéo qui inclut contre leur consentement la mort d&rsquo;un de leurs proches.</p>
<p>Il en reste 4 pour lesquels un lien pourrait être établi. MAIS. Dans le cas des joueuses de cricket Chinelle Henry et Chedean Nation, il s&rsquo;agit d&rsquo;un simple évanouissement (peut-être effectivement dû à un retour à l&rsquo;entrainement trop précoce après leur vaccination) et elles ont repris l&rsquo;entrainement dans la semaine. Dans le cas du cycliste Greg Luyssen, il est possible qu&rsquo;il ait fait un effort trop important en prenant part à une course majeure 3 jours seulement après sa seconde dose, alors qu&rsquo;il avait de la fièvre. Ce n&rsquo;est qu&rsquo;un mois plus tard (donc le lien est compliqué à établir formellement) qu&rsquo;on lui a diagnostiqué une fibrose cardiaque, mais si cela a mis fin à sa carrière, il n&rsquo;a pas fait d&rsquo;arrêt cardiaque. Enfin dans le cas de la coureuse Meghan Roth, c&rsquo;est elle qui a fait le lien entre son arrêt cardiaque lors du marathon de Boston et sa vaccination deux semaines avant… par le vaccin de Johnson&#x26;Johnson, qui n&rsquo;est pas celui pour lequel on a pu trouver un surrisque de myocardites.</p>
<p>Moralité&nbsp;: arrêtez d&rsquo;instrumentaliser les drames dans la vie des gens pour construire un narratif boiteux, c&rsquo;est pénible.</p>
<hr />
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p>Parlons toujours vaccin, mais parlons aussi cancer. Non parce qu&rsquo;on nous a rebattu les oreilles à dire que le vaccin ARNm, c&rsquo;était pas un vaccin mais une «&nbsp;thérapie génique&nbsp;», donc pour une fois qu&rsquo;on peut parler réellement de vaccin thérapeutique, on va pas s&rsquo;en priver.</p>
<p>La découverte en question (<a href="https://www.science.org/doi/10.1126/scitranslmed.abo4778">publiée tout fraîchement là</a>) est en réalité une «&nbsp;thérapie cellulaire&nbsp;» (bon, on repassera pour la thérapie génique, mais restez, ça va être intéressant quand même). Les chercheurs ont prélevé des cellules cancéreuses, les ont modifiées génétiquement via l&rsquo;outil d&rsquo;édition du génome CRISPR-Cas9 afin de leur faire exprimer un composé chimique qui rétablit le suicide cellulaire chez les cellules malades, avant de les injecter dans des sujets atteints de glioblastome, un cancer du cerveau contre lequel il n&rsquo;existe à l&rsquo;heure actuelle pas de traitement. Non seulement ces cellules, qui, étant elles-mêmes cancéreuses, savent identifier et retrouver leurs consœurs (alors que le système immunitaire est aveugle à les voir), ont complètement éliminé la tumeur ciblée, mais en plus, et c&rsquo;est là que le terme de «&nbsp;vaccin&nbsp;» intervient, elles créent de l&rsquo;immunité. En poussant les cellules tumorales au suicide, elles leur font également produire des molécules qui «&nbsp;appellent&nbsp;» le système immunitaire sur place, lequel devient alors capable de voir les cellules cancéreuses… et donc de leur tomber sur le coin de la tronche si jamais une rechute devait se produire.</p>
<p>Le système a été jugé très fiable car, lors de la modification du génome, les chercheurs ont également introduit dans les cellules cancéreuses un interrupteur de sécurité à deux niveaux pour l&rsquo;empêcher de développer son propre petit cancer perso. Ces essais sur l&rsquo;animal ayant été concluants, les chercheurs espèrent commencer au plus vite les tests sur l&rsquo;humain en proposant l&rsquo;essai thérapeutique à des malades qui, à l&rsquo;heure actuelle, sont condamnés. Le système est versatile, et des applications pour d&rsquo;autres cancers pourraient voir le jour si les tests sur l&rsquo;humain sont concluants.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Covid &#45; Variant</strong>&nbsp;: si le monde a les yeux rivés sur XBB.1.5 qui décime la population chinoise dans les grandes villes, c&rsquo;est contre un cousin, issu d&rsquo;une autre branche d&rsquo;Omicron, que les chercheurs Britanniques veulent mettre en garde. CH.1.1, surnommé «&nbsp;Orthos&nbsp;» représente déjà 25% des contaminations au UK et vient d&rsquo;être détecté en Espagne. Mais contrairement à XBB1.5 qui a des mutations de la Spike le rendant plus contagieux, Orthos a pris de son oncle, le variant Delta, une mutation qui peut le rendre beaucoup plus dangereux pour les cellules une fois qu&rsquo;il est dedans. Son évolution est surveillée par les ministères de la santé britannique et espagnol, et l&rsquo;OMS l&rsquo;a à l&rsquo;œil.</p>
<p><em>Source&nbsp;: OMS</em></p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>BigPharma</strong>&nbsp;: «&nbsp;oui, pourquoi tu parles toujours des mensonges des antivax et pas de ceux de BigPharma, t&rsquo;es une vendue, [insérez ici litanie très longue, répétitive et pénible pleine de spéculations sur l&rsquo;embonpoint de mon compte en banque et l&rsquo;usage mercantile de mon postérieur]&nbsp;». Déjà, parce que les antivax mentent tellement que c&rsquo;est une source sans fin, je pourrais en parler tous les jours et je couvrirai pas tout pour autant. Ensuite, parce que c&rsquo;est faux&nbsp;: quand BigPharma merde, j&rsquo;en parle, et c&rsquo;est le cas aujourd&rsquo;hui.</p>
<p>C&rsquo;est le très respecté média d&rsquo;investigation américain The Intercept (c&rsquo;est marrant hein, mais même quand il y a vraiment un complot, ben c&rsquo;est jamais les complotistes qui le découvrent) qui a révélé le pot aux roses (et non pas le poteau rose, comme j&rsquo;ai pu lire à certains endroits)&nbsp;: BioNTech a exercé, avec la complicité du gouvernement allemand, des pressions sur Twitter pour réduire au silence des voix dissidentes. Que tous les conspis rangent les cotillons&nbsp;: il n&rsquo;est pas question ici de dissimuler des voix parlant d&rsquo;effets secondaires ou d&rsquo;inefficacité ou de quoi que ce soit de ce genre, bien au contraire. Il s&rsquo;agissait d&rsquo;empêcher de s&rsquo;exprimer ceux qui réclamaient la levée des brevets sur les vaccins afin que ceux-ci soient plus accessibles pour les pays pauvres. Tout commence à la fin 2020, lorsque Nina Morschhaeuser, spécialiste des politiques publiques chez Twitter, reçoit une note de BioNTech l&rsquo;avertissant d&rsquo;une campagne à venir pour obtenir cette fameuse levée des brevets. Au départ, il est question de sécurité, avec risque de création massive de faux comptes ou de prises de contrôle des comptes des dirigeants des laboratoires par les activistes. Elle relaye donc la note à ses collègues en charge de la sécurité. Mais une seconde demande intervient, de la part de la porte-parole de BioNTech, appuyée par l'Office fédéral de la sécurité des technologies de l'information (une importante administration allemande)(ndle: Bundesamt für Sicherheit in der Informationstechnik ou BSI), demandant cette fois que soit masquée l&rsquo;intégralité des tweets de comptes ciblant son entreprise pendant les deux jours que devaient durer la campagne.</p>
<p>A l&rsquo;heure actuelle, il n&rsquo;est pas clair encore que Twitter a accédé à cette requête, et à quel point, mais les faits sont déjà graves, et les équipes de The Intercept sont en train de remonter plus loin encore, jusqu&rsquo;à un intense lobbying pour entraver la décision de l&rsquo;OMC de lever exceptionnellement les brevets, et dans lequel, une fois encore, le gouvernement allemand serait impliqué… L&rsquo;affaire est à suivre, parce que l&rsquo;enquête est longue et minutieuse. Les complots existent, nous aussi on sait en trouver. Sauf que nous, on a des preuves.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Justice</strong>&nbsp;: le juge des référés du tribunal administratif de Paris a annulé la décision de la Commission mixte paritaire des publications et agences de presse de retirer à France Soir son statut d&rsquo;organe de presse. On se rassure, il ne s&rsquo;agit que d&rsquo;une décision provisoire, portant sur un vice de forme (en l&rsquo;occurrence, le fait qu&rsquo;un membre de la commission a pas été fichu de fermer sa grande bouche et a annoncé le résultat probable de l&rsquo;évaluation avant que la commission se soit réunie), en attendant que le fond soit rejugé. Mais on va dire que ces temps-ci, la justice et la vérité scientifique ne sont pas en très bons termes…</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Vaccin bivalent</strong>&nbsp;: la nouvelle s&rsquo;est répandue un peu partout que le vaccin bivalent causerait des AVC chez les plus de 65 ans, mais cela ressemble de plus en plus à une fausse alerte. En réalité, la { abbr("U.S. FDA", "The United States Food and Drug Administration" ) } a repéré un signal statistique partiel (une anomalie de la survenue de certains évènements pour certaines tranches d&rsquo;âge) et les étudie pour savoir s&rsquo;il est judicieux de suspecter un lien avec la vaccination. A l&rsquo;heure actuelle, le signal en question n&rsquo;a produit aucun élément de causalité.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Vous vous souvenez, la semaine dernière, je vous parlais de ce naturopathe qui a enfin été arrêté pour son implication dans la mort de, au moins, trois de ses «&nbsp;patients&nbsp;». Comme ça fait du bruit, le gouvernement s&rsquo;en mêle et la secrétaire d&rsquo;état à la citoyenneté a tenu à mettre en garde les Français contre les gourous et les charlatans…</p>
<p>Dis voir (attendez, je vérifie comment elle s&rsquo;appelle, non parce qu&rsquo;on peut être énervé contre les gens et prononcer leur nom correctement) Sonia, est-ce que tu te foutrais pas un peu de notre gueule&nbsp;? On a un organisme qui est sensé lutter contre les gourous et les charlatans, ça s&rsquo;appelle la Miviludes, et il y a tellement de pression pour les empêcher de bosser qu&rsquo;ils sont 9 là&nbsp;! Evidemment qu&rsquo;il y a des gourous et des charlatans partout, les gars en charge de la lutte, ils se comptent sur les doigts des deux mains&nbsp;! Pour toute la France&nbsp;! Vous vous attendiez à quoi&nbsp;? «&nbsp;Il est impératif que les Français soient mieux informés sur les risques qu'ils encourent pour leur santé&nbsp;», ben bien sûr, évidemment, mais comment on est sensés informer les gens quand personne ne fait taire les désinformateurs en chef&nbsp;? Où est le CNRS pour empêcher Mucchielli de dire que le vaccin tue plus que la maladie&nbsp;? Où est l&rsquo;ARS pour reconnaître que c&rsquo;est pas acceptable&nbsp;de nommer à la succession de Raoult à l&rsquo;IHU le mec qui a signé toutes les autorisations du comité d&rsquo;éthique pour des essais cliniques qui étaient dangereux voire illégaux ? Où est le gouvernement pour prendre la défense des vulgarisateurs qui ont fait tout le boulot de communication correcte sur l&rsquo;épidémie à sa place et qui se retrouvent menacés de mort pour ça&nbsp;? «&nbsp;Il faut renforcer la Miviludes&nbsp;» mais non, Sonia, tu dis pas «&nbsp;il faut renforcer la maison&nbsp;» quand tout ce que tu as c&rsquo;est un unique mur porteur peint en jaune canari pour faire gai et coiffé d&rsquo;un bout de carton&nbsp;! Il faut construire la Miviludes, là elle tient debout par opération du Saint-Esprit (et abnégation de 9 pauvres fonctionnaires). Ça va bien deux minutes de foutre le feu aux rideaux puis de s&rsquo;étonner que la maison flambe, nous on en a marre de s&rsquo;échiner à lancer des seaux d&rsquo;eau pendant que les voisins nous engueulent parce qu&rsquo;on gaspille l&rsquo;eau potable&nbsp;! Oui, mes métaphores sont en forme ce soir&nbsp;!</p>
<hr />
<h3 id="point-methode-de-la-semaine-devenir-chercheur--trouver-sa-place-hors-de-france"><a href="#point-methode-de-la-semaine-devenir-chercheur--trouver-sa-place-hors-de-france">POINT METHODE DE LA SEMAINE&nbsp;: Devenir chercheur &#45; Trouver sa place (Hors de France)</a></h3>
<p>La France est victime d&rsquo;un phénomène appelé «&nbsp;la fuite des cerveaux&nbsp;» (non… non pas celui-là, non… quoique aussi, mais on va pas en parler aujourd&rsquo;hui). Sous-payés, mal considérés, ayant du mal à trouver un emploi, beaucoup de chercheurs partent à l&rsquo;étranger.</p>
<p>Je ne vais pas vraiment pouvoir vous faire un guide à ce sujet-là, car les procédures sont extrêmement variables d&rsquo;un pays à l&rsquo;autre, mais je vais pouvoir donner quelques précisions d&rsquo;ordre général, si jamais vous êtes un jeune chercheur avec l&rsquo;appel du large.</p>
<ol>
<li>
<p>Parlez anglais. En France, il est encore de coutume de publier en français, c&rsquo;est même tellement la norme que, lorsque vous candidatez pour un poste à l&rsquo;université, il vous faudra fournir des traductions de vos articles (au moins les abstracts) s&rsquo;ils ne sont pas en français. Le problème, c&rsquo;est que le monde de la recherche parle anglais. Les articles s&rsquo;écrivent en anglais. Si personne ne peut vous lire en anglais parce que vous ne publiez qu&rsquo;en français, alors personne ne vous cite, et, virtuellement, votre travail n&rsquo;existe pas pour le reste du monde. Donc, dès le départ, montez votre dossier tourné vers l&rsquo;international.</p>
</li>
<li>
<p>Ne perdez par de temps et d&rsquo;énergie avec la qualification ou l&rsquo;habilitation à diriger des recherches. Ce sont des lubies franco-françaises. Partout ailleurs, votre diplôme et votre CV sont les seules choses sur lesquelles vous serez évalué pour savoir si vous correspondez au poste et si vous êtes apte à encadrer des doctorants de la nouvelle génération. A titre d&rsquo;exemple, je n&rsquo;ai jamais eu de poste de MCF (les maîtres de conférence) en France, je suis donc très loin d&rsquo;avoir mon habilitation et personne ne me laisserait, si je rentrais, encadrer un doctorant avant probablement une petite décennie. Sur mon poste en Estonie, la seule raison pour laquelle on ne m&rsquo;a pas confié de thésard, c&rsquo;est que mon contrat est plus court que leur temps de thèse, et perdre son encadrant en cours de doctorat c&rsquo;est toujours le bordel.</p>
</li>
<li>
<p>Entrez pour l&rsquo;excellence, restez pour l&rsquo;humain. Le monde académique est parfois violent et impitoyable. Si vous ne pouvez pas savoir comment sont les gens avant de travailler avec eux, ne restez pas à un endroit où vous êtes maltraité. Il est bon de candidater à des projets d&rsquo;excellence et à des postes où vous êtes dans votre spécialité, c&rsquo;est ce qui vous rendra légitime. Mais si vous êtes compétent, que vous publiez bien (voir point 1) et que vous avez le goût de votre métier, le monde est vaste. Installez vous là où les gens vous donne envie de rester.</p>
</li>
<li>
<p>Faites confiance aux collègues (ceux qui ne vous donnent pas envie de partir). Le monde est vaste et les collègues bougent. Le monde académique est dur et tout le monde le sait. N&rsquo;hésitez pas à dire quand c&rsquo;est difficile pour vous «&nbsp;bientôt je n&rsquo;ai plus de travail, il n&rsquo;y a pas de poste qui s&rsquo;ouvre, je n&rsquo;ai pas eu ma bourse de recherche etc.&nbsp;» car il y aura toujours quelqu&rsquo;un pour vous dire «&nbsp;et tu connais machine&nbsp;? elle part en congé maternité, le département va chercher quelqu&rsquo;un pour l&rsquo;année universitaire qui arrive, je peux leur en parler&nbsp;» ou «&nbsp;je crois que mon institut relance son programme de bourse l&rsquo;an prochain, bon c&rsquo;est qu&rsquo;un an mais ça dépanne&nbsp;». Et, une fois que vous aurez réussi à avoir les pieds au sec et sur le dur, n&rsquo;oubliez pas de rendre la pareille «&nbsp;t&rsquo;as plus rien à partir d&rsquo;octobre&nbsp;? attends, je crois que le labo cherche quelqu&rsquo;un pour 6 mois, c&rsquo;est pas beaucoup, mais ça peut t&rsquo;aider déjà&nbsp;». La science, c&rsquo;est un sport d&rsquo;équipe, pas un sport de combat.</p>
</li>
</ol>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas, même si on en parle de moins en moins (qui l&rsquo;eut cru, que le déni ne réglait pas tout&nbsp;?). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur <a href="https://www.facebook.com/TheDendrobateDoctor/?ref=page_internal">la page Facebook du Docteur</a>.</p>
    </div>)
}