
    import { Article } from "@/atoms/Article";
    
    export const Article20230618LechodeslabosMetadata = {"tags":["covid","Djokovic","patch","Albert Edelfelt","Louis Pasteur","La biologie fait des vidéos","Des vaccins et des hommes","Vulgarisation","Endométriose","Dérive sectaire","Thierry Casasnovas","France Soir","Biostatisticien","Mathias Wargon","Azalbert","Bahrain Victorious","Gino Mäder","Tour de Suisse","Magnus Sheffield","Martine Wonner","Violaine Guérin","hydroxychloroquine"],"title":"l'Écho des Labos - 18 juin 2023","description":"Aujourd&#39;hui, c&#39;est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l&#39;état de la recherche sur l&#39;épidémie de Covid-19 et le reste. Si vous aimez la chronique, vous pourrez bientôt nous soutenir sur KissKissBankBank.","date":"2023-06-18","layout":"layouts/post.njk"}
    
    export const Article20230618Lechodeslabos : Article = ({
      className, title, KissKissBankBank, Facebook
    }) => {
      return (<div className={className}>
          <h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Tous les fakes ne sont pas forcément dus à des chefs de file conspis vociférant sur les réseaux sociaux. Certains sont le fait de chercheurs apparemment sérieux, dans des publications apparemment sérieuses (nan, rassurez-vous, je vais pas en remettre une couche sur Didier, on a compris). Juste avant que je parte en Finlande, un abonné est venu en MP me dire que, quand même, j&rsquo;avais râlé fort sur le patch magique de Djokovic, mais ça avait l&rsquo;air d&rsquo;être sérieux en vrai, puisqu&rsquo;il avait trouvé des publications scientifiques sur le site du fabricant, et il y en avait même un certain nombre. Il me donne le lien pour que j&rsquo;aille regarder.</p>
<p>Et là, on fait un premier stop. Vous voyez ça, et bien c&rsquo;est exactement ce qu&rsquo;il faut faire. Quelqu&rsquo;un (en l&rsquo;occurrence moi, mais on s&rsquo;en fout) vous dit un truc, ça vous intrigue ou vous semble bizarre, allez à la source de l&rsquo;info. L&rsquo;info vous semble sérieuse en raison de critères objectifs (il y a des publications scientifiques) mais un peu pointus, contactez quelqu&rsquo;un qui pourra y voir clair pour lui demander son avis.</p>
<p>Reprenons, c&rsquo;était quoi alors ces publications&nbsp;? Je suis le lien, j&rsquo;arrive sur une liste où il y a effectivement beaucoup de publications mises en avant par le fabricant, censées montrer que son autocollant magique fonctionne. Je décide d&rsquo;en ouvrir 3 au hasard, parmi celles dont je peux avoir accès au texte complet (soit directement, soit via le célèbre site d&rsquo;une célèbre kazakhe). La première est un protocole mené sur des patients atteints de sclérose en plaque, auxquels on colle le patch pendant leur programme habituel de rééducation, et on dit qu&rsquo;ils se portent mieux que d&rsquo;ordinaire. Mais y a pas de groupe de contrôle, donc en fait on en sait rien, poubelle, suivant. La seconde étude est un protocole similaire, cette fois avec un groupe contrôle, mais sans placebo (il y a le groupe à qui on colle le bidule et le groupe à qui on colle rien), donc impossible de savoir si les améliorations (dans une seule des catégories testées, les autres ne montrant aucune différence entre le groupe test et le groupe contrôle) sont supérieures à l&rsquo;effet placebo. Poubelle, suivant. La troisième étude enfin commence par expliquer le principe des nanoparticules et vous balance dès la section suivante des dessins new age sur «&nbsp;l&rsquo;aura du magnétisme humain&nbsp;». Bon. Je signale donc à l&rsquo;abonné que rien de ce que j&rsquo;ai vu ne peut décemment être qualifié d&rsquo;étude scientifique et qu&rsquo;il y a pas mal de gens qui mériteraient de perdre leur job dans l&rsquo;histoire… Mais il s&rsquo;interroge, car l&rsquo;étude que lui avait ouverte semblait très sérieuse et était même publiée dans un journal tout à fait légitime dans une vraie maison d&rsquo;édition.</p>
<p>Et là, on fait un second stop. Ça, c&rsquo;est encore une fois ce qu&rsquo;il faut faire. Si vous avez des éléments contradictoires en votre possession, demandez à ce qu&rsquo;ils soient examinés, car s&rsquo;il y a une vraie contradiction quelque part, il doit aussi y avoir une explication. Et explication, il y a (et pour la peine, je vais interrompre ma série sur la vulgarisation cette semaine pour vous parler de ça dans le Point méthode de la semaine), elle s&rsquo;appelle «&nbsp;le parasitisme&nbsp;». Lorsqu&rsquo;il a fait sa recherche, mon abonné ne s&rsquo;est pas aperçu que le journal dans lequel était publiée l&rsquo;étude n&rsquo;était pas «&nbsp;Journal of Biomedical Materials Research&nbsp;» (journal tout à fait respecté, qui fait partie du premier quartile dans son domaine et possède un bon facteur d&rsquo;impact et une solide revue par les pairs) mais «&nbsp;International Journal of Biomedical Materials Research&nbsp;» (un torchon hors-sol édité par une des plus grosse maison d&rsquo;édition prédatrices qui soit, qui fait croire qu&rsquo;il est basé à New-York alors qu&rsquo;il est au fin fond du Pakistan et qui acceptera de publier que le lavement au cactus peut vous guérir de la chtouille &#45; ou qu&rsquo;un autocollant magique va vous faire gagner Roland-Garros, c&rsquo;est pareil, hein &#45; si vous lui filez entre 770$ et 1670$).</p>
<p>Mais au-delà de ça, il y a un truc qui m&rsquo;a vraiment énervée dans cet échange. C&rsquo;est pas qu&rsquo;un abonné vienne me dire que peut-être, j&rsquo;avais parlé trop vite, non, ça c&rsquo;est cool. C&rsquo;est qu&rsquo;en lisant les publications qu&rsquo;il me citait, je me suis aperçue qu&rsquo;il y avait des médecins, liés à cette entreprise, qui avaient enrôlé des patients vulnérables atteints d&rsquo;une maladie incurable dans des protocoles à l&rsquo;autocollant magique au lieu de les inclure dans des vrais essais cliniques qui avaient peut-être une chance de faire évoluer leur maladie. Et ces gens-là sont la honte de leur profession.</p>
<hr />
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p>Y a pas grand-chose cette semaine, alors j&rsquo;en profite pour vous partager une découverte de mon périple en terre du Nord&nbsp;: saviez-vous que le portrait de Pasteur, genre LE portrait de Pasteur, celui qu&rsquo;on voit dans tous les livres d&rsquo;histoire, celui qu&rsquo;on sort à toutes les sauces quand on parle de vaccination, celui qui est limite devenu l&rsquo;allégorie des vaccins à lui tout seul, hé bien c&rsquo;est un Finnois qui l&rsquo;a fait&nbsp;? Il s&rsquo;appelait Albert Edelfelt (ça se prononce comme on peut) et hormis la peinture, il était manifestement spécialisé en moustache impressionnante et capacité à survivre au typhus. Donc si jamais vous aimez l&rsquo;histoire de l&rsquo;art, le gars était pour moi une chouette découverte. Ça et le fait que les Finnois mangent les petits pois crus.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Vulgarisation</strong>&nbsp;: comment rendre attractif un débunk&nbsp;? Comment faire que des gens s&rsquo;intéressent à un pavé de 115 pages, lorsqu&rsquo;en face on a un documentaire tout prêt&nbsp;? C&rsquo;est à cette question qu&rsquo;a tenté de répondre Mickaël de La biologie fait des vidéos, en proposant une série de vidéos courtes consacrées au débunk que nous avons produit sur «&nbsp;Des Vaccins et des hommes&nbsp;». Donc allez voir son travail, le premier épisode est sorti (<a href="https://www.youtube.com/watch?v=vlM_bo_dKXc">là</a>) et peut-être que je suis un peu dedans.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Endométriose</strong>&nbsp;: il y a quelques mois, les résultats d&rsquo;une étude portant sur un test salivaire pour dépister l&rsquo;endométriose avaient été rendus publics… et les chercheurs étaient sceptiques. L&rsquo;étude était intéressante, mais souffrait de limitations méthodologiques importantes, qui ne rendaient pas vraiment les résultats généralisables ou exploitables, et certainement pas au point d&rsquo;affirmer que le test détectait 96% des cas, comme le disait l&rsquo;équipe. Mais bon, ça arrive que les résultats soient bancals (pourquoi on dit pas bancaux là, sérieusement&nbsp;? C&rsquo;est n&rsquo;importe quoi le français&nbsp;!) lors d&rsquo;une étude pilote et ensuite confirmés. Et lorsqu&rsquo;une nouvelle étude est sortie il y a quelques jours (<a href="https://evidence.nejm.org/doi/full/10.1056/EVIDoa2200282">là</a>), avec des résultats encore très bons, j&rsquo;étais plutôt enthousiaste. Donc j&rsquo;ouvre le papier… et là je déchante. L&rsquo;étude n&rsquo;est pas mauvaise en soi, mais elle n&rsquo;a adressé AUCUNE des limitations méthodologiques relevées par les pairs&nbsp;: l&rsquo;échantillon est toujours trop petit, les marqueurs inflammatoires ne sont pas spécifiques, la symptomatique n&rsquo;est précisée nulle part et les données patients sont parcellaires. Donc, autant j&rsquo;ai très envie d&rsquo;y croire, autant pour l&rsquo;instant, ben ça marche toujours pas. La méthode, c&rsquo;est pas de la déco, les enfants, faut faire ça sérieusement.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Dérive sectaire</strong>&nbsp;: on en finit plus de trouver des trucs sur Thierry Casasnovas, alias Titi Les Jus de Fruits, alias, le Gourou Illuminé qui Sait Faire Repousser Vos Bras. Cette fois-ci, c&rsquo;est sa compagne qui a été placée en garde-à-vue pour… le volet financier. De vous à moi, ça me turbosaoule que ce soit ça qui concentre les efforts des flics et du procureur dans cette histoire quand on parle d&rsquo;un mec qui a probablement tué des gens à force d&rsquo;expliquer aux diabétiques qu&rsquo;ils avaient pas besoin d&rsquo;insuline, mais c&rsquo;est bien le fisc qui a fait tomber Al Capone, donc bon, on fait avec ce qu&rsquo;on a… Même si, comme Scarface, on n&rsquo;a aucun doute sur le fait qu&rsquo;il se défendra chèrement&nbsp;: à l&rsquo;heure actuelle, ses adeptes ont déjà versé près de 100.000€ pour financer ses avocats.</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>France Soir</strong>&nbsp;: vous vous souvenez de quand France Soir a menacé des chercheurs et des médecins (dont notre bon vieux Biostatisticien) de la guillotine&nbsp;? Sans doute. Est-ce que vous vous souvenez de quand Mathias Wargon, le chef des urgences de St-Denis, avait confronté Azalbert à ce sujet sur le plateau de BMFTV, en lui disant en résumé qu&rsquo;il était un gros dangereux&nbsp;? Sans doute moins. Est-ce que vous saviez que Azalbert avait donc attaqué le Dr. Wargon en diffamation&nbsp;? Sans doute pas, mais comme on les reconnait parce qu&rsquo;ils osent tout, personne n&rsquo;est surpris. Vous serez donc heureux d&rsquo;apprendre que le tribunal a poliment rappelé à Azalbert que la critique (surtout des menaces de mort), ça n&rsquo;est pas de la diffamation, et qu&rsquo;il faut les laisser parce que maintenant ils ont du travail (enfin ça c&rsquo;est pas dans le jugement, mais quand je vois la lettre d&rsquo;assignation, <a href="https://twitter.com/wargonm/status/1641836439506755586">dispo ici</a>, je me dis qu&rsquo;ils ont dû le penser très fort).</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>On le sait, c&rsquo;est devenu récurrent désormais, dès que quelqu&rsquo;un de jeune, si possible sportif meurt, c&rsquo;est la foire à la saucisse des «&nbsp;célafôtovaxin&nbsp;», comme si les gens jeunes étaient jamais morts avant. On en avait déjà parlé, les arrêts cardiaques ont toujours existé chez les sportifs de haut niveau, plus exposé que les autres à déclencher une éventuelle pathologie dormante. Et je trouve en général cette récupération dégueulasse. Mais là, on a franchi un cap. Vendredi, la Bahrain Victorious a annoncé la mort de son coureur Gino Mäder, à l&rsquo;âge de 26 ans. La veille, il avait été héliporté après que les secouristes aient dû le réanimer lors d&rsquo;une étape du Tour de Suisse. Malgré l&rsquo;action rapide des secours, Gino n&rsquo;a pas survécu, et la complosphère piaille donc à qui veut l&rsquo;entendre que tout est la faute de la vaccination. Je n&rsquo;ai pas eu besoin de chercher s&rsquo;il était vacciné ou non, s&rsquo;il avait une pathologie préexistante ou non, le drame a choqué et l&rsquo;info est donc disponible en une de TOUS les journaux helvètes&nbsp;: Gino a été retrouvé en arrêt cardiaque au fond d&rsquo;un ravin après avoir raté un virage dénoncé par d&rsquo;autres coureurs avant l&rsquo;épreuve comme particulièrement dangereux. Tellement dangereux qu&rsquo;en fait il n&rsquo;a pas chuté seul, Magnus Sheffield, un autre coureur, est toujours hospitalisé pour commotion cérébrale. Il y a vraiment des gens qui sont nés avant la honte.</p>
<hr />
<h3 id="point-methode-de-la-semaine-parasites-et-prédateurs"><a href="#point-methode-de-la-semaine-parasites-et-prédateurs">POINT METHODE DE LA SEMAINE&nbsp;: parasites et prédateurs</a></h3>
<p>Les journaux prédateurs vivent des frais que des chercheurs sont prêts à payer pour voir leurs papiers publiés, peu importe la qualité. De fait, leur niche écologique est, normalement, assez restreinte, et se compose majoritairement de deux proies principales&nbsp;: les chercheurs peu scrupuleux (ça c&rsquo;est Martine Wonner et Violaine Guérin, qui arrivent pas à faire publier leur papier tout pourri montrant que leur traitement à la mord-moi-l&rsquo;œil il marche, et qui donc se rabattent sur un journal prêt à publier n&rsquo;importe quoi, même l&rsquo;effet protecteur de l&rsquo;hydroxychloroquine sur les accidents de trottinettes), et les (jeunes, souvent) chercheurs très désespérés (ça, c&rsquo;est un effet pervers du système «&nbsp;publish or perish&nbsp;» qui impose aux chercheurs d&rsquo;avoir, par exemple, un certain nombre de publications pour avoir le droit de soutenir, ou de demander un avancement, ou d&rsquo;être titularisé, poussant souvent des chercheurs consciencieux mais écrasés par les délais à accepter de payer pour accélérer le processus et être dans les temps imposés). Mais même si cela arrive, il n&rsquo;y a pas assez de proies pour tous les prédateurs sur le marché. Et donc, comme toujours, le prédateur s&rsquo;adapte.</p>
<p>Et il peut alors se tourner vers le parasitisme. Le but dans ce cas est de «&nbsp;parasiter&nbsp;» un autre journal, connu et respectable, en utilisant le même titre mais légèrement modifié (souvent en ajoutant «&nbsp;International&nbsp;» devant), de façon à tromper les doctorants et jeunes chercheurs peu expérimentés, souvent mal encadrés, ayant parfois des problèmes avec la langue, pour leur faire croire qu&rsquo;ils payent des frais «&nbsp;normaux&nbsp;» (il y a des frais pour les vrais journaux aussi, et c&rsquo;est un autre scandale, mais on en parlera une autre fois) pour être publiés dans un vrai journal.</p>
<p>Du coup, si vous voulez savoir si un journal est légitime, lorsque vous faites une recherche, usez et abusez des «"» qui vous permettront de rechercher le titre exact, comparez les éditeurs, et non seulement les titres de journaux et n&rsquo;hésitez pas à consulter les listes comme Stop Predatory Journals ou la liste de Beall pour y voir plus clair si vous avez un doute.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec Jaanipäev, les festivités du milieu de l&rsquo;été (même si les Nordiques aiment à croire qu&rsquo;on peut tout soigner avec le sauna et la vodka, c&rsquo;est quand même non). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
        </div>)
  }