
import { Article } from "@/atoms/Article";

export const Article20230813LechodeslabosMetadata = {"tags":["covid","conséquences","inaction","Canada","porphyrie","plomb","ayurvéda","holistique","arsenic","mercure","nématode","permafrost","Panagrolaimus kolymaensis","cryptobiose","pergélisol","Éris","zoonose","virus du Nil occidental","Gironde","CHU de Bordeaux","dengue","OMS","Santé Publique France","Francesca Gino","université de Stanford","Elizabeth Bik","Marc Tessier-Lavigne","Didier Raoult","IHU Marseille","comité d’éthique","fraudes au comité d’éthique","Pierre Edouard Fournier","université d’Aix-Marseille","Pierre-Jean Weiller","Conférence nationale des comités de protection des personnes","Mélenchon","Philippot","Asselineau","Estrosi","vrai complot","Usbek et Rica","Julian Wolf","Grand Réveilleur","désinformation"],"title":"l'Écho des Labos - 13 août 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-08-13","layout":"layouts/post.njk"}

export const Article20230813Lechodeslabos : Article = ({
  className, title, img, KissKissBankBank, Facebook
}) => {
  return (<div className={className}>
      { img("/img/stuartRitchie/academia.png",  "voir la figcaption",  "width:100%" ) }
<dl>
<dt>Description</dt>
<dd>a man is walking, saying:
<blockquote>
<p>Science is probably the best thing humans ever invented.<br />
<em><strong>Academia</strong></em> on the other hand, really isn't.</p>
</blockquote>
</dd>
<dd>&#45; "Science Fictions" a comic based on the book by Dr. Stuart Ritchie (retranscrit par Jena Thornwyrd)
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Pour se remettre en jambe, j&rsquo;avais envie de vous parler, non pas directement d&rsquo;un fake (même si on va en parler un peu quand même) mais des conséquences que ça a. Après tout, qu&rsquo;est-ce que ça peut lui faire à cette grenouille de malheur si les gens croient des tas de trucs pas vrais, pensez-vous peut-être, même pour les fausses médecines, au pire, si ça marche pas, ça fait rien du tout. Je me permets de rappeler à l&rsquo;assemblée que «&nbsp;rien faire du tout&nbsp;» c&rsquo;est déjà un problème en soi quand on est dans une situation où il faudrait que quelque chose soit fait. Rien faire du tout face à une crise d&rsquo;asthme, une méningite ou un cancer, c&rsquo;est mortel. Mais plus largement, c&rsquo;est pas dit que les fausses médecines et les fausses croyances qui y sont liées fassent «&nbsp;rien du tout&nbsp;» et aujourd&rsquo;hui, pour illustrer ça, je vais vous parler du cas d&rsquo;une patiente canadienne de 39 ans, qui se présente à l&rsquo;hôpital pour des douleurs abdominales sévères, avec constipation et vomissements, des nausées épouvantables et une très grande fatigue, un tableau charmant.</p>
<p>L&rsquo;histoire commence à devenir étrange quand ses symptômes échappent complètement à toutes les hypothèses formulées par les médecins&nbsp;: pas d&rsquo;infection, d&rsquo;appendicite, de parasite, rien. La patiente effectue 3 passages aux urgences en l&rsquo;espace de 6 semaines, devant des médecins de plus en plus perplexes, jusqu&rsquo;à ce que les symptômes deviennent si sévères que l&rsquo;équipe suggère un cas de porphyrie. La porphyrie est une maladie rare, dans laquelle l&rsquo;organisme a des difficultés a fabriqué l&rsquo;hémoglobine, le composant principal du sang, ce qui a logiquement plein de conséquences (la plus intéressante étant de donner, dans sa phase avancée, des symptômes ayant sans doute contribué à créer le mythe du vampire, mais on s&rsquo;éloigne du sujet, si vous voulez, je vous en parlerai un jour, c&rsquo;était mon sujet de dissertation en littérature médiévale). En poussant les analyses de sang, les médecins découvrent que, dans le cas de leur patiente, la porphyrie est déclenchée par un très lourd empoisonnement au plomb (le composant n&rsquo;avait pas été testé lors de ses précédents passages car ce type d&rsquo;empoisonnement est rarissime chez l&rsquo;adulte). Un taux de plomb 25 fois supérieur à la norme se balade dans son sang.</p>
<p>Et là, forcément, vous me voyez venir. Comment un tel niveau de poison peut se retrouver accidentellement dans le corps de quelqu&rsquo;un&nbsp;? Réponse&nbsp;: il peut pas. Il s&rsquo;agit d&rsquo;une ingestion volontaire (je ne dis pas consciente, la patiente prenait volontairement des comprimés, mais n&rsquo;avait aucune conscience qu&rsquo;ils contenaient du plomb, attention) car depuis un an, elle suivait un «&nbsp;traitement&nbsp;» ayurvédique contre l&rsquo;infertilité. La «&nbsp;médecine ayurvédique&nbsp;» qui se prétend «&nbsp;holistique&nbsp;» a, entre autres absurdités, une croyance en des propriétés curatives de certains métaux lourds, et trouver des taux délirants de plomb, d&rsquo;arsenic ou de mercure dans ses préparations est d&rsquo;une banalité affligeante… et tout le monde s&rsquo;en fout parce que ce sont des compléments alimentaires et pas des médicaments donc c&rsquo;est aussi surveillé que le dopage dans le cyclisme. Les autorités canadiennes n&rsquo;ont ainsi pu donner qu&rsquo;un simple avertissement au fabricant, qui n&rsquo;a techniquement enfreint aucune réglementation. Quant à la patiente, elle en sera quitte pour (en plus évidemment d&rsquo;arrêter immédiatement de prendre ces saloperies) un an de traitement contre l&rsquo;empoisonnement au plomb. Une période pendant laquelle il lui a été recommandé d&rsquo;éviter à tout prix une grossesse, sous peine que le fœtus souffre du même empoisonnement que sa mère. L&rsquo;histoire (<a href="https://www.cmaj.ca/content/195/30/E1010">rapportée ici</a>) ne dit pas si elle sera encore capable de concevoir après ça.</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>C&rsquo;est une découverte qui peut faire froid dans le dos, sans mauvais jeu de mots (mais aussi avec mauvais jeu de mots, c&rsquo;est vous qui voyez). En 2018, un nématode (c&rsquo;est une espèce de ver rond qui a la particularité d&rsquo;avoir des tailles variant du microscopique au mètre de long) découvert dans un terrier d&rsquo;écureuil fossilisé, dans le permafrost sibérien, avait pu être sorti de son sommeil. On ignorait à l&rsquo;époque quel âge il avait exactement et depuis combien de temps il se trouvait prisonnier des glaces. Une étude génétique (<a href="https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1010798">parue là</a>) a depuis montré qu&rsquo;il appartenait au genre Panagrolaimus kolymaensis, une espèce connue pour être capable de cryptobiose, un état extrême de stase dans lesquels les individus plongés peuvent survivre très longtemps avant de se réveiller lorsque les conditions sont favorables. La question demeurait&nbsp;: longtemps à quel point&nbsp;? Car jusqu&rsquo;ici, le record connu pour une cryptobiose était de 39 ans (tout de même&nbsp;!) une durée incompatible avec les lieux de la découverte du nématode en question.</p>
<p>La réponse a fini par tomber. 46.000 ans. A une vache près. Si la nature est merveilleuse, elle aussi terrifiante (ça va souvent ensemble). Alors que le permafrost fond à vitesse grand V, le pergélisol en-dessous quant à lui regorge de créatures similaires, endormies depuis des dizaines de milliers d&rsquo;années, qui n&rsquo;attendent que leur réveil. Des créatures parfois microscopiques et pathogènes, contre lesquelles notre espèce n&rsquo;a absolument aucune immunité naturelle. Franchement, si on a réussi à maitriser la fission de l&rsquo;atome et à aller dans l&rsquo;espace pour finir butés par un ver chelou, je vais mal le prendre.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Covid &#45; Éris</strong>&nbsp;: ça faisait un moment qu&rsquo;on avait pas eu un variant avec un petit nom sympa (oui, parce que les lettres et les chiffres, c&rsquo;est bien pratique pour les chercheurs, mais Gérard et Micheline, ils retiennent pas). Éris fait donc son petit bonhomme de chemin et serait déjà la source de 35% de contaminations testées. Comme d&rsquo;habitude (non parce qu&rsquo;on commence vraiment à avoir l&rsquo;habitude qu&rsquo;il nous fasse ce coup-là), ce variant ne semble pas plus dangereux que ses cousins mais en revanche plus résistant aux anticorps (c&rsquo;est-à-dire que vous pouvez tout à fait faire comme une amie à moi qui a dû penser que les variants c&rsquo;était des Pokémons, vous pouvez les attraper tous). La bonne nouvelle en revanche est qu&rsquo;on observe pas d&rsquo;échappement vaccinal concernant les formes graves, ce qui veut dire que la vaccination est toujours aussi efficace pour empêcher Éris de buter des gens.</p>
<p><em>Source&nbsp;: Santé Publique France</em></p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Zoonose</strong>&nbsp;: j&rsquo;ai souvent fait office d&rsquo;oiseau de mauvais augure quand j&rsquo;annonçais que, tôt ou tard, les différentes zoonoses de l&rsquo;hémisphère sud allaient venir nous tomber sur le coin de la tronche, sans compter celles qu&rsquo;on ne connait pas encore. Et j&rsquo;aime pas spécialement avoir raison dans des cas comme ça. Mais il s&rsquo;avère que j&rsquo;ai raison. Le dernier en date, c&rsquo;est le virus du Nil occidental qui vient de débarquer en France, avec au moins 7 cas attestés en Gironde, dont deux ont dû être hospitalisés pour des complications neurologiques. La bonne nouvelle, c&rsquo;est que le virus ne se transmet pas entre humains (enfin, sauf par le sang, du coup, ce qui a incité l&rsquo;EFS de Gironde a passé en état d&rsquo;alerte, à tester toutes les poches de sang en sa possession… trouvant ainsi les deux derniers cas, asymptomatiques, de la série actuelle). La mauvaise nouvelle, c&rsquo;est que ça se transmet par les moustiques communs, qu&rsquo;ils sont absolument partout et qu&rsquo;ils peuvent même le transmettre à leurs œufs, produisant ainsi une nouvelle génération de moustiques contaminants bien massive comme il faut (un moustique, c&rsquo;est 100 à 200 œufs en moyenne…). Le Comité de veille et d&rsquo;anticipation des risques sanitaires du CHU de Bordeaux est formel&nbsp;: le virus est désormais implanté pour longtemps, et il va falloir vivre avec.</p>
<p><em>Source&nbsp;: COVARS du CHU de Bordeaux</em></p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Dengue</strong>&nbsp;: poussé par le changement climatique qui modifie les aires de répartition des moustiques et de leurs hôtes (en particulier les oiseaux migrateurs), le virus connait une expansion inédite. En France métropolitaine l&rsquo;année 2022 était déjà un record avec 378 cas et 2023 semble être partie pour la dépasser avec déjà 229 cas au compteur. Le virus touche désormais plus de 130 pays et plus aucun continent n&rsquo;est épargné.</p>
<p><em>Source&nbsp;: OMS &#x26; Santé Publique France</em></p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Fraude scientifique</strong>&nbsp;: si vous vous souvenez de mon histoire sur Francesca Gino, vous n&rsquo;avez pas pu manquer le fait que le président himself de l&rsquo;université de Stanford s&rsquo;est retrouvé également acculé après que des chercheurs indépendants (en l&rsquo;occurrence un étudiant de première année qui est allé, au culot, demander l&rsquo;aide de rien de moins que la merveilleuse Elizabeth Bik) aient révélé qu&rsquo;un nombre impressionnant de ses études, réparties sur une vingtaine d&rsquo;années, comportaient des traces flagrantes (à se demander comment personne a rien dit avant…) de manipulation sur des images et des résultats de tests. Signe que, peut-être, les choses commencent à évoluer dans le bon sens, Marc Tessier-Lavigne a présenté sa démission après plusieurs semaines de polémique. On va essayer de pas y croire trop fort quand même…</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Justement, transition toute trouvée, croyons-y pas trop fort en tout cas en France. Une étude portant sur (soupir… on va dire que je m&rsquo;acharne… mais en vrai, il en a pas marre de faire que des conneries&nbsp;? J&rsquo;ai d&rsquo;autres sujets à traiter moi) 456 études de Didier Raoult et de son IHU qui portaient des signes de problèmes éthiques a montré que 248 d&rsquo;entre elles, réparties sur à peu près une décennie, portaient le même numéro d&rsquo;approbation du comité d&rsquo;éthique, un numéro normalement unique à chaque étude. Les fraudes au comité d&rsquo;éthique remontent à 2009, signe que tout cela avait démarré bien avant la pandémie et la soi-disant obligation de travailler dans l&rsquo;urgence. C&rsquo;est tout simplement une des plus grosses fraudes de l&rsquo;histoire de la science, en termes de volume d&rsquo;articles et de nombre d&rsquo;études impliquées.</p>
<p>Qui s&rsquo;en fout&nbsp;? Le nouveau directeur de l&rsquo;IHU, Pierre Edouard Fournier, déjà, car s&rsquo;il est censé être le gars qui fait le ménage, il est aussi… co-auteur de plusieurs des études incriminées, et ne semble absolument pas menacé à son poste pour autant. Suivant. Le référent intégrité de l&rsquo;université d&rsquo;Aix-Marseille, Pierre-Jean Weiller, ensuite, puisqu&rsquo;il est censé veiller à ce que ce genre de choses n&rsquo;arrivent pas, et les différentes alertes qu&rsquo;il a reçues depuis des années sont toutes restées lettres mortes. Lui non plus n&rsquo;est pas inquiété. Suivant. La Conférence nationale des comités de protection des personnes est muette, également, elle qui est en charge de mettre en avant, justement, le rôle des comités d&rsquo;éthique dont l&rsquo;IHU s&rsquo;est joué. Mais aucune réaction, aucune condamnation, ils doivent être passés sous un tunnel. Suivant. Les institutions de tutelles et les politiques ayant ouvertement soutenu Raoult pendant la crise (et là, peu importe votre camp, de Mélenchon à Philippot, en passant par Asselineau, Estrosi et toute la clique, il est possible de taper sur tout le monde, alors c&rsquo;est pas l&rsquo;angle d&rsquo;attaque qui manque), enfin, rien silence radio, le monde s&rsquo;en fout, circulez y a rien à voir, l&rsquo;intégrité, c&rsquo;est quoi ça, ça se mange&nbsp;?</p>
<p>Je vous invite à jeter un œil <a href="https://researchintegrityjournal.biomedcentral.com/articles/10.1186/s41073-023-00134-4">au papier, en accès libre</a> et facilement compréhensible même pour les néophytes, pour vous rendre compte de l&rsquo;ampleur du fiasco. Et si jamais mes conspis préférés passent dans le coin&nbsp;: hé les gars&nbsp;! Vous voulez un complot, un vrai avec des magouilleurs qui abusent de leur position pour l&rsquo;argent et le prestige et qui s&rsquo;en sortent grâce à leurs copains bien placés et leurs liens avec le pouvoir, tout en ayant mis des gens en danger et volé de l&rsquo;argent public&nbsp;? Ben y en a un, juste là&nbsp;!</p>
<hr />
<h3 id="point-methode-de-la-semaine-anatomie-du-complot"><a href="#point-methode-de-la-semaine-anatomie-du-complot">POINT METHODE DE LA SEMAINE&nbsp;: anatomie du complot</a></h3>
<p>Dans ce point méthode, je parle souvent et beaucoup de la manière de faire de la recherche. Je parle moins souvent mais tout de même aussi de la manière de faire de la vulgarisation de cette recherche. Je parle plus rarement de ce qu&rsquo;il faut faire ou ne pas faire quand la vulgarisation ne suffit plus et lorsqu&rsquo;on a un proche qui se laisse embarquer dans des théories du complot. Mais je n&rsquo;ai pas vraiment parlé jusque là de la manière dont naissait ces théories-là. D&rsquo;abord, parce que ce n&rsquo;est pas vraiment ma spécialité, il y a des gens, en psychologie, sociologie, infocom, histoire des médias etc, qui étudient ça bien mieux que moi, et j&rsquo;ai tendance à fermer ma grande bouche quand je connais pas le sujet. Ensuite parce qu&rsquo;il est très compliqué d&rsquo;avoir un récit de l&rsquo;intérieur, de la formation, de la genèse des théories du complot, on peut juste en faire l&rsquo;autopsie une fois qu&rsquo;on lui a fait la peau.</p>
<p>Mais comme je pense que c&rsquo;est un sujet important, je voulais vous relayer cet excellent article de Usbek et Rica, une enquête sur Julian Wolf (<a href="https://usbeketrica.com/fr/article/complotisme-dans-la-peau-de-julian-wolf-le-plus-grand-desinformateur-de-france?s=04">à lire ici</a>), le créateur du Grand Réveilleur, et considéré comme le premier désinformateur de France, un type aux 130.000 abonnés sur son canal Telegram qu&rsquo;il a abreuvé de fausses informations toutes plus lunaires les unes que les autres pendant deux ans, avant de quitter le navire. Allez donc le lire, pour comprendre comment on en arrive à dire, lire et croire n&rsquo;importe quoi, et comment ce sont rarement des intentions louables qui sont derrière tout ça.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec le retour de congrès (au contraire, j&rsquo;ai encore choppé mal dans l&rsquo;avion). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}