
import { Article } from "@/atoms/Article";

export const Article20231029LechodeslabosMetadata = {"tags":["covid","Pfizer","pharmacovigilance","Boiron","anencéphalie","Florian Philippot","péricardite","myocardite","douleur thoracique","essoufflement","dyspnée","palpitations","troubles du rythme cardiaque","troubles cardiaques","Migraine","vaccination","Archéologie","lamassu","Irak","Sargon II","Khorsabad","rougeole","Ardèche","antivax","escrocs","Homéoformation","tribunal d’Albi","Agence Nationale du Développement Professionnel Continu","ANDPC","Sisyphe","gros caillou","Camus","IHU Marseille","violations à l’éthique","Didier Raoult","ANSM"],"title":"l'Écho des Labos - 29 octobre 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Monbazillac, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-10-29","layout":"layouts/post.njk"}

export const Article20231029Lechodeslabos : Article = ({
  className, title, img, KissKissBankBank, Facebook
}) => {
  return (<div className={className}>
      { img("https://immunizebc.ca/sites/default/files/2023-02/bccdc-formaldehyde_1200x600.jpg",  "voir figcaption en-dessous",  "width:100%" ) }
<dl>
<dt>Traduction</dt>
<dd>Jena
</dd>
<dd>
<h2 id="les-vaccins-sont-sûrs-quantités-comparés-de-formaldéhyde"><a href="#les-vaccins-sont-sûrs-quantités-comparés-de-formaldéhyde">Les vaccins sont sûrs: quantités comparés de formaldéhyde</a></h2>
<ul>
<li>Il y a, à peu près, 60 fois plus de formaldéhyde dans une poire de 100g que dans une dose de vaccin.</li>
<li>Il y a <em>au minimum</em> 10× plus de formaldéhyde qui circule naturellement dans le corps d'un bébé que dans une dose de vaccin.</li>
<li>Toute quantité résiduelle présente dans une dose de vaccin est sûre et ne dépasse pas 0,1 mg par dose.</li>
</ul>
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Monbazillac, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>On va s&rsquo;attaquer aujourd&rsquo;hui à un fake ridicule et pas très crédible, mais qui commence doucement à me chauffer les oreilles parce qu&rsquo;il semble être le dernier argument des cuistres de tout poil. «&nbsp;Oui, mais en vrai c&rsquo;est la vérité véritable que LE vaccin a plein d&rsquo;effets secondaires très graves, même le patron de Pfizer l&rsquo;a reconnu, alors tu vois, sale grenouille de [insérez ici tout un tas de qualificatifs pas très élogieux pour ma pomme]&nbsp;!&nbsp;». Allez, on respire un grand coup et on y va.</p>
<p>D&rsquo;où ça sort, encore, cette histoire&nbsp;? Lorsque je remonte la chronologie des publications, il semble que la nouvelle vague saumâtre qui nous occupe ait démarré avec la publication par Pfizer de plusieurs documents (qui lui étaient demandés dans le cadre des accords passés avec les Etats, donc c&rsquo;est pas un «&nbsp;communiqué&nbsp;urgent&nbsp;» ou un «&nbsp;rapport de dernière minute&nbsp;» c&rsquo;est la doc attendue publiée au moment demandé) dont un traitant des «&nbsp;mises à jour des prévisions pour 2023&nbsp;». Ce document traite de ce qui est attendu en matière de couverture vaccinale et de réduction des risques, mais également d&rsquo;effets secondaires (parce que un traitement a toujours des effets secondaires, quand il n&rsquo;en a pas, c&rsquo;est que c&rsquo;est pas un traitement, c&rsquo;est un placebo, un grigri, un bisou magique, du sucre vendu très cher par Boiron, ce que vous voulez, mais pas un traitement). Des bouts de ce document ont été sortis de leur contexte et publiés en masse par les anencéphales habituels (dont Florian Philippot qui décidément ne rate jamais une occasion de se taire avec une constante qui forcerait l&rsquo;admiration si elle n&rsquo;était pas puissamment navrante).<br />
Que disent les documents&nbsp;? Les documents synthétisent les résultats de la pharmacovigilance, à savoir que des cas de péricardites ou de myocardites ont été recensés, principalement chez des adolescents mâles de 12 à 17 ans. Les symptômes disparaissent en général en quelques jours, mais il est prudent de consulter en cas de douleur thoracique, d&rsquo;essoufflement ou de dyspnée ou encore de palpitations et autres troubles du rythme cardiaque. Le même rapport dit également, quelques pages plus loin, que la balance bénéfice-risque reste favorable pour tous les groupes d&rsquo;âge pour lesquels le vaccin a été approuvé, notamment parce que ces troubles cardiaques sont encore plus fréquents dans le cas où les patients contractent le Covid (et oui, je continuerai à dire LE Covid, l&rsquo;Académie ne peut rien contre moi, il faudra m&rsquo;abattre).<br />
Mais c&rsquo;est vraiment nouveau ça, ou y a un air de déjà vu&nbsp;? Tout à fait, de telles déclarations (bien que moins sourcées à l&rsquo;époque, forcément) étaient déjà présentes dans les rapports du même laboratoire présentés en 2022 et depuis septembre 2021.<br />
Du coup, est-ce qu&rsquo;on s&rsquo;en fout pas un peu&nbsp;? Si. Enfin, c&rsquo;est une info importante pour les médecins et il est normal que le laboratoire communique là-dessus par transparence, mais en vrai y a rien de nouveau sous le soleil, tout ce qui est dit dans le rapport est connu depuis des mois voire des années, ça n&rsquo;affole personne qui sache lire un article, et ça n&rsquo;a toujours pas fait les milliers de morts/zombies/pantins de la 5G qu&rsquo;on nous avait promis, et je trouve que décidément l&rsquo;apocalypse se fait attendre.</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>Parfois, une découverte, c&rsquo;est une absence de découverte. Et c&rsquo;est en fait pas mal. C&rsquo;est le cas de <a href="https://onlinelibrary.wiley.com/doi/10.1111/ene.16058">l&rsquo;étude dont on va parler aujourd&rsquo;hui</a> qui s&rsquo;est penchée sur le lien entre l&rsquo;augmentation en fréquence et en intensité des migraines et la vaccination contre le Covid. L&rsquo;hypothèse avait surgi il y a quelques mois, au milieu de tout ce dont on accusait alors LE vaccin (on rappelle que des vaccins, y en a des dizaines, des centaines, il faut arrêter de bouffer des expressions moisies comme ça, c&rsquo;est à truc à choper l&rsquo;ergotisme). Les chercheurs sont allés un peu plus loin et se sont demandé&nbsp;: les migraines sont-elles aggravées par la vaccination contre le Covid19, ou même par le Covid lui-même&nbsp;?</p>
<p>Réponse&nbsp;: chou blanc sur toute la ligne. L&rsquo;étude a été menée auprès de 550 patients suivis par le service de neurologie d&rsquo;un hôpital de Barcelone, dont la grande majorité (448) étaient vaccinés et dont une petite moitié (247) a contracté le Covid. Les premiers résultats montraient que près d&rsquo;un quart des patients interrogés se plaignaient d&rsquo;une aggravation de leurs symptômes depuis la contamination, et plus de 10% depuis de la vaccination. A première vue, on se dirait que cette aggravation existe, mais qu&rsquo;elle est plus importante en cas de Covid qu&rsquo;en cas de vaccin. Mais en fait, même pas. Car l&rsquo;équipe avait accès à un second jeu de donnés&nbsp;: les journaux de migraine que leurs patients tiennent, dans lesquels sont notées les crises, leur date, durée et intensité, ainsi que les éventuels déclencheurs suspectés (stress, fatigue, alcool, mauvaise nuit etc.). En étudiant ces journaux (remplis par les patients eux-mêmes au moment de leurs crises), les chercheurs se sont aperçus que ceux-ci contredisaient les déclarations des mêmes patients, et qu&rsquo;aucune augmentation n&rsquo;avait réellement lieu dans aucun groupe, hormis dans la phase aigüe de la maladie pour ceux qui contractaient le Covid. Cette étude est intéressante pour deux raisons. D&rsquo;abord, elle est rassurante quant aux impacts de la vaccination et de la maladie sur les migraines. Mais ensuite, elle pose question sur la façon de traiter le témoignage de patients, certains d&rsquo;avoir vu leur condition se dégrader, alors même que les éléments matériels prouvent le contraire.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Archéologie</strong>&nbsp;: dans un monde qui perd la tête, on a retrouvé un nouveau lamassu sans la sienne. Pour ceux qui ne le savaient pas (et cherchent un nouveau truc à caser au Scrabble), un lamassu c&rsquo;est un taureau ailé (non pas le riz, celui-là a une tête humaine, enfin sauf celui-là qui a plus de tête, mais vous me comprenez) assyrien, vous pouvez en admirer au Louvre (et vous rendre compte qu&rsquo;ils sont en fait sculptés avec 6 pattes pour que ça rende joli peu importe si on le regarde de face ou de profil), mais celui-ci vient d&rsquo;être découvert en Irak. La bestiole est en albâtre, haute de près de 4 mètres et tout aussi longue, et incroyablement conservée, le détail des plumes par exemple étant encore parfaitement visible. Lourde de près de 18 tonnes, la sculpture date du règne de Sargon II (-722 à -705) et sa tête manquante, découpée par des pillards, l&rsquo;attend au musée de Bagdad depuis la fin des années 1990 lors de sa saisie par les douanes. Poésie de l&rsquo;histoire, si le lamassu a été à l&rsquo;origine construit pour protéger la ville de Khorsabad et ses habitants, ce sont les habitants qui s&rsquo;en sont faits les protecteurs et qui ont rendu cette découverte possible&nbsp;: en 2014, alors que l&rsquo;Etat Islamique déferle sur la région, les habitants, craignant pour leur lamassu un destin similaire à celui des Bouddhas détruits par les talibans, l&rsquo;enterrent et le cachent pour le protéger avant de eux-mêmes fuir la région.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Rougeole</strong>&nbsp;: l&rsquo;épidémie en Ardèche ne faiblit pas et plus de 60 enfants ont été touchés par la maladie. Si la plupart étaient vaccinés, ils étaient en réalité non-protégés car vaccinés… trop tôt. Cette situation est exceptionnelle, car elle découle d&rsquo;une autre épidémie qui avait secoué le pays de 2008 à 2011 (23.000 cas, 10 morts) et au cours de laquelle l&rsquo;Ardèche, sévèrement touchée, avait préventivement vacciné des enfants de moins de un an. Or, si cette mesure a été efficace pour protéger ces enfants à cette époque, elle est insuffisante pour générer une immunité qui dure toute la vie, une seconde dose étant alors nécessaire. Les parents d&rsquo;enfants vaccinés avant un an sont donc appelés à se rapprocher de leur pédiatre pour effectuer ce rappel, surtout s&rsquo;ils sont dans une zone d&rsquo;incidence de la maladie.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Antivax</strong>&nbsp;: cela fait longtemps qu&rsquo;on s&rsquo;attend à ce qu&rsquo;un drame se produise. De fait, il y a déjà eu des drames qu&rsquo;on pourrait dire indirects&nbsp;: une médecin qui s&rsquo;est suicidée suite aux injures et au harcèlement, des vulgarisateurs menacés partis en dépression et en burn-out, des endroits saccagés et bien entendu un nombre impossible à estimer de gens mis en danger pour rien, dont certains l&rsquo;ont payé ou le paieront peut-être de leur vie, en mourant d&rsquo;une maladie évitable. Mais jusqu&rsquo;à présent, il n&rsquo;y avait pas encore eu de drame direct. C&rsquo;est hélas chose faite. La semaine dernière s&rsquo;est ainsi ouvert le procès du meurtre d&rsquo;une Bavaroise de 54 ans étranglée puis abattue de plusieurs carreaux d&rsquo;arbalète dans la tête. Vaccinée et favorable à la vaccination, elle a été tuée par son fils antivax de 21 ans pour l&rsquo;empêcher de vacciner son petit frère de 11 ans. Celui-ci n&rsquo;a montré aucun remord, expliquant simplement qu&rsquo;il trouvait «&nbsp;triste qu&rsquo;elle ne [lui] laisse pas d&rsquo;autre choix […] pour que [son] frère ne subisse pas la même chose que [lui]&nbsp;». En effet, le jeune homme se plaint depuis sa vaccination d&rsquo;un «&nbsp;empoisonnement au formaldéhyde d&rsquo;aluminium&nbsp;», une substance absolument inconnue au bataillon, qui semble être le mélange des délires traditionnels autour de l&rsquo;aluminium (que ce vaccin ne contient par ailleurs pas) et du formaldéhyde, ou formol, utilisé parfois pour inactiver les virus des vaccins vivants atténués (comme la polio, donc aucun rapport ici). Si lui-même refuse de plaider la maladie mentale, l&rsquo;expertise du tribunal reconnaît bien là de réels délires, qui le rendent toutefois toujours accessible à une condamnation. Certes. Mais ce garçon n&rsquo;a pas inventé un terme pareil, il a lu ou entendu ça de la bouche de quelqu&rsquo;un d&rsquo;autre. Quelqu&rsquo;un qui n&rsquo;est pas sur le banc des accusés, et qui continue à déverser le même discours toxique dans allez savoir combien d&rsquo;oreilles reliées à des cerveaux fragiles…</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Homéopathie</strong>&nbsp;: il ne faut pas rire du malheur de son prochain, fusse un homéopathe. Mais on peut se réjouir à juste titre de voir le bras puissant de la justice s&rsquo;abattre sur la face satisfaite des escrocs. Et oui, je peux dire escrocs, puisque c&rsquo;est un tribunal qui l&rsquo;a dit. Le couple de gérants de Homéoformation (société aujourd&rsquo;hui liquidé, komparazar) a donc été reconnu coupable d&rsquo;escroquerie par le tribunal d&rsquo;Albi. En effet, depuis 2020, l&rsquo;Agence Nationale du Développement Professionnel Continu (ANDPC), agence financée par de l&rsquo;argent public, a cessé de prendre en charge les formations liées à l&rsquo;homéopathie. Pas de problèmes pour nos deux escrocs (j&rsquo;ai le droit le juge il a dit) qui ont modifié les libellés de leurs formations et continué à toucher de l&rsquo;argent public jusqu&rsquo;à ce qu&rsquo;une inspection mette la combine à jour. Le préjudice, estimé à 80.000€ pour la collectivité et 36.000€ d&rsquo;indemnités pour les professionnels ayant suivi une formation faussement certifiée, a valu 4 mois de prison avec sursis pour le couple. D&rsquo;escrocs. Ça fait du bien, c&rsquo;est pas souvent.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Vous voyez Sisyphe&nbsp;? Grand, grec, têtu, avec un gros caillou, un pote de Camus&nbsp;? Et bien parfois, j&rsquo;ai l&rsquo;impression qu&rsquo;on se ressemble. Est-ce que je vais encore parler de l&rsquo;IHU&nbsp;? Oui. Est-ce que j&rsquo;en ai pas un peu marre&nbsp;? Si. Mais voyez-vous, ce bête gros caillou, il a encore roulé sur la pente, alors faut bien s&rsquo;y remettre.</p>
<p>Cela fait maintenant plus d&rsquo;un an que les recherches cliniques sont interdites à l&rsquo;IHU de Marseille, parce que [insérer ici la très, très, trop longue liste des violations à l&rsquo;éthique, à la méthode et à l&rsquo;intelligence commises par cet institut]. Pour retrouver ce droit (non parce que un Institut Hospitalo-Universitaire qui peut pas recevoir de patients, c&rsquo;est un peu con quand même), l&rsquo;IHU devait se plier à plusieurs règles.</p>
<ol>
<li>que les porteurs de projet qui n&rsquo;étaient pas formés à l&rsquo;éthique de la recherche (rien ne va dans cette phrase) fassent une formation à l&rsquo;éthique (en ligne, de 4h, autant vous dire que c&rsquo;est le cours de base)</li>
<li>que les chercheurs arrêtent de publier n&rsquo;importe quoi (genre «&nbsp;l&rsquo;HCQ ça marche mais que chez nous&nbsp;»)</li>
<li>que les études s&rsquo;en tiennent à une méthodologie fiable et respectent les protocoles d&rsquo;éthique.</li>
</ol>
<p>Autant vous dire qu&rsquo;on leur demandait <strong>LA BASE</strong>.</p>
<p>Que s&rsquo;est-il passé&nbsp;? 4 porteurs de projet ont refusé de faire la formation (c&rsquo;est 4 heures, les mecs, et de toute façon, vous pouvez pas porter de projets pour l&rsquo;instant, z&rsquo;êtes au chômdu, z&rsquo;avez que ça à foutre de vos journées). Une nouvelle étude de Raoult est sortie, co-signée par des chercheurs toujours en poste, qui dit que l&rsquo;HCQ en fait ça marche mais que à l&rsquo;IHU. L&rsquo;étude en question a été qualifiée de «&nbsp;plus grand essai thérapeutique sauvage connu&nbsp;» par pas moins de 16 sociétés savantes quand on s&rsquo;est aperçu que 30.000 patients avaient été traités sans consentement, sans accord du comité d&rsquo;éthique et sans dépôt de protocole. Et quand le scandale a été tel qu&rsquo;ils ont été obligés de rétracter le papier, Didier a twitté «&nbsp;c&rsquo;est nous les gentils&nbsp;». Texto. Citation dans le texte. Mon neveu a plus d&rsquo;arguments et il est né cet été.</p>
<p>Et avec ça donc, qu&rsquo;a fait l&rsquo;ANSM&nbsp;? Cette institution garante du contrôle de la recherche, de l&rsquo;intégrité des scientifiques, de la qualité des essais médicaux&nbsp;? Elle a autorisé l&rsquo;IHU a reprendre les essais cliniques sur la personne humaine. Je vous jure que j&rsquo;y croyais pas non plus. En vrai, ils sont pas aussi branques, l&rsquo;IHU reste sous contrôle renforcé, doit rendre des comptes à l&rsquo;ANSM tous les 3 mois pendant au moins un an, mais vu l&rsquo;ampleur du scandale et le fait que des gens impliqués dans les divers essais truqués et publications foireuses sont toujours en poste, c&rsquo;est clairement pas suffisant. Ca le serait si jamais l&rsquo;ANSM avait prouvé, par le passé, qu&rsquo;elle était réactive en cas d&rsquo;alerte de mauvaises pratiques. La longue et indécente carrière de Didi l&rsquo;Hydroxy nous a prouvé que ce n&rsquo;était pas le cas.</p>
<hr />
<h3 id="point-méthode-de-la-semaine-les-escaliers-de-la-recherche"><a href="#point-méthode-de-la-semaine-les-escaliers-de-la-recherche">POINT MÉTHODE DE LA SEMAINE&nbsp;: les escaliers de la recherche</a></h3>
<p>Je vous l&rsquo;annonce tout de suite, il n&rsquo;y aura pas un vrai écho des labos la semaine prochaine, pour cause de déplacement et de plein de trucs à gérer sur plein de candidatures. Mais pour autant, je ne compte pas vous laisser sans rien, et j&rsquo;ai bien envie de vous proposer, comme j&rsquo;ai déjà fait une fois ou deux, une petite édition spéciale.</p>
<p>Cette fois-ci, je voudrais vous parler des différents types de chercheurs, de comment on gravit (ou pas…) les échelons depuis son doctorat jusqu&rsquo;à devenir professeur, qui enseigne et qui non, qui est en poste permanent et qui déménage tous les 6 mois, qui a quoi comme diplôme et qui a le droit d&rsquo;être premier auteur quand les autres sont «&nbsp;et al.&nbsp;». De coup, je vous propose d&rsquo;utiliser l&rsquo;espace commentaire pour poser des questions à ce sujet, parler d&rsquo;aspects que vous voudriez voir traiter ou qui vous semblent obscurs et j&rsquo;essaierai d&rsquo;intégrer tout ça.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec Halloween, Samhain, ou appelez ça comme vous voulez. En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}