
import { Article } from "@/atoms/Article";

export const Article20230604LechodeslabosCopyMetadata = {"tags":["covid","FDA","Bronchiolite","Agence Européenne du Médicament","Dider Raoult","Twitter","Djokovic"],"title":"l'Écho des Labos - 4 juin 2023","description":"Aujourd&#39;hui, c&#39;est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l&#39;état de la recherche sur l&#39;épidémie de Covid-19 et le reste. Si vous aimez la chronique, vous pourrez bientôt nous soutenir à nouveau sur KissKissBankBank (on y travaille).","date":"2023-06-04","layout":"layouts/post.njk"}

export const Article20230604LechodeslabosCopy : Article = ({
  className, title, img, KissKissBankBank, Facebook
}) => {
  return (<div className={className}>
      { img("/img/perquisIHU.png",  "Perquisition au bureau de Raoult: poster d'X-Files,  trucs douteux,  kit de magie 2000",  "width:100%" ) }
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }, c&rsquo;est tout nouveau, ça vient de sortir.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Le fake de cette semaine est venu à mes oreilles par la douce et mélodieuse voix des copains de SPAV (<a href="https://www.facebook.com/StopAntivax">que vous pouvez trouver ici</a>), parce que, askiparé, «&nbsp;ils&nbsp;» vont mettre de l&rsquo;ARN messager dans tous les vaccins maintenant. Outre le fait qu&rsquo;on ne sait jamais qui sont ces «&nbsp;ils&nbsp;» en question (les gouvernements&nbsp;? les laboratoires&nbsp;? Marcel et son orchestre&nbsp;?), c&rsquo;est surtout complètement débile, et on va voir pourquoi.</p>
<p>Déjà, comme d&rsquo;habitude, la source est obscure et impossible à vérifier. Certains posts font état de «&nbsp;Michael Yeadon, ex-scientifique en chef de Pfizer&nbsp;» (ça existe ça comme fiche de poste&nbsp;? vous croyez qu&rsquo;ils ont des «&nbsp;administratifs en chef&nbsp;» aussi&nbsp;?), et autant le monsieur a bel et bien bossé pour Pfizer, autant il est impossible de trouver une source (un billet, un post, une vidéo) où il tiendrait ce genre de propos. Donc déjà ça part pas bien.</p>
<p>Ensuite, l&rsquo;ARN messager est un produit fragile et délicat à manipuler. Quand bien même on en ajouterait dans les vaccins classiques, il serait complètement dégradé dans la plupart des cas avant même qu&rsquo;on tente une injection. Je ne reviens même pas sur le fait que le but de l&rsquo;ARN messager, c&rsquo;est de pousser la cellule cible à produire des protéines que le système immunitaire doit cibler, ça n&rsquo;a, si vous me passez l&rsquo;expression, aucun putain de sens de rajouter ça dans un vaccin qui marche déjà.</p>
<p>Vraie question du coup, pourquoi «&nbsp;ils&nbsp;» feraient ça&nbsp;? Alors, j&rsquo;ai parcouru un peu les différents posts… et j&rsquo;ai rien compris. Y en a qui disent que c&rsquo;est pour obliger chaque gouvernement à acheter 10 doses par personne (ce qui a l&rsquo;air méga pas rentable pour les états, donc je vois pas comment tu peux avoir un plan pareil sans penser que les gouvernements vont gueuler et imposer aux laboratoires publics de fabriquer des substituts, c&rsquo;est un plan tout pourri). Y en a qui disent que c&rsquo;est pour affaiblir le système immunitaire et «&nbsp;dépopuler&nbsp;» (encore une fois, je rappelle, la dépopulation, ça arrange ni les états ni les grosses compagnies&nbsp;: tu peux pas payer les gens une misère pour faire un boulot difficile quand t&rsquo;es en pénurie de main d&rsquo;œuvre, alors que quand tu as un poste disponible pour 20 candidats, tu fais ce que tu veux). Y en a qui mixent les deux, comme quoi ça affaiblirait le système immunitaire pour rendre ensuite les gens dépendants de traitements payants pour compenser…</p>
<p>Personnellement, je connais qu&rsquo;une maladie où tu es dépendant de traitements à vie parce que ton système immunitaire est affaibli, c&rsquo;est le SIDA, et s&rsquo;il nous fait autant chier, c&rsquo;est bien parce que précisément on manque encore d&rsquo;un vaccin…</p>
<hr />
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p>Il y a du nouveau dans la compréhension du Covid long (si vous avez crié «&nbsp;enfin&nbsp;» sur votre chaise en lisant ça, vous méritez un biscuit). De nouveaux résultats de l&rsquo;étude Compare sont disponibles (<a href="https://compare.aphp.fr/2023/05/26/trajectoires-devolution-des-symptomes-du-covid-long">et vous pouvez lire le rapport ici</a>), et ils éclairent sur, non seulement la vitesse de guérison du Covid long, mais également sa trajectoire.</p>
<p>Portant sur plus de 2.000 patients atteints de Covid long, l&rsquo;étude montre tout d&rsquo;abord une répartition normale en courbe de Gauss de la vitesse de rémission&nbsp;: environ 4% des patients récupèrent «&nbsp;rapidement&nbsp;» avec une rémission complète en 2 ans, environ 5% souffrent de symptômes importants et persistants qui ne montrent pas de signes d&rsquo;amélioration, et, au milieu, environ 90% des patients constatent une amélioration lente de leurs symptômes avec une réduction d&rsquo;environ 25% des symptômes en 2 ans.<br />
Les symptômes les plus fréquemment rapportés sont une fatigue persistante, de l&rsquo;essoufflement, le fameux «&nbsp;brouillard mental&nbsp;» et des troubles du goût et/ou de l&rsquo;odorat.</p>
<p>Mais surtout, l&rsquo;étude a pu tracer des corrélations assez spécifiques entre la forme que prend la maladie aigue, et le comportement de sa forme longue. Les patients récupérant «&nbsp;rapidement&nbsp;» (en 2 ans donc, on est d&rsquo;accord en vrai c&rsquo;est long) étaient généralement plus jeunes que les autres et sans antécédents de maladie fonctionnelle, mais surtout avait fait un Covid aigu qui présentait plus souvent des symptômes digestifs et des douleurs cervicales, dorsales et lombaires importantes.</p>
<p>A l&rsquo;inverse, les patients ne présentant aucune amélioration étaient généralement fumeurs, plus âgés et avec des antécédents auto-immuns, mais également une forme aigue du Covid bien différente avec des symptômes cardiaques (tachycardie, bradycardie, palpitations, arythmies) ainsi que des bouffées de chaleur, sueurs et intolérance générale au chaud et au froid.</p>
<p>Sur la base de ces résultats, les chercheurs font l&rsquo;hypothèse que la grande hétérogénéité des symptômes du Covid long viendrait en réalité du fait que différentes formes de Covid aigu ne déclenchent pas les mêmes mécanismes sous-jacents et ne donnent pas les mêmes complications à terme.<br />
Les études se poursuivent pour mieux comprendre comment prendre les différentes formes en charge.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Bronchiolite</strong>&nbsp;: la prévention de la bronchiolite a reçu de nouvelles armes, après l&rsquo;approbation cette semaine par les USA, et la semaine dernière par l&rsquo;Agence Européenne du Médicament, d&rsquo;un vaccin bien particulier destiné cette fois-ci aux adultes.<br />
En effet la bronchiolite peut également être dangereuse pour les plus de 60 ans (on estime qu&rsquo;elle tue entre 6.000 et 10.000 adultes de plus de 65 ans chaque année aux USA).<br />
L&rsquo;impact sur la santé publique devra encore être évalué en conditions réelles, mais l&rsquo;essai clinique à l&rsquo;origine de l&rsquo;autorisation a montré une efficacité permettant de prévenir 83% des infections.</p>
<p><em>Source&nbsp;: FDA</em></p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Raoulteries</strong>&nbsp;: vous avez été nombreux à m&rsquo;en parler, à me l&rsquo;envoyer en MP, bref, il fallait qu&rsquo;on parle de Didier. Evidemment, l&rsquo;étude est complètement bidon (<a href="https://www.youtube.com/watch?v=Iauq3c69YvE">tellement que ça a même sorti le Biostatisticien de sa sieste, et il a fait une vidéo sur ça</a>), évidemment c&rsquo;est un scandale parce que 30.000 personnes ont reçu des traitements sans aucune surveillance des instances de protection des personnes, évidemment dans un monde juste, on n&rsquo;en parlerait à peine parce que Didier serait en taule.</p>
<p>Mais en vrai, le vrai problème, c&rsquo;est pas tant lui (Didier fait des dingueries, plus personne est surpris).</p>
<p>Le vrai problème, c&rsquo;est «&nbsp;comment est-ce qu&rsquo;une institution déjà sous surveillance pour des essais cliniques illégaux sur des patients a pu faire le plus gros essai illégal jamais recensé à ce jour sans que personne, ni à l&rsquo;ANSM, ni à l&rsquo;ARS, ni au ministère de la Recherche, ni l&rsquo;Ordre des Médecins ni NULLE PART ne s&rsquo;y oppose&nbsp;?&nbsp;». Parce que, à ce stade, soit toutes les instances de contrôle sont aveugles et sourdes, soit Raoult bénéficie d&rsquo;une protection extrêmement suspecte. Et ça commence à se voir les gars à ce stade…</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Désinformation</strong>&nbsp;: Twitter a annoncé cette semaine qu&rsquo;il quittait le Code européen de bonnes pratiques, un guide de lutte contre la désinformation signé par une trentaine de géants de l&rsquo;Internet.</p>
<p>En vrai, je suis pas réellement convaincue que ça fasse quoi que ce soit, mais c&rsquo;est inquiétant d&rsquo;avoir un poids lourd (fusse un poids lourd de fosse septique comme Twitter) qui manifeste aussi ouvertement qu&rsquo;il en a rien à foutre que la désinformation passe par lui.</p>
<p>Sachant que les lois européennes en matière de numérique doivent encore évoluer vers un durcissement au mois d&rsquo;août, le ministre délégué au Numérique a prévenu que par ce geste, Twitter s&rsquo;exposait à être purement et simplement exclu de l&rsquo;Union Européenne s&rsquo;il venait à enfreindre ses règles à plusieurs reprises.</p>
<p>Et je me prends à songer qu&rsquo;on y perdrait peut-être pas au change…</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Raoulteries</strong>&nbsp;: oui, je sais, on a déjà parlé de Raoult cette semaine, mais pendant que je rédigeais cette chronique, y a eu du nouveau alors que la section précédente était déjà rédigée.</p>
<p>Figurez-vous les enfants que l&rsquo;étude des 30.000, l&rsquo;étude qui devait faire trembler les gouvernements du monde entier, l&rsquo;étude avec ses résultats «&nbsp;validés par huissier&nbsp;» (qu&rsquo;est-ce qu&rsquo;on a pu rire avec les collègues sur ce coup-là), cette étude incroyable qui était toujours en pré-print parce que aucun journal réputé n&rsquo;en voulait (sans doute ébloui par tant de génie), cette étude…</p>
<p>A été rétractée par l&rsquo;IHU.</p>
<p>Alors, j&rsquo;espère qu&rsquo;ils ont compris que ça change rien au fait qu&rsquo;ils ont fait un truc illégal, c&rsquo;est pas «&nbsp;circulez y a rien à voir&nbsp;», mais vue la réaction de Didier, j&rsquo;ai un doute sur la capacité des équipes à comprendre le monde. Le mec a littéralement simplement dit pour sa défense «&nbsp;C&rsquo;est nous les gentils&nbsp;!&nbsp;» (<a href="https://twitter.com/raoult_didier/status/1664701726648160262">et si vous me croyez pas, et franchement vous avez raison parce que c&rsquo;est lunaire, vous pouvez le constater sur son Twitter</a>).</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>En règle générale, je fais partie des gens qui s&rsquo;ennuient ferme lorsqu&rsquo;ils regardent le sport à la télé. C&rsquo;est sans doute culturel, chez nous, on n&rsquo;a jamais regardé le sport, à part maman Dendrobate qui regardait le tennis, mais sans Federer, c&rsquo;est moins intéressant.</p>
<p>Et c&rsquo;est pas Djokovic qui va aider à changer ça. Non parce que après avoir fait sa princesse avec l&rsquo;histoire du pass vaccinal en Australie, après avoir fait la promotion d&rsquo;un nationaliste serbe qui croit voir des supers pyramides primitives même-que-c&rsquo;est-nous-qu&rsquo;on-a-inventé-la-civilisation-avant-tout-le-monde-t&rsquo;as-vu dans des stupides tas de terre en forme de tas (c&rsquo;est-à-dire plus large à la base qu&rsquo;au sommet, comme tous les tas quoi), v&rsquo;là t&rsquo;y pas qu&rsquo;il se balade à Roland Garros avec le même genre de patch à la con que votre tata new age elle colle sur son téléphone pour se protéger des ondes.</p>
<p>Sauf que lui, c&rsquo;est pas pour moins diffuser la 4G, lui c&rsquo;est soi-disant une «&nbsp;nanotechnologie formidable&nbsp;» qui permet «&nbsp;aux cellules de mieux communiquer entre elles grâce aux photons&nbsp;» et qui est censé améliorer les performances, l&rsquo;équilibre, l&rsquo;endurance, la récupération et sans doute faire le service de balle de match à sa place à ce stade.</p>
<p>Je rappelle, à toutes fins utiles, que les photons, c&rsquo;est de la lumière, les cellules s&rsquo;en foutent si on est pas une plante (alors de fait, le fameux patch a été testé sur les petits pois… mais de mémoire les tennismen, même serbes, ne font pas partie de la famille des petits pois).</p>
<p>Le mec il a juste l&rsquo;équivalent du slip magique à 400€ l&rsquo;autocollant.</p>
<hr />
<h3 id="point-methode-de-la-semaine-la-vulgarisation-choisir-le-bon-interlocuteur"><a href="#point-methode-de-la-semaine-la-vulgarisation-choisir-le-bon-interlocuteur">POINT METHODE DE LA SEMAINE&nbsp;: la vulgarisation&nbsp;: choisir le bon interlocuteur</a></h3>
<p>Si vous êtes en train de lire cette chronique, c&rsquo;est soit que vous estimez que je vous apporte quelque chose de fiable et intéressant, soit que vous cherchiez quelque chose en particulier et vous êtes tombés chez moi par accident, auquel cas bienvenue, soit que vous êtes en désaccord avec ce que je raconte et vous faites du «&nbsp;hate reading&nbsp;» mais franchement vous devriez faire quelque chose de plus intéressant de votre dimanche soir, vous allez vous faire un ulcère. Parlons donc des deux premiers cas.</p>
<p>Qu&rsquo;est-ce qui fait que, pour les premiers vous croyez ce que je raconte, et pour les seconds que vous allez décider, ou pas, de me croire&nbsp;? La première réponse à ça est déjà que, en réalité, vous ne me «&nbsp;croyez&nbsp;» pas.</p>
<p>Vous me faites confiance.</p>
<p>Et c&rsquo;est très différent, car la confiance, contrairement à la croyance, n&rsquo;annule pas l&rsquo;esprit critique.</p>
<p>De ce fait, plusieurs fois, certains d&rsquo;entre vous ont pointé des erreurs, des contre-sens ou des anomalies dans ce que j&rsquo;écrivais, des ressources erronées ou manquantes dans les liens que je donnais. Vous me faites confiance pour faire un boulot correct, mais vous ne me croyez pas, vous me savez faillible et de fait vous n&rsquo;hésitez pas à pointer ce qui vous semble bizarre.</p>
<p>Du coup, pourquoi me faites-vous confiance alors&nbsp;?</p>
<ul>
<li>La première raison, c&rsquo;est justement cette faillibilité. Plusieurs fois, dans la chronique, j&rsquo;ai publié des errata, des addenda, j&rsquo;ai mis en avant des commentaires qui nuançaient mon propos ou l&rsquo;actualisaient, j&rsquo;ai modifié des tournures de phrases ou corrigé des liens. Vous faites confiance parce que vous savez que j&rsquo;accorde plus d&rsquo;importance à la véracité des infos que je donne, qui peuvent être importantes pour vous, qu&rsquo;à mon ego personnel, dont franchement tout le monde se fout.</li>
<li>La seconde, c&rsquo;est la compétence. Vous savez, par mon métier, que j&rsquo;ai la compétence pour comprendre les études dont je parle, pour faire des recherches correctement, pour déterminer si un papier est fiable et correct ou s&rsquo;il est de l&rsquo;IHU (pardon, c&rsquo;était plus fort que moi). Mais, et ceux d&rsquo;entre vous qui m&rsquo;ont demandé des conseils en MP le savent tout particulièrement, je connais aussi mon domaine de compétence et où il s&rsquo;arrête, je n&rsquo;ai aucun problème à dire «&nbsp;je ne sais pas&nbsp;», «&nbsp;je ne suis pas compétente&nbsp;», «&nbsp;je ne peux pas comprendre ça assez bien&nbsp;» et à renvoyer vers plus compétent que moi.</li>
<li>La troisième, c&rsquo;est la transparence. Toutes les sources dont je parle sont données. Vous pouvez les lire ou les faire lire par quelqu&rsquo;un de compétent. Vous pouvez voir s&rsquo;il s&rsquo;agit de vraies sources fiables ou si c&rsquo;est douteux. Vous avez accès au texte brut, et parfois au débat scientifique qui l&rsquo;entoure. Mais aussi la transparence en ce qui me concerne, et concerne l&rsquo;équipe. Vous savez où je bosse et pour qui. Vous savez qui j&rsquo;ai dans le nez et pourquoi. Vous avez même su quand le Covid m&rsquo;a fracassé la tête, alors que ça aurait été tellement plus simple, pour quelqu&rsquo;un qui défend la vaccination et était vacciné, de simplement passer ça sous silence pour servir le narratif.</li>
</ul>
<p>Je pense que ces trois critères sont valables pour toute vulgarisation. Ne croyez personne, mais faites confiance à condition. Accordez votre confiance aux gens qui admettent quand ils se trompent mais qui font tout pour que ça arrive le moins souvent possible, qui admettent quand ils ne sont pas compétents mais qui s&rsquo;appuient sur les gens qui le sont, et qui le font en toute transparence. Et ne regrettez jamais de retirer votre confiance, même simplement temporairement, par mesure de précaution, lorsque vous sentez que ces critères ne sont pas, plus ou mal remplis.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on n&rsquo;y retourne pas la semaine prochaine, car je serai en train de prendre l&rsquo;air en Finlande (si vous entendez plus parler de moi, je serai tombée dans une hiidenkirnu quelque part dans la baie d&rsquo;Helsinki en crapahutant sur les caillasses à la poursuite d&rsquo;une bestiole quelconque&nbsp;; ne soyez pas triste, je serai morte en faisant ce que j&rsquo;aimais). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}