
import { Article } from "@/atoms/Article";

export const Article20230319LechodeslabosMetadata = {"tags":["covid","Brutus","Alexandra Henrion-Caude","les Vaxxeuses","Covid19Fédé","accident nucléaire","Fukushima","Tchernobyl","chiens","Covid long","Santé Publique France","pharmacovigilance","fluoroquinolones","insomnies sévères","troubles neurologiques","troubles psychiatriques","paralysie","douleurs","Ministère de la Santé de Tanzanie","Tanzanie","fièvre","hémorragies","insuffisance rénale","ebola","Ouganda","Robert Herrick","Vénus","volcans actifs","planétologie","homéopathie","overdose","syndrome atropinique","confusion","anxiété","perte de contrôle des mouvements","perte de la parole","atteinte neurologique","neurotransmetteur","datura","belladone"],"title":"l'Écho des Labos - 19 mars 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-03-19","layout":"layouts/post.njk"}

export const Article20230319Lechodeslabos : Article = ({
  className, title, img, UTip
}) => {
  return (<div className={className}>
      { img("/img/errantScience.png",  "",  "width:100%" ) }
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { UTip( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>J&rsquo;ai parlé la semaine dernière du torchon de Brutus, pardon, du livre d&rsquo;Alexandra Henrion-Caude. Certains d&rsquo;entre vous (et des followers des Vaxxeuses ou de Covid19Fédé, y a pas que vous) ont demandé s&rsquo;il y allait avoir un débunk.<br />
La réponse est non, déjà parce qu&rsquo;on est à peine en train de sortir de celui du docu d&rsquo;Arte, ensuite parce qu&rsquo;on a des vies et enfin parce que l&rsquo;intégralité du bouquin peut tomber dans trois catégories de problèmes&nbsp;: des affirmations sourcées avec des sources qui n&rsquo;en sont pas (genre un post de blog mis en face d&rsquo;une étude scientifique), l&rsquo;utilisation de sources qui disent le contraire de ce que le bouquin leur fait dire (genre dire que le rapport de la pharmacovigilance établit des liens de causalité, alors que la première page du rapport dit l&rsquo;exact inverse) et le cherry picking de l&rsquo;espace intersidéral le plus perché que t&rsquo;as jamais vu.<br />
Il est possible d&rsquo;utiliser un de ces trois biais pour chaque page du bouquin. Il n&rsquo;y a rien de plus à en tirer.</p>
<p>Alors, bien entendu, vous n&rsquo;êtes pas obligés de me croire sur parole, et ça tombe bien parce qu&rsquo;il y a un vaillant paladin qui s&rsquo;est farci les 27 premières pages. C&rsquo;est <a href="https://threadreaderapp.com/thread/1634921727187877892.html">à lire ici</a>, et c&rsquo;est pas compliqué&nbsp;: il y a grand minimum une grosse connerie par page. Et ça ne surprendra personne.</p>
<hr />
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p>Les accidents nucléaires sont rarissimes, mais leurs conséquences peuvent durer dans le temps. On ne sait pas bien combien, on ne sait pas bien lesquelles et on ne sait même pas si toutes sont vraiment problématiques. Ainsi, les travaux d&rsquo;observations de la zone irradiée de Fukushima ont montré que les mammifères prospéraient bien plus qu&rsquo;avant l&rsquo;incident&nbsp;: quels que soient les effets de la radioactivité, ils sont moins invalidants pour les espèces que la présence humaine.<br />
Mais cette semaine, c&rsquo;est un travail sur la zone d&rsquo;exclusion de Tchernobyl qui va nous intéresser. Les chercheurs se sont penchés sur le génome de 302 chiens, plus de 35 ans après l&rsquo;accident. Ils ont comparé leurs prélèvements avec le génome de plus d&rsquo;un millier de chiens à travers le monde et les résultats (<a href="https://www.science.org/doi/10.1126/sciadv.ade2537">à lire ici</a>) sont particulièrement intéressants. Tout d&rsquo;abord, parce que les chiens de Tchernobyl ont bel et bien une signature génétique unique au monde&nbsp;: ils sont porteurs de mutations qu&rsquo;on ne trouve chez aucun autre chien, de race pure ou à l&rsquo;état sauvage. Ensuite, parce que le suivi génétique nous en apprend beaucoup sur les structures familiales en place, à savoir que l&rsquo;ensemble des chiens vivant autour de la centrale dans un rayon de 45km sont répartis en 15 familles complexes. Enfin, parce que les brassages génétiques observés sont signes de la bonne santé des groupes&nbsp;: les différentes familles se reproduisent régulièrement entre elles et engendrent des portées viables, montrant ainsi que le matériel génétique est modifié mais toujours fonctionnel.<br />
Cette étude est la première portant sur l&rsquo;impact de la radioactivité à plus de 30 ans sur les grands mammifères, elle est donc appelée à être répliquée, mais le projet est actuellement à l&rsquo;arrêt, la zone de la centrale étant proche de la frontière biélorusse et donc inaccessible aux scientifiques.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Covid long</strong>&nbsp;: Santé Publique France a tenté un premier recensement national du nombre de Covids longs. A des degrés différents, 2 millions de personnes seraient atteintes en France. Si la majorité des patients guérit dans l&rsquo;année suivant la maladie, 20% présentent encore des symptômes 18 mois après l&rsquo;infection. Les unités dédiées au Covid long et la prise en charge par rééducation semblent améliorer considérablement l&rsquo;état des malades, même après des mois de symptômes, et devraient donc être déployées en plus grand nombre sur le territoire.</p>
<p><em>Source&nbsp;: Santé Publique France</em></p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Pharmacovigilance</strong>&nbsp;: le suivi des médicaments permet à la pharmacovigilance de repérer, au long de la vie d&rsquo;un traitement, les effets secondaires rares qui lui sont liés. Mais une fois que la pharmacovigilance a repéré un problème, il faut encore que les autorités se bougent pour en tenir compte. Et quand elles ne le font pas, c&rsquo;est un problème. C&rsquo;est le problème actuellement avec les antibiotiques de la famille des fluoroquinolones. Particulièrement puissants, ils peuvent être particulièrement utiles dans les infections graves ou face à des bactéries résistantes aux autres classes d&rsquo;antibiotiques. Mais ils ont été régulièrement prescrits en première intention, et cela même alors que des effets secondaires, rares, mais très graves, peuvent survenir&nbsp;: insomnies sévères, troubles neurologiques et psychiatriques, paralysie, douleurs invalidantes et persistantes. Sur les 4 dernières années, ce serait ainsi 6 millions de prescriptions qui auraient été faite en infraction avec les recommandations de la pharmacovigilance&nbsp;: des cystites non-compliquées, des sinusites, des otites… Mais aucune gestion du risque et du changement de la balance bénéfice-risque n&rsquo;a été faite au niveau national, et aucune information aux patients n&rsquo;a été faite. A l&rsquo;heure actuelle, il y aurait 200 victimes d&rsquo;empoisonnement aux fluoroquinolones en France.</p>
<p><em>Source&nbsp;: Agence Européenne du Médicament</em></p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Epidémie</strong>&nbsp;: la Tanzanie appelle à l&rsquo;aide les experts de la communauté internationale pour comprendre ce qui se passe sur son territoire. Une maladie non-identifiée, visiblement transmissible et très sévère (fièvre, hémorragies, insuffisance rénale) a fait son apparition. Sur 7 patients identifiés avec les symptômes, 5 sont décédés. Si une forme atypique d&rsquo;Ebola est suspectée (l&rsquo;Ouganda voisin sort tout juste d&rsquo;une épidémie de 4 mois qui a fait 55 morts), il n&rsquo;y a pas de certitudes à l&rsquo;heure actuelle.</p>
<p><em>Source&nbsp;: Ministère de la Santé de Tanzanie.</em></p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Recherche</strong>&nbsp;: il faut pas laisser les chercheurs s&rsquo;ennuyer. Ainsi, le chercheur en géophysique Robert Herrick s&rsquo;est retrouvé pris dans le cauchemar du chercheur&nbsp;: les réunions interminables en visio. Et comme c&rsquo;est méga chiant, et que les trois-quarts du temps, on y fait de la figuration, Robert a commencé à chercher des trucs pour s&rsquo;occuper. En l&rsquo;occurrence, il s&rsquo;est occupé à comparer des images radars de Vénus (chacun son truc), pendant 200h (ça en fait des réunions), en explorant manuellement des données que personne n&rsquo;avait eu le courage d&rsquo;explorer avant tellement c&rsquo;était laborieux de tout faire à la main, mais il se faisait vraiment chier. Et à force de comparer tout à la main, il a pu observer un changement de terrain qui était en fait une coulée… et il a prouvé l&rsquo;existence de volcans actifs sur la planète. Révolutionnant ainsi tout un pan de la planétologie. Il s&rsquo;ennuyait en réunion à ce point.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Alors, arrêtez tout, on a trouvé le premier cas d&rsquo;homéopathie avec des effets secondaires. Plus précisément, un Allemand de 53 ans a été admis aux urgences pour overdose liée à un traitement homéopathique. Vous avez bien lu. Si vous savez comment l&rsquo;homéopathie fonctionne, le principe est de prendre une substance quelconque, de la diluer des milliers de fois jusqu&rsquo;à ce qu&rsquo;il n&rsquo;en reste plus un seul atome en présence, de pulvériser ce rien sur des billes de sucre et ensuite de les prendre. Donc normalement c&rsquo;est sans risque (et c&rsquo;est pour la même raison que c&rsquo;est absolument sans effet). Mais il peut arriver un accident à la préparation, comme partout. Et notre bon teuton est donc arrivé avec tous les signes d&rsquo;un syndrome atropinique (confusion, anxiété, perte de contrôle des mouvements, perte de la parole), une atteinte neurologique causée par un neurotransmetteur produit par des plantes comme la datura ou la belladone. Belladone que le monsieur prenait en 4CH (donc normalement y a rien) mais qui était cette fois-ci (<a href="https://www.tandfonline.com/doi/abs/10.1080/15563650.2021.1918704">à lire là</a>) à une dose 600 fois supérieure à la dose pouvant provoquer des troubles chez l&rsquo;adulte. Du coup, non seulement ça sert à rien, mais des fois même c&rsquo;est dangereux, champion&nbsp;!</p>
<hr />
<h3 id="point-methode-de-la-semaine-placebo-et-troubles-somatiques"><a href="#point-methode-de-la-semaine-placebo-et-troubles-somatiques">POINT METHODE DE LA SEMAINE&nbsp;: placebo et troubles somatiques</a></h3>
<p>J&rsquo;interromps un peu ma série sur les publications scientifiques car je suis tombée sur ce cas, et il m&rsquo;a semblé intéressant de vous en parler. Un habitant de Moselle s&rsquo;est retrouvé au cœur d&rsquo;une procédure judiciaire après que l&rsquo;ANFR (Agence nationale des fréquences) ait dû intervenir à son domicile avec la gendarmerie, sollicitée par des habitants excédés par le fonctionnement chaotique de leur antenne relais qui ne leur permettait pas d&rsquo;utiliser correctement ni leurs téléphones portables, ni leur Wi-Fi, ni leur GPS. Les agents réalisent alors que l&rsquo;antenne fonctionne mais que quelque chose brouille son signal et suivent la piste jusqu&rsquo;à la maison… d&rsquo;un électrosensible.</p>
<p>L&rsquo;homme en question avait installé un brouilleur chez lui pour se protéger des émissions de l&rsquo;antenne, qu&rsquo;il estimait responsable de ses maux de tête, vertiges et troubles du sommeil. Outre le fait que la détention de ce type de matériel n&rsquo;est pas vraiment autorisée au premier pélos venu, il faut que je vous explique un peu comment fonctionne l&rsquo;appareil en question. Basiquement, pour brouiller une onde, vous devez envoyer une autre onde de même nature et de puissance supérieure. Si vous voulez une analogie, si vous voulez empêcher votre voisin d&rsquo;écouter sa musique, il faut que, de votre côté, vous blastiez du gros son bien plus fort avec des plus grosses enceintes. Et bien là c&rsquo;est pareil. Pour se protéger des ondes, notre bon monsieur fait marcher en permanence… un truc qui génère encore plus d&rsquo;ondes. Qui plus est, pour bien tomber dans les clichés, notre sujet a tapissé l&rsquo;intégralité de son logement d&rsquo;aluminium. L&rsquo;aluminium est un isolant, certes, mais si cela peut peut-être empêcher les ondes de rentrer, cela les empêche aussi de sortir. Notre électrosensible vivait donc en permanence à côté d&rsquo;un énorme générateur d&rsquo;ondes, ondes qui étaient en plus amplifiées par les multiples échos sur les murs en alu.</p>
<p>Et que croyez-vous que le monsieur disait de tout ça&nbsp;? Que depuis qu&rsquo;il avait son précieux brouilleur, il dormait mieux et que ses troubles diminuaient. La confiscation de son brouilleur (donc le fait de l&rsquo;empêcher de dormir à côté d&rsquo;un truc plus fort qu&rsquo;une antenne relais) a réactivé ses symptômes, au point que, pour les soulager, il a … racheté un brouilleur et recommencé. Entrainant de nouveau l&rsquo;intervention des forces de l&rsquo;ordre, parce que mec sérieux tu dégommes toutes les communications du patelin, les gens le savent quand tu recommences. Et donc, 4 confiscations de brouilleurs plus tard (il y a des gens persistants), le procureur de la République a décidé de ne pas poursuivre, car les troubles de l&rsquo;homme sont bien réels, et il ne cherchait pas à perturber le voisinage. Il est juste réellement convaincu que les ondes causent ses symptômes… mais juste les ondes dont il sait que c&rsquo;est des ondes.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec la St-Patrick. En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur <a href="https://www.facebook.com/TheDendrobateDoctor/?ref=page_internal">la page Facebook du Docteur</a>.</p>
    </div>)
}