
    import { Article } from "@/atoms/Article";
    
    export const Article20230521LechodeslabosMetadata = {"tags":["covid","HPV","papillomavirus humain","Gérard Délépine","papillomavirus","intégristes catholiques","Fouché","Henrion-Caude","Joyeux","paléontologie","Paranthropus boisei","Parkinson","NeuroGeno","Centre international de recherche en infectiologie de Lyon","protéine d’enveloppe pro-inflammatoire","ENV","HERV-W","Biodiversité","CNRS","Muséum National d’Histoire Naturelle","Université de Montpellier","pesticides","Des vaccins et des hommes","La Tronche en Biais","Perrone","Saintes","André Bercoff","Florian Philippot","Nicolas Dupont-Aignan","Vincent Pavan","Louis Fouché"],"title":"l'Écho des Labos - 21 mai 2023","description":"Aujourd&#39;hui, c&#39;est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l&#39;état de la recherche sur l&#39;épidémie de Covid-19 et le reste. Si vous aimez la chronique, vous pourrez bientôt nous soutenir à nouveau sur KissKissBankBank (on y travaille).","date":"2023-05-21","layout":"layouts/post.njk"}
    
    export const Article20230521Lechodeslabos : Article = ({
      className, title, img
    }) => {
      return (<div className={className}>
          <dl>
<dt>{ img("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnzcwT7B2RDylLo9VEm0ipoxZWO-KsaTCEfV6roEUHKDykY7gFiqZ4vtscXQvvBK-8JSg&#x26;usqp=CAU",  "↓",  "width:100%" ) }</dt>
<dd>Une case en haut à gauche énonce:"Les critiques clament que la vaccination contre le HPV ménera à la promiscuité". Un médecin vaccine une petite fille, elle dit d'un air neutre:"Je suis tellement excité là maintenant". /sarcasme
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pourrez bientôt nous soutenir à nouveau sur KissKissBankBank (on y travaille).</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>On en a déjà parlé, mais on va y revenir à chaque fois que c&rsquo;est nécessaire&nbsp;: les gens qui vous disent «&nbsp;je suis pas antivax mais&nbsp;» sont antivax. On avait prédit que ceux qui s&rsquo;opposaient au vaccin Covid trouveraient rapidement une nouvelle cible une fois l&rsquo;actualité passée, et ça ne loupe pas, maintenant leur cible, c&rsquo;est le vaccin contre le HPV.</p>
<p>Alors, quand je dis «&nbsp;maintenant&nbsp;», je suis un poil de mauvaise foi&nbsp;: en Europe, la France est classée 27e en matière de couverture vaccinale à ce sujet, la cible n&rsquo;est donc pas nouvelle. Il y a 15 ans de défiance à l&rsquo;actif des Français sur ce sujet, et le plus drôle (le pire, c&rsquo;est comme vous voulez), c&rsquo;est que les arguments actuels sont déjà ceux qu&rsquo;on m&rsquo;a sortis à moi quand j&rsquo;avais 14 ans. Pour les vulgarisateurs et les débunkeurs, c&rsquo;est un peu désespérant, à croire que RIEN de ce qui a pu être dit en 15 ans n&rsquo;a réussi à passer la barrière tympanique pour trouver un encéphale à qui parler. Le dernier relai en date, c&rsquo;est Gérard Délépine, un médecin dont le gros du travail consiste à écrire des bouquins qui intiment aux gens de «&nbsp;sortir de la soumission chimique&nbsp;» rien que ça (pour rappel, la soumission chimique, c&rsquo;est normalement le fait de droguer des gens pour s&rsquo;en servir d&rsquo;objet sexuel ou ce genre de truc, il y a vraiment des comparaisons qu&rsquo;il faut pas faire dans la vie) sur des sujets auxquels manifestement il pane que dalle. Du coup, c&rsquo;est pas grave, on va lui expliquer.</p>
<p>«&nbsp;il est impossible d&rsquo;éradiquer les papillomavirus (HPV) qui disposent de nombreux réservoirs animaliers et dont il existe au moins 200 souches différentes alors que les derniers vaccins n&rsquo;en combattent actuellement que 9&nbsp;»&nbsp;: le vaccin ne vise pas à éradiquer tous les HPV, mais seulement ceux qui sont dangereux, et qui ne sont heureusement qu&rsquo;une poignée. De mémoire, on en compte une grosse dizaine, avec quelques souches rares contre lesquelles on a pas encore de vaccin. Eliminer les souches bénignes, on s&rsquo;en cogne un peu. Quand à avoir de «&nbsp;nombreux réservoirs animaliers&nbsp;»… le H dans HPV, c&rsquo;est pour «&nbsp;humain&nbsp;» (Humain PapillomaVirus), il y a des papilloma chez les animaux, mais, par définition, jamais le HPV, enfin Gérard, ressaisis-toi&nbsp;!<br />
«&nbsp;le lien de causalité exclusive des HPV sur la survenue des cancers du col n&rsquo;est pas établi&nbsp;»&nbsp;: le lien de causalité exclusive entre quoi que ce soit n&rsquo;est jamais établi nulle part dans aucune maladie. Pas même entre l&rsquo;alcool et la cirrhose, pas même entre le tabac et le cancer du poumon, et pas même entre tes conneries et mon AVC à venir Gérard. Pour autant, ça n&rsquo;empêche pas d&rsquo;établir la causalité. Le tabac donne le cancer du poumon comme le HPV donne le cancer du col de l&rsquo;utérus (et aussi du pénis, de l&rsquo;anus, de la gorge, mais on va y revenir).<br />
«&nbsp;après les campagnes de vaccination généralisée, le nombre de cancers n&rsquo;a baissé nulle part et a même augmenté dans les groupes d&rsquo;âge les plus vaccinés&nbsp;»&nbsp;: alors ça, c&rsquo;est juste parfaitement faux. On en parle dans le débunkage qu&rsquo;on a réalisé sur le documentaire «&nbsp;Des Vaccins et des Hommes&nbsp;» au chapitre HPV (<a href="https://bigpragma.wordpress.com/2023/04/14/11-hpv-et-gardasil/">ici, quand je vous dis que c&rsquo;est TOUJOURS les mêmes arguments moisis</a>), vous verrez comment truquer des courbes, ça fait peut-être bien dans un argumentaire, mais ça se voit.</p>
<p>«&nbsp;L&rsquo;infection à HPV touche plus de 80% des femmes sexuellement actives, ne donne aucun signe et disparait spontanément en moins de deux ans dans la quasi-totalité des cas. Sa persistance éventuelle constitue vraisemblablement un témoin d&rsquo;une activité sexuelle importante&nbsp;»&nbsp;: l&rsquo;infection à HPV, hors vaccination, touche 80% des humains de plus 40 ans, point. C&rsquo;est pour ça que tu as aussi des hommes qui ont des cancers liés à ça, Gérard, tu fais une fixette sur les nanas, les psychanalystes auraient des choses à en dire s&rsquo;ils étaient pas d&rsquo;aussi gros charlatans que toi… On suppose qu&rsquo;elle disparait, mais on en sait rien, et sa résurgence chez les personnes immunodéprimées laisse plutôt à penser que le virus est juste contrôlé par le système immunitaire et ressort faire la samba si on lui laisse une ouverture. Enfin, et on commence à toucher à un nœud du problème&nbsp;: le discours qui consiste à dire «&nbsp;de toute façon, celles qui vont en mourir, c&rsquo;est juste des grosses traînées alors qu&rsquo;est-ce qu&rsquo;on s&rsquo;en fout&nbsp;». Ce n&rsquo;est pas pour rien que les fers de lance de la mouvance antivax contre le HPV sont des intégristes catholiques (Fouché et Henrion-Caude aujourd&rsquo;hui, quand j&rsquo;étais jeune c&rsquo;était Joyeux, tout ça, ça sort du même calice). Il ne faut pas se tromper, ces gens-là ne cherchent pas à protéger la santé des gens, ils cherchent à imposer leur morale&nbsp;: lorsqu&rsquo;on leur demande leur méthode pour lutter contre les cancers du col, ils vous répondent «&nbsp;l&rsquo;abstinence et le respect de soi&nbsp;» (ça marche super bien aux USA, où les lycées qui prônent ce genre de méthode sont les seuls à avoir des épidémies massives de chlamydias, comme le monde est taquin), disant implicitement que ceux (et surtout celles) qui vont être malades n&rsquo;étaient de toute façon pas dignes de respect, n&rsquo;avaient pas une bonne morale.<br />
C&rsquo;est d&rsquo;autant plus stupide que le HPV fait partie de la même famille de virus que ceux qui causent les saloperies de verrues plantaires que vous chopez en seulement 15 secondes dans le pédiluve de la piscine&nbsp;: il est extrêmement contagieux, simplement échanger votre serviette ou votre maillot de bain avec votre cousine ou votre meilleur pote peut suffire. Est-ce qu&rsquo;on va se mettre à traiter les gens de débauchés de la serviette-éponge&nbsp;? Non, bon, alors, faut arrêter un peu les conneries Gérard.</p>
<hr />
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p>J&rsquo;ai très envie cette semaine de vous parler d&rsquo;une découverte qui est encore en suspens, parce que la science, c&rsquo;est long, c&rsquo;est compliqué, ça prend du temps. Mais elle est tellement intéressante que je me suis dit qu&rsquo;on allait prendre quelques pincettes et vous la partager quand même. Donc, avant qu&rsquo;on commence, rappelez-vous que, quand on parle paléontologie, on est jamais à l&rsquo;abri de découvrir quelques mois plus tard un fémur ou une molaire qui flanque tout par terre, c&rsquo;est le jeu, ma pauvre Lucy.</p>
<p>Donc. Ceux qui me connaissent savent que je travaille sur les espèces animales, en particulier sur tout ce qu&rsquo;elles font et qu&rsquo;on avait dit que c&rsquo;était une capacité à nous, bien à nous, rien qu&rsquo;à nous. Mais quand est-ce que ça commence «&nbsp;nous&nbsp;»&nbsp;? Est-ce que Néandertal c&rsquo;est nous, est-ce que Homo habilis, c&rsquo;est nous&nbsp;? Et c&rsquo;est là que les mêmes questions pénibles que j&rsquo;adore poser peuvent être posées aussi par les collègues paléontologues.</p>
<p>La découverte en question concerne un lointain cousin appelé Paranthropus boisei. Il a vécu en Afrique orientale il y a quelque chose comme 2.8 millions d&rsquo;années. Et il lui a été attribué plusieurs outils en pierre taillée, à Nyayanga, ce qui ferait de lui le premier fabricant d&rsquo;outils en pierre de l&rsquo;histoire, bien avant la lignée Homo. Ce lointain cousin se serait servi de ces outils pour découper des carcasses d&rsquo;animaux marins déjà morts, comme des tortues ou des hippopotames, lorsque les plantes de son alimentation principales venaient à manquer.<br />
On dispose également de traces montrant qu&rsquo;il a pu se servir de ces outils pour broyer et «&nbsp;prémâcher&nbsp;» des plantes trop dures pour ses dents mais abondantes dans son environnement, comme le sorgho. Cette découverte semble indiquer que, non seulement les outils ne sont pas apparus avec le genre Homo, mais en plus ce ne sont même pas nos ancêtres qui en ont été les premiers artisans.</p>
<p>Les sites en Afrique montrent que les différentes espèces se sont côtoyées longuement, il est donc possible que nos ancêtres aient commencé à imiter les comportements de leurs voisins de palier, avant de devenir les grands artisans que l&rsquo;on connaît. Si le sujet vous intéresse, je vous renvoie vers le numéro de mai de Pour la Science, qui consacre plusieurs articles aux découvertes et hypothèses sur le sujet.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Parkinson</strong>&nbsp;: il existe deux formes de la maladie de Parkinson, selon le consensus actuel (qui est encore fragile sur les maladies de ce type), une qui démarre dans les viscères, au niveau du tractus gastro-intestinal, et une qui démarre dans le cerveau, au niveau de l&rsquo;amygdale. A terme, les deux ont la même issue, mais leur progression est différente&nbsp;: celle qui nait dans l&rsquo;intestin a pour symptôme précoce des formes de rêves particulièrement agités (voire même dangereux) que la forme naissant dans le cerveau n&rsquo;a pas. Mais comment la forme intestinale nait-elle&nbsp;? Une équipe de chercheurs d&rsquo;Helsinki, en Finlande, a découvert (<a href="https://www.frontiersin.org/articles/10.3389/fcimb.2023.1181315/full">à lire ici</a>) que la présence en surnombre de certaines bactéries intestinales de la famille Desulfovibrio favorisait l&rsquo;accumulation d&rsquo;une protéine neuronale tenue aujourd&rsquo;hui pour responsable de la maladie. Les bactéries étant principalement acquises par l&rsquo;environnement (elles sont présentes dans la boue, l&rsquo;environnement marin ou, plus rarement, l&rsquo;intestin d&rsquo;autres animaux), il serait possible de lutter contre leur présence pour ralentir la progression de la maladie et la destruction des cellules nerveuses.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Covid &#45; réveil viral</strong>&nbsp;: on est pas sortis du sable les enfants, mais ça vous vous en doutiez déjà. Une étude conjointe de la société NeuroGeno et du Centre international de recherche en infectiologie de Lyon (<a href="https://www.sciencedirect.com/science/article/pii/S2589004223006818">à lire ici</a>) a confirmé le lien entre infection au Sars-Cov2 et présence de «&nbsp;la protéine d&rsquo;enveloppe pro-inflammatoire (ENV) du rétrovirus endogène humain HERV-W&nbsp;». Vous avez rien compris&nbsp;? C&rsquo;est normal, c&rsquo;est un peu technique, on va y aller doucement. HERV-W (qu&rsquo;on va appeler Hervé parce que c&rsquo;est plus pratique), Hervé donc était un rétrovirus (comme le VIH, oui) qui a rencontré Homo sapiens il y a des millions d&rsquo;années (à un moment où, peut-être, on n&rsquo;était même pas encore Homo sapiens, c&rsquo;est vous dire). Sauf que, au lieu de nous cogner sur la tronche comme son cousin, Hervé s&rsquo;est dit qu&rsquo;il faisait rudement bon vivre bien au chaud dans ces si jolies petites cellules de mammifère, et il s&rsquo;est intégré dans notre ADN, une prouesse dont quasiment seuls les virus de sa famille sont capables. Alors attention, Hervé ne s&rsquo;est pas installé sans cadeau, et on pense aujourd&rsquo;hui qu&rsquo;il joue un rôle majeur dans la bonne production de la syncytine, une hormone essentielle au bon fonctionnement du placenta et à l&rsquo;accroche de l&rsquo;embryon. Ce nom vous dit quelque chose&nbsp;? Pas étonnant&nbsp;: dans les milieux antivax, de nombreux intervenants avaient pointé la ressemblance entre la protéine spike et cette hormone, arguant que le corps allait aussi apprendre à s&rsquo;en défendre et nous rejouant la tragédie «&nbsp;ils vous venir prendre le ventre de vos femmes&nbsp;» qu&rsquo;on connait tous par cœur. Une des raisons pour laquelle c&rsquo;était débile, c&rsquo;est qu&rsquo;il y a déjà des trucs qui ressemblent à la syncytine dans le corps, dont Hervé, et le système immunitaire ne s&rsquo;y trompe pas. Le problème, c&rsquo;est que voir passer des milliards de virions porteurs d&rsquo;une clé qui ressemble à la protéine qu&rsquo;il aide à produire, Hervé ça a dû le rendre tout chabada. Et donc, il sort de sa phase de sommeil où il assemblait gentiment des protéines (on le sait grâce à la fameuse protéine d&rsquo;enveloppe, c&rsquo;est comme s&rsquo;il laissait traîner ses couvertures partout) et il se balade à nouveau, créant une co-infection. La protéine d&rsquo;enveloppe pourrait donc être un marqueur de forme sévère, mais également la cible d&rsquo;une piste de traitement.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Biodiversité</strong>&nbsp;: l&rsquo;activité agricole est la principale cause de la disparition de 25% des oiseaux en 40 ans sur le sol européen, le chiffre atteignant même 57% pour les espèces dites agricoles. C&rsquo;est le constat alarmant qui ressort de la dernière étude conjointe du CNRS, du Muséum National d&rsquo;Histoire Naturelle et de l&rsquo;université de Montpellier (<a href="https://www.cnrs.fr/sites/default/files/press_info/2023-05/CPCNRS-oiseauxagriculture-FRok.pdf">à lire ici</a>). Si le changement climatique a également eu un rôle à jouer (en déréglant les périodes de migrations, en rendant les nidifications plus sujettes aux regels qui tuent les nichées ou en faisant subir des évènements météorologiques hors normes aux populations), c&rsquo;est bien l&rsquo;intoxication de la chaîne alimentaire par les pesticides (classiques ou bio, hein, on rappelle que l&rsquo;agriculture biologique utilise aussi des pesticides, et que les oiseaux se foutent de savoir s&rsquo;ils sont labelisés ou pas, la bouillie bordelaise est aussi toxique pour eux que le roundup) qui est à l&rsquo;origine de la majeure partie de leur déclin.</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Débunk</strong>&nbsp;: alors, on a pas réussi à faire l&rsquo;émission promise autour de l&rsquo;équipe du débunk de «&nbsp;Des Vaccins et des Hommes&nbsp;», mais rassurez-vous, on l&rsquo;a enregistrée cet aprem, même si c&rsquo;est pas en live, vous allez pouvoir en profiter pour découvrir les coulisses de ce travail sur la chaîne de la Tronche en Biais, patience, ça arrive&nbsp;!</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Ça faisait quelque temps qu&rsquo;on avait pas eu de nouvelles de Perrone et ça nous avait pas manqué, dis donc. Mais voilà qu&rsquo;il est apparu ce jeudi, comme la Vierge à ses fidèles (je déconne à peine, il y avait 1.500 personnes là pour l&rsquo;écouter aligner mal deux pauvres phrases et le rassemblement était à Saintes, ça s&rsquo;invente pas). La journée était animée par André Bercoff (oui, oui, le présentateur star de Sud Radio, au cas où vous auriez encore un doute sur son degré de professionnalisme), en la présence éclairante (ne pas dire illuminée, ne pas dire illuminée…) de Florian Philippot et Nicolas Dupont-Aignan et avec les interventions de Vincent Pavan et Louis Fouché (j&rsquo;ai le droit de dire «&nbsp;famille&nbsp;»&nbsp;? Là, je crois que je les ai tous&nbsp;!). Après avoir raconté leur «&nbsp;entrée en résistance&nbsp;» (si vous entendez feuler dans le fond, pas de panique, c&rsquo;est moi…), les divers intervenants glosent sur la «&nbsp;débâcle de l&rsquo;Occident&nbsp;», le péril imminent de «&nbsp;l&rsquo;éducation sexuelle à l&rsquo;école&nbsp;» et «&nbsp;l&rsquo;empoisonnement massif des populations par la vaccination&nbsp;» (ça fait deux ans que j&rsquo;attends de mourir dans 6 mois, on va dire que c&rsquo;est pas au point cette affaire). Le meilleur résumé viendra encore des organisateurs eux-mêmes&nbsp;: «&nbsp;S&rsquo;il y a un élément qui montre que ces deux journées publiques sont déjà un succès, c&rsquo;est que jusqu&rsquo;à présent, la presse nationale les a totalement ignorées.&nbsp;» Un déni pareil, on a envie de le flanquer dans du formol pour pouvoir permettre aux générations futures de le contempler.</p>
<hr />
<h3 id="point-methode-de-la-semaine-les-biais-cognitifs-une-histoire-qui-dure"><a href="#point-methode-de-la-semaine-les-biais-cognitifs-une-histoire-qui-dure">POINT METHODE DE LA SEMAINE&nbsp;: les biais cognitifs, une histoire qui dure</a></h3>
<p>Je vous parle souvent des différents biais dans lesquels on peut tomber lorsqu&rsquo;on veut comprendre une étude scientifique, un phénomène un peu complexe ou prendre une décision éclairée. Si ces biais nous nuisent alors, il faut bien comprendre qu&rsquo;ils sont là pour une raison&nbsp;: au quotidien, raisonner ainsi est un avantage. Si je cherche mes clés, et que je pense que je les ai juste laissées dans mon autre sac à main (j&rsquo;ai pas deux sacs à main, mais faisons comme si), le plus simple c&rsquo;est que j&rsquo;aille regarder dans mon sac à main. En science, si je pense que quelque chose est vrai, la bonne démarche, ça va être de tenter par tous les moyens de prouver que c&rsquo;est faux («&nbsp;mon médicament marche, la preuve, je l&rsquo;ai donné au patient, il va mieux&nbsp;» oui, mais est-ce qu&rsquo;il va pas mieux juste avec le temps, l&rsquo;attention, si on lui donne une tasse de rien etc.), dans la vraie vie, ça serait juste chiant&nbsp;: je pense que c&rsquo;est dans mon autre sac à main, je vais pas commencer à inspecter le contenu du congélateur.</p>
<p>En vérité, ces biais sont si évolutionnairement utiles qu&rsquo;ils sont très anciens dans l&rsquo;arbre du vivant. Et ainsi, on a même pu prouver que les rats étaient sensibles aux mêmes biais cognitifs que nous. En particulier un biais qu&rsquo;on appelle le biais de conjonction. Je vous laisse ici l&rsquo;interview, <a href="https://www.francetvinfo.fr/replay-radio/le-billet-sciences-du-week-end/les-rats-font-les-memes-erreurs-logiques-que-nous_5797931.html">à lire ou écouter</a> des journalistes d&rsquo;Epsiloon qui se sont attelés à vulgariser ces résultats.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec la fin du semestre (ah le joli mois de mai&nbsp;! ce doux moment où les étudiants qui ont séché les cours tout le printemps apparaissent soudain dans mes classes comme des champignons après la pluie…). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur <a href="https://www.facebook.com/TheDendrobateDoctor/?ref=page_internal">la page Facebook du Docteur</a>.</p>
        </div>)
  }