
import { Article } from "@/atoms/Article";

export const Article20230924LechodeslabosMetadata = {"tags":["covid","Japon","Kyoto","Alex Jones","Parkinson","neurones dopaminergiques","dopamine","mitophagie","Covid long","fibrine","fibrinogène","OMS","méduse-boite"],"title":"l'Écho des Labos - 24 septembre 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-09-24","layout":"layouts/post.njk"}

export const Article20230924Lechodeslabos : Article = ({
  className, title, KissKissBankBank, Facebook
}) => {
  return (<div className={className}>
      <h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Après les fakes européens et américains dont nous avons pas mal parlé, pourquoi ne pas regarder un peu ce qui se fait plus loin&nbsp;? Non parce qu&rsquo;il y a pas de raisons que les gens soient plus ou moins perchés selon la géographie (à part pour les montagnards, mais c&rsquo;est un peu différent, c&rsquo;est pas le même genre de perchés, on s&rsquo;éloigne du sujet, là, non&nbsp;?). Bref, cette semaine notre fake arrive tout droit du Japon, parce que pourquoi pas.</p>
<p>Le pitch ce coup-ci, c&rsquo;est que le Japon aurait lancé une investigation massive, pour enquêter sur des millions (rien que ça…) de morts liés au vaccin contre le Covid… Alors, en vrai, ça pourrait aller très vite, puisque face à l&rsquo;emballement médiatique, le ministère de la Santé du Japon a précisé que, de un, aucune investigation n&rsquo;était en cours parce que, de deux, le pays n&rsquo;avait recensé aucun décès lié au vaccin contre le Covid. Voilà, merci, bonsoir.</p>
<p>Mais sur cette chaîne, on aime bien approfondir un peu, alors c&rsquo;est un peu court jeune homme tout ça. Regardons de plus près quels sont les arguments et les sources de nos copains antivax ce coup-ci.<br />
Ils ont comme source un article scientifique, un vrai. Tombez pas de votre chaise, comme d&rsquo;hab ils l&rsquo;ont interprété n&rsquo;importe comment. L&rsquo;étude se penche sur l&rsquo;autopsie de 4 patients décédés sans cause apparente peu de temps après leur vaccination, en évoquant l&rsquo;hypothèse d&rsquo;une «&nbsp;tempête de cytokines&nbsp;», un effet inflammatoire connu (surtout comme une complication du Covid, en vrai, mais bon). Et la conclusion de l&rsquo;étude c&rsquo;est… qu&rsquo;il est impossible de conclure. Il va falloir vraiment qu&rsquo;on prenne le temps de leur expliquer que quand on dit «&nbsp;il faut avoir une source&nbsp;», ce qu&rsquo;on entend en fait c&rsquo;est «&nbsp;il faut avoir une source qui raconte la même chose que toi, Gérard, et pas juste l&rsquo;avoir imprimée et plastifiée dans un classeur&nbsp;».<br />
Bon, en plus de l&rsquo;étude, ils ont le témoignage d&rsquo;un professeur de l&rsquo;université de Kyoto, qui parle d&rsquo;investigations à l&rsquo;échelle mondiale et de risque colossal pour la population japonaise. A son sujet, l&rsquo;université de Kyoto a réagi en disant qu&rsquo;elle n&rsquo;avait aucune responsabilité concernant la parole de ses employés retraités, ce que ce professeur est en réalité, et que de telles affirmations sans preuve n&rsquo;engageaient que lui. Bon.<br />
Mais du coup, qui a levé ce lièvre-là, qui est allé chercher un retraité désavoué et une étude non-concluante tordue dans tous les sens pour nous pondre une ânerie pareille&nbsp;? Et bien à la source de ce boxon, on retrouve… Alex Jones, de Infowars. Mais si, vous savez, Alex Jones. Le mec qui a expliqué que la fusillade de Sandy Hook dans une école primaire avait jamais eu lieu, que les parents étaient tous des comédiens et qui a été condamné à payer 965 millions de dollars de dommages et intérêts pour ça l&rsquo;année dernière, excusez du peu, et y a encore des affaires qui courent donc ça va encore grimper&nbsp;? Voilà, ce mec-là, une source parfaitement fiable donc…</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>Cette semaine, j&rsquo;aimerais vous parler d&rsquo;une belle découverte, mais qui est un poil technique à comprendre, alors il va falloir s&rsquo;accrocher un peu. Il va être question de la maladie de Parkinson, une maladie de plus en plus commune, avec le vieillissement de la population mais encore mal comprise, et pour laquelle il n&rsquo;y a à l&rsquo;heure actuelle aucun traitement.</p>
<p>Jusqu&rsquo;ici, le consensus était que la maladie avait pour déclencheur la dégénérescence des neurones dopaminergiques, des cellules nerveuses en charge d&rsquo;utiliser la dopamine (une hormone qui sert à plein, mais alors vraiment PLEIN de trucs, donc je vais pas m&rsquo;étaler là-dessus, retenez juste qu&rsquo;elle est impliquée dans le circuit de la récompense, donc dans le plaisir, la motivation et l&rsquo;addiction, ça suffira pour l&rsquo;instant) pour faire fonctionner la «&nbsp;voie nigro-striatale&nbsp;» (retenez juste que c&rsquo;est un des chemins que la fameuse dopamine peut emprunter dans le cerveau pour faire ses trucs) qui alimente les aires corticales motrices (globalement, des zones du cerveau en charge de la coordination, de la précision et du calibrage des mouvements, donc quand elles déconnent, vous perdez en précision, en coordination, et en contrôle de la force). La mort lente et progressive des neurones en question conduit à la perte des fonctions motrices, et donc à la progression de Parkinson. C&rsquo;est bon, tout le monde suit&nbsp;?</p>
<p>Bon. Sauf qu&rsquo;en fait, pas tout à fait. <a href="https://www.cell.com/neuron/fulltext/S0896-6273(23)00629-3">Une équipe américaine a montré</a> que la maladie commence en réalité plus tôt que ça. Avant même qu&rsquo;ils commencent à mourir, ces neurones présentent en réalité des dysfonctionnements de la mitophagie. En gros (mais alors en très gros, si des neurologues passent par là, pas taper siouplé), chaque cellule, neurone inclus, possède des mitochondries, des trucs (ce sont techniquement des anciennes bactéries qui sont entrées en symbiose avec la cellule dans des temps immémoriaux, mais c&rsquo;est compliqué, on va dire des trucs) qui fournissent à la cellule son énergie. Comme toute structure du corps, elles peuvent devenir trop vieilles, ou faire n&rsquo;imp parce qu&rsquo;elles sont surmenées, et il faut alors les détruire pour les remplacer. C&rsquo;est le rôle de deux gènes, dont l&rsquo;un est un peu le superviseur de l&rsquo;autre&nbsp;: le premier active le second, le second pousse les mitochondries défectueuses vers la sortie. Les gens porteurs de copies défectueuses de ces gènes développent la maladie parce que leur organisme garde plein de gros machins inefficaces pour les faire fonctionner au lieu de tout cramer et de repartir sur des bases saines (toute analogie avec l&rsquo;administration française est tentante mais n&rsquo;engage que vous). Sauf que les chercheurs ont découvert que le second gène a également un rôle insoupçonné dans la bonne libération de… la dopamine, dont on parlait dès le départ. Ce qui fait que la mutation de ce gène peut, en réalité, également empêcher les synapses (les capteurs au bout des neurones, en charge de réceptionner les molécules comme la dopamine) de faire correctement leur boulot, et donc d&rsquo;avoir des problèmes de fonctionnement bien avant que leur dégénérescence advienne. De fait, la simple stimulation de ce gène pourrait avoir des effets retardateurs importants dans le développement de la maladie. Je vous avais prévenu, c&rsquo;est technique. Mais c&rsquo;est une belle avancée, car elle ouvre la voie à des traitements intervenant avant la mort neuronale, et donc qui permettraient de conserver les capacités pendant longtemps.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Covid long</strong>&nbsp;: c&rsquo;est peu dire qu&rsquo;on connait encore mal la maladie, ce qui la provoque et surtout comment aider les patients qui en son atteints. Alors que certains continuent de douter de l&rsquo;existence même de la maladie ou attribuent les symptômes au stress, <a href="https://www.nature.com/articles/s41591-023-02525-y">une équipe d&rsquo;Oxford a publié</a> une découverte très intéressante&nbsp;: l&rsquo;existence de biomarqueurs prédictifs du Covid long, et en particulier du fameux «&nbsp;brouillard mental&nbsp;». Le fait pour un patient de faire ou non un Covid long se jouerait en réalité au tout début de la maladie, et se verrait grâce à des taux anormalement élevés de fibrine et de fibrinogène, deux protéines impliquées dans la cicatrisation et surtout dans l&rsquo;inflammation. En clair, plus l&rsquo;organisme d&rsquo;un patient réagit fortement à la présence du virus, plus son risque de développer un Covid long est grand. Cette explication irait également dans le sens d&rsquo;un plus faible risque de Covid long chez les personnes vaccinées, puisque la réaction immunitaire est en général moins violente, du fait de la présence d&rsquo;une immunité acquise plus efficace.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Covid &#45; origines</strong>&nbsp;: à l&rsquo;heure où les variants se multiplient, et où l&rsquo;on découvre de plus en plus de réservoirs animaux, la communauté scientifique n&rsquo;a pas abandonné l&rsquo;idée de mettre la main de manière formelle sur l&rsquo;hôte intermédiaire. De fait, l&rsquo;OMS a demandé à la Chine de recevoir une nouvelle mission internationale d&rsquo;étude sur son sol, et de coopérer pour de vrai cette fois, en lui donnant un accès total et libre à l&rsquo;ensemble des éléments qu&rsquo;elle demande. Mais la Chine continue à freiner des quatre fers, et il est à craindre que le temps perdu fasse disparaitre pour de bon ce qu&rsquo;il reste des pistes génétiques encore exploitables sur place.</p>
<p><em>Source&nbsp;: OMS</em></p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Covid &#45; statistiques</strong>&nbsp;: on va pas se mentir, on nage dans la purée (et c&rsquo;est pas évident, lorsque vous voyez la texture de la purée). Plus de tests massifs, plus de suivi des cas ou des hospitalisations. Seuls subsistent la collecte des motifs de passage aux urgences (et «&nbsp;suspicion de Covid&nbsp;» a pris gentiment plus de 30% la semaine dernière), le recensement des recours à SOS Médecins (près de +20% en une semaine) et le suivi effectué par Sentinelle via son réseau de généralistes et pédiatres (qui estime l&rsquo;incidence à 82 cas pour 100.000 habitants, un niveau digne des plus beaux pics de 2022). Bref, il se passe quelque chose, mais on sait pas quoi, et à part l&rsquo;hôpital, tout le monde a l&rsquo;air de s&rsquo;en cogner un peu. Et maintenant j&rsquo;ai envie de purée, en plus.</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Oiseaux</strong>&nbsp;: les résultats du concours du meilleur photographe d&rsquo;oiseaux 2023 sont sortis. <a href="https://www.birdpoty.com/bpoty-2023-winners">Je vous encourage à aller jeter un œil</a>, ce sont des petites merveilles, et ça fait du bien de regarder la beauté du monde dans le chaos ambiant.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>On savait déjà qu&rsquo;il n&rsquo;y avait pas nécessairement besoin d&rsquo;avoir un cerveau pour vivre lorsqu&rsquo;on est un animal (en sont témoins les coraux, les vers de terre et Gérard), mais il était jusque-là plutôt admis qu&rsquo;il fallait un cerveau pour être capable d&rsquo;apprendre de ses expériences, et il semblerait de fait que non. <a href="https://www.cell.com/current-biology/pdfExtended/S0960-9822(23)01136-3">L&rsquo;expérience qui remue le secteur</a> porte sur la méduse-boite, qui n&rsquo;est pas en forme de boite mais de cloche parce que le monde ne fait aucun sens. Le petit animal d&rsquo;un centimètre à peine est dépourvu de cerveau mais possède en revanche 24 yeux, répartis sur le corps en 4 rhopalies, chacune ayant un «&nbsp;centre de traitement de l&rsquo;image&nbsp;» d&rsquo;un millier de neurones, et rien qui soit centralisé. A titre de comparaison, une pauvre mouche a au minimum 200.000 neurones. En se servant de ce système visuel assez développé (comparé au reste), les chercheurs ont réussi à montrer qu&rsquo;en couplant un stimulus visuel à un mécanique, les méduses pouvaient apprendre, en l&rsquo;espace de seulement 7 minutes, à éviter un obstacle imitant un élément de leur environnement naturel, dans lequel elles peuvent normalement se déplacer librement. J&rsquo;aurais beaucoup, mais alors beaucoup, de vannes à faire sur certains de nos conspécifiques alors que des animaux sans cerveau sont capables d&rsquo;adapter leur comportement en moins de 10 minutes face à l&rsquo;apport d&rsquo;éléments nouveaux, mais j&rsquo;ai peur que ce soit sans fin.</p>
<hr />
<h3 id="point-méthode-de-la-semaine-les-emballements-médiatiques-et-la-science"><a href="#point-méthode-de-la-semaine-les-emballements-médiatiques-et-la-science">POINT MÉTHODE DE LA SEMAINE&nbsp;: les emballements médiatiques et la science</a></h3>
<p>Il y a une raison pour laquelle la chronique a une section «&nbsp;Piste de la semaine&nbsp;». Toutes les avancées ne sont pas des découvertes renversantes, tout ce qui est découvert n&rsquo;est pas encore solide, ou fiable, ou confirmé. Il y a une raison pour laquelle je rappelle régulièrement les limitations des études, ou le fait que c&rsquo;est encore publié en pré-print, ou qu&rsquo;on attend des résultats sur des plus grandes cohortes. Et cette raison-là, nos grands médias ne l&rsquo;ont manifestement pas comprise.</p>
<p>La semaine dernière, je vous ai parlé, dans la section «&nbsp;Piste de la semaine&nbsp;» donc, des résultats d&rsquo;un essai concernant un vaccin contre le cancer du poumon. Vous pouvez aller vérifier par vous-mêmes, mais voici les infos que j&rsquo;ai apportées&nbsp;: ce vaccin ne cible qu&rsquo;un sous-groupe particulier (les porteurs d&rsquo;un certain gène, même s&rsquo;il est chez 50% de la population, en récidive d&rsquo;un type spécifique de cancer du poumon après une immunothérapie), il améliore la survie mais ce n&rsquo;est pas un miracle absolu (si 44% des patients survivaient contre 27% du groupe contrôle, ça veut quand même dire que plus de la moitié sont morts en un an), et surtout l&rsquo;équipe a joué de malchance car son recrutement a été interrompu à cause du Covid et la puissance de l&rsquo;étude est faible, elle doit donc absolument être répliquée sur une plus grosse cohorte. C&rsquo;est donc une piste. Une belle piste, une piste prometteuse et qui donne espoir, mais c&rsquo;est une piste.</p>
<p>Et donc quand je m&rsquo;astreins à enrober de précautions l&rsquo;information que je diffuse, ça m&rsquo;emmerde un peu que les médias à large audience se mettent à titrer partout que c&rsquo;est «&nbsp;un vaccin qui va sauver des milliers de vie&nbsp;» (parce que pour l&rsquo;instant, on parle de survie à un an, ils sont pas sauvés les gars encore), «&nbsp;une avancée incroyable dans la lutte contre le cancer&nbsp;» (ce sont des résultats exploratoires, c&rsquo;est encourageant certes, mais faut se calmer), et autre «&nbsp;découverte majeure porteuse d&rsquo;espoirs&nbsp;» (mais peut-être de faux espoirs, y as-tu seulement pensé, Gérard&nbsp;?). Bref, la méthode, dans la vulgarisation, c&rsquo;est aussi de savoir transmettre non seulement les connaissances nouvelles, mais aussi le degré de confiance qu&rsquo;on a à leur sujet. Et là, les gars, on y est pas.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec la visite du pape en France (manifestement pour ça, c&rsquo;est encore la médecine qui fait le mieux le boulot). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}