
    import { Article } from "@/atoms/Article";
    
    export const Article20230716LechodeslabosMetadata = {"tags":["covid","Guillain-Barré","Pérou","Philippot","zika","Brésil","lupus","chikungunia","dengue","Agence Spatiale Européenne","ESA","exoplanète","antibiorésistance","nourséothricine","IST","Santé Publique France","UK","gonorrhée","chlamydias","herpès","condylomes","syphilis","coqueluche","Vaucluse","Gard","Bouches-du-Rhône","centre hospitalier d’Avignon","Biodiversité","Osteocephalus vasquezi","grenouille","Pérou","Andes","Amazone","Office National d' Indemnisations des Accidents Médicaux","Oniam","HPV","papillomavirus humain"],"title":"l'Écho des Labos - 16 juillet 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-07-16","layout":"layouts/post.njk"}
    
    export const Article20230716Lechodeslabos : Article = ({
      className, title, img, KissKissBankBank, Facebook
    }) => {
      return (<div className={className}>
          <dl>
<dt>{ img("https://i0.wp.com/humoroutcasts.com/wp-content/uploads/2022/01/2BD2B8AD-C65C-4F03-B2A3-E3545F3651F4.jpeg?fit=570%2C572&#x26;ssl=1",  "",  "width:100%" ) }</dt>
<dd>une illustration d'un sisyphe qui essait de pousser le variant delta comme un gros boulet.
</dd>
<dt>Écrit par:</dt>
<dd>Paul Lander
</dd>
<dt>Artiste:</dt>
<dd>Dan McConnell
</dd>
<dt>Pour le site:</dt>
<dd>Humor Outcasts
</dd>
<dt>Url d'origine:</dt>
<dd><a href="https://humoroutcasts.com/2022/cartoon-latest-in-the-trials-of-sisyphus/">https://humoroutcasts.com/2022/cartoon-latest-in-the-trials-of-sisyphus/</a>
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Vous avez peut-être entendu parler de l&rsquo;épidémie de Guillain-Barré qui sévit actuellement au Pérou. Si oui, vous avez sans doute entendu également nos antivax locaux et leurs relais habituels (genre Philippot, qui est décidément de tous les bons coups) se répandre sur leur explication favorite dès qu&rsquo;une maladie, un accident ou une chute de météorites se produit&nbsp;: célafotovaksin. C&rsquo;est débile et on est habitués, mais cette épidémie, elle est bel et bien là, alors qu&rsquo;est-ce qui se passe&nbsp;?</p>
<p>Déjà, posons les bases&nbsp;: Guillain-Barré, c&rsquo;est quoi, et qu&rsquo;est-ce qu&rsquo;on en sait&nbsp;? C&rsquo;est une maladie auto-immune, ce qui veut dire que, pour une raison ou une autre, le corps prend un de ses composants pour un ennemi et l&rsquo;attaque. Dans ce cas, ce sont les muscles qui sont atteints et qui deviennent faibles, parfois jusqu&rsquo;à la paralysie. En général, les patients récupèrent en quelques semaines, mais une hospitalisation peut être nécessaire si les muscles du diaphragme sont touchés ou si l&rsquo;immobilisme de la personne génère des escarres ou des phlébites. Quant à la cause, elle est inconnue, mais la maladie est le plus souvent précédée d&rsquo;une infection (Zika au Brésil a par exemple été relié à une augmentation importante des cas), d&rsquo;une autre maladie systémique (comme le lupus) et, dans de très rares cas d&rsquo;une vaccination anti-grippe (on note une augmentation de 1 à 2 cas pour un million de vaccinés… mais de 40 à 70 cas pour un million de grippés, la balance bénéfice-risque est donc toujours jugée favorable).</p>
<p>Sachant cela, le Pérou enquête actuellement pour essayer de remonter au déclencheur de l&rsquo;épidémie, et les principaux suspects pour l&rsquo;instant sont Zika, le Chikungunia et la dengue. Ce dernier est le favori des autorités médicales, car il s&rsquo;avère que, depuis le début de l&rsquo;année, il sévit de manière majeure dans le pays (début mai, on comptait près de 73.000 cas et 79 décès, une augmentation de plus de 110% par rapport à 2022). Les investigations sont en cours (si vous voulez en savoir plus et que vous parlez espagnol, <a href="https://www.dge.gob.pe/portalnuevo/vigilancia-epidemiologica/subsistema-de-vigilancia/dengue/alertas-epidemiologicas-y-documentos-normativos-dengue/">y a toute la doc là</a>), et pour l&rsquo;instant, personne n&rsquo;a la réponse. Elle viendra (peut-être, car lors de l&rsquo;épidémie de 2019, même si un lien avec une bactérie provoquant des diarrhées aigües était suspecté, la cause réelle n&rsquo;avait jamais été identifiée), mais certainement pas des experts Twitter…</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>Sur cette page, on parle souvent de l&rsquo;infiniment petit avec les virus et les bactéries, pour une fois parlons de l&rsquo;infiniment grand. L&rsquo;Agence Spatiale Européenne a annoncé cette semaine avoir identifié l&rsquo;exoplanète la plus brillante jamais découverte, si brillante qu&rsquo;elle ne … devrait pas pouvoir exister. Dans son communiqué (<a href="https://www.esa.int/Science_Exploration/Space_Science/Cheops/Cheops_shows_scorching_exoplanet_acts_like_a_mirror">à lire ici</a>), l&rsquo;agence explique que ce comportement de «&nbsp;miroir&nbsp;» est lié à des nuages de métal dans l&rsquo;atmosphère de la planète (oui, je sais, c&rsquo;est bizarre, mais y a bien des planètes sur lesquelles il pleut des diamants, qu&rsquo;est-ce que vous voulez…). De la taille de Neptune, la planète est couverte de nuages formés de gouttes de titane, des gouttes qui ne devraient pas pouvoir exister au vu de la température trop élevée de la planète.</p>
<p>Mais comme elle était là, avec ses nuages impossibles, il a bien fallu admettre que la réalité avait plus d&rsquo;imagination que nous. Dans le cas présent, les chercheurs en ont conclu que ces nuages pouvaient se former malgré une température absurde parce que l&rsquo;atmosphère de la planète était tellement saturée de métal à l&rsquo;état gazeux que celui-ci n&rsquo;avait, au bout d&rsquo;un moment, plus nulle part où aller et commençait à condenser. Une atmosphère qui ne devrait pas exister non plus, car la planète est trop proche de son étoile (elle en fait le tour en 19 jours). Les chercheurs ont bien quelques hypothèses, mais elles vont réclamer des études plus approfondies. Et ça fait partie des trucs que j&rsquo;aime avec la science. Quand on a des modèles qui marchent, on s&rsquo;en sert pour découvrir le monde, jusqu&rsquo;au moment où on tombe sur un truc qui oblige à changer le modèle avec lequel on l&rsquo;a trouvé. Et au lieu d&rsquo;être vexés, on trouve ça juste génial. «&nbsp;Les scientifiques refusent de remettre en question leurs dogmes, ils refusent d&rsquo;avoir tort&nbsp;!&nbsp;» Ecoute Gérard, y a des collègues, là, ils sont prêts à changer la physique parce qu&rsquo;il y a un caillou qui brille trop dans l&rsquo;espace, alors tu devrais redescendre d&rsquo;un cran.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Antibiotique</strong>&nbsp;: ce n&rsquo;est hélas pas une nouveauté, mais dans la lutte contre l&rsquo;antibiorésistance, nos armes s&rsquo;épuisent de jour en jour. Et l&rsquo;idée du moment est donc d&rsquo;essayer de ressortir des vieux antibiotiques, dans l&rsquo;espoir que les bactéries les aient pas vus depuis des générations et y soient sensibles. «&nbsp;Mais comment ça se fait qu&rsquo;on utilise plus ces vieux médicaments pas chers à la place de tous ces trucs coûteux de Big Pharma, là&nbsp;?!&nbsp;» Et bien Gérard, parce que des fois, un médicament, il est vieux, efficace et pas cher, mais il est toxique. C&rsquo;est ce qui s&rsquo;est produit pour la nourséothricine, produite dans les années 40 mais rapidement arrêtée. Et qui vient d&rsquo;être ressuscitée (<a href="https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3002091">dans ce papier</a>) car des analyses plus poussées ont permis de séparer ses composants et d&rsquo;en isoler un, peu toxique, mais qui serait efficace contre des bactéries résistantes, à l&rsquo;origine de maladies graves. Des essais in vivo doivent être menés prochainement.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>IST</strong>&nbsp;: puisqu&rsquo;on parle d&rsquo;antibiorésistance, parlons de pathologies qui peuvent y être liées. Les chiffres du UK sont alarmants (<a href="https://www.gov.uk/government/statistics/sexually-transmitted-infections-stis-annual-data-tables/sexually-transmitted-infections-and-screening-for-chlamydia-in-england-2022-report">à lire ici</a>, mais on ferait bien de pas trop faire les malins, car nous on n&rsquo;a plus de chiffres depuis 2016, donc la prochaine étude de Santé Publique France va peut-être nous filer un sacré taquet sur la tête)&nbsp;: chaque jour 400 personnes dans la tranche des 15-24 ans contractent une IST sur l&rsquo;île, qui cumule pas loin de 400.000 infections sur l&rsquo;année 2022. La gonorrhée (qui est de plus en plus résistante aux antibios) a pris plus de 50% de cas en plus en une année, les chlamydias près de 25%, l&rsquo;herpès a pris plus de 13% de cas supplémentaires, les condylomes (liés au HPV) ont augmenté de 8.5% et le taux de syphilis est du jamais vu depuis 1948. Certes, une partie des cas est mécaniquement liée à l&rsquo;augmentation du dépistage (plus 13.8%) mais ça ne suffit pas à tout expliquer (surtout qu&rsquo;il peut s&rsquo;agir d&rsquo;un facteur confondant&nbsp;: moi aussi, si je me mettais à pisser des lames de rasoir, j&rsquo;irais me faire dépister). La tendance serait mondiale car les USA enregistrent des augmentations similaires (avec la moitié des cas chez les adolescents et les adultes de moins de 25 ans… on n&rsquo;insistera jamais assez sur le fait que ne pas faire d&rsquo;éducation sexuelle en expliquant qu&rsquo;il faut juste être abstinents à des classes entières de jeunes primates défoncés aux hormones ne peut que se solder par ce type de résultats), et il va falloir commencer à choisir si les gens préfèrent engraisser BigPharma ou BigLatex.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Coqueluche</strong>&nbsp;: depuis le début du mois, le Vaucluse a enregistré une soixantaine de cas de coqueluche, avec quelques cas débordant dans le Gard et les Bouches-du-Rhône. Si les deux tiers des cas concernent le centre hospitalier d&rsquo;Avignon, dans lequel la maladie a été introduite et s&rsquo;est répandue comme une trainée de poudre, le reste a contracté la maladie à l&rsquo;extérieur. On rappelle que la vaccination contre la coqueluche est obligatoire à partir de 2 mois depuis 2018, et que si on s&rsquo;est emmerdé à la rendre obligatoire c&rsquo;est que c&rsquo;est important, donc faisez pas les cons, vaccinez-vous (<a href="https://www.youtube.com/watch?v=C_honGEP0Sw">et si vous avez oublié la tronche que ça a comme maladie, je vous met la vidéo de Doc Primum sur le sujet, ça remet les idées en place</a>).</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Biodiversité</strong>&nbsp;: si des espèces disparaissent malheureusement, et de plus en plus vite, on continue également à en découvrir. Osteocephalus vasquezi est ainsi une nouvelle espèce de grenouille, découverte au Pérou, sur les pentes orientales des Andes, dans le bassin de l&rsquo;Amazone. Vivant entre 1.000 et 1.150 mètre d&rsquo;altitude, l&rsquo;espèce aurait divergé d&rsquo;avec les autres de son genre il a 2.5 millions d&rsquo;années.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Hé&nbsp;! Vous aussi vous êtes toujours pas morts en masse de votre vaccination alors que vous auriez dus, bande de sales moutons&nbsp;? Bon, ben si comme moi vous commencez à trouver qu&rsquo;on vit quand même les «&nbsp;derniers 6 mois à vivre&nbsp;» les plus longs de la Terre, sachez que vous êtes loin d&rsquo;être seuls. En effet, alors qu&rsquo;il devait y avoir des morts en masse partout et des cadavres dans les rues, en France l&rsquo;Oniam (Office National d' Indemnisations des Accidents Médicaux) a reçu pour l&rsquo;instant en tout et pour tout…1.020 dossiers de demande d&rsquo;indemnisation pour des effets secondaires liés au vaccin contre le Covid (et venez pas me dire &nbsp;«&nbsp;oui mais forcément, les autres ils sont tous morts&nbsp;» le dossier peut être déposé par les familles Gérard, et vu que tous les antivax connaissent 60 personnes dans leur entourage qui en sont mortes, il devrait y en avoir un peu plus quand même). Sur le nombre total de doses administrées, ça veut dire que 0.00066% des injections ont été suivies de problèmes suffisamment gênants pour que les patients demandent à être indemnisés (et ça ne garantit toujours pas le lien de causalité, là c&rsquo;est juste les dossiers déposés).<br />
Pour l&rsquo;instant, l&rsquo;Oniam a pu se prononcer dans 241 dossiers, dont 72 ont effectivement été reçus et vont aboutir à une indemnisation pour des patients ayant souffert de péricardites et de myocardites. Ca fait 7% des demandes, soit donc 0.0000462% des injections. J&rsquo;oserai donc dire que ça s&rsquo;est bien passé, en fait.<br />
Ah et aussi, tant qu&rsquo;on y est&nbsp;: ces gens sont (ou vont être prochainement) indemnisés pour ces effets secondaires. Pour des vaccins qui étaient censés être issus d&rsquo;un super accord secret dont tout le monde a entendu parler comme quoi les labos seraient dégagés de toute responsabilité et les victimes jamais prises en charge, ça non plus, c&rsquo;est pas ultra vérifié.</p>
<hr />
<h3 id="point-methode-de-la-semaine-la-vulgarisation--quand-sarrêter"><a href="#point-methode-de-la-semaine-la-vulgarisation--quand-sarrêter">POINT METHODE DE LA SEMAINE&nbsp;: la vulgarisation &#45; Quand s&rsquo;arrêter</a></h3>
<p>La vulgarisation, c&rsquo;est bien, c&rsquo;est chouette, ça rend le monde moins bête, mais hélas rarement moins méchant. Et parfois Sisyphe il en marre de porter toujours le même caillou. A mon sens, et avec la petite expérience qui est la mienne, je pense qu&rsquo;il existe 4 raisons pour lesquelles, un jour, on peut jeter l&rsquo;éponge:</p>
<ol>
<li><strong>L&rsquo;inutilité</strong> Face à certaines personnes, il faut savoir reconnaître qu&rsquo;on ne peut plus rien, qu&rsquo;elles sont trop loin. Peut-être qu&rsquo;elles reviendront un jour (et on a, parmi les vulgarisateurs et débunkers, des anciens tenants qui font un boulot formidable comme Mr Sam, Elizabeth Feytit ou Sohan Tricoire), mais c&rsquo;est un chemin intérieur et, si on a pu leur laisser des ressources qui les aideront lors de ce chemin-là, ça ne sert à rien de leur jeter des trucs à la tronche. Surtout si c&rsquo;est un proche. Alors, oui, c&rsquo;est très dur de voir un proche sombrer, mais il faut bien comprendre que là, tout ce qu&rsquo;on peut dire est inutile, en revanche, on peut continuer à être là, en évitant au maximum les sujets délicats, et en maintenant un lien, parfois le dernier, entre la personne et la réalité. Ce n&rsquo;est pas pour rien que les dérives sectaires cherchent avant tout à couper les gens de leur entourage, et il ne faut pas laisser ça se produire. Parfois, avoir raison, dire la vérité, c&rsquo;est moins important que faire ce qu&rsquo;il faut pour protéger quelqu&rsquo;un en danger.</li>
<li><strong>La peur</strong> Je ne dirai pas «&nbsp;le danger&nbsp;» car chez les vulgarisateurs, nous avons tous été, à différents degrés, harcelés, insultés, menacés. Mais chacun le vit différemment et personne n&rsquo;a à expliquer aux victimes de violences comment elles doivent les vivre. Si quelqu&rsquo;un s&rsquo;amuse à retrouver vos proches pour leur envoyer des menaces voilées, il y a des gens que ça terrifient et qui vont préférer tout arrêter, et c&rsquo;est ok. Moi, ça m&rsquo;a mise en colère et je me suis juste dit qu&rsquo;il allait prendre les flics au cul, ce con, mais c&rsquo;est moi et c&rsquo;est comme ça. Alors bien sûr, la peur n&rsquo;empêche pas le courage, précisément parce que le courage, c&rsquo;est être mort de trouille et y aller quand même. Mais chacun a son niveau de courage, et c&rsquo;est ok de refuser d&rsquo;y aller, parce qu&rsquo;en face, ils sont trop nombreux. N&rsquo;en voulez pas à ceux qui jettent l&rsquo;éponge, vous ne savez pas ce qu&rsquo;ils vivent.</li>
<li><strong>La fatigue</strong> Il y a Internet, et il y a la vie. A part quelques-uns d&rsquo;entre nous dont vulgarisateur est devenu le métier, on a des vies à côté, un travail, une famille, des loisirs, un chaton tout pelucheux, ce que vous voulez. Et tout ne peut pas toujours rentrer. L&rsquo;épuisement et le burn-out sont des maux bien connus des vulgarisateurs, encore plus s&rsquo;ils sont chercheurs ou médecins, et donc issus de professions déjà très touchées par ce mal. Certains vont ralentir le rythme, certains vont louvoyer, certains vont arrêter. Il faut remplir le frigo et payer les factures (moi, j&rsquo;ai 5 abonnés sur ma page KissKissBankBank, alors à moins que l&rsquo;un d&rsquo;entre eux soit Bill Gates, ils me payent gentiment le café, merci à eux, mais je reste obligée d&rsquo;avoir un travail avec un contrat et tout), il faut dormir, il faut vivre avec les gens qui sont là. N&rsquo;en voulez pas à ceux qui ralentissent le rythme, ils essayent juste de vous consacrer du temps dans une vie bien remplie.</li>
<li><strong>Le dégoût</strong> Parfois, on a plus le cœur à faire ce qu&rsquo;on fait. C&rsquo;est triste mais ça arrive, comme on se lasse d&rsquo;un hobby, d&rsquo;un CDI, d&rsquo;un mari. Il faut imaginer Sisyphe heureux, disait Camus, mais s&rsquo;il ne l&rsquo;est plus un jour, il laisse tomber son caillou. C&rsquo;est décevant pour le public, bien sûr, mais gardez bien en tête que, si vous aimez tant nos contenus, c&rsquo;est parce qu&rsquo;on aime ce qu&rsquo;on fait, c&rsquo;est ça qui nous rend bons. Laissez-nous le panache de sortir avant de devenir médiocre.</li>
</ol>
<p>Mais vous en faites pas, moi, je serai encore là la semaine prochaine.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec le 14 juillet (et n&rsquo;importe quelle autre fête nationale, pour autant qu&rsquo;on ait pu en juger). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
        </div>)
  }