
import { Article } from "@/atoms/Article";

export const Article20230212LechodeslabosMetadata = {"tags":["covid","USA","Russie","Sars-Cov","Sars-Cov2","SRAS","Corée du Sud","coronavirus","Spoutnik","désinformation","Transgene","cancer","chimiothérapie","radiothérapie","LRRC15","Eiger biopharmaceuticals","FDA","US-FDA","AEM","papillomavirus humain","HPV","Arte","Anne Georget","Amine Umlil","hôpital de Cholet","Eric Loridan","Denis Agret","antivax","antivaxx"],"title":"l'Écho des Labos - 12 février 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-02-12"}

export const Article20230212Lechodeslabos : Article = ({
  className, title, img, UTip
}) => {
  return (<div className={className}>
      <dl>
<dt>{ img("https://www.inquirer.com/resizer/MtnyC8cTjdt-eIpK7CJFG3dSPGw=/760x507/smart/filters:format(webp)/arc-anglerfish-arc2-prod-pmn.s3.amazonaws.com/public/SLWBXZ2RSVFOXPCB72DIW3JSUE.jpg",  "" ) }</dt>
<dd>Adam Zyglis, School SCIENCE FAIR
</dd>
<dd>3 enfants présentent leur projet pour la kermesse scientifique de l'école:
<ol>
<li>la première : La maquette de volcan qui utilise la réaction avec du bicarbonate de soude.</li>
<li>le deuxième: Un exposé sur le pH de l'eau.</li>
<li>la troisième: Expérimentation &#45; la santé de ma communauté: Ma maman ne m'as pas faite vacciner alors voyons ce qu'il arrive.</li>
</ol>
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { UTip( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Bon. Alors. Normalement on ne parle pas de politique dans la chronique, parce que c&rsquo;est pas le sujet, mais là on va être un peu obligés. Sauf si vous avez vécu dans un bunker ces derniers mois (auquel cas, en vrai, retournez-y, ça craint dehors en ce moment), vous avez une idée, ne serait-ce que vague, du fait que les USA et la Russie ont en ce moment une relation tendue, genre plus que d&rsquo;habitude, genre vraiment plus que d&rsquo;habitude. La Russie ne peut pas bombarder les USA parce qu&rsquo;elle est déjà rêche niveau obus, elle ne peut pas leur faire du chantage économique parce que sa monnaie commence à valoir moins que celle du monopoly donc elle tacle là où elle peut, à savoir la désinformation. Si vous vous souvenez, ce n&rsquo;est pas la première fois qu&rsquo;on parle de l&rsquo;influence russe dans la désinformation concernant le Covid (je vous conseille d&rsquo;aller rechercher sur la chaîne toute l&rsquo;histoire sur la tentative de faire passer une campagne de désinformation par des Youtubeurs connus). Mais cette fois, c&rsquo;est beaucoup plus frontal&nbsp;: le ministère de la défense a tenu une conférence de presse pour accuser les USA d&rsquo;être à l&rsquo;origine du Sars-Cov2. Bon, faisons comme si ces gens avaient toujours un semblant de crédibilité, et regardons un peu les arguments majeurs&nbsp;:</p>
<p>Une université soutenue par la fondation de Bill Gates a organisé un exercice de réaction face à un coronavirus quelques mois avant le début de l&rsquo;épidémie&nbsp;: laissez-moi vous rappeler l&rsquo;existence d&rsquo;une merveilleuse saloperie appelée le SRAS, causé par le virus Sars-Cov (ben oui, si le Covid vient de Sars-Cov2, c&rsquo;est qu&rsquo;il y a eu un 1…). Le SRAS a frappé très durement plusieurs pays d&rsquo;Asie et particulièrement la Corée du Sud de 2002 à 2004 et a causé la mort de 914 personnes pour 8.000 cas. Il s&rsquo;agissait du premier coronavirus aussi agressif sur l&rsquo;être humain, et à ce moment-là, les chercheurs se disent «&nbsp;Ca va recommencer, on va en reprendre un sur la tronche, il faut qu&rsquo;on soit prêts&nbsp;». Donc, en vrai, ça faisait plus de 15 ans qu&rsquo;on faisait des exercices pour se préparer.</p>
<p>Le vaccin des labos américains a été prêt trop vite, c&rsquo;est suspect&nbsp;: alors, j&rsquo;ai fait un peu de recherche sur les différentes annonces… Les premiers à avoir annoncé que ça y est, leur vaccin était prêt… c&rsquo;était les Russes, avec Spoutnik. Faites-en ce que vous voulez.</p>
<p>Les Américains travaillent sur des modifications de virus et c&rsquo;est même possiblement pour faire des armes biologiques&nbsp;: et c&rsquo;est là qu&rsquo;on retombe sur la partie politique. Parce qu&rsquo;en fait, qui en a quoi que ce soit à faire d&rsquo;entendre des non-spécialistes dire «&nbsp;j&rsquo;ai pas de preuves mais je suis sûr que c&rsquo;est la faute à machin&nbsp;?&nbsp;», à quoi ça sert&nbsp;? Ca sert à appuyer le narratif «&nbsp;les Américains fabriquent des armes biologiques en Ukraine, et on doit bombarder leurs infrastructures pour se défendre&nbsp;». Le Covid ici, c&rsquo;est avant tout un prétexte pour charger la barque et demander à l&rsquo;ONU d&rsquo;enquêter (spoiler&nbsp;: l&rsquo;ONU a examiné les éléments apportés par les Russes et n&rsquo;a rien trouvé de convaincant, ni sur le Covid ni sur le reste). De plus en plus, il devient difficile de s&rsquo;attaquer à la désinformation sans devoir aussi s&rsquo;attaquer aux structures qui sont derrière et à ses causes. Il ne suffit plus de montrer que les gens racontent n&rsquo;importe quoi, de plus en plus il faut commencer à répondre à la question «&nbsp;pourquoi untel ira-t-il raconter n&rsquo;importe quoi&nbsp;?&nbsp;». Et je suis pas sûre qu&rsquo;on soit armés pour ça…</p>
<hr />
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p>Aujourd&rsquo;hui, on va à nouveau parler vaccin contre le cancer, parce que c&rsquo;est une branche en plein essor, et c&rsquo;est tant mieux. Cette fois, il va être question d&rsquo;un vaccin personnalisé, qui sera utilisé après une chimiothérapie, pour prévenir les récidives.</p>
<p>C&rsquo;est la biotech française Transgene qui vient de présenter des résultats positifs d&rsquo;essais cliniques phase 1. Le principe est le suivant&nbsp;: pendant qu&rsquo;un patient suit un traitement par chimio et/ou radiothérapie, les particularités génétiques de sa tumeur sont séquencées afin de trouver des marqueurs. En trois ou quatre mois, il est alors possible de créer un vaccin sur mesure, qui va apprendre au système immunitaire du patient à reconnaître ces marqueurs spécifiques et à cramer la tronche de toute cellule qui en serait porteuse, protégeant ainsi des récidives.</p>
<p>Les tests portent pour l&rsquo;instant sur des cancers de la tête et du cou, pour lesquelles la récidive est importante (1 patient sur 2) et rapide (2 à 3 ans). Les premiers patients ont reçu leur injection il y a un peu plus de deux ans et aucune rechute n&rsquo;est à déplorer pour l&rsquo;instant. Des essais se poursuivent sur des cancers de l&rsquo;ovaire et d&rsquo;autres essais plus larges sont prévus rapidement. Si ce traitement ne sera hélas d&rsquo;aucune aide pour les patients dont les tumeurs ne répondent pas à la chimio ou la radiothérapie, il reste un formidable espoir pour préserver les patients en rémission du risque de récidive.</p>
<p><em>Source&nbsp;: IUCT &#45; Oncopole Toulouse</em></p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Covid &#45; gravité</strong>&nbsp;: pourquoi certaines personnes ont-elles un vague rhume quand elles attrapent le Covid et pourquoi d&rsquo;autres restent-elles au fond du lit à délirer de fièvre et à maudire tout ce que la création compte de micro-organismes&nbsp;? La réponse est peut-être dans une protéine nouvellement découverte&nbsp;: LRRC15. Elle est décrite (<a href="https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3001967">ici</a>) comme un «&nbsp;velcro cellulaire&nbsp;» s&rsquo;attachant au virus et l&rsquo;empêchant de se répandre dans des tissus plus fragiles. Si son rôle est encore mal compris, il semblerait qu&rsquo;elle puisse produire une barrière physique entre les poumons et le virus… à condition d&rsquo;être produite à temps et en assez grand nombre. Une affaire à suivre.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Covid &#45; Traitement</strong>&nbsp;: Eiger biopharmaceuticals vient de publier les nouveaux résultats (<a href="https://www.nejm.org/doi/full/10.1056/NEJMoa2209760">ici</a>) de ses études sur un traitement par interférons en injection unique. Il permettrait de réduire de moitié le risque d&rsquo;hospitalisation chez les patients infectés, un effet protecteur encore plus fort si on ne regarde que les patients non-vaccinés (56% de réduction du risque). Jusqu&rsquo;ici, le traitement n&rsquo;était approuvé ni par la FDA, ni par l&rsquo;AEM, faute de preuves claires de son efficacité. Il n&rsquo;est pas encore dit si cette position va évoluer, car les intervalles de confiance des résultats ne sont pas très clairs et les échantillons pas très larges. A suivre également.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Cancer</strong>&nbsp;: la France est très, très à la traîne dans la prévention des cancers liés au papillomavirus humain, le HPV. Cancer du col de l&rsquo;utérus majoritairement, mais aussi de la vulve, de l&rsquo;anus, ou encore certains cancers ORL (non, je ne vais pas m&rsquo;étendre sur pourquoi, vous êtes assez grands), chaque année le HPV cause 6.400 cancers en France, les trois-quarts chez les femmes. Autant de maladies qui sont désormais évitables&nbsp;: avec une couverture vaccinale de plus 75% chez les hommes et presque 80% chez les femmes, le UK ou encore l&rsquo;Australie sont en passe d&rsquo;éliminer le cancer du col de l&rsquo;utérus, le 4e plus mortel au monde chez les femmes. En France, la couverture vaccinale est lamentable (27e rang européen…) avec 13% des femmes et 6% des hommes seulement. Manque de pédagogie, manque de visibilité, et large audience accordée aux tribunes antivaccins (n&rsquo;est-ce pas Arte&nbsp;? n'est pas Anne Georget&nbsp;? 6.400 cancers par an vous remercient) et conservatrices («&nbsp;ça n&rsquo;arrive pas si vous éduquez bien vos ados et qu&rsquo;ils n&rsquo;ont pas de rapports sexuels&nbsp;» ce sont des ados, le principe de réalité est plus fort que votre morale à la mord-moi-la-trompe&nbsp;!), le Plan Cancer vise cette année à atteindre 60% de couverture vaccinale chez les 11-19 ans. Et c&rsquo;est pas gagné.</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Désinformation</strong>&nbsp;: la lutte contre la désinformation progresse petit à petit, et les têtes qui racontaient n&rsquo;importe quoi commencent enfin à tomber. Amine Umlil, le pharmacien hospitalier de l&rsquo;hôpital de Cholet a ainsi été révoqué pour propagande anti-vaccinale mettant en danger la santé publique. Eric Loridan, chirurgien et figure de proue des anti-masques (pour un chirurgien, ça devrait faire flipper tout le monde) a été interdit d&rsquo;exercer pendant 3 mois. La figure de proue des anti-vax Denis Agret écope quant à lui d&rsquo;une interdit d&rsquo;exercer pendant 3 ans. Il semblerait que le Conseil de l&rsquo;Ordre se soit souvenu qu&rsquo;en fait, il avait un boulot…</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Arte. Arte. Sérieusement, Arte&nbsp;? Tu sais, j&rsquo;ai pas que ça à foutre de ma vie que de t&rsquo;obliger à faire ton boulot de service public, à savoir proposer une information honnête et fiable. On est à peine en train de finir avec le documentaire moisi que tu nous avais pondu (on est à 120 pages de débunk là, et on a pas encore terminé, et ça nous prend un temps fou et une bibliographie monstre, parce que tu as merdé à ce point) que tu nous en sors un autre. C&rsquo;est le deuxième documentaire ouvertement antivax en 4 mois, sérieusement, les gars à ta prod, ils sniffent quoi&nbsp;?</p>
<p>J&rsquo;ai horreur de ça, parce qu&rsquo;à la base, c&rsquo;est un argument pourri, mais là, c&rsquo;est tellement énorme dans le n&rsquo;importe quoi que je suis obligée de poser la question.</p>
<p>Arte, qui te paye&nbsp;? Qui te paye pour les 6.400 cancers par an liés uniquement à la défiance contre le vaccin HPV&nbsp;? Qui te paye pour les résurgences de rougeole alors qu&rsquo;elle avait quasiment disparu de France&nbsp;? Qui te paye pour les complications du Covid et de la grippe&nbsp;? Le pire, c&rsquo;est que c&rsquo;est techniquement le service public qui te paye, les gens payent des impôts pour que tu leur donnes des fausses infos qui vont les mettre en danger, sérieusement, pour qui tu bosses à ce stade, Arte&nbsp;? Qui a à y gagner avec ce que tu fais (hormis la même bande qu&rsquo;on retrouve absolument partout aux génériques des documentaires pourris que tu nous ponds depuis des années sur le jeûne, les vaccins et l&rsquo;homéopathie, parce que eux tu les payes pour raconter de la merde, donc ça peut pas être eux qui t&rsquo;achètent, ça fait pas sens)&nbsp;? Sérieusement, on peut plus dire que c&rsquo;est de l&rsquo;incompétence à ce stade, le rasoir d&rsquo;Hanlon commence à tendre clairement du côté de la malveillance. Du coup, moi je veux bien qu&rsquo;on soit une quinzaine à perdre nos week-ends pour démonter tes âneries, mais à un moment, il va falloir couper l&rsquo;arrivage à la source. Et il va falloir qu&rsquo;on se demande qui est la source et pourquoi elle fait ça. Est-ce que c&rsquo;est les gars à la prod juste y croient très fort et qu&rsquo;ils utilisent la chaîne pour répandre leur évangile&nbsp;? Est-ce qu&rsquo;à force d&rsquo;inspiration allemande, il y a des anthroposophes partout dans tes organes de décision&nbsp;? Est-ce que j&rsquo;ai vraiment envie de me coltiner aussi des recherches sur ça, est-ce que tu peux pas juste revenir à la raison&nbsp;?</p>
<hr />
<h3 id="point-methode-de-la-semaine-la-publication-scientifique--les-différents-types-darticles"><a href="#point-methode-de-la-semaine-la-publication-scientifique--les-différents-types-darticles">POINT METHODE DE LA SEMAINE&nbsp;: la publication scientifique &#45; les différents types d&rsquo;articles</a></h3>
<p>Aujourd&rsquo;hui nous entamons notre grand voyage à travers la publication scientifique. Et avant de publier quoi que ce soit, on va donc déjà commencer par se demander ce qu&rsquo;on a à dire, et donc quelle forme notre publication peut prendre.</p>
<p><strong>J&rsquo;ai fait une grosse découverte/un gros essais clinique</strong>&nbsp;: il s&rsquo;agit des cas que vous avez le plus vus dans la chronique si vous avez cliqué sur les liens que je vous propose. Dans ces cas-là, on écrit un «&nbsp;Original Research&nbsp;», il s&rsquo;agit du type d&rsquo;article le plus long et le plus fourni (les papiers avec des graphs et des tableurs partout) et il doit toujours présenter des résultats originaux, dont la méthodologie est détaillée et dont les données sont accessibles.</p>
<p><strong>J&rsquo;ai trouvé un petit truc/j&rsquo;ai des données partielles mais intéressantes/j&rsquo;ai vaguement un truc mais j&rsquo;ai peur de me le faire piquer</strong>&nbsp;: ici, cela dépend des disciplines. En sciences médicales, c&rsquo;est là qu&rsquo;on va trouver les «&nbsp;Cas cliniques&nbsp;», en biologie les «&nbsp;Etudes de cas&nbsp;», dans mon domaine et dans d&rsquo;autres, on va parler de «&nbsp;Short Communication&nbsp;» etc. Dans tous les cas, il s&rsquo;agit d&rsquo;articles plus courts, moins centrés sur la méthodologie mais très précis sur la présentation des données, qui sont centrales.</p>
<p><strong>J&rsquo;ai rien foutu mais j&rsquo;ai envie de juger le boulot des autres</strong>&nbsp;: ça va être le travail des «&nbsp;Méta-Analyses&nbsp;», c&rsquo;est-à-dire de compiler les travaux des autres sur un sujet précis et d&rsquo;en tirer une réponse globale, qui tienne compte le mieux possible des biais différents dans les différentes études et des possibles erreurs statistiques. Il s&rsquo;agit, à l&rsquo;heure actuelle, du plus haut niveau de preuves dont la science soit capable.</p>
<p><strong>Je voudrais travailler sur un truc mais j&rsquo;ai pas les moyens/j&rsquo;ai peut-être levé un truc intéressant</strong>&nbsp;: si c&rsquo;est en médecine, on va parler des «&nbsp;Rapports de Cas&nbsp;» (en gros «&nbsp;hé les gars, j&rsquo;ai un patient il fait ça, quelqu&rsquo;un sait ce que c&rsquo;est&nbsp;?&nbsp;»), dans les autres domaines, on parle plus des «&nbsp;Letters&nbsp;», c&rsquo;est-à-dire qu&rsquo;il s&rsquo;agit de chercheurs signalant des faits intéressants à d&rsquo;autres, mais ils ne sont pas attestés et doivent être pris avec précaution. En général, ce sont des articles qui n&rsquo;ont d&rsquo;intérêt que pour les autres chercheurs, pour savoir ce qu&rsquo;il se passe d&rsquo;intéressant dans leur discipline en ce moment.</p>
<p><strong>Je veux parler de ce qu&rsquo;on a à dispo pour bosser</strong>&nbsp;: si l&rsquo;idée est de faire le point sur ce qu&rsquo;on sait dans un domaine, on écrit un «&nbsp;Etat de l&rsquo;Art&nbsp;», si on veut plus parler des documents à disposition, on va parler plutôt d&rsquo;une «&nbsp;Revue de la Littérature&nbsp;», et si on veut présenter un ouvrage qui est nouveau dans le domaine et dont on pense qu&rsquo;il est important, on écrit une «&nbsp;Review&nbsp;».</p>
<p><strong>Je suis pas content/Je trouve que telle équipe fait de la merde/Je pense que là on est face à un gros problème dans la discipline</strong>&nbsp;: c&rsquo;est là que servent les articles «&nbsp;Opinion&nbsp;», qui sont l&rsquo;équivalent du courrier des lecteurs des journaux scientifiques. Ils n&rsquo;ont pas valeur de preuve, mais ils servent à s&rsquo;engueuler entre chercheurs par journal interposé. Et des fois ça soulage (je suis en train d&rsquo;en écrire un comme ça, ça défoule pour de vrai comparé à un article classique).</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec la Saint-Valentin la semaine prochaine (ne me remerciez pas). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur <a href="https://www.facebook.com/TheDendrobateDoctor/?ref=page_internal">la page Facebook du Docteur</a>.</p>
    </div>)
}