
    import { Article } from "@/atoms/Article";
    
    export const Article20230129LechodeslabosMetadata = {"tags":["covid","Mort subitement","documentaire","thanatopracteurs","thrombose","fibre blanche","globules rouges","linguistique","Basque","château d’Irulegi","syndrome post-Covid","TINU","tubulo interstitielle néphrite et uvéite","OMS","Eric Guedj","AP-HM","Oiseaux des jardins","Mouvement du Sang Pur","détox","naturopathe","George Della Pietra","Idriss Aberkane","Le Biostatisticien"],"title":"l'Écho des Labos - 29 janvier 2023","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2023-01-29"}
    
    export const Article20230129Lechodeslabos : Article = ({
      className, title, img, UTip
    }) => {
      return (<div className={className}>
          <dl>
<dt>{ img("https://www.enago.com/academy/wp-content/uploads/2018/07/Pubtoons_15.png",  "↓" ) }</dt>
<dd>Une femme en blouse blanche hurle avec un mégaphone estampillé SCIENCE sur un homme en chemise orange et bermuda caki tenant une manette de jeux vidéos dans les mains et portant un casque de réalité virtuelle marqué SOCIAL MEDIA.
</dd>
<dd>
<p><strong>Le voyage d'un manuscript dans la revue par les pairs</strong></p>
</dd>
<dd>
<p><em>Quatre scientifiques, le premier présente son étude, les 3 autres l'étudient:</em></p>
</dd>
<dd>Le scientifique qui présente son étude :
<blockquote>
<p>Le document énonce que cette pomme est remplie de plus de nutriments qu'aucun autre fruit.</p>
</blockquote>
<ol>
<li>Premier critique:<br />
"Vous auriez dû utiliser des pêches plutôt."</li>
<li>Deuxième critique:<br />
"Ce n'est pas une pomme, c'est une poire."</li>
<li>Troisième critique:<br />
"Je veux que cette pomme passe aussi des appels."</li>
</ol>
</dd>
<dd>enago.com, <em>publicité</em>
</dd>
<dd>traduction par Jena Thornwyrd
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Tartu, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { UTip( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>«&nbsp;Mort subitement&nbsp;» ce n&rsquo;est pas qu&rsquo;un hashtag conspi, c&rsquo;est également tout un film «&nbsp;documentaire&nbsp;» (que ce genre aura été maltraité pendant la pandémie…) dans lequel des thanatopracteurs américains vous expliquent que le vaccin tue en masse, pour changer. C&rsquo;est incroyable que les conspi trouvent encore des débunkers à qui parler en vrai, moi si je les écoute, j&rsquo;aurais dû mourir en juillet 2021, en décembre 2021 (bon, ça a failli, mais c&rsquo;était le Covid, bizarrement), en mai 2022, en novembre 2022 et en juin 2023 (bon celui-là, il y est pas encore, mais vu comment ça s&rsquo;est passé pour les autres, je suis sereine j&rsquo;avoue).</p>
<p>Bon. Et de quoi qu&rsquo;on est donc sensé mourir ce coup-ci dis-moi donc tout ça un peu&nbsp;? Au début, il est question de caillots, et donc je me dis «&nbsp;ok, pourquoi pas, après tout, on a bien trouvé une augmentation des cas de thrombose pour certaines populations avec certains vaccins&nbsp;». Mais vous vous en doutez, ça part vite en coui…cacahuète. Déjà, y en a un qui dit que ce ne sont pas des caillots de sang mais de «&nbsp;fibre blanche&nbsp;», et moi les seuls caillots de trucs blancs que je connais, c&rsquo;est dans le lait caillé, donc je sais bien que certains ont du fromage blanc dans le crâne, mais faut pas pousser. On va y revenir, bougez pas.</p>
<p>Les autres intervenants du film se contentent eux de parler de «&nbsp;caillots mutants&nbsp;». Ok. Pouce. Deux secondes. Quoi&nbsp;? Alors, un caillot, c&rsquo;est du sang qui coagule, et donc qui est mort. Pour muter, il faut que des changements génétiques s&rsquo;expriment lors de la reproduction. Or, et j&rsquo;espère que tout le monde est assis, on se reproduit pas des masses quand on est mort. Si, si, je vous jure. Alors peut-être que les gars veulent parler de caillots issus de sang mutant et qu&rsquo;ils s&rsquo;expriment mal, mais là aussi spoiler&nbsp;: les globules rouges, le composant majoritaire du sang, sont des cellules sans noyau. Donc elles mutent que pouic. Peut-être que c&rsquo;est la moelle osseuse qui mute et les fabrique défectueux alors&nbsp;? Peut-être, mais dans ce cas pourquoi ça se verrait juste là et pas sur les autres composants que fabrique la moelle&nbsp;?</p>
<p>La meilleure solution, c&rsquo;est encore de parler de ça à… des thanatopracteurs. Ben oui, parce que le pékin moyen, on lui montre un truc chelou sorti d&rsquo;un macchabé, il trouve ça inquiétant, mais en vrai, vous avez pas idée du nombre de truc chelous qu&rsquo;il y a dans le corps humain. La beauté intérieure, c&rsquo;est une fumisterie les enfants. Et les thanatopracteurs sont assez formels&nbsp;: oui, des fois quand on sort le sang des gens, il y a des caillots, mais ça a toujours été le cas. Oui, des fois il y en a beaucoup, c&rsquo;est normal. Oui, parfois, certains sont élastiques avec des trucs blancs à l&rsquo;intérieur, ce sont des fibroses, c&rsquo;est normal aussi. Non, ils n&rsquo;ont rien vu de suspect depuis la vaccination Covid et de toute façon, ils ne connaissent pas le statut vaccinal des corps qu&rsquo;ils reçoivent, donc personne ne peut tirer de conclusion comme ça. En revanche, ils sont aussi formels sur le fait que conserver des tissus et des fluides prélevés sur les corps comme le montre le film avec ses tas de petits flacons et bocaux est parfaitement illégal. Un commentaire à faire à ce sujet, peut-être&nbsp;?</p>
<hr />
<h3 id="decouverte-de-la-semaine"><a href="#decouverte-de-la-semaine">DECOUVERTE DE LA SEMAINE</a></h3>
<p><strong>Linguistique</strong>&nbsp;: je ne vous parle pas souvent de mes premières amours (en recherche, je parle, hein, évidemment, c&rsquo;est pas Closer ma chronique) mais cette fois-ci, c&rsquo;est l&rsquo;occasion. Pour ce qui est de la linguistique européenne, il existe un grand mystère&nbsp;: le basque. Ça peut sembler étrange, mais le basque n&rsquo;est relié à aucune des langues qui l&rsquo;entourent, ni à leurs ancêtres, point de grec ou de latin, d&rsquo;anglo-saxon ou de celte, le basque est ce qu&rsquo;on appelle un isolat, un truc qui semble être apparu, comme un champignon au milieu de rien. La moindre découverte à son sujet est donc très précieuse, car on y comprend pas grand-chose. En 2021, des archéologues avaient mis au jour une amulette en forme de main sur le site du château d&rsquo;Irulegi. Datée d&rsquo;environ 2.000 ans, l&rsquo;amulette devait visiblement être clouée sur une porte et était gravée d&rsquo;une longue inscription de 4 lignes. La première vient tout juste d&rsquo;être déchiffrée, et elle indique «&nbsp;sorioneku&nbsp;». Or, le basque actuel possède un mot proche, «&nbsp;zonioneko&nbsp;» qui désigne le caractère chanceux, ce qui fait totalement sens sur une amulette. Même si vous ne parlez pas basque, il est possible d&rsquo;avoir accès au dossier montrant les photos de l&rsquo;amulette et <a href="http://www.aranzadi.eus/la-escritura-en-la-mano">les différents alphabets comparés ici</a></p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Covid des enfants</strong>&nbsp;: une forme inquiétante de syndrome post-Covid a été identifié dans la tranche d&rsquo;âge des 14-15 ans. Appelé TINU, pour tubulo interstitielle néphrite et uvéite, le syndrome existe déjà, mais il est rare. En France, il a touché 46 enfants entre 2000 et 2018. Or, les cas ont explosé avec l&rsquo;arrivée du Covid&nbsp;: une étude (<a href="https://www.medrxiv.org/content/10.1101/2023.01.23.23284848v1.full.pdf">encore en pré-print, donc comme d&rsquo;hab on reste prudent, mais c&rsquo;est ici</a>) a recensé 48 cas entre avril 2020 et mars 2021, pour une moyenne d&rsquo;âge de 14.7 ans. Seule une partie des cas (21) avait pu être testée à l&rsquo;époque, mais tous étaient positifs au Covid. En revanche, l&rsquo;immense majorité (44/48), s&rsquo;ils étaient infectés, étaient asymptomatiques. Des recherches sur des cohortes dans d&rsquo;autres pays doivent être menées pour voir si les données se recoupent.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Covid long</strong>&nbsp;: l&rsquo;impasse dont je veux parler aujourd&rsquo;hui n&rsquo;est pas une impasse scientifique réellement, car la recherche progresse. Il s&rsquo;agit plutôt de parler de l&rsquo;impasse dans laquelle les patients se retrouvent, car le temps de la recherche n&rsquo;est pas, hélas, le temps de la maladie. La science, quoi qu&rsquo;elle fasse, arrive toujours trop tard pour quelqu&rsquo;un. Alors que l&rsquo;OMS estime qu&rsquo;entre 10% et 20% des malades du Covid sont atteints ensuite par sa forme longue, les patients continuent à se plaindre du scepticisme qu&rsquo;ils rencontrent face à une partie de la communauté médicale. Cela vient du fait que la collection des symptômes, même si elle est désormais bien établie (<a href="https://www.nature.com/articles/s41579-022-00846-2">voir ici</a>) est large, et le diagnostic compliqué. A l&rsquo;heure actuelle, il n&rsquo;est plus probable de trouver un biomarqueur unique (ce qui ne veut pas dire qu&rsquo;il n&rsquo;y a pas de potentiels biomarqueurs reliables à différentes formes) et certains spécialistes, comme Eric Guedj de l&rsquo;AP-HM, croient bien plus au diagnostic par l&rsquo;imagerie. Le spécialiste s&rsquo;inquiète également de pathologies qui seraient à tort attribuées à des Covid longs, non diagnostiquées à temps, et qui occasionneraient une perte de chance pour les malades. Certains chercheurs ont plaidé pour que l&rsquo;origine de la maladie soit plus psychologique que physiologique, mais cette hypothèse est très franco-française, et je n&rsquo;ai trouvé aucune étude à peu près correctement construite qui puisse étayer cette hypothèse. Mais le bruit fait par une petite étude méthodologiquement mauvaise en 2021 a grandement affecté le moral des patients. La recherche fait pourtant des progrès sur les traitements&nbsp;: la rééducation cognitive et olfactive, les anticoagulants et anti-inflammatoires, le paxlovid etc. Mais la cause échappe encore aux chercheurs, et cela pourrait durer un moment&nbsp;: si le Covid est une maladie infectieuse, le Covid long ressemble de plus en plus à une maladie auto-immune. Et sur ce sujet, la recherche est lente.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p>J&rsquo;ai attendu 4 mois le retour de la peer-review pour un de mes papiers et maintenant le journal m&rsquo;annonce que j&rsquo;ai 14 jours pour faire toutes les corrections demandées par les relecteurs, dont certaines sont mutuellement exclusives. Et sinon, ça va, vous&nbsp;?</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Science participative</strong>&nbsp;: le programme «&nbsp;Oiseaux des jardins&nbsp;» est toujours un des programmes de science participative les plus populaires de France et il permet aux chercheurs une compréhension beaucoup plus fine des différents mécanismes affectant les oiseaux. Ce dernier week-end de janvier, comme chaque année depuis 10 ans, 10.000 à 40.000 Français vont compter les oiseaux dans leurs jardins et fournir ainsi les données d&rsquo;hiver (espèces migratrices, hivernantes, population par espèce) aux chercheurs. Si vous aussi, vous voulez participer aux recherches, vous pouvez vous renseigner sur le programme (<a href="https://www.oiseauxdesjardins.fr/">ici</a>) et vous tenir prêts pour le comptage d&rsquo;été, le dernier week-end de mai.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Alors, je sais qu&rsquo;il y a un nouveau jeu Harry Potter qui doit sortir bientôt, mais j&rsquo;aurais vraiment aimé que toute cette histoire de «&nbsp;sang pur&nbsp;» se cantonne à la fiction… Mais comme le monde ne cesse de faire des trucs, comme dit notre bon roi, systématiquement débiles mais toujours inattendus, il existe bel et bien un «&nbsp;mouvement du Sang Pur&nbsp;».</p>
<p>Qu&rsquo;est-ce qu&rsquo;ils font me demanderez-vous (à part sécher les cours d&rsquo;Histoire parce que personne ne peut être fier d&rsquo;avoir un nom de mouvement pareil en ayant eu la moyenne au brevet des collèges)&nbsp;? Déjà, manifestement, ils s&rsquo;arnaquent entre eux pour se refiler des traitements détox sensés «&nbsp;drainer le vaccin&nbsp;». Je le redis, la détox, pour quoi que ce soit (à part si vous êtes en détox, genre la cure pour vous sevrer de l&rsquo;héroïne, ce genre de détox) ça ne sert à rien, vous avez déjà une détox interne, ça s&rsquo;appelle un foie et deux reins, et si la détox ne se fait plus vous êtes mal, jaune et aux urgences, pas en train de vous enfiler un jus de pruneau-kalé-spiruline avec vos comprimés de chlorure de magnésium.</p>
<p>Ensuite, ils réclament l&rsquo;ouverture d&rsquo;une banque de sang pur, parce qu&rsquo;ils veulent pas recevoir le «&nbsp;sang contaminé&nbsp;» des vaccinés. Niveau «&nbsp;sang contaminé&nbsp;» et banque de sang, j&rsquo;ai beaucoup de comparaisons à faire et aucune qui soit de bon goût, donc on va passer. Mais puisque cette banque n'existe pas, il y a un naturopathe suisse, George Della Pietra pour ne pas le nommer (oups), qui propose de fournir du sang «&nbsp;pur&nbsp;» à ses clients. Alors. Y a beaucoup trop de trucs qui vont pas dans cette phrase mais on va essayer.</p>
<ol>
<li>Il y a plein de pays où acheter, vendre et globalement échanger du sang est illégal et la Suisse en fait partie</li>
<li>Quand est-ce qu&rsquo;on arrête ce type pour trafic d&rsquo;organes du coup (oui, le sang compte comme un organe)&nbsp;?</li>
<li>Depuis quand, quand vous êtes dans une situation où vous avez besoin d&rsquo;une transfusion, vous avez le temps que Gégé la débrouille vous fasse un chronopost avec les poches de sa cave perso&nbsp;?</li>
<li>Est-ce que c&rsquo;est possible de faire plus malsain encore&nbsp;?</li>
</ol>
<p>La réponse à la question 4 est oui, puisque certains sont même en train de dire que «&nbsp;le prochain bitcoin&nbsp;» ce sera… le sperme pur. Alors, je suis allée vérifier sur le marché de la cryptomonnaie et il existe bien un jeton appelé «&nbsp;Unvaxxed sperm&nbsp;», l&rsquo;action avait démarré à 0.00001149$ la paillette et s&rsquo;est effondrée une fois que tout le monde n&rsquo;est pas mort subitement du vaccin pour se trouver aujourd&rsquo;hui autour de 0.0000001867$ la paillette de sperme. J&rsquo;ai calculé, ça veut dire que le mec doit éjaculer dans une éprouvette à chaque repas (en partant du principe qu&rsquo;il a du sang de Hobbit et qu&rsquo;il en fait huit par jour), tous les jours, pendant un millénaire pour pouvoir se payer un café au distributeur de ma fac où il est à 50 cents. Notez, ça va les occuper un moment.</p>
<hr />
<h3 id="point-methode-de-la-semaine-devenir-chercheur-le-bon-et-le-mauvais-chercheur"><a href="#point-methode-de-la-semaine-devenir-chercheur-le-bon-et-le-mauvais-chercheur">POINT METHODE DE LA SEMAINE&nbsp;: Devenir chercheur&nbsp;: le bon et le mauvais chercheur</a></h3>
<p>On ne nait pas un bon chercheur, on le devient. Ce qui est normal, parce qu&rsquo;en vrai on ne nait pas grand-chose à part rouge et braillard. Lorsqu&rsquo;on se lance dans la recherche, comment savoir si on est sur la bonne voie pour devenir, pas juste un chercheur, mais un bon chercheur.<br />
Avec la pandémie, on a beaucoup plus entendu parler de la bibliométrie, cette analyse des données bibliographiques qui permet de savoir comment un chercheur est cité, combien de fois et à quelle fréquence.</p>
<p>Faut-il être beaucoup cité pour être un bon chercheur&nbsp;? J&rsquo;espère pas, parce que mon H-index à moi est tout minable (mais quand même plus gros que celui d&rsquo;Idriss Aberkane, faut pas déconner). Mais c&rsquo;est quoi, au juste, un H-index&nbsp;? C&rsquo;est un index calculé selon le nombre X de fois que X publications ont été citées. Par exemple, j&rsquo;ai un indice H de 3, car j&rsquo;ai au moins 3 publications qui ont été citées au moins 3 fois, si je voulais avoir un indice de 4, il faudrait que au moins 4 publications aient été citées au moins 4 fois, et peu importe que j&rsquo;en ai une citée 9 par exemple, ça ne change rien au mode de comptage. Evidemment, dans un petit domaine de niche comme le mien, on est rarement cité, et les H-index restent petits&nbsp;: mon superviseur, une sommité dans son domaine, plafonne à 17. A l&rsquo;inverse, dans des domaines très répandus ou très généralistes, c&rsquo;est très facile d&rsquo;être cité beaucoup&nbsp;: Le Biostatisticien, qui est encore pourtant un tout jeune plein de jus, a déjà un indice de 14. Du coup, un bon chercheur ne peut pas vraiment se mesurer à son indice, pas en tout cas si vous ne savez pas quel est l&rsquo;indice moyen attendu dans son domaine, et est-ce qu&rsquo;il est en début ou en fin de carrière.</p>
<p>Publier beaucoup, c&rsquo;est une chose, mais il faut publier bien. Un indice qui vous permet de savoir si vous êtes ou pas dans la bonne direction c&rsquo;est&nbsp;: avez-vous eu, ou non, un article rétracté&nbsp;? Ça peut arriver, dans une carrière, et la peer-review est là pour ça, mais ça doit vous poser question&nbsp;: êtes-vous allé trop vite, parce qu&rsquo;être le premier à publier était plus important que d&rsquo;être sûr de vos résultats&nbsp;? Avez-vous tellement cru en votre hypothèse que vous vous êtes aveuglé tout seul&nbsp;? Avez-vous subi des pressions (auquel cas, il est temps pour vous de songer à changer de labo)&nbsp;? Avez-vous triché parce qu&rsquo;avoir cette publi, c&rsquo;était nécessaire pour avoir un poste, une promotion, des crédits&nbsp;? Il est généralement possible de rectifier le tir, mais vous êtes sur la mauvaise pente et il va falloir vous poser les bonnes questions.</p>
<p>Pour ma part, je tends à penser qu&rsquo;on est un bon chercheur lorsqu&rsquo;on a l&rsquo;amour de la vérité et la volonté de faire avancer le monde ensemble, sans marcher sur la tête des autres pour avoir sa place, sans chercher à casser le travail des autres pour conserver son hégémonie et sans étouffer les nouvelles pousses parce qu&rsquo;avoir raison devient plus important que savoir ce qui est vrai. Il y a malheureusement des chercheurs comme ça. Je donnerai pas de noms mais j&rsquo;ai une liste. Et chaque année, elle s&rsquo;allonge…</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec la Saint Paul (oui, c&rsquo;était ma fête cette semaine, et mon saint patron a pour attribut le livre et l&rsquo;épée, je trouve que ça me va bien). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, autant que possible, restez chez vous. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur <a href="https://www.facebook.com/TheDendrobateDoctor/?ref=page_internal">la page Facebook du Docteur</a>.</p>
        </div>)
  }