
    import { Article } from "@/atoms/Article";
    
    export const Article20240121LechodeslabosMetadata = {"tags":["covid"],"title":"l'Écho des Labos - 21 janvier 2024","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Gascogne, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2024-01-21","layout":"layouts/post.njk"}
    
    export const Article20240121Lechodeslabos : Article = ({
      className, title, img, KissKissBankBank, Facebook
    }) => {
      return (<div className={className}>
          { img("https://www.webedcafe.com/extern/program_media/mededcafe.com/2016/hpv_q1_2016//figure_images/Stoler/w714/Slide44w714.PNG",  "voir figcaption en-dessous",  "width:100%" ) }
<dl>
<dt>Description &#x26; Traduction</dt>
<dd>l'éditrice<br />
Scène
</dd>
<dd>Un docteur vaccine une fillette<br />
Dialogue
</dd>
<dd>Docteur: "Les critiques clament que la vaccination contre la papilomavirus humain ménera à la promiscuité".<br />
La fillette (sarcastique): "Je suis tellement exité là maintenant"<br />
Crédits
</dd>
<dd>Ann Telnaes
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Gascogne, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Ceux qui me suivent depuis un certain temps auront remarqué, avec le nombre de fakes qu&rsquo;on a traité ensemble ici, la désinformation est rarement idéologiquement neutre. Cela veut dire qu&rsquo;on fait rarement croire à d&rsquo;autres des choses fausses sans raison (je parle à des gens à l&rsquo;origine de l&rsquo;intox, pas de Tata Micheline qui a cliqué sur «&nbsp;partager&nbsp;» sans comprendre ce qu&rsquo;elle lisait) et des raisons, la plupart du temps, il y en a deux&nbsp;: l&rsquo;argent (les gars ont un truc à vendre, ou bien ça va les faire élire à un poste bien rémunéré, ou ça va couler un de leurs concurrents) et l&rsquo;idéologie (les gars veulent faire adhérer les autres à leur vision du monde, qu&rsquo;elle soit politique, religieuse, philosophique, ce qu&rsquo;on veut). C&rsquo;est pour ça que, si j&rsquo;estime que suivre l&rsquo;argent est parfois une bonne piste pour comprendre qui raconte n&rsquo;importe quoi et pourquoi, je pense que ça ne doit jamais être la seule hypothèse et que le fameux «&nbsp;qui te paye&nbsp;?&nbsp;» n&rsquo;est pas la panacée. Il y a des gens qui n&rsquo;ont rien à gagner à la désinformation, si ce n'est que les autres adoptent leur vision du monde, et comme ils sont convaincus et apparemment désintéressés, ce sont peut-être les plus dangereux.</p>
<p>La dernier rapport de la Fondation des Femmes (que vous pouvez lire ici https://fondationdesfemmes.org/fdf-content/uploads/2024/01/Mobilisation-anti-avortement-en-France-FINAL.pdf) pointe ainsi une importante vague de désinformation menée par les anti-IVG, où à peu près tous les types possibles de fakes y passent&nbsp;: vidéo truquée de «&nbsp;souffrance&nbsp;» de fœtus avorté (on passera sur le fait que le cortex cérébral ne commence sa spécialisation que vers 6 mois et qu&rsquo;aucune IVG n&rsquo;est jamais pratiquée à ce stade), témoignage bidon de jeunes filles «&nbsp;absolument trop fières&nbsp;» de ne pas avoir eu recours à l&rsquo;IVG suite à une grossesse lycéenne (au vu de la crédibilité des histoires, je pense que ce sont les mêmes qui ont vu leur mère mourir trois fois du vaccin Covid), fausses informations médicales (sur le risque de stérilité en particulier, mais aussi sur la procédure d&rsquo;IVG), études bidons avec une méthodologie digne de l&rsquo;IHU publiées dans des journaux obscurs, sites Internet usurpant l&rsquo;identité d&rsquo;associations respectables, faux groupes de parole, fausses hotlines, bref, la totale. La cartographie dressée par le rapport montre également que les relais de ces comptes et contenus de désinformation sur l&rsquo;IVG sont des relais également actifs lorsqu&rsquo;il faut propager d&rsquo;autres types de désinformation, en particulier sur la guerre en Ukraine ou la vaccination HPV. Bref, prudence à tous, ce n&rsquo;est même pas parce que quelqu&rsquo;un n&rsquo;a rien à vous vendre qu&rsquo;il ne cherche pas à vous faire prendre des vessies pour des chandeliers en cristal à cinquante branches style rococo. Y en a dont c&rsquo;est plus que le métier&nbsp;: c&rsquo;est la vocation.</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>Aujourd&rsquo;hui en 2024, plusieurs milliers de patients souffrent toujours de Covid long, avec des formes et des degrés de gravité divers. Si la maladie a beaucoup touché des patients déjà identifiés comme à risque, elle a aussi coupé les jambes à des profils plus inattendus, en particulier jeunes et actifs. Il se passe donc quelque chose, sans lien avec une pathologie préexistante, qui entraîne une réaction invalidante de l&rsquo;organisme. Et une équipe pense avoir enfin mis le doigt dessus.</p>
<p>Le papier est publié dans la prestigieuse revue Science (ici https://www.science.org/doi/10.1126/science.adg7942) et est considéré comme suffisamment important pour qu&rsquo;un éditeur se farcisse la rédaction d&rsquo;un résumé avant l&rsquo;introduction, ce qui est relativement rare (disons comme une pluie de grenouille, ça s&rsquo;est déjà vu, c&rsquo;est documenté et on a même des explications très satisfaisantes pour ça, n&rsquo;empêche que ça surprend quand même). Et contre toute attente, ce sont des Suisses qui ont fait la percée (j&rsquo;ai rien contre les Suisses, j&rsquo;ai de très bons amis Suisses, mon camarade de lutte contre les pénibles Steve Claude est Suisse, mon cher Biostatisticien est Suisse d&rsquo;adoption, n&rsquo;empêche que c&rsquo;est pas sur eux qu&rsquo;on aurait parié vu le fric que tout un tas de pays a mis sur la table pour trancher cette question). Alors, on se calme tout de suite, on parle de percée, pas de solution encore.</p>
<p>Les dernières avancées sur le sujet pointaient un problème inflammatoire, une condition qui ferait que le système immunitaire n&rsquo;arrive pas à revenir à son état de base, et que l&rsquo;inflammation endommage de nombreux tissus et organes, à l&rsquo;origine de la grande variété de symptômes. Mais on manquait d&rsquo;un marqueur spécifique, d&rsquo;un truc qui puisse se voir dans une prise de sang et permette de dire à un patient «&nbsp;c&rsquo;est ça que vous avez&nbsp;», voire même qui permette de remonter à la source et de fermer les valves. Pour l&rsquo;équipe Suisse, et contre toute attente, ça n&rsquo;est pas l&rsquo;immunité acquise qui déconne, c&rsquo;est l&rsquo;immunité innée. Je vais faire un (ultra turbo speed) bref rappel des immunités&nbsp;: l&rsquo;immunité innée est celle qui n&rsquo;apprend jamais (elle fait du délit de faciès et cogne sur tout ce qu&rsquo;elle trouve moche, elle est la première ligne de défense des tout-petits et la dernière face aux wannabe cancers avant qu&rsquo;ils deviennent des vraies tumeurs, puisque les cellules ont des têtes qui lui reviennent pas)&nbsp;; l&rsquo;immunité acquise est celle qui se spécialise pour se défendre (donc ça prend du temps la première fois, mais c&rsquo;est beaucoup plus efficace la suivante, et c&rsquo;est sur elle que repose la vaccination, puisqu&rsquo;en l&rsquo;entraînant dans une fausse première attaque, on la prépare à l&rsquo;avance pour une éventuelle seconde rencontre). Je reprends donc, contre toute attente, alors qu&rsquo;on pensait que c&rsquo;était l&rsquo;immunité acquise qui «&nbsp;apprenait mal&nbsp;» ce qu&rsquo;était le Covid et continuait à taper sur des trucs qui lui ressemblait une fois qu&rsquo;il n&rsquo;y a plus rien, c&rsquo;est en fait une partie de l&rsquo;immunité innée qui montre des signes anormaux. Cette partie s&rsquo;appelle le système du complément (et je vais vraiment pas rentrer dans les détails), elle a des tas de protéines impliquées dans son fonctionnement (et je vais VRAIMENT pas rentrer dans les détails) dont certaines de la famille C5b qui ont la particularité de pouvoir s&rsquo;intégrer dans la membrane des cellules et induire la mort cellulaire. Et ce sont elles que les chercheurs ont retrouvées en large surnombre chez les patients atteints de Covid long.</p>
<p>Encore une fois, au risque de décevoir ceux d&rsquo;entre vous qui sont concernés ou qui accompagnent un proche malade, cette découverte nous offre la possibilité d&rsquo;avoir un biomarqueur sanguin, on est sur de la détection. Mais elle ne nous donne pas (encore) la compréhension du mécanisme à l&rsquo;origine de l&rsquo;emballement du système du complément (c&rsquo;est un grand sensible, à peu près tout depuis le gluten jusqu&rsquo;au produit de contraste des scanners en passant par certaines levures ou l&rsquo;amiante, ou encore l&rsquo;herpès voire même l&rsquo;hémoglobine elle-même peut le déclencher…) ni de traitement potentiel, car il s&rsquo;agit, comme toujours dès qu&rsquo;il est question d&rsquo;immunologie, d&rsquo;un beau bordel pour savoir qui régule quoi et comment. Mais la recherche avance.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Oncologie</strong>&nbsp;: je me suis beaucoup moquée, à raison, de Christian Schaller. Je dis «&nbsp;à raison&nbsp;» car si vos reins suent sang et eau (et urine, du coup, surtout) chaque jour que Lemmy fait pour filtrer les déchets de votre organisme et les foutre dehors, c&rsquo;est pas pour que vous décidiez de tout lui renvoyer dans les néphrons chaque matin parce qu&rsquo;un illuminé du bocal avec un tambour premier prix vous a convaincu que boire son pipi au petit déj entre deux tartines c&rsquo;était tendance. On se retrouve parfois à dire des évidences, mais par les temps qui courent, il faut parfois s&rsquo;y résoudre&nbsp;: le pipi, c&rsquo;est pas bon à manger. Sauf si vous êtes un nanorobot autopropulsé en route pour aller nucléariser un cancer. Et je ne pensais jamais avoir à écrire une phrase comme ça dans ma vie. Développons donc un peu. L&rsquo;incroyable piste de la semaine, c&rsquo;est la mise au point par une équipe espagnole de nanorobots capables de se propulser seuls pour remonter les canaux urinaires afin de s&rsquo;agglomérer sur une tumeur de la vessie et de délivrer un traitement à base d&rsquo;isotope radioactif de l&rsquo;iode. Ce traitement est déjà utilisé pour traiter des cancers très localisés, comme celui de la thyroïde, mais il faut pouvoir accéder à la tumeur, ce qui peut être compliqué avec la vessie. Aujourd&rsquo;hui, le traitement principal repose sur la chirurgie suivie par chimiothérapie, mais hélas entre 30% et 70% des patients rechutent dans les 5 ans. L&rsquo;idée de l&rsquo;équipe est donc d&rsquo;envoyer via les voies naturelles une armada de nanorobots, qui se propulseraient tous seuls et iraient donc délivrer le précieux traitement. Avec quelle énergie les faire fonctionner, vue la petite taille des machines&nbsp;? En leur faisant manger le pipi dans lequel ils se déplacent (pardon le terme technique c&rsquo;est «&nbsp;absorber de l&rsquo;enzyme uréase via leur surface poreuse en silice pour alimenter une réaction chimique qui les propulse&nbsp;» mais de fait ils mangent du pipi). Les résultats des essais sur la souris (disponibles ici https://www.nature.com/articles/s41565-023-01577-y) montrent que non seulement les petits robots fonctionnent à merveille pour se déplacer et s&rsquo;accrocher à la tumeur, mais que ce traitement pourrait être particulièrement efficace puisqu&rsquo;une seule injection conduit à une réduction de 90% du volume de la tumeur. Si l&rsquo;équipe est enthousiaste, elle est aussi prudente, et va lancer une nouvelle phase d&rsquo;étude pour évaluer le taux de récidive à 5 ans de son traitement, lequel est pour l&rsquo;instant inconnu.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Pandémie</strong>&nbsp;: chez les chercheurs, les médecins et les vulgarisateurs, nous sommes nombreux à nous dire que nous avons eu de la chance avec le Covid. Ce n&rsquo;est pas sympa pour les milliers de personnes qui en sont morts ou qui vivent encore avec des séquelles, mais c&rsquo;est une vérité&nbsp;: on aurait pu tomber sur pire, bien, bien pire, et on était clairement pas prêts à faire face. Mais avons-nous appris&nbsp;? Serons-nous plus prêts lors de la suivante (car oui, suivante il y aura, il faut se faire une raison)&nbsp;? L&rsquo;entretien de National Geographic avec Paul Offit de la division des maladies infectieuses de l&rsquo;hôpital pour enfants de Philadephie (à lire ici https://www.nationalgeographic.fr/sciences/sante-publique-medecine-le-covid-a-teste-nos-limites-serons-nous-prets-pour-la-prochaine-pandemie) montre que le chemin est long et que la prochaine pandémie pourrait réussir à nous prendre autant par surprise que celle du Covid, mais aussi que nous avons pu tirer des leçons importantes de cette crise, et que, peut-être, elles feront la différence lors de la prochaine. Peut-être.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>HPV</strong>&nbsp;: sans grande surprise, les premiers résultats de la vaccination HPV, lancée au sein des collèges à la rentrée 2023, sont décevants. L&rsquo;objectif des 30% de collégiens vaccinés (établissements publics et privés sous contrat) fin 2023 n&rsquo;est clairement pas atteint et c&rsquo;est un euphémisme. Par exemple, la région Grand-Est est considérée comme «&nbsp;bonne élève&nbsp;» avec 7.486 vaccinés sur un objectif de … 19.311. Les causes sont multiples. D&rsquo;abord une campagne de désinformation massive de la part des antivax qui, commençant à se lasser du Covid, ont trouvé là un nouveau cheval de bataille. Ensuite, une opposition farouche des représentants religieux, qui ont particulièrement pesé sur les établissements privés confessionnels sous contrat, qui continuent à assimiler les HPV à des infections sexuellement transmissibles (on rappelle que c&rsquo;est la même famille que les verrues plantaires et c&rsquo;est aussi absurdement contagieux) qui ne s&rsquo;attraperaient pas lorsqu&rsquo;on se «&nbsp;comporte de manière respectable&nbsp;», mais qui ont aussi un impact sur les parents d&rsquo;élèves du public, lequel a dû faire face à plusieurs assignations et saisies de tribunaux de la part d&rsquo;associations de parents d&rsquo;élèves. Etonnamment, la Suède, dont on nous a rebattu les oreilles pendant la crise du Covid parce qu&rsquo;elle ne confinait pas, ne semble plus faire figure de modèle auprès des antitous, elle qui affiche fièrement une couverture vaccinale HPV de plus de 80%.</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Vaccination Covid</strong>&nbsp;: on a pas mal parlé ces temps-ci du nombre de morts imputables, rétrospectivement, aux traitements sortis de nulle part et en particulier l&rsquo;hydroxychloroquine. Mais on a pas assez parlé du nombre de morts évités, et en particulier par la vaccination. Une étude, chapeauté par l&rsquo;OMS (et dont le pré-print est disponible ici https://www.medrxiv.org/content/10.1101/2024.01.12.24301206v1) s&rsquo;est attelée à ce recensement, et elle a estimé que près d&rsquo;un million et demi de vies humaines ont été épargnées grâce à la vaccination massive dans le monde. Une nouvelle qui fait du bien.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>On reparle de Didier&nbsp;? Allez, on reparle de Didier&nbsp;! La semaine dernière quand on a évoqué le cas de Didier sur CNews, il s&rsquo;est passé plusieurs choses. La première, c&rsquo;est que j&rsquo;ai retrouvé l&rsquo;étude dont il parlait pour expliquer que le vaccin ARNm «&nbsp;produit des protéines inconnues&nbsp;» et que c&rsquo;est comme ça que «&nbsp;des lymphomes apparaissent&nbsp;» parce que ça «&nbsp;injecte de l&rsquo;ADN dans les ganglions&nbsp;» et, sans surprise, y a rien de tout ça dans le papier (allez vérifier par vous-même si le cœur vous en dit, c&rsquo;est là https://www.nature.com/articles/s41586-023-06800-3).</p>
<p>La seconde, c&rsquo;est que certains d&rsquo;entre vous sont venus en commentaires me raconter que en plus d&rsquo;expliquer que le vaccin filait des cancers mais n&rsquo;avait jamais rien changé à la mortalité, Didier s&rsquo;était aussi fendu d&rsquo;explications sur le fait que ni la ceinture ni les airbags n&rsquo;avaient jamais sauvé personne en voiture, c&rsquo;est le fait de mettre des radars et tout ça. Et ça me paraissait gros. Donc j&rsquo;ai voulu vérifier (des fois que, le bouche à oreille, une histoire un peu trop belle, tout ça). Je tombe donc sur un extrait d&rsquo;émission, et effectivement, le grand Didier, avec ses grands cheveux et sa grande gueule, est là en train de dire des grandes conneries (la ceinture, l&rsquo;airbag, la mortalité, tout comme on me l&rsquo;avait annoncé en commentaire). Bon. Mais je me méfie quand même. A notre époque, les fakes ça court les rues, même les deep fakes. Donc je veux remonter plus loin, bon, sur quelle chaîne ça passe ce truc&nbsp;? Dans le coin en haut à gauche, je vois «&nbsp;GPTV&nbsp;» et je hausse un sourcil. Est-ce que ce serait pas un canular, comme pour «&nbsp;Chat GPT TV&nbsp;» un truc pour dire que c&rsquo;est fait par une IA&nbsp;? Et bien, mes amis, j&rsquo;aurais préféré&nbsp;! En fait, pas du tout, c&rsquo;est l&rsquo;acronyme de «&nbsp;Géopolitique Profonde TV&nbsp;», et si vous pensez que c&rsquo;est la même douille qu&rsquo;avec les QAnon et leur état profond, vous avez eu le nez creux. La chaîne Youtube, c&rsquo;est juste le festival de la saucisse, avec des trucs sur «&nbsp;la GPA du Nouvel Ordre Mondial&nbsp;», «&nbsp;Poutine l&rsquo;homme providentiel&nbsp;» (si vous pensez que celui-là a mal vieilli, il est du 8 janvier 2024…), «&nbsp;Frexit&nbsp;: l&rsquo;union des patriotes&nbsp;» et j&rsquo;en passe. Vraiment, faut passer des trucs comme ça. Et si vous vous demandez «&nbsp;mais sérieux qui a le temps de monter un truc pareil&nbsp;», la réponse est apparemment le même mec que celui qui tient Radio Courtoisie. Au moins le mec est constant dans ses délires, on va dire&nbsp;?</p>
<hr />
<h3 id="point-méthode-de-la-semaine-léthique-à-quel-prix"><a href="#point-méthode-de-la-semaine-léthique-à-quel-prix">POINT MÉTHODE DE LA SEMAINE&nbsp;: l&rsquo;éthique à quel prix&nbsp;?</a></h3>
<p>Lorsqu&rsquo;on parle d&rsquo;éthique, les choses semblent souvent posées comme évidentes&nbsp;: il y a le bon chercheur, celui qui respecte les procédures d&rsquo;éthique, et il y a le mauvais chercheur, qui s&rsquo;en fout et ne respecte rien. Evidemment, c&rsquo;est plus compliqué que ça, et notamment parce que l&rsquo;éthique se paye parfois cher. Comment dénoncer des mauvaises pratiques quand votre contrat est précaire&nbsp;? Comment refuser de nettoyer un peu trop les résultats quand celui qui vous le demande est un ponte du domaine&nbsp;? Comment résister à la pression de celui qui finance votre projet de recherche d&rsquo;être inclus comme co-auteur de l&rsquo;article alors qu&rsquo;il a strictement rien foutu sur le projet&nbsp;? C&rsquo;est compliqué. Pour vous illustrer ça, je vais vous parler d&rsquo;un cas, a priori bien moins grave, qui m&rsquo;est arrivé il y a quelques temps.</p>
<p>Fin décembre, je reçois enfin les rapports de peer-review d&rsquo;un de mes articles. Il y a une forme de légende dans le milieu de la recherche qui veut que Reviewer 1 est toujours enthousiaste et demande peu de corrections, que Reviewer 2 est toujours mal luné et demande soit le rejet pur et simple soit des corrections majeures, et que, quand il n&rsquo;est pas possible de les concilier, arrive Reviewer 3 qui est exigeant mais juste et dont les demandes sont les plus utiles pour le papier. Mes rapports ne dérogeaient pas à cette règle. Au bout de quelques jours, je m&rsquo;attèle aux corrections&nbsp;: Reviewer 1 a quelques demandes faciles à remplir, Reviewer 2 a pris mon article pour mettre directement trouzmille commentaires désagréables dessus (si, si, quand on dit texto d&rsquo;une partie «&nbsp;il n&rsquo;y a ni modèle ni méthode et ça n&rsquo;est pas comme ça qu&rsquo;on fait de la science en fait&nbsp;», on est désagréable) et Reviewer 3 a envoyé un document séparé avec, notamment, une proposition de changement d&rsquo;ordre des parties. Et tandis que je parcours les documents, je tombe, soudain, sur un nom.</p>
<p>Ceci n&rsquo;est pas censé arriver. La revue par les pairs est faite en double aveugle&nbsp;: les auteurs ne connaissent pas les reviewers et les reviewers ne connaissent, a priori, pas les auteurs (je dis a priori parce que le Reviewer 2 désagréable, dans un passage, me prend de haut en me genrant au féminin… mon hypothèse est qu&rsquo;il s&rsquo;est servi de références que j&rsquo;ai mises en disant que les résultats préliminaires de l&rsquo;étude étaient déjà publiés pour faire une recherche sur ma tronche, mais passons). Afin que les reviewers puissent, sans pression aucune, dire ce qu&rsquo;ils pensent d&rsquo;un article, il est important que leurs noms n&rsquo;arrivent jamais jusqu&rsquo;à l&rsquo;auteur. Et pourtant, il était là. Car Reviewer 2, maintenant identifié comme Rodrigo (il s&rsquo;appelle pas vraiment Rodrigo, c&rsquo;est pour la narration), a mis tellement de commentaires partout sur mon article que ceux-ci sont passés en format réduit et qu&rsquo;il a dû oublié d&rsquo;en anonymiser un. Et donc là, dans la marge, traîne un magnifique «&nbsp;Cette figure est sans intérêt, elle peut disparaître. Signé Rodrigo&nbsp;». Et là, on a un problème. Mon éditeur a un problème parce qu&rsquo;il aurait dû vérifier ce qu&rsquo;il m&rsquo;envoie et que maintenant la confidentialité de la peer-review n&rsquo;est plus garantie. Moi j&rsquo;ai un problème, parce que je ne peux pas faire comme si je n&rsquo;avais rien vu, mais si je le signale à mon éditeur, il peut décider d&rsquo;annuler tout le processus et de recommencer, et je n&rsquo;ai aucune envie de faire prendre 6 mois dans la vue à mon article, en plus du fait que trouver des reviewers dans ma spé est dur en maudit. Et Rodrigo a un problème, parce que quand on insulte des collègues, il faut être vraiment certain qu&rsquo;ils puissent jamais vous retrouver en conférence…</p>
<p>Tandis que je réfléchis sur la bonne chose à faire (en même temps que j&rsquo;avance les corrections), un autre problème se pose à moi&nbsp;: le nom de Rodrigo m&rsquo;est absolument inconnu, or nous sommes dans une petite spécialité. Est-ce que je dis le contraire d&rsquo;un papier à lui et c&rsquo;est pour ça qu&rsquo;il est tout fâché&nbsp;? Je demande à Google Scholar&nbsp;: aucun résultat, le mec n&rsquo;a publié aucun papier de sa vie, rien. Et là, on a un plus gros problème&nbsp;: on ne peut pas demander d&rsquo;être relecteur à quelqu&rsquo;un qui n&rsquo;est pas compétent dans le domaine, or, pour ça, il faut avoir publié. Mais le journal est sérieux, et je sais qu&rsquo;il ne ferait pas une erreur pareille. Et là j&rsquo;ai un doute. Je demande à Google tout court et mon doute se confirme. Rodrigo est un simple pauvre étudiant, dans un département avec plein de professeurs influents. Et Rodrigo, tout mal dégrossi qu&rsquo;il soit, est probablement une victime&nbsp;d&rsquo;un schéma bien connu&nbsp;: son encadrant est sollicité pour une peer-review, il accepte, et refile le boulot à un étudiant qui n&rsquo;a pas le choix de refuser. Et qui donc commet des bourdes en commentant des papiers. L&rsquo;option «&nbsp;je peux aussi juste fermer ma gueule&nbsp;» devient de moins en moins tenable.</p>
<p>J&rsquo;ai fini par décider de d&rsquo;abord faire les corrections demandées par les 3 reviewers, de renvoyer le papier puis d&rsquo;écrire dans la foulée à l&rsquo;éditeur. Afin de lui expliquer le problème, je prends soin de lui préciser le nom que j&rsquo;ai vu apparaître dans mon document. Je lui explique aussi qu&rsquo;il pourra vérifier dans la version corrigée de l&rsquo;article que j&rsquo;ai adressé les commentaires de chacun de la même façon, et que cette brèche n&rsquo;a pas eu d&rsquo;impact sur mon travail. Et je croise les doigts pour que ça n&rsquo;annule pas tous mes efforts de correction. Hier j&rsquo;ai reçu sa réponse. L&rsquo;article va être traité normalement (j&rsquo;ai eu de la chance) et il confirme que Rodrigo n&rsquo;est pas la personne à qui l&rsquo;article était adressé, qu&rsquo;il est étrange que son nom apparaisse et qu&rsquo;une enquête va être diligentée, et qu&rsquo;enfin les procédures vont être revues pour réduire le risque de ce genre de bourdes à l&rsquo;avenir. J&rsquo;ai eu de la chance cette fois-ci. J&rsquo;ai fait ce qu&rsquo;il fallait, je pense, mais j&rsquo;ai quand même besoin d&rsquo;avoir de la chance pour ne pas le payer.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec le retour de mon éditeur (il a beaucoup de pouvoir mais pas celui-là). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, aimez la science, la vraie, et ceux qui la font. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
        </div>)
  }