
import {FC} from "react";

export const Article20240128LechodeslabosMetadata = {"tags":["covid"],"title":"l'Écho des Labos - 28 janvier 2024","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Panache, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche et de ceux qui la font.","date":"2024-01-28","layout":"layouts/post.njk"}

export type Article20240128LechodeslabosProps = {className?: string, title: string, img: (...args: unknown[]) => string, KissKissBankBank: (...args: unknown[]) => string, Facebook: (...args: unknown[]) => string}

export const Article20240128Lechodeslabos : FC<Article20240128LechodeslabosProps> = ({
  className, title, img, KissKissBankBank, Facebook
}) => {
  return (<div className={className}>
      { img("https://cdn.mos.cms.futurecdn.net/gPmGqqRrdyB5PM9Z9dsGBP.jpg",  "voir figcaption en-dessous",  "width:100%" ) }
<dl>
<dt>Crédits</dt>
<dd>Sheneman
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Panache, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche et de ceux qui la font.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Vous avez peut-être entendu parler cette semaine d&rsquo;une nouvelle annonce incroyable (comme à peu près chaque semaine depuis 3 ans…) concernant la terrible dangerosité du vaccin Covid et venant tout droit des USA. Si ça vous a échappé, rassurez-vous, vous avez pas loupé grand-chose. Pour ceux qui ont suivi, la polémique oppose le Dr Joseph Lapado (qui est le «&nbsp;general surgeon&nbsp;» c&rsquo;est grosso modo le chef du département de la santé de Floride) à… tout le reste des autorités sanitaires (et là vous vous dites que ça part pas bien). La raison&nbsp;? Le fait que les vaccins à ARNm feraient courir des risques «&nbsp;invraisemblables&nbsp;» aux patients et que le discours rassurant serait «&nbsp;trompeur&nbsp;». Bon. On attend toujours l&rsquo;hécatombe qu&rsquo;on nous promet depuis janvier 2021, mais il pourrait avoir raison sur des risques sous-estimés, donc de quoi que cause donc le monsieur&nbsp;?</p>
<p>La réponse n&rsquo;est pas très dure à trouver pour la simple et bonne raison qu&rsquo;il tient le même discours alarmiste depuis l&rsquo;automne 2022, et que donc tout a largement été débunké depuis. Mais on va le faire quand même.<br />
Déjà, quel est le risque dont il est question&nbsp;? Il s&rsquo;agit d&rsquo;une potentielle augmentation du risque de troubles cardiaques mortels chez les moins de 40 ans, conclusion d&rsquo;une analyse sur laquelle Lapado s&rsquo;était déjà appuyé pour recommander une non-vaccination des jeunes adultes contre le Covid en octobre 2022. Bon. C&rsquo;est un risque sérieux, et comme dirait quelqu&rsquo;un, si c&rsquo;est vrai, c&rsquo;est très grave. Mais est-ce que c&rsquo;est vrai&nbsp;? Que vaut l&rsquo;analyse en question&nbsp;?<br />
Sur quelles preuves le monsieur se base-t-il&nbsp;? Et déjà, on va se heurter à un problème&nbsp;: il ne se base pas sur une analyse des données, il se base sur la cinquième version d&rsquo;une analyse des données, après avoir refusé de faire publier les quatre premières, qui elles montraient que c&rsquo;était le Covid et non le vaccin qui augmentait le risque de trouble cardiaque grave chez les jeunes adultes. Et ces premières versions étaient très catégoriques «&nbsp;Le risque associé à une infection à la COVID-19 dépasse clairement tout risque potentiel associé au vaccin à ARN.&nbsp;» En l&rsquo;occurrence on parle d&rsquo;un facteur 10 chez les 18-24 ans et 5 chez les 25-39 ans. C&rsquo;est du sérieux. Mais alors, pourquoi la dernière analyse est-elle différente&nbsp;? Est-ce que des données nouvelles ont changé l&rsquo;interprétation faite de la balance bénéfice-risque&nbsp;?</p>
<p>QUE POUIC. Lapado a tout simplement supprimé des passages de l&rsquo;analyse avant de l&rsquo;envoyer pour publication. A l&rsquo;origine, on avait un soupçon, au point que le vérificateur général du ministère de la Santé avait ouvert une enquête dès le mois suivant sur des soupçons de falsifications suite à une dénonciation anonyme (probablement un membre de l&rsquo;équipe d&rsquo;analyse qui a reconnu tout de suite la supercherie), mais comme ce n&rsquo;étaient que des soupçons, la plainte est classée faute de preuve. Mais depuis cette année, c&rsquo;est une certitude&nbsp;: grâce à la loi de la Floride sur l&rsquo;accès aux documents gouvernementaux, des journalistes ont mis la main sur les versions antérieures du rapport et les ont soumises à l&rsquo;avis d&rsquo;épidémiologistes (c&rsquo;est très rocambolesque mais <a href="https://www.tampabay.com/news/health/2023/04/07/florida-surgeon-general-covid-19-vaccine-study-heart-problems-men/">c&rsquo;est documenté ici</a>) et ceux-ci sont unanimes&nbsp;: «&nbsp;omission inexplicable&nbsp;», «&nbsp;comportement irresponsable&nbsp;», «&nbsp;mensonge pur et simple&nbsp;», les chercheurs contactés n&rsquo;ont pas mâché leurs mots devant l&rsquo;ampleur de la mascarade. Lapado, lui, continue d&rsquo;expliquer sur tous les réseaux qu&rsquo;il a raison, peu importe que le rapport ait été manipulé ou non.</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>La biologie en général et la médecine en particulier ne sont pas particulièrement des choses ragoûtantes lorsqu&rsquo;on est pas habitués. Donc on va y aller doucement, et je vais déjà préparer le terrain&nbsp;: ce que vous allez lire est un progrès important et une bonne nouvelle, faut pas crier. Mais vous pouvez vomir si vous y tenez.</p>
<p>Des chirurgiens de Pennsylvanie (<a href="https://www.pennmedicine.org/news/news-releases/2024/january/first-successful-external-liver-perfusion-using-a-porcine-liver">le communiqué est ici</a>) ont réussi à transplanter un foie de porc génétiquement modifié sur un humain en état de mort cérébral, et ce foie a fonctionné à merveille pendant 72h. Voilà, on respire un grand coup et on y va par pallier.<br />
«&nbsp;Seigneur Dieu, pour quoi foutre&nbsp;?&nbsp;» Bien sûr, il ne s&rsquo;agit pas de proposer des solutions définitives, mais l&rsquo;idée est de pouvoir proposer une greffe de secours aux malades en attente d&rsquo;un donneur, le temps que leur organe arrive. En France, chaque année, entre 500 et 1.000 malades meurent sur la liste d&rsquo;attente des greffes, après avoir espéré un organe qui n&rsquo;est jamais venu. Il s&rsquo;agit donc d&rsquo;une avancée pour offrir un sursis à des patients qui n&rsquo;ont plus aucune autre option.<br />
«&nbsp;Mais pourquoi un porc OGM&nbsp;? On peut pas prendre un vrai cochon&nbsp;?&nbsp;» On pourrait, mais on parle quand même d&rsquo;une transplantation interespèce, et il faut savoir que le premier risque de la greffe, c&rsquo;est le rejet (le système immunitaire décrète que ce truc est pas à lui et il le fout dehors, et tant pis si y a plus rien pour filtrer le sang derrière, c&rsquo;est pas son problème). Les modifications génétiques sont juste là pour essayer d&rsquo;améliorer la compatibilité avec l&rsquo;humain receveur. Après, vous pouvez trouver pas éthique qu&rsquo;on modifie le génome d&rsquo;un animal pour notre intérêt à nous, et c&rsquo;est votre droit. Mais dans ce cas, vous allez devoir vous opposer à à peu près tous les traitements anticancers, immunologiques et bien d&rsquo;autres, qui sont aussi testés sur des rats génétiquement modifiés. Ce n&rsquo;est pas un truc fait à la légère, mais ça n&rsquo;est pas spécialement une nouveauté on va dire.<br />
«&nbsp;Mais pourquoi tu greffes un mort&nbsp;? C&rsquo;est pas de lui rendre son foie qui va faire qu&rsquo;il est moins mort&nbsp;?&nbsp;» Non, de fait. En revanche, il n&rsquo;y a plus de risque pour lui. Un patient en état de mort cérébrale ne peut pas mourir plus, il est mort. En revanche le reste de son corps fonctionne normalement, et donc on peut observer en conditions réelles comment le foie et l&rsquo;organisme interagissent, et donc comment la greffe prendrait sur un patient qu&rsquo;on essaierait d&rsquo;empêcher de mourir. Il va de soi que, pour une procédure de ce type, on ne prend pas un mourant au pif à l&rsquo;hôpital et que la famille est impliquée dans le processus.<br />
«&nbsp;Ok… mais trois jours c&rsquo;est pas grand-chose, c&rsquo;est beaucoup d&rsquo;effort juste pour ça, non&nbsp;?&nbsp;» Ca le serait si l&rsquo;expérience avait échoué au bout de 72h, ce qui n&rsquo;est pas le cas. L&rsquo;expérience a parfaitement fonctionné jusqu&rsquo;à ce qu&rsquo;elle soit interrompue par l&rsquo;équipe médicale, parce que c&rsquo;était la durée à laquelle la famille avait consenti, mais pas plus. C&rsquo;est suffisant pour que les chercheurs aient obtenu les infos qu&rsquo;ils voulaient et que les médecins aient observé ce qu&rsquo;ils avaient à observer, tout en ne prolongeant pas inutilement l&rsquo;attente des proches, qui ont sans doute besoin de récupérer le corps et de faire leur deuil en paix, peut-être, on peut l&rsquo;espérer, un peu aidés par la pensée que le dernier acte de leur défunt a été d&rsquo;aider la recherche à sauver d&rsquo;autres malades dans le futur.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Troubles menstruels</strong>&nbsp;: depuis le temps qu&rsquo;on attendait des vraies études complètes sur les potentiels troubles menstruels liés à la vaccination Covid, les résultats qui viennent de tomber (<a href="https://www.epi-phare.fr/rapports-detudes-et-publications/vaccins-covid%e2%80%9119-saignements-menstruels/">et qui sont à lire ici</a>)sont plus que bienvenus. Mais je crains qu&rsquo;ils ne contentent pas celles et ceux (mais surtout celles ce coup-ci) qui cherchent un responsable à leurs maux. Est-ce que le vaccin contre le Covid génère des troubles menstruels&nbsp;? Oui et non (ça commence bien…). Il apparait que le signal ne concerne que les vaccins à ARNm, déjà, et surtout que la dose initiale. Aucun signal n&rsquo;apparait après les doses de rappel. Bon, et ces troubles alors, ils existent bien&nbsp;? Tout à fait, il existe un surrisque de saignements abondants pouvant conduire à des arrêts de travail ou des hospitalisations, mais l&rsquo;étude montre qu&rsquo;on est face à un phénomène très rare, de l&rsquo;ordre de 8 cas par million de femmes. Ok, mais quid des cas plus légers alors&nbsp;? L&rsquo;étude n&rsquo;a pas été capable de mettre en évidence un quelconque lien de causalité entre les troubles plus légers et la vaccination. En langage clair, ça veut dire que ces troubles n&rsquo;arrivent pas plus après une vaccination qu&rsquo;ils n&rsquo;arrivent dans la population générale, c&rsquo;est a priori simplement le timing qui donne cette impression. Du coup, on parle de séquelles ou pas, cette fois-ci&nbsp;? Toujours pas, l&rsquo;étude met également en évidence que les troubles ne durent que 1 à 3 mois (alors pour les concernées, je me doute que c&rsquo;est long, mais ça ne s&rsquo;appelle pas une séquelle). Si vous avez toujours des problèmes passé ce délai, vous êtes selon toute vraisemblance atteinte de quelque chose qui n&rsquo;a rien à voir et il est important d&rsquo;investiguer réellement. S&rsquo;accrocher à cette hypothèse ne fera que retarder votre diagnostic.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Maladie de Charcot</strong>&nbsp;: vous vous souvenez de la fois où je vous ai raconté comment on avait remonté la piste d&rsquo;une incroyable épidémie de Charcot dans un tout petit bourg de montagne jusqu&rsquo;à des pas très bons cueilleurs de champignons qui avaient tous mangé la pas très bonne fausse morille&nbsp;? Une nouvelle enquête de ce genre est en train de démarrer dans la Somme, après que 5 habitants de la même rue (mais non-apparentés, ce qui est important car la maladie a aussi un facteur génétique) aient contracté la maladie de Charcot (ou SLA). Alors, champignon aussi ce coup-là&nbsp;? Apparemment pas, mais la fausse morille n&rsquo;est pas la seule responsable identifiée de la SLA, puisqu&rsquo;en 2017, une forte concentration de la maladie (2.4 fois supérieure à celle attendue en population générale) autour de l&rsquo;étang de Thau, dans l&rsquo;Hérault, avait pu être attribuée à une toxine produite par des cyanobactéries vivant sur le lac (les fameuses «&nbsp;algues vertes&nbsp;», ce qui est un nom débile puisque plein d&rsquo;algues qui n&rsquo;ont fait de mal à personne sont vertes). Au début, la piste alimentaire (via la consommation de fruits de mer contaminés) avait été étudiée, avant qu&rsquo;on s&rsquo;aperçoive que la toxine était particulièrement volatile et était donc inhalée par les sportifs pratiquant des activités sur l&rsquo;eau. Dans la Somme, pour l&rsquo;instant, le mystère demeure.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Diarrhées</strong>&nbsp;: je dirais bien qu&rsquo;on est dedans jusqu&rsquo;au cou, mais la blague est facile. Une nouvelle étude britannique (<a href="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011714">à lire ici</a>) a mis en évidence un lien significatif entre dérèglement climatique (en particulier augmentation des températures et de l&rsquo;humidité) et la propagation de Campylobacter, une charmante saloperie qui se loge dans le tube digestif et provoque maux de tête, fièvre, douleur abdominale et, disons-le franchement, diarrhée de niveau volcanique pendant 3 à 6 jours. Assez pour tuer un enfant, une personne âgée ou n&rsquo;importe qui n&rsquo;ayant pas accès à des solutions de réhydratation. Mais ça va plaire à Didier Relou, ça se traite à l&rsquo;azithromycine.</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Paludisme</strong>&nbsp;: après le Cap-Vert, le Cameroun envisage bien de devenir le prochain pays d&rsquo;Afrique ayant réussi à éradiquer le paludisme de son territoire. Ce lundi, le pays a ainsi lancé la première campagne de vaccination de masse contre le paludisme, avec un produit du groupe GSK. Testé dans trois projets pilotes au Malawi, Kenya et Ghana, le vaccin avait provoqué une baisse spectaculaire de la mortalité (13% de réduction, toutes causes confondues, chez les enfants en âge de recevoir le vaccin, ainsi qu&rsquo;une réduction qualifiée de substantielle par les soignants des formes graves du paludisme ainsi que des hospitalisations). Le Cameroun paye chaque année un lourd tribut au paludisme, avec près de 3.5 millions de cas et près de 2.500 morts.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Vous savez pourquoi je suis pas sur Twitter (oui, je sais, il faut dire X maintenant, mais c&rsquo;est comme pour le Covid, où il fallait soi-disant dire «&nbsp;la&nbsp;», je fais ce que je veux, et une langue dans laquelle des mots arrivent à être masculin au singulier et féminin au pluriel n&rsquo;a aucune leçon à me donner sur la manière dont je m&rsquo;en sers. Même que je dis UN tractopelle, d&rsquo;abord)&nbsp;? Bref, outre le fait que je suis manifestement quelqu&rsquo;un d&rsquo;un peu sanguin et prompt aux digressions, je ne suis pas sur Twitter parce que les dramas me filent de la tension, donc j&rsquo;ai un mot du médecin pour me tenir loin de cette poubelle. Mais là, je vais devoir vous en parler un peu quand même.</p>
<p>Dans une espèce de crossover nul qu&rsquo;on attendait pas (ou alors avec horreur, façon Alien VS Predator), on assiste depuis cette semaine à une coalition entre Raoult et la clique de l&rsquo;IHU (Chabrière en première ligne) et Booba (le rappeur, pas le petit ourson qui roule et glisse sur la blanche neige). Raoult l&rsquo;appelle «&nbsp;petit frère&nbsp;» (les gars de IAM se retourneraient dans leurs tombes s&rsquo;ils étaient morts), Booba se balade avec un tee-shirt «&nbsp;Complotiste&nbsp;» et dit aux chercheurs qui contredisent Saroumane de «&nbsp;bien fermer leur gueule&nbsp;». Ça pourrait prêter à rire. Sauf que Booba, il a 6 millions de followers. 6 millions de comptes qu&rsquo;il est en train de jeter sur les journalistes (Julien Pain en premier), les médecins (en particulier Jérôme Barrière, cancérologue, qui a eu le malheur de rappeler que, non, on ne peut pas contracter Creutzfeldt-Jakob suite à vaccin, et encore moins en mourir en 2022 suite à vaccin de 2021, la maladie mettant des années à se développer) et bien sûr tous les vulgarisateurs qui ont le malheur de se dresser sur sa route (typiquement Cogito Ergo Seum l&rsquo;a tagué sur sa publi, je serai pas surprise que ses DM aient pris feu…).</p>
<p>Ces gens-là sont menacés, en toute impunité, harcelés en masse, traités d&rsquo;assassin et trainés dans la boue en public, pour simplement faire leur travail avec intégrité. Alors, si vous êtes sur ces réseaux, si vous le pouvez&nbsp;:</p>
<ol>
<li>ne relayez jamais les posts de ceux qui racontent n&rsquo;importe quoi, ça leur donne de la popularité et donc de la puissance</li>
<li>signalez systématiquement tous les commentaires et les contenus menaçants, injurieux, harcelants</li>
<li>pensez à manifester votre soutien à ces gens-là, ils savent que la majorité silencieuse est derrière eux, mais savoir ne suffit pas, ils ont besoin de vous entendre pour tenir le coup, ils s&rsquo;accrochent à l&rsquo;énergie que vous leur donnez, alors donnez-en plein</li>
<li>ne rentrez pas en guerre ouverte avec les followers agressifs, ça ne sert à rien, mais si ce sont des contacts à vous qui partagent des contenus de ce type, et que vous pouvez les raisonner, intervenez.</li>
</ol>
<p>Au début de la pandémie, le journaliste Julien Hernandez publiait dans Futura un article intitulé «&nbsp;2020 en France, les scientifiques sont-ils en sécurité&nbsp;?&nbsp;» En 2024, il est clair que la réponse est Non.</p>
<hr />
<h3 id="point-méthode-de-la-semaine-comment-faire-un-bon-vulgarisateur-quand-on-est-chercheur"><a href="#point-méthode-de-la-semaine-comment-faire-un-bon-vulgarisateur-quand-on-est-chercheur">POINT MÉTHODE DE LA SEMAINE&nbsp;: Comment faire un bon vulgarisateur quand on est chercheur&nbsp;?</a></h3>
<p>Il s&rsquo;agit d&rsquo;une question fort intéressante, qui est en réalité multiple. C&rsquo;est quoi la «&nbsp;bonne vulgarisation&nbsp;»&nbsp;? C&rsquo;est quoi être un «&nbsp;bon vulgarisateur&nbsp;»&nbsp;? Comment on transmet le goût de notre spécialité à un public qui en a peut-être même jamais entendu parler&nbsp;? Est-ce qu&rsquo;il reste du café&nbsp;?<br />
Comme c&rsquo;est une question intéressante, il y a des gens intéressants que se la posent, comme mon très cher collègue Canadien Andrew Creighton. Et comme les gens qui se la posent sont aussi un peu bizarres, ils peuvent faire des trucs bizarres, genre me la poser à moi.<br />
Ça donne cette très chouette interview pour le journal du département de sémiotique de Tartu, Hortus Semioticus, et je vous laisse la découvrir ici (<a href="https://www.hortussemioticus.ut.ee/blog/features/popularizing-science-an-interview-with-pauline-suzanne-delahaye/">pour ceux qui parlent la langue d&rsquo;Elton John</a>), parce que finalement j&rsquo;ai déjà fait le travail une fois, j&rsquo;ai un peu la flemme de le refaire.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas et ses conséquences non plus visiblement. En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, aimez la science, la vraie, et ceux qui la font. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}