
import {FC} from "react";

export const Article20240303LechodeslabosMetadata = {"tags":["covid"],"title":"l'Écho des Labos - 3 mars 2024","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Caudeau, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2024-03-03","layout":"layouts/post.njk"}

export type Article20240303LechodeslabosProps = {className?: string, title: string, img: (...args: unknown[]) => string, KissKissBankBank: (...args: unknown[]) => string, Facebook: (...args: unknown[]) => string}

export const Article20240303Lechodeslabos : FC<Article20240303LechodeslabosProps> = ({
  className, title, img, KissKissBankBank, Facebook
}) => {
  return (<div className={className}>
      { img("https://zotero.hypotheses.org/files/2019/06/citation-warning.png",  "voir figcaption en-dessous",  "width:100%" ) }
<dl>
<dt>Crédits</dt>
<dd>Zotero(?)
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Caudeau, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Les Fakes ne sont pas juste perchés, mensongers, antiscience, dangereux et particulièrement viraux, ils sont aussi une véritable mine d&rsquo;or pour ceux qui savent les exploiter. Vous savez, les premiers à hurler en boucle à la face du pauvre monde «&nbsp;Qui vous paye&nbsp;?!&nbsp;» (la réponse étant généralement «&nbsp;la recherche publique, et elle le fait très mal&nbsp;»). Aussi incroyable que cela puisse paraître, ces gens-là ont gagné un fric fou en répandant leur propagande antivax, et c&rsquo;est le Washington Post qui a levé le lièvre en inspectant les déclarations fiscales (<a href="https://www.washingtonpost.com/nation/2024/02/21/covid-misinformation-earnings/">vous pouvez lire leur enquête ici</a>) de quatre grandes organisations antivax américaines.</p>
<p>La première, Children's Health Defense, fondée et dirigée par Robert Kennedy Jr. (oui, oui, le mec qui disait au congrès qu&rsquo;il avait les preuves que le vaccin donnait l&rsquo;autisme, que la pandémie était un prétexte pour installer la 5G et qui fait partie d&rsquo;un noyau de 12 personnes à l&rsquo;origine à elles seules des deux tiers de la désinformation en ligne concernant la pandémie selon l&rsquo;étude du Center for Countering Digital Hatred… un type formidable quoi), a multiplié ses gains par 8 entre la période pré-pandémie et 2022, approchant les 24 millions de dollars, ce qui a permis à son adorable dirigeant d&rsquo;envisager de financer sa campagne présidentielle, ainsi qu&rsquo;à l&rsquo;organisation d&rsquo;étendre son activité de désinformation sur la moitié du pays.<br />
La deuxième, Informed Consent Action Network, fondée et dirigée par le type qui a produit Vaxxed, le documentaire qui défend la thèse d&rsquo;Andrew Wakefield, le fameux médecin corrompu qui a inventé le lien entre vaccination ROR et autisme (un autre type bien quoi), a quant à elle multiplié ses gains par 4, pour un joli pactole de plus de 13 millions de dollars, que l&rsquo;organisation souhaite utiliser en harcèlement judiciaire contre toute forme d&rsquo;obligation vaccinale.<br />
Les deux autres, Front Line Covid-19 Critical Care Alliance et America's Frontline Doctors, ont la particularité d&rsquo;avoir été créées pendant la crise du Covid, et sont passées entre leur première année d&rsquo;existence et 2022 de 1 million à 21 millions de dollars de recettes, juste en racontant n&rsquo;importe quoi sur les réseaux et en facturant un rein des consultations en visio durant lesquelles elles prescrivaient du shampooing pour mouton à des patients parfois déjà très gravement atteints.</p>
<p>Point intéressant, parce que je sais que la chose est toujours un poil sensible comme sujet, les journalistes ont également eu accès à la liste des donateurs. La moitié des très gros dons (plus de 100.000 dollars) viennent de «&nbsp;fonds conseillés par les donateurs&nbsp;», des fonds qui distribuent anonymement l&rsquo;argent d&rsquo;ultra-riches en fonction d&rsquo;une ligne directrice de projets et de valeurs. Parmi ces fonds, deux d&rsquo;entre eux ont versé au moins un million de dollars à au moins trois des quatre organisations citées, qui étaient donc considérées en adéquation avec leurs valeurs directrices, puisque les fonds sont « dédiés à l'avancement des valeurs bibliques ou conservatrices »… Vous ferez ce que vous voudrez de cette info.</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>Ce n&rsquo;est pas une découverte très réjouissante, même si elle n&rsquo;est guère surprenante. Depuis plusieurs années déjà, on tend à découvrir des microplastiques absolument partout, à des endroits où on ne pensait pas en trouver, qui seraient encore épargnés, mais il semblerait qu&rsquo;il n&rsquo;y ait plus de zones non-polluées, ni haut dans les airs, ni dans les glaces, ni au fond des mers, et ni même, maintenant, au cœur du placenta humain. L&rsquo;étude, réalisée par des chercheurs du Nouveau-Mexique (<a href="https://academic.oup.com/toxsci/advance-article-abstract/doi/10.1093/toxsci/kfae021/7609801">et disponible ici</a>), a testé 62 placentas et TOUS sans exception ont été positifs aux microplastiques. Les concentrations sont variables (de 6.5 à 720 microgrammes de plastique par gramme de tissu placentaire, avec une moyenne entre 128 et 146) et les compositions variées (plus de la moitié étant du polyéthylène, le truc qui sert à faire les bouteilles en plastique, suivi par le PVC et le nylon).</p>
<p>L&rsquo;impact sur la santé humaine, en particulier celle du fœtus, est inconnu, mais la technique développée par l&rsquo;équipe à l&rsquo;origine de l&rsquo;étude devrait permettre une détection et une numération beaucoup plus efficace, et donc faire avancer la recherche sur le sujet. C&rsquo;est également l&rsquo;occasion pour moi de rappeler, en cette époque de délires New-Age en tout genre, que découvrir des déchets toxiques dans le placenta, c&rsquo;est un peu normal, car c&rsquo;est un organe qui sert d&rsquo;interface mais également de filtre. Et que donc, consommer le placenta après la naissance, c&rsquo;est aussi intelligent que manger le sac de son aspirateur («&nbsp;oui, mais les autres femelles mammifères, elles le mangent bien, elles, c&rsquo;est naturel…&nbsp;» Oui, et elles mangent aussi le caca de leurs petits et parfois celui qui boite un peu trop, autre chose&nbsp;?).</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Effets secondaires du vaccin Covid</strong>&nbsp;: une nouvelle étude de pharmacovigilance est sortie, une étude massive (99 millions de personnes, excusez du peu, on est tout simplement sur une des plus grosses études de sécurité sur la vaccination jamais réalisée au monde, je veux plus jamais entendre après ça des gens dire que ce vaccin-là est moins testé que les autres…) qui est le produit du travail d&rsquo;un consortium de 8 pays (dont la France, cocorico), mais une étude que personne n&rsquo;a lue avant de se mettre à hurler que «&nbsp;Omondieuyadeseffetssecondairesonlesavaitviteunnouveaunuremberg&nbsp;» (alors qu&rsquo;<a href="https://www.sciencedirect.com/science/article/pii/S0264410X24001270">elle est disponible en libre accès ici</a>). Bon. Du coup, quoi qu&rsquo;elle dit l&rsquo;étude&nbsp;? Déjà l&rsquo;étude s&rsquo;est penchée sur trois vaccins différents (ceux de Pfizer, de Moderna et d&rsquo;AstraZeneca), donc évidement on a des variables selon le produit utilisé, mais je vais essayer de vous faire un truc concis. Les auteurs confirment la présence des «&nbsp;signaux&nbsp;» déjà repérés par la pharmacovigilance, sur les cas de myocardites ou de paralysie de Bell par exemple. Mais sur l&rsquo;immense majorité des cas, leurs conclusions sont assez claires «&nbsp;In this study including more than 99 million people vaccinated against SARS-CoV-2, the risk up to 42 days after vaccination was generally similar to the background risk for the majority of outcome. » (Dans cette étude incluant plus de 99 millions de personnes vaccinées contre le SARS-CoV-2, le risque jusqu&rsquo;à 42 jours après la vaccination était en général similaire au risque observé en population générale pour la majorité des manifestations et de leurs issues.) En effet, si le vaccin représente bel et bien un surrisque pour certains troubles…le Covid aussi, et sa force de frappe en population générale tend à niveler les troubles représentés et leur fréquence. Toutefois, les auteurs disent bien «&nbsp;pour la majorité&nbsp;» et non pas pour tous les cas. Deux effets secondaires surnagent en effet de l&rsquo;étude, dont le surrisque n&rsquo;est pas compensé par le surrisque lié à la maladie elle-même, et je sais que ça va décevoir les conspis qui font une fixette dessus, mais aucun n&rsquo;est lié à Pfizer. Il s&rsquo;agit d&rsquo;un surrisque de syndrome de Guillain-Barré et de thrombose veineuse cérébrale, tous les deux liés à l&rsquo;administration de la première dose d&rsquo;AstraZeneca, disparaissant lors des doses suivantes. Les chercheurs rappellent qu&rsquo;il s&rsquo;agit de données déclaratives, sur lesquelles ils ont peu de prise, mais globalement, l&rsquo;étude vient renforcer ce dont on se doutait déjà. Donc je comprends vraiment pas pourquoi tout le monde crie.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Pénurie de médicaments</strong>&nbsp;: l&rsquo;ANSM déclare la situation «&nbsp;catastrophique&nbsp;». Les signalements pour rupture de stocks sont en hausse de plus de 30% en 2023 par rapport à 2022, soit près de 130% de plus qu&rsquo;en 2021. Les causes sont multiples, comme toujours, mais beaucoup pointent l&rsquo;Inde et la Chine, premiers fabricants mondiaux, qui refusent d&rsquo;honorer notamment les commandes d&rsquo;amoxicilline alors que leurs industriels ont 3 mois de stocks d&rsquo;avance. Les associations de médecins et de pharmaciens appellent à une relocalisation d&rsquo;urgence de la production en Europe.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p>Vous savez c&rsquo;est quoi une pleurésie&nbsp;? Et bien jusqu&rsquo;en début de semaine, je savais pas non plus. C&rsquo;est excessivement nul, 0/5, ne recommande absolument pas.</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Ebola</strong>&nbsp;: c&rsquo;est rare d&rsquo;avoir une bonne nouvelle concernant Ebola, alors on en profite. La dernière étude de Epicentre, la branche épidémiologie de Médecins sans Frontières (à lire ici https://www.thelancet.com/journals/lanxxx/article/PIIS1473-3099(23)00819-8/abstract) montre que la vaccination contre Ebola permet de diminuer de moitié la létalité de la maladie (c&rsquo;est-à-dire, à quel point les personnes infectées meurent). L&rsquo;impact de cette vaccination sur la mortalité (qui n&rsquo;est pas la létalité, on rappelle, ça c&rsquo;est à quel point il y a des victimes dans la population lors d&rsquo;une épidémie, donc avec la létalité, la transmission et d&rsquo;autres facteurs qui jouent) est encore à l&rsquo;étude, mais les données précédentes sur la transmission sont encourageantes.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Didier. Ecoute, Didier, tu n&rsquo;as pas besoin d&rsquo;en arriver là. Je vais pas te dire que ça peut encore s&rsquo;arranger, c&rsquo;est pas vrai, mais il y a encore moyen de faire du damage control, tu vois, ce n&rsquo;est pas obligé que ça finisse comme ça.<br />
Alors évidemment, quand t&rsquo;expliquais que t&rsquo;étais le plus grand expert du monde alors que t&rsquo;étais déjà interdit de publication dans certaines des plus grandes revues du domaine, on ricanait un peu, c&rsquo;est vrai. Puis quand tu t&rsquo;es tellement enfoncé avec tes études pourries qui avaient tellement de red flags partout que c&rsquo;est un miracle que l&rsquo;IHU ait pas été prise d&rsquo;assaut par une horde de taureaux fous, on s&rsquo;est franchement foutu de ta gueule, j&rsquo;avoue. Et puis, quand on a vu que les rétractations commençaient à tomber, mais que tu continuais sur ta lancée, on a commencé à se poser des questions. Déjà, 9 de tes articles ont été rétractés, et c&rsquo;est comme si ça t&rsquo;avait donné des ailes, maintenant tu vas sur des plateaux parler des «&nbsp;civilisations de rats polis avec les humains&nbsp;» (je jure que c&rsquo;est vrai, je m&rsquo;en suis étouffée avec mon café) et des «&nbsp;poulets qui composent 70% des tous les oiseaux de la Terre&nbsp;» (je me suis pas étranglée parce que j&rsquo;étais en train d&rsquo;éponger le café, mais vu qu&rsquo;on compte 52 milliards de poules et, selon les études, entre 50 et 400 milliards d&rsquo;oiseaux sauvages, sans compter les autres oiseaux domestiques ou liminaires, de toute façon c&rsquo;est non). Maintenant, y en a 66 de plus sur la sellette, des que les éditeurs sont prêts à faire sauter si tu réponds pas très sérieusement aux questions que les reviewers te posent Didier, et on sait, toi, moi et le monde, que tu ne le feras pas. Et derrière ça, il y a plus de 450 études avec de graves problèmes d&rsquo;éthique, qui, elles aussi, commencent à être sous enquête, et, elles aussi, elles risquent de finir dans l&rsquo;incinérateur de la science.<br />
Alors c&rsquo;est ça ton plan, Didier&nbsp;? «&nbsp;Vous verrez, dans un siècle, on parlera encore de moi&nbsp;», «&nbsp;Moi, je suis numéro 1, je reste numéro 1&nbsp;»… Tu vas nous faire ce coup-là, vraiment&nbsp;? Graver ton nom dans l&rsquo;histoire de la science comme le chercheur le plus rétracté de toute l&rsquo;histoire de la recherche, le pire fraudeur que le monde académique est produit&nbsp;? C&rsquo;est la France qui sera en haut de ce classement de la honte&nbsp;? Tu fais chier, Didier…</p>
<hr />
<h3 id="point-méthode-de-la-semaine-la-rétractation"><a href="#point-méthode-de-la-semaine-la-rétractation">POINT MÉTHODE DE LA SEMAINE&nbsp;: La rétractation</a></h3>
<p>La rétractation ne doit pas, ne devrait pas être vue comme une punition. Aujourd&rsquo;hui, c&rsquo;est pourtant le cas, et c&rsquo;est triste. En science, on devrait pouvoir dire «&nbsp;j&rsquo;ai écrit ce papier il y a 20 ans, je me suis rendu compte que j&rsquo;avais tort, je voudrais qu&rsquo;il soit rétracté pour que les gens ne soient pas induits en erreur&nbsp;».</p>
<p>Car rétracté, ce n&rsquo;est pas censuré, ou annulé (comme le disait feu Montagnier qui avait décidément rien compris à rien). Le papier reste en ligne, il n&rsquo;est pas mis sous le tapis, vous ne pouvez pas cacher le fait que vous vous êtes trompé, mais il est barré d&rsquo;un grand «&nbsp;retracted&nbsp;» qui ne laisse aucun doute et qui fait que vos collègues ne peuvent plus être induits en erreur, mais quand même comprendre comment quelqu&rsquo;un qui vous citait à une époque antérieure a pu arriver à ses conclusions, par exemple.</p>
<p>Mais pour l&rsquo;instant, rétracté ça revient encore à être puni chez les chercheurs. Ça veut dire qu&rsquo;on a fait un travail tellement mauvais que c&rsquo;est comme s&rsquo;il n&rsquo;existait pas. Evidemment, cela dépend des circonstances&nbsp;: si c&rsquo;est l&rsquo;auteur qui a demandé la rétractation, il passe juste pour un guignol. S&rsquo;il a été rétracté par l&rsquo;éditeur, pire encore, si c&rsquo;est après une affaire publique, c&rsquo;est la marque de l&rsquo;infamie et, parfois, la fin de sa carrière. Parfois c&rsquo;est mérité. Si vous voulez connaître des gens pour qui c&rsquo;était très très mérité, des gens qui pour l&rsquo;instant coiffent encore Didier sur le podium du plus gros fraudeur de l&rsquo;Histoire, je vous recommande la chaîne de Bobby Broccoli (se prendre au sérieux, c&rsquo;est pour les experts avec 180 de QI), en particulier ses vidéos sur Hwang Woo Suk, l&rsquo;homme qui a fait croire qu&rsquo;il arrivait à cloner des humains (<a href="https://youtu.be/ett_8wLJ87U?si=NjVEyVOCBi-XX2id">Partie 1/2 ici</a>) et sur Jan Hendrik Schön, l&rsquo;homme qui a fait semblant de sauver la loi de Moore (<a href="https://youtu.be/nfDoml-Db64?si=HiG_vvjUqO54mEiY">Partie 1/3 ici</a>).</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec le débordement intempestif des ruisseaux et rivières du coin (en général, c&rsquo;est même plutôt le contraire…). En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, aimez la science, la vraie, et ceux qui la font. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}