
import { Article } from "@/atoms/Article";

export const Article20240211LechodeslabosMetadata = {"tags":["covid"],"title":"l'Écho des Labos - 11 février 2024","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Vézère, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2024-02-11","layout":"layouts/post.njk"}

export const Article20240211Lechodeslabos : Article = ({
  className, title, img, KissKissBankBank, Facebook
}) => {
  return (<div className={className}>
      { img("https://www.lemonde.fr/blog/vidberg/files/2008/04/075-viagra.1207170906.gif",  "voir figcaption en-dessous",  "width:100%" ) }
<dl>
<dt>Crédits</dt>
<dd>Vidberg
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Vézère, je suis le Dendrobate<br />
Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19<br />
et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>C&rsquo;est un fake bien standard avec lequel on commence cette semaine, mais il semble absolument increvable, alors il faut bien faire quelque chose (quelque chose qui est peut-être l&rsquo;équivalent de vider l&rsquo;océan à la petite cuillère mais bon…). Alors qu&rsquo;il devient possible désormais de dresser des bilans, incomplets certes, mais de plus en plus solides, de la pandémie de Covid, une vieille rengaine tourne dans les milieux conspi, antivax, antitout, ou simplement dans l&rsquo;opposition systématique&nbsp;: l&rsquo;épidémie n&rsquo;était qu&rsquo;une hystérie collective sans fondement. On l&rsquo;a beaucoup entendue durant le cœur de la crise, on l&rsquo;entend encore beaucoup, le problème, c&rsquo;est que plus les bilans deviennent précis, moins cette affirmation a du sens.</p>
<p>La première évaluation concerne le nombre de morts. Si le chiffre officiel, c&rsquo;est-à-dire, des morts qui ont été dument déclarés comme morts du Covid, tourne autour de 7 millions dans le monde (ce qui est déjà pas mal, hein, c&rsquo;est comme si on avait exterminé le Nicaragua tout entier), le consensus scientifique est désormais ferme sur le fait que le chiffre est très largement sous-estimé. L&rsquo;épidémiologiste Antoine Flahault (<a href="https://atlantico.fr/article/decryptage/le-covid-une-hysterie-collective-sans-fondement-voila-ce-que-disent-les-chiffres-de-la-mortalite-avec-4-ans-de-recul-malades-patients-personnes-a-risque-deces-morts-vaccin-grippe-espagnole-vaccination-immunite-traitement-antoine-flahault">en interview ici</a> au sujet de la comparaison Covid vs grippe espagnole) donne en exemple le fait que, de décembre 2022 à mars 2023, le gouvernement chinois n&rsquo;a déclaré que 60.000 décès, là où les analyses de mortalité et les données remontées des hôpitaux estiment les morts sur cette période proches du million et demi, soit une sous-déclaration d&rsquo;un facteur 25. Les études les plus récentes parlent d&rsquo;entre 25 et 30 millions de morts de 2020 à 2023.</p>
<p>La seconde évaluation concerne le fait que le Covid n&rsquo;est pas un problème derrière nous, et qu&rsquo;il continue à faire des victimes en nombre important. Certes, entre la vaccination, l&rsquo;immunité post-infection, le meilleur traitement des cas graves et des soins intensifs qui respirent un peu, sa létalité n&rsquo;est plus que de 1 mort pour 1000 malades. Mais paradoxalement, sa forte contagiosité et son évolution par «&nbsp;vagues&nbsp;», avec risque de saturation hospitalière, fait que sa mortalité absolue demeure importante même avec une faible létalité, du fait de sa capacité à toucher un grand nombre de personnes. Sur le dernier trimestre de 2023, la maladie a continué à provoquer un excédent de mortalité dans le monde, réclamant tout de même environ 700.000 vies.</p>
<p>«&nbsp;Oui mais la grippe aussi, elle tue&nbsp;» Oui, aussi. 10.000 morts chaque hiver à peu près. Mais bizarrement, cet argument n&rsquo;est jamais sorti pour inciter à une meilleure couverture vaccinale contre la grippe ou pour encourager le port du masque dès qu&rsquo;on est un peu malade. C&rsquo;est presque comme si c&rsquo;était une fausse excuse, vous trouvez pas&nbsp;?</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>Cette semaine c&rsquo;est une découverte mêlant psychiatrie et électricité dont je vais vous parler, et les deux ont une histoire compliquée. S&rsquo;il y a un passif difficile voire carrément abusif de l&rsquo;usage de l&rsquo;électricité en psychiatrie, les dernières avancées dans le domaine permettent d&rsquo;envisager une nouvelle collaboration plus mesurée, plus respectueuse des patients et surtout plus efficace. Le cas dont je parle aujourd&rsquo;hui est également intéressant parce qu&rsquo;il est un exemple de comment faire ses «&nbsp;propres recherches&nbsp;» correctement.</p>
<p>Tout commence en 2016 lorsque Amber Pearson, 26 ans, consulte pour de sévères crises d&rsquo;épilepsie. Les crises sont si sévères et invalidantes qu&rsquo;il est décidé, deux ans plus tard, de procéder à l&rsquo;ablation d&rsquo;une petite zone du cerveau pensée être responsable des crises. Cela s&rsquo;appelle une cortectomie, et c&rsquo;est une opération tentée chez les patients résistants aux traitements. Malheureusement, ça n&rsquo;a pas l&rsquo;effet espéré et l&rsquo;épilepsie d&rsquo;Amber continue de s&rsquo;aggraver. Il est donc décidé de tenter la stimulation cérébrale profonde, qui consiste à placer une électrode à l&rsquo;intérieur du cerveau pour que celle-ci envoie des impulsions électriques dans une zone bien précise, identifiée comme à l&rsquo;origine des crises. L&rsquo;opération d&rsquo;Amber se passe bien et la fréquence ainsi que l&rsquo;intensité de ses crises chutent drastiquement, lui permettant un retour à une vie quasiment normale.</p>
<p>Et là vous allez me dire «&nbsp;mais dis donc la grenouille, l&rsquo;épilepsie, c&rsquo;est pas de la psychiatrie, c&rsquo;est de la neurologie&nbsp;!&nbsp;» et vous aurez raison. Mais l&rsquo;histoire ne s&rsquo;arrête pas là. Car Amber a un second problème&nbsp;: elle souffre de troubles obsessionnels compulsifs (TOC), un trouble psychiatrique qui oblige le patient à répéter les mêmes actions sans pouvoir s&rsquo;en empêcher, allant par exemple, dans le cas d&rsquo;Amber, à se laver les mains jusqu&rsquo;au sang tous les jours à force de les frotter. Et constatant à quel point son implant cérébral lui change la vie, Amber fait ses «&nbsp;propres recherches&nbsp;»&nbsp;: ne serait-il pas possible de stimuler électriquement aussi la zone qui l&rsquo;oblige à laver ses mains 50 fois par jour&nbsp;? Amber épluche les bases de données de recherche et s&rsquo;aperçoit qu&rsquo;il y a eu plusieurs projets pilotes qui ont montré qu&rsquo;il était possible d&rsquo;améliorer la condition des patients atteints de TOC chez qui les traitements médicamenteux échouaient par électrostimulation ou électrochocs. Elle compile 20 ans de recherche sur le sujet et, à son rendez-vous de suivi, elle soumet aux médecins une proposition de changement de paramètres de son appareil, afin qu&rsquo;il fasse double-emploi. Amber ayant fait un état de l&rsquo;art très complet sur le sujet, les médecins sont intéressés, bien qu&rsquo;aucun appareil n&rsquo;ait jamais été conçu pour traiter deux problèmes en même temps. Ils décident de tenter de mettre au point un tel dispositif. En 2019, l&rsquo;appareil d&rsquo;Amber est modifié et un suivi rigoureux commence. 5 ans plus tard, les résultats tombent (<a href="https://www.cell.com/neuron/fulltext/S0896-6273(23)00747-X">et ils sont à lire là</a>)&nbsp;: l&rsquo;épilepsie et les TOC sont désormais suffisamment sous contrôle pour offrir une vie quasiment normale à la patiente. L&rsquo;université de Pennsylvanie a donc décidé de se lancer dans la démocratisation de ce type d&rsquo;implant. 2.5 millions d&rsquo;Américains seraient atteints de TOC, dont 40% seraient résistants aux traitements existants actuellement.</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Thérapie génique</strong>&nbsp;: avec l&rsquo;arrivée des vaccins à ARN, il y a eu la grande panique de la «&nbsp;modification du génome&nbsp;». Mais modifier le génome n&rsquo;est ni facile, ni généralisable aisément, ni même faisable parfois sur l&rsquo;ensemble de l&rsquo;organisme. Et ce même lorsque cela est souhaitable. Une équipe de l&rsquo;hôpital pour enfants de Philadelphie vient ainsi de réussir à rendre l&rsquo;ouïe de manière quasiment complète à un jeune garçon. Aissam, 11 ans, souffrait de surdité profonde congénitale, une surdité liée plus précisément dans son cas à une mutation du gène responsable de l&rsquo;otoferline, une protéine qui joue un rôle central dans la transformation des stimuli sonores en informations chimiques traitables par le cerveau. Totalement sourd, Aissam a de surcroît grandi dans une communauté pauvre du Maroc, où il n&rsquo;a pas eu d&rsquo;éducation adaptée et n&rsquo;a jamais pu apprendre une langue des signes. Il communiquait avec un code personnel avec sa famille, seules personnes à pouvoir le comprendre. En injectant dans la cochlée un virus porteur d&rsquo;une copie fonctionnelle du gène défectueux chez Aissam, les chercheurs ont réussi à modifier quelques cellules localement, qui se sont mises à produire la protéine manquante. Assez pour que la transmission entre l&rsquo;oreille et le cerveau se rétablisse. Les résultats de l&rsquo;expérimentation (<a href="https://www.chop.edu/news/children-s-hospital-philadelphia-performs-first-us-gene-therapy-procedure-treat-genetic-hearing">annoncés ici</a>) soulèvent toutefois de nombreuses questions. Tout d&rsquo;abord, même s&rsquo;il entend parfaitement bien, Aissam ne sera pour autant sans doute jamais capable de parler, cette capacité n&rsquo;ayant pas été stimulée à temps, ce qui implique que les thérapies de ce type doivent cibler en priorité les enfants de moins de 5 ans. Ensuite, la mutation de Aissam est rare, et il n&rsquo;est pas dit que l&rsquo;exploit soit reproductible sur d&rsquo;autres affections entrainant le même problème. Enfin, si le traitement est bénéfique au petit Aissam, que son handicap coupait énormément du monde, il interroge aussi sur la possibilité, la volonté ou l&rsquo;éthique du «&nbsp;traitement&nbsp;» du handicap, notamment dans les pays qui ont un niveau d&rsquo;éducation assez élevé et où les enfants peuvent apprendre une langue des signes dès leur plus jeune âge. Beaucoup de réflexions en perspective.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Alzheimer</strong>&nbsp;: les causes de la maladie ne sont pas encore bien comprises. Une part est génétique, une part est sans doute environnementale, mais c&rsquo;est la première fois qu&rsquo;une cause médicamenteuse est mise en évidence. Les médecins londoniens ont en effet affirmé (<a href="https://francais.medscape.com/voirarticle/3611026?form=fpf">dans un papier publié ici</a>) avoir mis en évidence 5 cas d&rsquo;Alzheimer précoces directement reliés à la prise d&rsquo;hormone de croissance entre 1958 et 1985. Or, à cette époque, l&rsquo;hormone de croissance est produite à partir de glandes de personnes décédées. La thérapie est interrompue en 1985 après que des lots contaminés aux prions aient déclenché une maladie de Creutzfeld-Jacob chez trois patients américains, mais ce n&rsquo;était manifestement pas les seuls dégâts causés. Les patients londoniens pourraient quant à eux souffrir de la transmission de protéine béta-amyloïde, impliquée dans la dégénérescence neuronale. Les travaux sont en cours d&rsquo;examen plus poussés par le reste de la communauté scientifique.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Culture scientifique</strong>&nbsp;: Alain Fisher, le président de l&rsquo;Académie de Médecine, sort un livre sur la prévention en médecine. Je ne sais pas ce qu&rsquo;il vaut, mais il y fait une place importante à un constat alarmant&nbsp;: la science en France va mal. Rare pays d&rsquo;Europe à stagner en termes de développement de la recherche, fuite des cerveaux et réduction sur la scène internationale, rémunération en moyenne inférieure d&rsquo;un quart comparée à ses voisins, mais surtout grave méconnaissance, aussi bien par les politiques que par le grand public, de la science et du monde de la recherche, qui permet à une culture anti-scientifique de se répandre, de prospérer et de vendre. Bref, on est pas sortis des ronces les enfants…</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>HPV</strong>&nbsp;: alors que la campagne chez nous patine sévèrement, d&rsquo;autres pays, bien plus en avance, nous permettent un point de comparaison, et il est encourageant. C&rsquo;est le cas de l&rsquo;Ecosse, qui a publié son rapport de suivi des cancers du col de l&rsquo;utérus, et le résultat (<a href="https://academic.oup.com/jnci/advance-article-abstract/doi/10.1093/jnci/djad263/7577291?redirectedFrom=fulltext&#x26;login=false">à lire ici</a>) est sans appel&nbsp;: chez les femmes nées entre 1988 et 1996 (donc celles qui ont pu commencer à recevoir le vaccin dans l&rsquo;adolescence), aucun cas de cancer n&rsquo;est survenu chez celles qui étaient complètement vaccinées. Aucun. Zéro. Nothing. Pas. Un. Seul. Alors, il y en a quand même, hein, c&rsquo;est grand l&rsquo;Ecosse, y a des gens. Mais aucun chez les femmes qui avaient pu être vaccinées dans leur adolescence de manière complète et en temps et heure. Aucun. Voilà. Des questions&nbsp;?</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>Quand j&rsquo;étais au lycée, on m&rsquo;avait raconté, comme une blague, qu&rsquo;à avoir inventé le Viagra avant Alzheimer, on allait avoir une génération de vieux avec des gaules incroyables mais qui auraient oublié quoi en faire (c&rsquo;est pas fin les ados, ça n&rsquo;a pas changé). SAUF QUE.</p>
<p>Sauf que en fait, peut-être que les deux sont liés. Et c&rsquo;est le très sérieux Unity College of London qui l&rsquo;a annoncé (<a href="https://www.ucl.ac.uk/news/2024/feb/erectile-dysfunction-drugs-linked-reduced-alzheimers-risk">là</a>), après que leurs recherches sur près de 270.000 hommes d&rsquo;en moyenne 59 ans, à qui on avait diagnostiqué un trouble de la fonction érectile, aient montré que, au bout de 5 ans, ceux qui prenaient des médicaments de type Viagra avaient 18% de risque en moins de développer la maladie d&rsquo;Alzheimer que ceux qui ne prenaient rien. Mieux encore, le lien était d&rsquo;autant plus significatif que les participants avaient reçu de nombreuses ordonnances et donc consommé de grandes quantités de pilule bleue durant l&rsquo;étude. Bien sûr, inutile de vous jeter sur les cachets juste pour prévenir la maladie, déjà parce que vous allez au-devant de journées très compliquées, et ensuite parce que plus d&rsquo;études sont nécessaires pour comprendre pourquoi ça marche, quel est le mécanisme derrière cette relation, et donc potentiellement créer des traitements préventifs adaptés.</p>
<p>Mais c&rsquo;est un peu drôle, quand on sait que le Viagra lui-même est né par accident. On testait un médicament pour le cœur, et puis en notant les effets secondaires, les chercheurs se sont dit qu&rsquo;ils tenaient un truc… Sérendipité, je crie ton nom.</p>
<hr />
<h3 id="point-méthode-de-la-semaine-faire-de-la-recherche-plus-simple"><a href="#point-méthode-de-la-semaine-faire-de-la-recherche-plus-simple">POINT MÉTHODE DE LA SEMAINE&nbsp;: Faire de la recherche plus simple</a></h3>
<p>Entre le livre de Fisher et mes petites aventures de candidatures dont je vous fais part de temps à autres, il est clair que la recherche semble démesurément compliquée, et qu&rsquo;il faut être fou pour vouloir travailler là-dedans. Pour la folie, on s&rsquo;en accommode, mais pour la lourdeur des procédures, il doit être possible de faire plus simple. Et parce que râler c&rsquo;est bien mais proposer des solutions, c&rsquo;est mieux, je voulais vous parler aujourd&rsquo;hui d&rsquo;une candidature qui se passe bien, parce que les institutions du pays aiment la transparence et le pragmatisme. Si si.</p>
<p>Après avoir passé du temps en Estonie, c&rsquo;est assez naturellement que je m&rsquo;intéresse à ce qui se fait chez le grand frère Finlande. Et voilà qu&rsquo;une annonce dans mon champ de compétence pour un contrat se présente. Si vous avez suivi mes précédentes pérégrinations, vous savez qu&rsquo;il est parfois nécessaire de rédiger plusieurs dizaines de pages et s&rsquo;y prendre des mois à l&rsquo;avance pour une candidature sur un projet de deux ans, réponse qui vous est apportée 6 mois plus tard. La deadline ici est proche, alors je regarde les pièces demandées.</p>
<ol>
<li>la preuve que j&rsquo;ai le droit de concourir à ce poste (ici, la photocopie de mon doctorat, mais si j&rsquo;étais en train de soutenir je pourrais fournir le rapport de mon école doctorale par exemple, niveau énergie ça me coûte deux clics)</li>
<li>un CV. Avec ou sans liste des publications&nbsp;? Sur combien de pages&nbsp;? Commenté, rédigé ou listé&nbsp;? Avec les expériences d&rsquo;enseignement ou juste la recherche&nbsp;? Autant de questions qu&rsquo;on se pose à chaque fois et qui font qu&rsquo;on fait autant de CV que de candidatures quasiment. Mais pas pour les Finlandais. Eux, ils mettent un lien vers un template, qui est le CV tel que défini par leur ministère de la recherche, et c&rsquo;est le même CV pour tout le monde, tout le temps, pour tous les postes.</li>
<li>une liste de publications. Ça aussi, c&rsquo;est généralement un truc à s&rsquo;arracher les cheveux, parce que ça change à chaque fois, c&rsquo;est pas clair, est-ce qu&rsquo;il faut ranger par langue, par type de publication, est-ce que la vulgarisation compte, les interviews dans le médias aussi …&nbsp;? Mais les Finlandais, ce genre de trucs, ça les saoule. Donc ils ont un template national unique pour ça aussi.</li>
<li>deux publications en rapport avec le poste concerné (ça c&rsquo;est des articles déjà publiés, donc on attache un PDF dans le mail et basta)</li>
<li>une lettre de motivation qui explique qui ont est, ce qu&rsquo;on fait, pourquoi on est un bon candidat sur ce poste et qui ils peuvent contacter pour avoir des références, le tout sur maximum 4 pages.<br />
Et c&rsquo;est tout. Et c&rsquo;est bouclé en un après-midi en fait. Mais comment ils sélectionnent avec ça&nbsp;?</li>
</ol>
<p>Déjà, de manière ouverte. L&rsquo;annonce contient une liste des critères qui vont être pris en compte dans l&rsquo;évaluation du candidat, précisant lesquels sont les plus importants. Ensuite de manière transparente. Lorsque la campagne se termine, ils envoient un mail de confirmation qu&rsquo;ils ont bien votre dossier, disent combien de candidatures ils ont reçu et à quelle date à peu près on peut espérer une réponse pour savoir si on est pris à un entretien ou pas. Qui plus est, de façon rapide. On parle d&rsquo;une deadline fin janvier pour une prise de poste en avril, parce que s&rsquo;ils recrutent, c&rsquo;est qu&rsquo;ils ont besoin de quelqu&rsquo;un et qu&rsquo;ils le veulent maintenant. Enfin, de manière fiable. A la date annoncée, j&rsquo;ai effectivement reçu une réponse disant que j&rsquo;étais convoquée à un entretien, mais également donnant un document plus complet (et confidentiel, donc pas dispo dans la candidature de base) pour permettre de préparer l&rsquo;entretien en annonçant à l&rsquo;avance les points sur lesquels ils vont poser les questions.</p>
<p>Le pragmatisme des Nordiques est terrifiant, le jour où ils désaoulent, ces mecs vont conquérir le monde. C&rsquo;est tellement facile que j&rsquo;en viens à me demander où est l&rsquo;arnaque. Et je crois qu&rsquo;en fait, l&rsquo;arnaque, c&rsquo;est les autres…</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec le mois de janvier, qui est un mois tout nul chaque année, ça ira mieux après. En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, aimez la science, la vraie, et ceux qui la font. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}