
import {FC} from "react";

export const Article20240114LechodeslabosMetadata = {"tags":["covid"],"title":"l'Écho des Labos - 14 janvier 2024","description":"Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Monbazillac, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.","date":"2024-01-14","layout":"layouts/post.njk"}

export type Article20240114LechodeslabosProps = {className?: string, title: string, img: (...args: unknown[]) => string, KissKissBankBank: (...args: unknown[]) => string, Facebook: (...args: unknown[]) => string}

export const Article20240114Lechodeslabos : FC<Article20240114LechodeslabosProps> = ({
  className, title, img, KissKissBankBank, Facebook
}) => {
  return (<div className={className}>
      { img("https://media.lelombrik.net/t/e4618c0889d42a664162c62676c73246/p/01.jpg",  "voir figcaption en-dessous",  "width:100%" ) }
<dl>
<dt>Crédits</dt>
<dd>Schwartz
</dd>
</dl>
<h2 id="-title-"><a href="#-title-">{ title }</a></h2>
<p>Aujourd'hui, c'est dimanche. Vous êtes donc bien sur Radio Monbazillac, je suis le Dendrobate Doctor et nous sommes ensemble pour faire l'état de la recherche sur l'épidémie de Covid-19 et le reste.</p>
<p>Si vous aimez la chronique, vous pouvez nous soutenir sur { KissKissBankBank( ) }.</p>
<p>Bienvenue à tous sur l'Echo des Labos.</p>
<hr />
<h3 id="fake-de-la-semaine"><a href="#fake-de-la-semaine">FAKE DE LA SEMAINE</a></h3>
<p>Cette semaine, je vais laisser parler ma flemme (oui, je peux, c&rsquo;est ma chronique, je fais que ce que je veux d&rsquo;abord) et un collègue Québécois (et ça, si vous ne le savez pas, ça s&rsquo;appelle un zeugma, c&rsquo;est ma figure de style préférée). Si vous ne connaissez pas le Pharmachien, je vous invite à aller à la rencontre de son blog, c&rsquo;est très drôle et très bien documenté.</p>
<p>Mais aujourd&rsquo;hui, je veux vous parler de son podcast (alors lui appelle ça un balado, parce que soit disant le Québec lutte contre les anglicismes ou chais pas quoi, n&rsquo;empêche que nous la clutch on appelle toujours ça l&rsquo;embrayage, hein&nbsp;!... bon où j&rsquo;en étais moi&nbsp;?). Car l&rsquo;ami a fait un podcast sur un sujet que je trouve fantastique&nbsp;: les dérives pseudo-médicales, mais quand ce sont les toubibs qui partent en banane. Et en l&rsquo;occurrence, il s&rsquo;attaque ce coup-ci (en 8 épisodes, c&rsquo;est plus une attaque, c&rsquo;est une campagne napoléonienne à ce stade) à une certaine Guylaine Lanctôt et à son livre «&nbsp;la mafia médicale&nbsp;». Alors, c&rsquo;est vrai que de ce côté de l&rsquo;Atlantique, on en a pas trop entendu parler (malgré son statut de best-seller). Mais pour vous donner une idée, il a été suffisant à l&rsquo;époque pour déclencher des manifs (et c&rsquo;est le Québec on rappelle, pas la France), entraver des campagnes de vaccination et déclencher des procès. Des années plus tard, il continue de faire des ravages, et les maîtres de la poutine citent encore d&rsquo;un œil ému le cas de Bernard Lachance, un chanteur populaire mort du SIDA qu&rsquo;il était sûr, grâce à cette femme, de ne pas avoir car ce n&rsquo;était qu&rsquo;une maladie inventée.</p>
<p>L&rsquo;antivaccinalisme tue. Tout le temps et partout dans le monde. Et il y a des cas, il faut les entendre pour y croire (et pour les entendre, c&rsquo;est là&nbsp;: https://derives.lepharmachien.com/)</p>
<hr />
<h3 id="découverte-de-la-semaine"><a href="#découverte-de-la-semaine">DÉCOUVERTE DE LA SEMAINE</a></h3>
<p>L&rsquo;altruisme est en général une bonne chose en ce bas monde, même s&rsquo;il faut avouer que ça dépend de quel côté de l&rsquo;équation on se trouve. L&rsquo;altruisme du berger allemand qui protège son maître au péril de sa vie est assez gênante pour le cambrioleur, même armé. L&rsquo;altruisme du petit enfant qui ramasse un oisillon tombé du nid pour le porter dans la maison est une plaie pour la fouine qui attendait en embuscade. Et, dans une découverte récente (à lire ici https://molecular-cancer.biomedcentral.com/articles/10.1186/s12943-023-01896-7), il commence à devenir probable que l&rsquo;altruisme des cellules cancéreuses soit un fléau pour les femmes qui cherchent à s&rsquo;en débarrasser.</p>
<p>Le cancer touche tout le monde, mais ici je parle des femmes car le papier traite du cancer du sein et c&rsquo;est donc sur 63 femmes que l&rsquo;étude a été faite. Je m&rsquo;arrête un instant pour rappeler que, si en temps normal, on considère que l&rsquo;échantillon est faible, le cas dont il va être question est également rare, et de fait il est compliqué de voir grand en termes d&rsquo;étude. Que nous raconte l&rsquo;article&nbsp;? Que jusqu&rsquo;ici, même pris à temps, certains cancers rechutent après une chimiothérapie, qui est parfois la seule option possible selon à quel type de sale crabe on a à faire. On le savait, mais on ne savait pas pourquoi, qu&rsquo;est-ce qui faisait la différence entre un cancer qui allait gentiment se laisser maraver la métastase et un qui allait faire de la résistance&nbsp;? Et la réponse est plutôt surprenante&nbsp;: l&rsquo;altruisme de certaines cellules de la tumeur.</p>
<p>Si c&rsquo;est une réponse surprenante, c&rsquo;est parce que le cancer est un peu défini comme des cellules qui, à cause de leurs mutations, prolifèrent de manière désorganisée, de façon «&nbsp;égoïste&nbsp;» c&rsquo;est-à-dire qu&rsquo;elles ne collaborent plus avec les autres composants de l&rsquo;organisme, monopolisant les ressources, désorganisant les structures pour finalement conduire au décès. La présence d&rsquo;altruisme chez les cellules cancéreuses était considérée comme hautement improbable. Et pourtant. En comparant les échantillons, les chercheurs de l&rsquo;Université de Médecine de Singapour se sont rendus compte que les tumeurs survivantes présentaient un très haut taux d&rsquo;une molécule appelée miR-125b, qui touche un petit nombre de cellules. Lorsque celles-ci sont présentes, la molécule va freiner leur propre prolifération tout en leur permettant d&rsquo;émettre des protéines qui rendent leurs voisines beaucoup plus résistantes à l&rsquo;arsenal chimique. En d&rsquo;autres termes, certaines cellules sont capables de sacrifier leur propre reproduction pour protéger les autres cellules de la tumeur lors des tentatives de s&rsquo;en débarrasser.</p>
<p>On va pas se mentir, c&rsquo;est pas une super nouvelle. Mais ce n&rsquo;est pas si noir que ça non plus, car tout ce qu&rsquo;on peut repérer, on peut trouver un moyen de le cibler. En effet, cette protection que produisent les cellules altruistes ne s&rsquo;appliquent qu&rsquo;à leurs voisines, et pas à elles-mêmes. En mettant au point des traitements ciblés, il devrait être possible de s&rsquo;attaquer prioritairement à elles avant de lancer le gros de l&rsquo;assaut thérapeutique. Tous les joueurs de RPG le savent&nbsp;: quand on doit affronter un groupe d&rsquo;adversaire, il faut toujours abattre le soigneur en premier…</p>
<hr />
<h3 id="piste-de-la-semaine"><a href="#piste-de-la-semaine">PISTE DE LA SEMAINE</a></h3>
<p><strong>Appareillage auditif</strong>&nbsp;: si vous êtes un peu dur de la feuille et que vous hésitez à porter des appareils, voilà qui devrait vous aider à être plus motivé. Des chercheurs américains ont mené une longue revue du lien entre appareillage auditif et espérance de vie (c&rsquo;est à lire ici https://www.thelancet.com/journals/lanhl/article/PIIS2666-7568(23)00232-5/fulltext) et il ressort que les porteurs réguliers d&rsquo;appareils auditifs (on a dit réguliers, donc une fois toutes les deux semaines parce que vos petits-enfants vous engueulent, ça ne suffit pas) voyaient leur risque de décès prématuré réduit de 25% par rapport aux personnes ayant des pertes auditives mais qui n&rsquo;en portaient pas. Alors attention, les chercheurs eux-mêmes n&rsquo;expliquent pas bien le lien qu&rsquo;ils ont trouvé (en fait, ils ont plein d&rsquo;hypothèses&nbsp;: meilleure santé mentale du fait d&rsquo;un moindre isolement, meilleur accès aux soins, risque diminué d&rsquo;accident, peut-être un facteur confondant qui fait que les gens soucieux de leur santé s&rsquo;appareillent plus etc.) et il faudra des études plus spécifiques pour étudier chaque facteur. Mais le lien est là, et il est intéressant de s&rsquo;y pencher, surtout si vous êtes concerné mais que vous avez cette comorbidité terrible qu&rsquo;on appelle&nbsp;: la flemme. Donnez peut-être une chance à vos appareils.</p>
<hr />
<h3 id="impasse-de-la-semaine"><a href="#impasse-de-la-semaine">IMPASSE DE LA SEMAINE</a></h3>
<p><strong>Corneille</strong>&nbsp;: vous avez été nombreux à me faire part des articles de presse relatant l&rsquo;histoire incroyable de cette corneille qui vit à Ménilmontant depuis deux mois. A la station Ménilmontant. Dans le métro, donc. Et pour l&rsquo;instant, il faut avouer que la situation est dans l&rsquo;impasse. Alors, pas de panique, elle est régulièrement nourrie par des voyageurs attentionnés, et un spécialiste du MNHN (Frédéric Jiguet, qui m&rsquo;a communiqué plein de chouettes données pour mon projet de recherche, un chercheur et un humain formidable si vous voulez mon opinion parfaitement objective et mesurée) est venu faire un premier constat qui est rassurant&nbsp;: l&rsquo;animal n&rsquo;est pas blessé, ne présente pas de signe de maladie ou d&rsquo;affaiblissement, elle sait faire attention aux rames de métro qui passent et n&rsquo;a pas l&rsquo;air spécialement paniquée par sa situation. Mais il est pour l&rsquo;instant compliqué de la sortir de là. La tentative de piégeage a échoué, car c&rsquo;est pas évident de convaincre un des animaux les plus futés du règne animal de rentrer dans une cage, même si c&rsquo;est plein de bouffe super intéressante. Ce qui peut fonctionner, ce que l&rsquo;équipe du MNHN utilise lorsqu&rsquo;il faut faire des captures, c&rsquo;est un canon à filet. Mais ça veut dire faire ça de nuit, dans une station parfaitement vidée de ses occupants, avec du personnel prévenu en amont (parce que sinon, un bruit qui ressemble à un énorme coup de feu en plein Paris, ça va être un problème), en évitant de toucher quoi que ce soit d&rsquo;électrique, au hasard les câbles sur lesquels elle se perche… C&rsquo;est pas évident. La situation est sous surveillance, mais pour l&rsquo;instant, c&rsquo;est un peu l&rsquo;impasse.</p>
<hr />
<h3 id="mauvaise-nouvelle-de-la-semaine"><a href="#mauvaise-nouvelle-de-la-semaine">MAUVAISE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Antivaccinalisme</strong>&nbsp;: on ne le redira jamais assez, le mouvement antivax tue. Il tue de manière indirecte, en provoquant des épidémies de maladies évitables comme la rougeole, ou en entravant les moyens de lutte contre la circulation d&rsquo;un virus comme le HPV. Il tue souvent pour des raisons très éloignées de quoi que ce soit de factuel, et de fait il s&rsquo;entend très bien avec les religions, les nouvelles sectes new age comme les bonnes vieilles abrahamiques. Ce n'est pas pour rien que les épidémies de rougeole en France depuis l&rsquo;instauration de l&rsquo;obligation vaccinale ont toutes démarré dans des écoles privées catholiques ou alternatives type Steiner&nbsp;; ce n&rsquo;est pas pour rien que c&rsquo;est avant tout l&rsquo;enseignement catholique qui se positionne contre la vaccination HPV à l&rsquo;école, d&rsquo;autant plus que le virus est encore perçu comme une IST, un truc qui n&rsquo;arrive pas aux gens qui suivent le dogme. Ce n&rsquo;est donc pas pour rien non plus que le terrible attentat qui a visé un centre de vaccination de la polio au Pakistan et fait 5 morts et 21 blessés parmi les forces de l&rsquo;ordre chargées de protéger les médecins est revendiqué par les Talibans, au motif que le vaccin contiendrait du porc visant à rendre impurs les vaccinés, ou serait un produit de l&rsquo;Occident pour stériliser les enfants musulmans… Pendant ce temps-là, le Pakistan demeure, avec son voisin l&rsquo;Afghanistan, les seuls pays au monde où la polio n&rsquo;a pas pu être éradiquée. Pour une raison qui doit sûrement exister quelque part chez les antivax, la terrible, dangereuse et malfaisante vaccination est venue à bout de la maladie partout ailleurs dans le monde.</p>
<hr />
<h3 id="bonne-nouvelle-de-la-semaine"><a href="#bonne-nouvelle-de-la-semaine">BONNE NOUVELLE DE LA SEMAINE</a></h3>
<p><strong>Paludisme</strong>&nbsp;: après des années de travail acharné et de priorisation des politiques publiques de santé, le Cap-Vert devient le 4e pays d&rsquo;Afrique à entrer dans la très convoitée catégorie des états «&nbsp;exempts de paludisme&nbsp;» de l&rsquo;OMS. Pour obtenir ce statut, le pays a dû réussir à interrompre la chaîne de transmission du parasite responsable pendant 3 années consécutives complètes, de manière à ce que le cycle de reproduction du parasite arrive à son terme sans avoir pu pénétrer dans un nouvel hôte humain. De ce fait, aucun cas n&rsquo;est détecté dans le pays depuis 2017. Ailleurs dans le monde, la maladie continue de toucher 250 millions de personnes et d&rsquo;en tuer 600.000 chaque année, dont plus de 90% en Afrique.</p>
<hr />
<h3 id="quest-ce-que-putain-de-quoi"><a href="#quest-ce-que-putain-de-quoi">«&nbsp;QU&rsquo;EST-CE QUE PUTAIN DE QUOI&nbsp;?&nbsp;»</a></h3>
<p>…est-ce que je vous ai déjà parlé de Didier&nbsp;? Alias Dédé-pipe-les-dés, alias Raoult-le-cacou, alias Saroumane-le-pas-si-blanc, alias Ma-retraite-aux-Baumettes. Je pense oui. Et chaque fois que je l&rsquo;ai fait (enfin, après la première salve où il s&rsquo;agissait juste d&rsquo;expliquer pourquoi son papier ne tenait pas la route quand le grand public ne savait pas qui il était), c&rsquo;est parce qu&rsquo;il a réussi à me prendre en défaut dans ma croyance qu&rsquo;il ne pouvait pas faire pire. Il ne pouvait pas s&rsquo;enfoncer plus. Et j&rsquo;avoue qu&rsquo;avec la publication de son papier où il avouait carrément avoir mené des essais illégaux sur des milliers de patients et s&rsquo;en carrer la bouillabaisse, je me suis dit que maintenant, il allait se tenir à carreau. C&rsquo;était obligé. Que pouvait-il faire de pire&nbsp;? Vous apprendrez qu&rsquo;il ne faut jamais poser cette question à l&rsquo;univers, il a une fâcheuse tendance à vous répondre.</p>
<p>Il pouvait faire de pire annoncer sur CNews, face à un Pascal Praud qui a autant d&rsquo;esprit critique sous le crâne que ma grande-tante a de cactus dans son frigo, que le vaccin à ARNm cause des cancers du système lymphatique. Et du coup il l&rsquo;a fait, parce que pourquoi perdre une occasion de buter encore plus de gens par ricochet de la défiance vaccinale quand il pouvait juste fermer sa grande moulinette à cagade, c&rsquo;te ravi de la crèche là&nbsp;?! Mais en vrai c&rsquo;est pas possible, il a perdu un pari avec quelqu&rsquo;un et il doit arriver à sortir l&rsquo;intégralité de toutes les dingueries tournant autour du Covid sans se faire arrêter, ou comment ça se passe&nbsp;?</p>
<p>On passera sur le fait que, en bon scientifique qu&rsquo;il est, il n&rsquo;explique absolument pas en quoi son affirmation aurait quoi que ce soit de vrai. Il y aurait «&nbsp;un certain nombre de protéines&nbsp;» mais on sait pas combien ni d&rsquo;où ça sort, qui ne seraient «&nbsp;pas la protéine Spike&nbsp;» mais on sait pas lesquelles c&rsquo;est ni comment il sait ça, dont «&nbsp;on ne sait pas ce qu&rsquo;elles font&nbsp;» mais c&rsquo;est sûr que c&rsquo;est lié avec le lymphome… Bref, on passera sur ça donc pour, avec le Pr Molimard du CHU de Bordeaux, poser la bonne question, la vraie, la seule qui compte&nbsp;: quand est-ce qu&rsquo;on prend des sanctions&nbsp;?</p>
<hr />
<h3 id="point-méthode-de-la-semaine--comment-prendre-une-décision-rationnelle-dans-une-situation-où-on-risque-de-ne-pas-lêtre"><a href="#point-méthode-de-la-semaine--comment-prendre-une-décision-rationnelle-dans-une-situation-où-on-risque-de-ne-pas-lêtre">POINT MÉTHODE DE LA SEMAINE&nbsp;: &nbsp;&#45; comment prendre une décision rationnelle dans une situation où on risque de ne pas l&rsquo;être</a></h3>
<p>L&rsquo;an dernier au REC (les Rencontres de l&rsquo;Esprit Critique de Toulouse), une des conférences d&rsquo;ouverture traitait de ce thème passionnant mais délicat&nbsp;: peut-on être rationnel avec une maladie grave&nbsp;? Je n&rsquo;ai pas la prétention de proposer un contenu aussi spécialisé et pointu, donc je vais aujourd&rsquo;hui préciser une variante un peu plus centrée sur mon domaine. Même si ce n&rsquo;est pas toujours bien vu de le dire, nous sommes de plus en plus nombreux à considérer nos animaux domestiques comme des membres de la famille. Des membres de la famille dont l&rsquo;espérance de vie est dramatiquement inférieure à la nôtre (à part si vous adoptez un cacatoès, ça vit 80 ans ce machin, mais par pitié réfléchissez avant de faire ça, c&rsquo;est un oiseau qui a des besoins bien spécifiques, en particulier en ce qui concerne la présence humaine), mais qui ne peuvent pas se prononcer directement sur ce qu&rsquo;ils souhaitent. C&rsquo;est donc à nous d&rsquo;interpréter les signes qu&rsquo;ils émettent avec nous et de prendre les décisions pour eux. Et ça peut être compliqué. Comment prendre une décision rationnelle&nbsp;?</p>
<p>Prenons un cas d&rsquo;étude. Dans la famille Dendrobate, nous avons un papy chat roux de près de 16 ans appelé Windows (un chat adorable mais complètement incompréhensible ayant conduit Frangin Dendrobate à le considérer «&nbsp;bugué&nbsp;», d&rsquo;où le nom). Comme beaucoup de papy chats, il est bouffé par l&rsquo;arthrose. N&rsquo;étant pas encore à un stade où la question de l&rsquo;acharnement thérapeutique peut se poser, la vétérinaire propose un traitement pour combattre la maladie, améliorer sa mobilité et prolonger sa durée de «&nbsp;vie en condition acceptable&nbsp;». A la fois, nous faisons confiance à la vétérinaire, qui est très compétente, à la fois je suis à peu près sûre que si on avait un traitement contre l&rsquo;arthrose ça se saurait. Comment départager les deux sans paniquer&nbsp;?</p>
<p>Si vous voulez vous lancer dans «&nbsp;vos propres recherches&nbsp;» de façon méthodique, la première chose à demander au praticien c&rsquo;est le nom de la molécule. En effet, les traitements changent souvent de nom commercial d&rsquo;un pays à l&rsquo;autre, mais les noms de molécules sont fixes. Ensuite, vous pouvez aller taper le nom de la molécule dans la base de données PubMed, qui est ce qu&rsquo;il y a de plus adapté pour les recherches en sciences médicales, peu importe le nombre de pattes que vous avez. Si la base de données ne renvoie pas de résultats (et que vous avez orthographié le truc correctement), c&rsquo;est mauvais signe et vous devez avoir une discussion sérieuse avec votre praticien sur votre volonté de ne soumettre votre petit compagnon qu&rsquo;à des traitements basés sur les preuves. Si la base de données répond, elle va en ce cas faire ce qu&rsquo;on appelle du «&nbsp;bruit&nbsp;», c&rsquo;est-à-dire qu&rsquo;elle va vous renvoyer des centaines de réponses à la tronche dont une minorité vous concerne. Il va falloir faire du tri.</p>
<p>Pour ça, les bases de données comme PubMed vous donne accès à une recherche avancée qui permet l&rsquo;usage facile des opérateurs booléens. Ces opérateurs sont des liens mis entre les mots clés&nbsp;: AND vous permettra de les lier (par exemple [nom de la molécule] AND [nom de l&rsquo;espèce] si vous voulez uniquement les études sur l&rsquo;espèce de votre animal), OR de les lier sans contrainte (par exemple «&nbsp;efficacité&nbsp;» OR «&nbsp;effets secondaires&nbsp;» si vous voulez connaître la tolérance comme l&rsquo;efficacité, mais que si les papiers ne traitent que d&rsquo;un sujet à la fois, c&rsquo;est pas grave), NOT d&rsquo;exclure un terme (par exemple si vous vous apercevez que la molécule a été testée pour plusieurs maladies mais que une seule vous intéresse, vous pouvez demander à la base d&rsquo;exclure toutes les autres). Une fois ce tri opéré, si je reprends notre cas d&rsquo;étude, il restait dans notre cas 3 études en tout et pour tout. C&rsquo;est peu. Est-ce un problème&nbsp;? Ça va dépendre des dates. Dans notre cas, l&rsquo;étude la plus ancienne date de 2021, c&rsquo;est donc que c&rsquo;est un produit assez nouveau et il y a peu d&rsquo;études simplement parce que les études c&rsquo;est long (surtout sur les maladies chroniques), je ne suis donc pas plus inquiète que ça. Si on avait juste quelques papiers dans les années 90, ça signerait en revanche le manque d&rsquo;intérêt de la recherche actuelle pour la molécule et ce serait pas bon. Bon et alors les études, que disent-elles&nbsp;?</p>
<p>Pour le savoir, il faut déjà arriver à les ouvrir. Certaines sont en accès libre mais c&rsquo;est une minorité. Pour les autres, je ne peux pas vous recommander d&rsquo;utiliser la plateforme très illégale de SciHub parce que c&rsquo;est mal, ni vous dire que SciHub étant bloqué en France on peut y accéder via le navigateur Tor, parce que c&rsquo;est franchement mal. Imaginons donc que vous avez trouvé les papiers. Dans ce cas, on va les trier en deux catégories, afin de pouvoir faire notre balance bénéfice-risque&nbsp;: ceux qui parlent des bénéfices et ceux qui parlent des risques (oui, bac+8 les enfants pour avoir des idées pareilles).<br />
Revenons à notre cas. Je ne crois pas aux bénéfices parce que je ne crois pas qu&rsquo;il existe de traitement pour l&rsquo;arthrose, en revanche je crois très fort que les médecins, pour humains comme pour animaux, simplifient parfois ce qu&rsquo;ils expliquent aux patients. Et dans ce cas, j&rsquo;ai eu plutôt raison. Les deux études portant sur l&rsquo;efficacité ne parlent pas de «&nbsp;traiter l&rsquo;arthrose&nbsp;», mais de diminuer l&rsquo;inflammation qu&rsquo;elle cause afin de réduire les douleurs et ralentir la perte de mobilité. Et ça, ça me parait plus cohérent. Comme toujours, on vérifie 3 choses importantes&nbsp;: Qui&nbsp;? (les chercheurs ont-ils des compétences et des affiliations cohérentes avec l&rsquo;étude qu&rsquo;ils font ici&nbsp;; en l&rsquo;occurrence oui) Combien&nbsp;? (sur combien de sujets est faite l&rsquo;étude&nbsp;; ici on a quelques dizaines d&rsquo;animaux, c&rsquo;est intéressant mais il va falloir des résultats très significatifs pour que je considère que ça marche) Comment&nbsp;? (l&rsquo;étude a-t-elle une méthode qui lui permet d&rsquo;évaluer correctement ce qu&rsquo;elle prétend&nbsp;; ici on étudie des chats pour une maladie de chats, donc ça fait sens, et la mesure prise en compte est la quantité d&rsquo;activité journalière, que les chercheurs estiment un reflet fiable de la mobilité et de l&rsquo;absence de douleur, pourquoi pas). Si vous n&rsquo;êtes pas sûr, le mieux c&rsquo;est encore d&rsquo;imprimer les études, de surligner les points qui vous semblent importants, intéressants ou obscurs, et d&rsquo;aller voir votre praticien avec ça. Dans notre cas à nous, le plateau des bénéfices est bien chargé. Mais quid de celui des risques&nbsp;?<br />
Une seule étude se centre dessus, mais le même risque est mentionné dans la discussion des deux autres, et comme il est le seul à apparaître, on peut raisonnablement conclure que si d&rsquo;autres risques existent, ils sont très rares. Disons le tout net, aucun traitement n&rsquo;est jamais sans risque, aucun. Pour évaluer ce plateau, il vous faudra vous poser 3 questions&nbsp;: Quelle fréquence&nbsp;? (le risque est-il rare, fréquent, indéterminé…&nbsp;; dans le cas présent il est évalué à 1 sur 100, ce qui veut dire qu&rsquo;il faut quand même se poser la question) Quelle gravité&nbsp;? (l&rsquo;effet secondaire ou la complication est-elle sévère, dangereuse, douloureuse, y a-t-il un traitement si ça arrive…&nbsp;; ici, il s&rsquo;agit d&rsquo;une complication cutanée qui est présentée comme très inconfortable, avec risque de surinfection si non traitée correctement, c&rsquo;est un vrai risque) Quelle chance dans notre cas précis&nbsp;? (vous connaissez votre animal, vous savez s&rsquo;il est sensible des intestins au moindre changement de couleur de sa nourriture, s&rsquo;il pisse partout dès que vous avez des invités ou s&rsquo;il suffit qu&rsquo;une puce le regarde pour qu&rsquo;il se gratte à mort, vous connaissez ses antécédents, ses problèmes actuels, sa nature, et vous pouvez vous faire aider de votre vétérinaire pour connaitre les races qui ont des prédispositions à tel ou tel problème). Si vous n&rsquo;êtes pas sûr ou que vous n&rsquo;avez pas compris certaines choses, encore une fois, impression, stabilo, véto. Dans notre cas, le risque ne semble pas majeur, mais il existe, et l&rsquo;inconfort de notre papy chat sera un vrai problème pour sa qualité de vie.</p>
<p>Alors, au final, comment peser la balance bénéfice-risque de manière rationnelle&nbsp;? Dans notre cas, il semble que le risque pour le confort doit être pris en compte, malgré la peur que nous avons de le voir se dégrader. Nous allons donc attendre, pour ne pas lui infliger un risque déraisonnable. Mais nous avons aussi confiance en les bénéfices du traitement, et nous serons prêts à le tenter, malgré notre peur des risques, lorsque nous constaterons que la maladie avance trop et commence à générer un inconfort déraisonnable. Je ne sais pas si c&rsquo;est la meilleure solution. Il est toujours possible de se reprocher plus tard d&rsquo;avoir pris un risque inutile ou d&rsquo;avoir trop attendu. Mais en se basant sur les preuves, il est possible de maximiser ses chances de faire le meilleur choix possible, en faveur du petit compagnon dont on est le porte-parole bien plus que de la peur qui entoure sa maladie. Être rationnel n&rsquo;est pas être insensible, c&rsquo;est, aussi, un outil pour prendre soin des autres fragiles.</p>
<hr />
<p>En espérant avoir pu apporter un peu de lumière dans le chaos ambiant, je rends l'antenne, et on y retourne la semaine prochaine, car l'épidémie ne se termine pas avec le remaniement ministériel, tout ne peut pas toujours être la faute du gouvernement. En attendant, prenez soin de vous et des chercheurs qui bossent dur, et, aimez la science, la vraie, et ceux qui la font. Bisous.</p>
<hr />
<p>Les commentaires ne sont pas gérés ici , un espace de discussions vous est réservé sous la publication correspondante sur { Facebook( ) } du Docteur.</p>
    </div>)
}